dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationClusterInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/DefaultProviderFirstParams.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/AbstractServiceDiscoveryFactoryTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/StandardMetadataServiceURLBuilderTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/model/MigrationRuleTest.java
dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java
dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosRegistryTest.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

Optimization code
1. add Override annotation
2. correct modifier order
3. correct parameter  order
4. replace with lambda

[3.0] Optimization code

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

[3.0] fix #10042, ignore overlapping lock exception and print log

---

dubbo-demo/dubbo-demo-triple/pom.xml
dubbo-rpc/dubbo-rpc-triple/pom.xml

fix non-reproducible data injected by os-maven-plugin used as extension: see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/dubbo/dubbo-parent-3.0.5.diffoscope
see #10066 
using it as a normal plugin restricts the impact without changed expected output = the proper dependency is used in the 2 pom.xml that require os-specific dependencies

use os-maven-plugin as plugin: fixes reproducible build

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/IOUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/User.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/User.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/EmbeddedZooKeeper.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ProtocolDetector.java

remove author

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandlerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleListenerTest.java

Fix migration init rule being changed after one conusmer inited.

[3.0] Fix INIT rule being changed

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java

[3.0] Disable migration file default

---

dubbo-dependencies-bom/pom.xml

Security issue: Update fastjson to 1.2.83

Update fastjson to 1.2.83

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/ServiceCheckUtilsTest.java

[3.0] Enhance ls command

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/ScopeBeanExtensionInjector.java

[3.0] fix ScopeBeanExtensionInjector npe

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/ServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/model/MigrationRuleTest.java

[3.0] Always get mapping from remote when migrate

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/CompositeReferenceCache.java

[3.0] fix #10044, sharing proxy instance with references

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCountCodecTest.java

fix #10078 Use synchronizedMap to avoid ConcurrentModificationException

[3.0] fix #10078, Use synchronizedMap to avoid ConcurrentModificationException

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/Constants.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java

fix https://github.com/apache/dubbo/issues/10105

[3.0-Triple] Triple support optimizer

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java

fix #10146, use concurrent hashmap to avoid ConcurrentModificationException

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryNotifier.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

fix #10031, separate configurators, routers notification from address notification.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/InstanceAddressURLTest.java

```java
@Override
public <T> Invoker<T> buildInvokerChain(final Invoker<T> originalInvoker, String key, String group) {
Invoker<T> last = originalInvoker;
URL url = originalInvoker.getUrl();
List<ModuleModel> moduleModels = getModuleModelsFromUrl(url);
List<Filter> filters;
if (moduleModels != null && moduleModels.size() == 1) {
filters = ScopeModelUtil.getExtensionLoader(Filter.class, moduleModels.get(0)).getActivateExtension(url, key, group);
} else if (moduleModels != null && moduleModels.size() > 1) {
filters = new ArrayList<>();
List<ExtensionDirector> directors = new ArrayList<>();
for (ModuleModel moduleModel : moduleModels) {
List<Filter> tempFilters = ScopeModelUtil.getExtensionLoader(Filter.class, moduleModel).getActivateExtension(url, key, group);
filters.addAll(tempFilters); …
```

[3.0] Fix InstanceAddressURL unable to get scopeModel when creating invoker

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemoryLimitCalculator.java

Improve: enhance scheduled executor for MemoryLimitCalculator

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/SwitchLogger.java

[3.0] Fix switch logger NPE

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ReflectionAbstractServerCall.java

[3.0] Optimization of ReflectionAbstractServerCall

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassLoaderResourceLoader.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ClassLoaderResourceLoaderTest.java

[3.0] Handle interrupted exception for ExtensionLoader

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java

Adjust the code for the class ServiceInstancesChangedListener to make it clearer.
Adjust the code for the class ServiceInstancesChangedListener to make it clearer.
Remove invalid code.

Adjusted the code to make it cleaner.

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ChannelWrappedInvoker.java

fix #10202, use getRemoteAddress

[3.0] fix #10202, use getRemoteAddress

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java

Fix https://github.com/apache/dubbo/issues/10198

fix qos failure in non-registry scenarios

---

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/buffer/ChannelBufferStreamTest.java

Refactor ChannelBufferStreamTest.testAll to improve the test experience

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java

Fix https://github.com/apache/dubbo/issues/10111

Revert #8948

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java

[3.0] Add class not found cache for PojoUtils

---

dubbo-common/src/test/java/org/apache/dubbo/common/utils/DubboAppenderTest.java

refactor DubboAppenderTest 

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

[3.0] Clear up env when destroy

---

.github/workflows/build-and-test-3.1.yml

[3.1] Rename actions name

---

dubbo-dependencies-bom/pom.xml

Fix https://github.com/apache/dubbo/issues/10269
Related pr https://github.com/apache/dubbo/pull/9552

[3.0] Fix dependencies pom hibernate version

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Cancel availability check for NopServiceDiscovery

---

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/filter/CacheFilter.java

using guard clause to refactor CacheFilter

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

feat: add final modifier

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/AbstractRetryTask.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java

refactor: FailBackRegistry using diamon operator

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java

add final modifier for lock in FrameworkModel

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/AbstractZookeeperClient.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/AbstractZookeeperTransporter.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/ZookeeperTransporter.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

refactor: inspect code of ZookeeperRegistry classes.

---

dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/AccessKeyAuthenticator.java
dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/utils/SignatureUtils.java
dubbo-plugin/dubbo-auth/src/test/java/org/apache/dubbo/auth/AccessKeyAuthenticatorTest.java
dubbo-plugin/dubbo-auth/src/test/java/org/apache/dubbo/auth/utils/SignatureUtilsTest.java

1. refactor SignatureUtils and related usage
2. split the big try-catch into pieces, make code more easy to understand
3. using try-with-resource clause

refactor SignatureUtils and related usage

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServerHandler.java

refactor: inspect code of netty4 classes.

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCall.java

fix https://github.com/apache/dubbo/issues/10289

[3.0-Triple] Fix  duplicate wrap executor

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java

Fix ProxyHolder class modifier

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/ScopeBeanExtensionInjector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionAccessorAware.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionFactory.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionInjector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/inject/AdaptiveExtensionInjector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/inject/SpiExtensionInjector.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/inject/AdaptiveExtensionInjectorTest.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/common/extension/ExtensionFactory.java
dubbo-compatible/src/test/java/org/apache/dubbo/common/extension/MyExtensionFactory.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionInjector.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/extension/SpringExtensionInjectorTest.java

1. refactor SpiExtensionInjector getInstance with guard clause
2. remove the public NAME field for test only in SpiExtensionInjector
3. remove useless pieces in ScopeBeanExtensionInjector

refactor ExtensionInjector and related

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/buffer/ByteBufferBackedChannelBuffer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/buffer/DynamicChannelBuffer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/ChannelHandlerDispatcher.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/DecodeHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/connection/ConnectionOrderedChannelHandler.java

refactor: inspect code of remoting classes.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

在init中添加initialized和ref的双重校验，避免initialized=true，但ref=null的问题
https://github.com/apache/dubbo/issues/10222

修改init方法，避免初始化失败后，ref为空的问题

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/AbstractAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/config/DubboConfigDefaultPropertyValueBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigBeanInitializer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboInfraBeanRegisterPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboSpringInitializer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboConfigConfigurationRegistrar.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/event/DubboApplicationStateEvent.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceAttributes.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanManager.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanSupport.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceCreator.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboBeanUtils.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/EnvironmentUtils.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigAliasPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/config/DubboConfigDefaultPropertyValueBeanPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/consumer/test/TestConsumerConfiguration.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/extension/SpringExtensionInjectorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/DubboConfigBeanInitializerTest.java

Optimize code and add some ut for config-spring module

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

[TRI] Fix tri timeout does not set

---

dubbo-registry/dubbo-registry-xds/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.RegistryFactory
dubbo-registry/dubbo-registry-xds/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceDiscoveryFactory
dubbo-registry/dubbo-registry-xds/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.xds.XdsCertificateSigner

[3.1] add xds miss file

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java

remove duplicate code snippets in AbstractInterfaceConfig#postProcessAfterScopeModelChanged()
From 243-245 line In AbstractInterfaceConfig, this is repeated as above 237-239 line.
So remove duplicate code snippets。

perf: remove duplicate code snippets in AbstractInterfaceConfig

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Request.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/CloseTimerTask.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java

refactor: inspect code of exchange classes.

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Online.java

Fix Qos Online command typo

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java

Fix triple protocol thread name

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/TelnetHandlerAdapter.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/support/TelnetHandlerAdapterTest.java

Disable telnet command by default

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java

fix 特殊情况下重复注入别名 

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/FilterChainBuilder.java

Fix CallbackRegistrationInvoker skip when throw exception

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigMode.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java

Fix override configMode

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ModuleConfigManager.java

unexport的时候，ModuleConfigManager的成员serviceConfigCache里面的config没删除，因此在此export时候一定会报错

unexport and delete config

---

dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/pom.xml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/pom.xml
dubbo-native-plugin/pom.xml
dubbo-spring-boot/dubbo-spring-boot-actuator/pom.xml
dubbo-spring-boot/dubbo-spring-boot-autoconfigure/pom.xml
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/pom.xml
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/pom.xml
dubbo-spring-boot/dubbo-spring-boot-starter/pom.xml

Fix https://github.com/apache/dubbo/issues/10363

Fix pom revision

---

dubbo-common/src/main/java/org/apache/dubbo/common/json/JSON.java
dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/AbstractJSONImpl.java
dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/FastJsonImpl.java
dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/GsonImpl.java

Expand on the common tools and methods of JSON
扩展一下关于json常用的工具方法

Expand on the common tools and methods of JSON

---

dubbo-rpc/dubbo-rpc-triple/pom.xml

[3.1-Triple] remove tri dubbo-compiler-version properties

---

dubbo-common/src/main/java/org/apache/dubbo/common/cache/FileCacheStoreFactory.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/service/GenericException.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractCacheManager.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MappingCacheManager.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReportInstance.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/MetaCacheManager.java

1. support dubbo.application.enable-file-cache=false
2. cache file add application name
#9891 #9800

Cache file add module name

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

refactor: inspect code of protocol classes.

---

dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/context/event/WelcomeLogoApplicationListener.java

Remove `Dubbo Spring Boot` info when start application.
Remove `Dubbo Spring Boot` info when start application. #10399

[ISSUE #10399] Remove `Dubbo Spring Boot` info when start application

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/util/CuratorFrameworkUtils.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/context/event/WelcomeLogoApplicationListener.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/util/DubboUtils.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/test/java/org/apache/dubbo/spring/boot/util/DubboUtilsTest.java

[3.0] Set ACL Provider

---

README.md

Update version and remove '#' in README.

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java

Fix triple unexport remove

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java

Related https://github.com/apache/dubbo/issues/10367

Fix unable to specify protocol from ConsumerConfig

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/ProviderReadinessProbe.java

Update Readiness probe

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/ProviderReadinessProbe.java

Set ready if there is no stated url provided

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceAttributes.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanBuilder.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

ApplicationConfig adds meshEnable configuration, ReferenceConfig adds providerPort configuration, and at the same time, api configuration, xml configuration, attribute configuration, and annotation configuration are modified.
After meshEnable is true, the registry is set to N/A, at least one tri protocol needs to be configured, and the ports configured by the default consumer and provider are the same. DubboReference only needs to configure providedBy (K8S Service name == provider application name) to call.
```properties
dubbo.application.name=dubbo-samples-mesh-consumer
dubbo.registry.address=N/A
dubbo.protocol.name=tri
dubbo.protocol.port=50052
dubbo.application.meshEnable=true
```
```java
// consumer
@DubboReference(providedBy = "dubbo-samples-mesh-provider")
private Greeter greeter; …
```

feat: add mesh enable config and process url in mesh mode

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java

fix issue 10425

---

dubbo-registry/dubbo-registry-multiple/src/test/java/org/apache/dubbo/registry/multiple/MultipleRegistry2S2RTest.java

replace Assertions with Assumptions

fix for issue#10213

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java

Remove to rpcInvocation string

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java

Fix nacos removeServiceInstancesChangedListener

---

dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java

Fix https://github.com/apache/dubbo/issues/10426

Fix nacos removeServiceAppMappingListener

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java

refactor: inspect protocol classes

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java

fix GenericFilter 从 Attachment 中获取generic参数获取不到的问题

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceBeanNameBuilder.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceBeanNameBuilderTest.java
dubbo-spring-boot/dubbo-spring-boot-actuator/src/test/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointAnnotationAutoConfigurationTest.java
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/test/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointAutoConfigurationTest.java

fixed ServiceBeanNameBuilder same version/group conflict (#10454)

---

dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/FastJsonImpl.java

DisableCircularReferenceDetect for fastjson impl

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/MetadataInfoTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/OverrideInstanceAddressURL.java

Fix transient init

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ReflectionBasedServiceDiscovery.java

fix (#10458) doUnregister 递归调用

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosAggregateListener.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

[3.0] Fix Nacos aggregate listen

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/service/GenericException.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/service/GenericExceptionTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java

generic exception support to transfer

generic_exception_support_transfer

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java

[3.0] Fix Executor rewrite

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/AccessLogData.java

使accesslog更加贴近常用的一些如nginx,tomcat的accesslog打印方式,在业务逻辑处理完成后进行打印,并携带完成时间
1.是否顺便改动date为localtimedate
2.consumer是否也要加一个类似accesslog的filter,这样consumer端和provider进行调用相关的问题排查会更加方便

optimize AccessLogFilter

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/TimeWindowCounter.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/aggregate/TimeWindowCounterTest.java

Add TimeWindowCounter and TimeWindowCounterTest
Related pr : https://github.com/apache/dubbo/pull/10331
Related issues : https://github.com/apache/dubbo/issues/9886
Related Documentation : https://qnac8r4ct8.feishu.cn/docx/doxcncmY1gYiRGX9ccX264W6JJd
Provide a sliding window to dynamically obtain recent data

metrics series 1 : add TimeWindowCounter

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java

Init deadlock

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeClassChecker.java

add switch to avoid generic call oom

add switch to no use

---

dubbo-common/src/main/java/org/apache/dubbo/common/metrics/model/MetricsKey.java
dubbo-dependencies-bom/pom.xml
dubbo-metrics/dubbo-metrics-api/pom.xml
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/AbstractMetricsReporter.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/AbstractMetricsReporterFactory.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/TimeWindowQuantile.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilter.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/service/DefaultMetricsService.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/aggregate/TimeWindowQuantileTest.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java

Related pr : https://github.com/apache/dubbo/pull/10331
Related issues : https://github.com/apache/dubbo/issues/9886
Related Documentation : https://qnac8r4ct8.feishu.cn/docx/doxcncmY1gYiRGX9ccX264W6JJd

metrics series 3 : add TimeWindowQuantile, MetricsFilter, DefaultMetricsService

---

dubbo-common/src/main/java/org/apache/dubbo/config/MetricsConfig.java
dubbo-metrics/dubbo-metrics-api/pom.xml
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java
dubbo-metrics/dubbo-metrics-prometheus/pom.xml
dubbo-metrics/dubbo-metrics-prometheus/src/main/java/org/apache/dubbo/metrics/prometheus/PrometheusMetricsReporter.java
dubbo-metrics/dubbo-metrics-prometheus/src/main/java/org/apache/dubbo/metrics/prometheus/PrometheusMetricsReporterFactory.java
dubbo-metrics/dubbo-metrics-prometheus/src/test/java/org/apache/dubbo/metrics/prometheus/PrometheusMetricsReporterFactoryTest.java
dubbo-metrics/dubbo-metrics-prometheus/src/test/java/org/apache/dubbo/metrics/prometheus/PrometheusMetricsReporterTest.java
dubbo-metrics/pom.xml

Related pr : https://github.com/apache/dubbo/pull/10331
Related issues : https://github.com/apache/dubbo/issues/9886
Related Documentation : https://qnac8r4ct8.feishu.cn/docx/doxcncmY1gYiRGX9ccX264W6JJd

metrics series 4 : add PrometheusMetricsReporter

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/AbstractRegistryService.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/EmbeddedZooKeeper.java

Add error code 5-2 ~ 5-20. (FAQ)

---

dubbo-distribution/dubbo-all/pom.xml
dubbo-distribution/dubbo-bom/pom.xml

Shade kubernetes and xds module

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java

make some 'if' statement be simplified and format code

[fix] some statement can be simplified

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java

[3.1] Remove useless toString in Timeout Filter

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java

[3.0] Remove useless toString in Timeout Filter

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java

[2.7] Remove useless toString in Timeout Filter

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ListenableStateRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailsafeClusterInvoker.java

faq-cluster

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceCreator.java

Optimize the log messages created by ReferenceConfig

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosInstanceManageUtil.java

fix #10541, save subscribed dataIds for unsubscription.

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java

Fix Service Discovery Port Match

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java

Fix https://github.com/apache/dubbo/issues/10607

Fix Nacos unSubscribe when shutdown

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLAddress.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLStrParserTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DefaultMetadataParamsFilter.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java

support ipv6

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java

fix https://github.com/apache/dubbo/issues/10610

fix: Fix unregisterServiceInstance not work in shutdown hook (#10610)

---

dubbo-dependencies-bom/pom.xml

[2.7] Update hessian version

---

dubbo-dependencies-bom/pom.xml

Update hessian-lite version

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/support/InstantiationStrategy.java

1. Use ? to populate the generics of Class. Avoid IDE warnings
2. Use @SuppressWarnings("unchecked") to suppress type conversion warnings
3. Add final to the field ScopeModelAccessor

style: Eliminate some IDE warnings

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/BroadcastClusterInvoker.java

Fix https://github.com/apache/dubbo/issues/10617

Fix broadcast context being cleared

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/serial/SerializingExecutor.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/ChannelEventRunnable.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java

Fix https://github.com/apache/dubbo/issues/10608

Fix ContextFilter not cleanup thread

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/protocol/QosProtocolWrapperTest.java

fix bug https://github.com/apache/dubbo/issues/10592

fix(qos): fix qos server not permit if set qos.accept.foreign.ip=true

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

Fix timeout type cast exception

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java

Fix PojoUtils support localdatetime,lcaldate,localtime serializable and deserialize

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java

Ensure this method of DefaultServiceInstance is thread safe to caller

thread safe for ServiceInstance

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveBalanceTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalanceTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalanceTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/beanutil/Bean.java
dubbo-metadata/dubbo-metadata-processor/src/test/java/org/apache/dubbo/metadata/annotation/processing/model/SimpleTypeModel.java

Fix some punctuation problems and incorrect writing position of ASF license header.
The ASF license header of the following files is written in the wrong place and should be written at the top of the file:
- dubbo-common/src/test/java/org/apache/dubbo/common/beanutil/Bean.java
The following files have punctuation errors in the ASF license header:
- dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveBalanceTest.java
- dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java
- dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalanceTest.java
- dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalanceTest.java
- …

docs: Fix some punctuation problems and incorrect writing position of ASF license header

---

.codecov.yml
.github/workflows/build-and-test-3.1.yml
.licenserc.yaml
.travis.yml

Try using GitHub action to check ASF license header.

feat: add apache/skywalking-eyes@main job

---

dubbo-dependencies-bom/pom.xml

fix 修复 snakeyaml 依旧存在的漏洞 升级 1.32

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java

**instanceof not throw NullPointExcetion**
```
// instanceof not throw NullPointExcetion
if (result.getException() != null && result.getException() instanceof RpcException) 
// Examle:
public static void main(String[] args) {
Exception e = null;
if (e instanceof Exception) {
System.out.println("instanceof");
}
System.out.println("success");
}
//Out:
success
```

fix optimize if null instanceof before

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

add attribute(providerNamespace) in @DubboReference, and add `provider-namespace` attribute in xsd, that fix issue https://github.com/apache/dubbo/issues/10637

fix #10637 assign provider namespace

---

dubbo-compiler/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper-curator5/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
pom.xml

fix issues remaining after #10067
see rebuild result for Dubbo 3.1.0 https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/dubbo/README.md
upgrade flatten plugin, remove duplicate plugin version definition

fix Reproducible Builds issues

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/JVMUtil.java

#10705 Control stack print lines

#10705 Control stack print lines

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java

Optimize the logic for obtaining the MigrationRule value
Extract and reuse duplicate code logic

Optimize the logic for obtaining the MigrationRule value

---

dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioCitadelCertificateSigner.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioConstant.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioEnv.java

Support Istio third-party-jwt

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/event/ThreadPoolExhaustedListener.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

Fix https://github.com/apache/dubbo/issues/10490

Add thread pool exhausted listener config

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java

Related with https://github.com/apache/shenyu/issues/4031

Support AliasFor

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServiceContext.java

Fix https://github.com/apache/dubbo/issues/10735

Fix getUrl NPE after setInvokers

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

Should not continue sending requests when it has timed out

---

.github/workflows/build-and-test-3.1.yml
dubbo-common/src/test/java/org/apache/dubbo/common/logger/slf4j/Slf4jLoggerTest.java
dubbo-dependencies-bom/pom.xml
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/MetadataReportInstanceTest.java
dubbo-spring-boot/pom.xml
pom.xml

Feat::Supports JDK 19 build and JUnit testing #10719

Feat::Supports JDK 19 build and JUnit testing #10719

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/RequestMetadata.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHeaderEnum.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/StreamUtils.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleServerStream.java

triple support upper header key

---

.github/workflows/build-and-test-scheduled-3.0.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml

Fix workflow branch name

---

.github/workflows/build-and-test-scheduled-3.0.yml

Ignore license check in 3.0

---

.github/workflows/release-test-3.1.yml

Add release test flow

---

.github/workflows/build-and-test-scheduled-3.0.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml

Fix corn job time

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.0.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ConfigValidationUtilsTest.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/dubbo.properties
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java
dubbo-spring-boot/dubbo-spring-boot-autoconfigure/src/test/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessorTest.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessor.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/test/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessorTest.java

triple flowcontrol sub 3.2 branch

triple flowcontrol

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/pu/PortUnificationTransporter.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationTransporter.java
dubbo-remoting/dubbo-remoting-netty4/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.api.pu.PortUnificationTransporter

fix no such extension by name netty4

fix no such extension by name netty4

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/Netty4BatchWriteQueue.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyBackedChannelBuffer.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandlerTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCountCodec.java

encode supports `MultiMessage`

encode supports multi message

---

dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ConnectionTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilterTest.java

Fix some errors in unit tests.
Correct the types in Mockito invocation and fix incorrect concurrent library uses.

Fix assertion error and class cast exception in unit tests.

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java

build error response when sending `MultiMessage` fail

build error response when sending MultiMessage fail

---

dubbo-common/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/FastJson2Impl.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/JsonUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/JsonUtilsTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/json/TestEnum.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/json/TestObjectA.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/json/TestObjectB.java
dubbo-dependencies-bom/pom.xml

Related with https://github.com/apache/dubbo/issues/10790

JsonUtils Support Fastjson2

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

Fix Registry Destroy Order

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/CollectionUtilsTest.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java

bugfix: meatadata service support read dubbo:protocol

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java

change tri support upper attachment config to enable by default

---

dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioCitadelCertificateSigner.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioConstant.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioEnv.java

Fix istio first-party-jwt

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java

Fix RpcUtils#getParameterTypes and AccessLogFilter#renameFile method

Fix RpcUtils#getParameterTypes and AccessLogFilter#renameFile method

---

dubbo-common/src/test/java/org/apache/dubbo/metadata/definition/ServiceDefinitionBuilderTest.java

Fix ServiceDefinitionBuilder uts

---

Jenkinsfile.sonar
dubbo-common/src/main/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilder.java

Try add sonarcloud

---

Jenkinsfile.sonar
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-consumer/pom.xml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/pom.xml
dubbo-distribution/dubbo-all/pom.xml
dubbo-distribution/dubbo-bom/pom.xml
dubbo-kubernetes/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceDiscovery
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/ServiceRestMetadataResolver.java
dubbo-native-plugin/pom.xml
dubbo-registry/dubbo-registry-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.metadata.SubscribedURLsSynthesizer
dubbo-test/dubbo-dependencies-all/pom.xml
dubbo-test/dubbo-test-modules/pom.xml
dubbo-test/dubbo-test-modules/src/test/java/org/apache/dubbo/dependency/FileTest.java
dubbo-xds/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceDiscovery
pom.xml

- 检查 dubbo-bom 包括所有模块
- 检查 dubbo-all 完整 shade
- 检查 SPI 声明使用

Add coverage module & file lint test

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
dubbo-common/src/main/java/org/apache/dubbo/common/constants/ProviderConstants.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
dubbo-configcenter/dubbo-configcenter-apollo/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/dubbo-spring-boot-compatible/pom.xml
dubbo-test/dubbo-test-spring3.2/pom.xml
dubbo-test/dubbo-test-spring4.1/pom.xml
dubbo-test/dubbo-test-spring4.2/pom.xml
pom.xml

Docs https://github.com/apache/dubbo-website/pull/1597

Set Fastjson2 as default, support JDK17 native test

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java

Fix MetadataService method order

---

pom.xml

Add tmp exclude for rat

---

Jenkinsfile.sonar

Add docker for jenkins

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Add some logs

---

dubbo-remoting/dubbo-remoting-zookeeper/pom.xml

Fix zookeeper pom

---

.github/workflows/build-and-test-pr.yml

Use remote key to start sonarcloud scan

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/ExchangeClient.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java

See https://github.com/apache/dubbo/issues/8752#issuecomment-1313479077

Revert #8755

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/SingleRouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/BitList.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/RouterChainTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

修复在 RouterChain 通知 notify 的时候 directory 提前修改了新的 invokers，导致 bitlist 原始数据不一致的问题

Fix early update directory

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosInstanceManageUtil.java

Remove guava usage in nacos registry

---

dubbo-native-plugin/src/main/java/org/apache/dubbo/common/metrics/MetricsReporterFactory$Adaptive.java
dubbo-native-plugin/src/main/java/org/apache/dubbo/common/threadpool/ThreadPool$Adaptive.java
dubbo-native-plugin/src/main/java/org/apache/dubbo/rpc/executor/IsolationExecutorSupportFactory$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/common/metrics/MetricsReporterFactory$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/common/serialize/Serialization$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/metadata/report/MetadataReportFactory$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/remoting/api/pu/PortUnificationTransporter$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouterFactory$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/rpc/executor/IsolationExecutorSupportFactory$Adaptive.java

Update spi for native code

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/ssl/SslClientTlsHandler.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/ssl/SslContexts.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/ssl/SslServerTlsHandler.java

ssl netty4

---

Jenkinsfile.sonar
dubbo-common/src/main/java/org/apache/dubbo/common/URL.java

What is the purpose of the change
When the org.apache.dubbo.common.URL uses setHost, setPassword, there is an NPE risk of the urlAddress property, because the URL has an empty constructor. For example, when zk pushes the url to the listener, it will call the DefaultServiceInstance.toURL method to construct the URL
@Override
public InstanceAddressURL toURL(String protocol) {
if (instanceAddressURL == null) {
instanceAddressURL = new InstanceAddressURL(this, serviceMetadata, protocol);
}
return instanceAddressURL;
}
The constructor of InstanceAddressURL here only sets its own properties, which is equivalent to calling the empty constructor of the parent class URL. The constructed URL instance urlAddress property is empty. When someone calls the setHost of this URL, an NPE error will be …

fix NPE bug of URL

---

.github/workflows/build-and-test-pr.yml

Fix shallow clone for sonarcloud

---

dubbo-compatible/src/test/java/org/apache/dubbo/cache/CacheTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/common/extension/ExtensionTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ApplicationConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ArgumentConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ConsumerConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/MethodConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ModuleConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ProtocolConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ProviderConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/config/RegistryConfigTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/echo/EchoServiceTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/filter/FilterTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/generic/GenericServiceTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/rpc/cluster/RouterTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/serialization/SerializationTest.java
dubbo-test/dubbo-test-modules/src/test/java/org/apache/dubbo/dependency/FileTest.java

Remove public modifier in dubbo-compatiable

---

dubbo-common/src/test/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtilTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandlerTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/CodecAdapterTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/DeprecatedExchangeCodec.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/DeprecatedTelnetCodec.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/ExchangeCodecTest.java

Refactor some test cases to remove public modifier

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java

Add `UNACCPTABLE_PROTOCOL` to prevent use `rest` and `grpc` protocol for metadata-service

Fix try use rest protocol

---

dubbo-test/dubbo-test-modules/src/test/java/org/apache/dubbo/dependency/FileTest.java

Fix FileTest separator in Win

---

dubbo-test/dubbo-test-modules/src/test/java/org/apache/dubbo/dependency/FileTest.java

Fix FileTest seperator in Win

---

pom.xml

Update Jacoco version

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassLoaderResourceLoader.java

Fix logger in ClassLoaderResourceLoader

---

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

XSD file append prefer-serialization fix

XSD file append prefer-serialization

---

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

Revert "XSD file append prefer-serialization"

---

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

:pencil2: XSD file append prefer-serialization

---

.github/workflows/build-and-test-pr.yml
dubbo-common/src/main/java/org/apache/dubbo/common/config/EnvironmentConfiguration.java
dubbo-common/src/test/java/org/apache/dubbo/common/config/EnvironmentConfigurationTest.java
pom.xml

Fix jacoco arg line not work in jdk17

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/InternalServiceConfigBuilder.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultMetricsServiceExporter.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/utils/UrlUtils.java

https://sonarcloud.io/project/issues?resolved=false&types=BUG&branch=3.2&id=apache_dubbo&open=AYR-in6sPg5-O_QVSBN9

Fix code style for 3.2

---

dubbo-kubernetes/src/test/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscoveryTest.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportTest.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/DubboMonitorTest.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/MockMonitorService.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleListenerTest.java
pom.xml

Enhance unit test cases

---

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/filter/MetricsCollectExecutor.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java

Fixed metrics collection getting wrong method name when generalize called

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/serial/SerializingExecutor.java
pom.xml

revert grpc header

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-metadata/dubbo-metadata-report-zookeeper/src/main/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReport.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/AbstractZookeeperClient.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/test/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClientTest.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/test/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClientTest.java

Fix service name mapping data being override when two process are creating persistent node in zookeeper at the same time.
BTW, this PR will fix the issue of `NodeExists for /dubbo/metadata`.
Root cause:
```java
protected void createPersistent(String path, String data) {
byte[] dataBytes = data.getBytes(CHARSET);
try {
client.create().forPath(path, dataBytes);
} catch (NodeExistsException e) {
// --------- Data will being overrided here --------------
try {
client.setData().forPath(path, dataBytes);
} catch (Exception e1) {
throw new IllegalStateException(e.getMessage(), e1);
}
} catch (Exception e) {
throw new IllegalStateException(e.getMessage(), e);
}
}
```

Fix zookeeper cas failed when create

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

Adjust the logic of timeout, fix triple about timeout countdown function problem

---

dubbo-dependencies-bom/pom.xml

Update fastjson2 version

---

dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

Add dubbo metrics AutoConfiguration.imports for Spring Boot 3 (related to #10997)

Add dubbo metrics AutoConfiguration.imports for Spring Boot 3 (related to #10997)

---

.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml

In scheduled testing, the error code inspector will only inspect error code in branch `3.1`.
Change properties in workflow files. (Specify the branch in checkout action.)

Correct the error code inspector working branch in scheduled testing.

---

.gitignore
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/pom.xml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/src/main/java/com/apache/dubbo/demo/graalvm/consumer/Application.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/pom.xml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/src/main/java/org/apache/dubbo/demo/graalvm/provider/Application.java
dubbo-native-plugin/src/main/resources/META-INF/native-image/reflect-config.json
dubbo-native-plugin/src/main/resources/META-INF/native-image/resource-config.json
dubbo-native/src/main/java/org/apache/dubbo/common/metrics/MetricsReporterFactory$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/common/serialize/Serialization$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/metadata/report/MetadataReportFactory$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/remoting/api/pu/PortUnificationTransporter$Adaptive.java
dubbo-native/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouterFactory$Adaptive.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ContextFilterTest.java

Fix native image compile failure and run binary package failure

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java

Get system properties from context

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleServerStream.java

opt some tri code

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriHttp2RemoteFlowController.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java

Fix flow controller trigger application init

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractServiceConfigTest.java

Read default prefer serialization from serialization first

---

dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java

Fix diagnostics log message errors

---

dubbo-dependencies-bom/pom.xml

Update Fastjson2 to 2.0.21

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReportInstance.java

Fixes https://github.com/apache/dubbo/issues/11096

Fix MetadataReportConfig being valid when pre config

---

dubbo-remoting/dubbo-remoting-api/pom.xml
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/AbstractWireProtocol.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/WireProtocol.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ssl/ContextOperator.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/EmptyProtocol.java
dubbo-remoting/dubbo-remoting-netty4/pom.xml
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettySslContextOperator.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/api/EmptyWireProtocol.java
dubbo-rpc/dubbo-rpc-rest/pom.xml
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/NettyRestProtocolServer.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java

ssl abstract and remoteapi remove netty

---

dubbo-dependencies-bom/pom.xml
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleCustomerProtocolWapper.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ReflectionAbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriBuiltinService.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleCustomerProtocolWapperTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/service/TriBuiltinServiceTest.java

replace protobuf depency in triple rpc with customer encoding/decoding
add TripleCustomerProtocolWapper.java
replace TripleRequestWrapper.TripleRequestWrapper with TripleCustomerProtocolWapper.TripleRequestWrapper
replace TripleRequestWrapper.TripleResponseWrapper with TripleCustomerProtocolWapper.TripleResponseWrapper

[DUBBO-11047][issue]Remove direct dependency of protobuf-java

---

dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

add more information when zk not connected (#11057)

---

dubbo-native-plugin/src/main/resources/META-INF/native-image/reflect-config.json
dubbo-native/src/main/java/org/apache/dubbo/remoting/api/pu/PortUnificationTransporter$Adaptive.java

Fix native reflect-config.json

---

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java

Enhance #9744

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/MultiInstanceTest.java

Try fix MultiInstanceTest

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/DeadlineFuture.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/DeadlineFutureTest.java

fix tri filter onError

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/MultiInstanceTest.java

Try fix MultiInstanceTest Again

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

Fix zk removeServiceInstancesChangedListener

---

dubbo-common/src/main/java/org/apache/dubbo/common/resource/GlobalResourcesRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/FrameworkExecutorRepository.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/MultiInstanceTest.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/DubboTestChecker.java

Add some check for MultiInstanceTest

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/CompositeConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/Configuration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/EnvironmentConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/InmemoryConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/OrderedPropertiesConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/PrefixedConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/PropertiesConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/SystemConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/AbstractDynamicConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/nop/NopDynamicConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/wrapper/CompositeDynamicConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigConfigurationAdapter.java
dubbo-common/src/test/java/org/apache/dubbo/common/config/SystemConfigurationTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/SerializeClassCheckerTest.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/MultiInstanceTest.java
dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/DubboTelnetDecodeTest.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/DefaultHessian2FactoryInitializer.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/Hessian2FactoryInitializer.java

Fix https://github.com/apache/dubbo/issues/11159

Revert #10839, #11082 and #11086

---

dubbo-dependencies-bom/pom.xml

Remove provided scope of protobuf-java

---

dubbo-common/src/main/java/org/apache/dubbo/common/resource/GlobalResourcesRepository.java

Correct the logger's error statement to info.

---

dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/pom.xml
dubbo-native-plugin/src/main/resources/META-INF/native-image/reflect-config.json

native support openjdk17

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerClassLoaderFilter.java
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.filter.ClusterFilter
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java

Fix https://github.com/apache/dubbo/issues/11168

Fix Consumer ClassLoader Change

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

ServiceName in nacos event: `DEFAULT_GROUP@@providers:org.apache.dubbo.samples.api.GreetingService:1.0.0:`
Origin ServiceName: `providers:org.apache.dubbo.samples.api.GreetingService:1.0.0:`
Fixes https://github.com/apache/dubbo/issues/11053

Fix Nacos ServiceName error

---

dubbo-common/src/test/java/org/apache/dubbo/common/model/person/PersonMap.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
dubbo-dependencies-bom/pom.xml

confirm that JSONObject can be converted to pojo extends Hashmap
1. When genericService is executed, the request object is JSONObject，Confirm that JSONObject can be converted to pojo extends Hashmap
run @Test testJSONObjectToPersonMapPojo  method

1.test JSONObject to personMap pojo, the personMap extends HashMap

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/SpringCloudServiceInstanceNotificationCustomizer.java

Fix Spring Cloud metadata override

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ProtocolPortsMetadataCustomizer.java

Fix https://github.com/apache/dubbo/issues/11201

Fix warn when port are the same

---

dubbo-rpc/dubbo-rpc-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter

Fix active limit filter not work

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/wrapper/CompositeDynamicConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/ListenerRegistryWrapper.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandler.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/RegistryManager.java

Merge error code 1-36 to 99-0 since they have the same meaning.
Change constants and error codes in the corresponding code.

Merge error code 1-36 to 99-0.

---

dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java

Fix Nacos empty ticket not work

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ReflectionMethodDescriptor.java
dubbo-common/src/test/java/org/apache/dubbo/common/logger/support/FailsafeLoggerTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/EmbeddedZooKeeper.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStream.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/initializer/DownloadZookeeperInitializer.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/ZookeeperUnixProcessor.java

Change some test-related error code to a separate series. 
1-24 -> 81-1
1-25 -> 81-2
1-23 -> 81-3
5-19 -> 81-4
https://github.com/apache/dubbo-website/pull/1781

Change some test-related error code to a separate series.

---

.github/workflows/build-and-test-pr.yml
dubbo-dependencies-bom/pom.xml
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryChangeWatcher.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/util/CuratorFrameworkUtils.java

Fix zk do not notify when instance changed. (Only work when instance removed or created)

Enhance Zookeeper ServiceDiscovery update

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/AbstractH2TransportListener.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/transport/AbstractH2TransportListenerTest.java

fix https://github.com/apache/dubbo/issues/11208
https://github.com/apache/dubbo-samples/pull/693

fix tri upper error

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/SslClientTlsHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/SslServerTlsHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/ReconnectTimerTask.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractEndpoint.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/ChannelHandlerDispatcher.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/MultiMessageHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/ChannelEventRunnable.java
dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyHelper.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServerHandler.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/javassist/JavassistProxyFactory.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/AbstractH2TransportListener.java

Merge some error codes with the same meaning.
3-3 -> 3-8
6-4 -> 99-0

Merge error code 3-3 to 3-8, 6-4 to 99-0.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMappingTest.java

Optimize MetadataServiceNameMapping cas report conflict

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/mock/MockServiceDiscovery.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/registry/MockServiceDiscovery.java
dubbo-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscovery.java
dubbo-kubernetes/src/test/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscoveryTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ReflectionBasedServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/support/MockServiceDiscovery.java
dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastServiceDiscovery.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

Recreate `serviceInstance` when updating.

Fix service instance update failed

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java

Enhance nacos service discovery update

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Fixes https://github.com/apache/dubbo/issues/11216

Fix app level configuration not work

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceDelegation.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/ServiceDiscoveryCacheTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/support/MockServiceDiscovery.java
dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleServiceDiscovery.java

Store old revisions

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Fix Multi Registry Override

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

Fix zk resubscribe failed

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java

Add some cas update failed logs

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java

Fix cas log parameter

---

dubbo-common/src/main/java/org/apache/dubbo/common/metrics/collector/DefaultMetricsCollector.java
dubbo-common/src/main/java/org/apache/dubbo/common/metrics/collector/stat/DefaultMetricsStatHandler.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/filter/MetricsCollectExecutor.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilter.java

Fix dubbo3.2 request matric code format

fix: code format

---

dubbo-native-plugin/src/main/resources/META-INF/native-image/reflect-config.json

Fix native about reflect config

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConsumerConfigTest.java

Fix config unable to serialize

---

dubbo-demo/dubbo-demo-triple/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-rpc/dubbo-rpc-triple/pom.xml
dubbo-xds/pom.xml

Update protobuf-java version in both dependency and plugin

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java

Fix test cases for service name mapping

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/AllowClassNotifyListener.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityManager.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/Fastjson2SecurityManager.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2AllowClassManager.java

Switch default check level

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java

fix issue #11277

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityManager.java

Add check status option

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

Fix service discovery metadata update failed

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-nacos/src/test/java/org/apache/dubbo/configcenter/support/nacos/MockConfigService.java
dubbo-configcenter/dubbo-configcenter-nacos/src/test/java/org/apache/dubbo/configcenter/support/nacos/RetryTest.java
dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java
dubbo-metadata/dubbo-metadata-report-nacos/src/test/java/org/apache/dubbo/metadata/store/nacos/MockConfigService.java
dubbo-metadata/dubbo-metadata-report-nacos/src/test/java/org/apache/dubbo/metadata/store/nacos/RetryTest.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosRegistryFactoryTest.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosRegistryTest.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosServiceDiscoveryFactoryTest.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosServiceDiscoveryTest.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtilsTest.java

Add nacos create client retry

---

.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/release-test.yml

Enable multi remote version integration test

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

Fix instance revision check

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java

Refactor nacos to update

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ReflectionAbstractServerCall.java

change class loader

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

Enhance class forname in triple

---

dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/XdsServiceDiscovery.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/AdsObserver.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/PilotExchanger.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/XdsListener.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/AbstractProtocol.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/impl/EdsProtocol.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/impl/LdsProtocol.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/impl/RdsProtocol.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/message/Endpoint.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/message/RouteResult.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/EdsEndpointManager.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/RdsRouteRuleManager.java
dubbo-xds/src/test/java/org/apache/dubbo/registry/xds/util/protocol/impl/DsProtocolTest.java
dubbo-xds/src/test/java/org/apache/dubbo/registry/xds/util/protocol/impl/EdsProtocolMock.java
dubbo-xds/src/test/java/org/apache/dubbo/registry/xds/util/protocol/impl/LdsProtocolMock.java
dubbo-xds/src/test/java/org/apache/dubbo/registry/xds/util/protocol/impl/RdsProtocolMock.java

Make xds router run

---

dubbo-native-plugin/src/main/resources/META-INF/native-image/reflect-config.json
dubbo-native-plugin/src/main/resources/META-INF/native-image/resource-config.json

Support fastjson2 in native case

---

.github/dependabot.yaml

As discussed in #11308, a Dependabot config is helpful for maintaining the project. For now, the config is set up to only suggest minor or patch version updates as its main intention is to keep up with bug and vulnerability fixes. Major version updates rarely can be automated as they usually break the build. 
This will add a Dependabot config with the following properties:
- Runs every Monday at 3am eastern time
- Will ignore major version updates
- Never has more than 20 open PRs at any given time
- The above properties are a suggestion and I'm happy to discuss any changes.
- I performed a dry-run and Dependabot will initially create a bunch of PRs (roughly 20). That will be a bit of work to go through them.
- Unfortunately it is not possible to exclude subfolders from the scan. So it …

Add Dependabot Config

---

dubbo-common/src/main/java/org/apache/dubbo/common/metrics/collector/DefaultMetricsCollector.java
dubbo-common/src/main/java/org/apache/dubbo/common/metrics/model/MetricsKey.java
dubbo-common/src/test/java/org/apache/dubbo/common/metrics/collector/DefaultMetricsCollectorTest.java

https://github.com/apache/dubbo/issues/11321
Change the name according to the naming convention
`mvn test` is ok.

Change the name according to the naming convention

---

dubbo-common/src/main/java/org/apache/dubbo/common/deploy/AbstractDeployer.java

fix deploy listener exception.
issue url: https://github.com/apache/dubbo/issues/11027

feat: fix deploy listener exception

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/release-test.yml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/src/main/java/com/apache/dubbo/demo/graalvm/consumer/Application.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/src/main/java/org/apache/dubbo/demo/graalvm/provider/Application.java

Support native ci check

---

dubbo-dependencies-bom/pom.xml

Bump spring version from 5.2.20.RELEASE to 5.3.25

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityManager.java

Fix https://github.com/apache/dubbo/issues/11394

Fix CME in SerializeSecurityManager

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/JRE.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/JRETest.java

Add JRE utils (#11393)

---

dubbo-dependencies-bom/pom.xml

Manage codehaus-jackson version in dependencies bom

---

dubbo-common/src/main/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtil.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeClassChecker.java
dubbo-common/src/test/java/org/apache/dubbo/common/beanutil/Bean.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/Person.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/User.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/SerializeClassCheckerTest.java

[2.7] Add serializable check for pojo

---

dubbo-common/src/main/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtil.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeClassChecker.java
dubbo-common/src/test/java/org/apache/dubbo/common/beanutil/Bean.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/Person.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/User.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/SerializeClassCheckerTest.java

[3.0] Add serializable check for pojo

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/QosScopeModelInitializer.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/SerializeCheckStatus.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/SerializeCheckUtils.java
dubbo-plugin/dubbo-qos/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.qos.command.BaseCommand
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/SerializeCheckStatusTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/SerializeCheckUtilsTest.java

Add SerializeCheckStatus command

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityConfigurator.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/SerializeSecurityConfiguratorTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolSecurityWrapper.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/FastJson2Serialization.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2Serialization.java

Fix classname

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/DefaultSerializeClassChecker.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityManager.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/DefaultSerializeClassCheckerTest.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/SerializeWarnedClasses.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/SerializeCheckUtils.java
dubbo-plugin/dubbo-qos/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.qos.command.BaseCommand
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/SerializeWarnedClassesTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/Fastjson2SecurityManager.java

Add SerializeWarnedClasses qos support

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityConfigurator.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityManager.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolSecurityWrapper.java

Enhance check

---

dubbo-dependencies/dubbo-dependencies-zookeeper-curator5/pom.xml

Fix curator5 version

---

dubbo-dependencies-bom/pom.xml

Bump netty from 4.1.72.Final to 4.1.87.Final

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AdaptiveMetrics.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AttachmentsAdapter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/FutureContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AdaptiveLoadBalanceFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/CompatibleFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolSerializationWrapper.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/FutureAdapter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/AccessLogData.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCountCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolServer.java

Solution to #11502. 
> Optimization of the problem that the attributes of some classes in the dubbo-rpc module lacks the 'final' modifier.

Modifier optimization, add 'final' modifier.

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java

Rename file cache to prevent being duplicated with CacheFilter

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java

We should not adopt the scheme of "first put new elements, then judge the capacity, and if it is full, trigger the proceedEviction() method".Instead, we should adopt the scheme of "first determine the capacity, then trigger the proceedEviction() method if it is full, and finally put in new elements".
```
@Test
void testPutAndGet() {
LFUCache<String, Integer> cache = new LFUCache<>(5, 0.2f);
for (int i = 0; i < 5; i++) {
cache.put(i + "", i);
cache.get(i + "");
}
cache.put("why", 18);
Integer why = cache.get("why");
System.out.println("why = " + why);
}
```
expect：18
but：null
before fix，when we put new element：first put new elements, then judge the capacity, and if it is full, trigger the proceedEviction() method.
so, "why" be eviction after proceedEviction() method.
Instead, we should …

Fix the bug in LFUCache#put() method

---

dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/FastJsonImpl.java
dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/GsonImpl.java
dubbo-common/src/test/java/org/apache/dubbo/common/json/impl/FastJsonImplTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/json/impl/GsonImplTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/JsonUtilsTest.java

To fix https://github.com/apache/dubbo/issues/11441

Enhance json util check

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java

Fix https://github.com/apache/dubbo/issues/11490

Fix config absent when refresh

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/DefaultSerializeClassChecker.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/FastJson2ObjectInput.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/FastJson2ObjectOutput.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/FastJson2Serialization.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/Fastjson2SecurityManager.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2SerializerFactory.java

Enhance serializable check option

---

dubbo-common/src/main/java/org/apache/dubbo/common/deploy/ApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataConstants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Try update service discovery for each 1s
- When application is starting, refresh each 30s
- When service is updating, refresh each 5s

Enhance service discovery update interval

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2SerializerFactory.java

Fix hessian2 serializable check

---

dubbo-common/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityConfigurator.java
dubbo-common/src/test/java/com/service/DemoService4.java
dubbo-common/src/test/java/com/service/DemoService5.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/SerializeSecurityConfiguratorTest.java

Fix https://github.com/apache/dubbo/issues/11560

Fix stackoverflow in SerializeSecurityConfigurator

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ProfilerServerFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvocationUtil.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

Set timeout value to string

---

.codecov.yml

Update codecov config

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ModuleEnvironment.java

Fix synchronized in ModelEnvironment

---

README.md

fixing the broken links (readme.md)

fixed broken link readme.md

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandler.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparatorTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationInvokerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandlerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/model/MigrationRuleTest.java

1. Fix volatile problem
2. Thread pool leak fix
3. Code optimization

Migration bugfix & optimization

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

verify https://github.com/apache/dubbo-samples/pull/747
fix https://github.com/apache/dubbo/issues/11648

fix tri wrapper pack npe

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/observation/ObservationReceiverFilter.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/observation/ObservationSenderFilter.java
dubbo-metrics/dubbo-metrics-default/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
dubbo-metrics/dubbo-metrics-default/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.filter.ClusterFilter

There were some problems with the previous migration.

fix: fix observation spi config

---

dubbo-maven-plugin/src/main/resources/META-INF/native-image/reflect-config.json

Sync reflect config

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/ConfiguratorFactory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterFactory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouterFactory.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/ConfiguratorFactory.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/report/MetricsReporterFactory.java
dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/MonitorFactory.java

feat: optimize code

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

optimize the multi params request performance of triple in wrap mode
reuse `ByteArrayOutputStream` in pack `wrap request`

optimize the multi params request performance of triple in wrap mode

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleCustomerProtocolWapper.java

replaced with EN assert

---

dubbo-dependencies-bom/pom.xml
dubbo-xds/pom.xml

Bump grpc-java from 1.41.0 to 1.53.0

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/sample/GaugeMetricSample.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/DefaultMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/MethodMetricsSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/SimpleMetricsCountSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/ThreadPoolMetricsSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsReporter.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/service/DefaultMetricsService.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/metrics/collector/DefaultMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/metrics/model/sample/GaugeMetricSampleTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/sampler/CountSamplerTest.java
dubbo-metrics/dubbo-metrics-metadata/src/main/java/org/apache/dubbo/metrics/metadata/collector/stat/MetadataStatComposite.java
dubbo-metrics/dubbo-metrics-metadata/src/test/java/metrics/metrics/collector/MetadataMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-registry/src/main/java/org/apache/dubbo/metrics/registry/collector/stat/RegistryStatComposite.java
dubbo-metrics/dubbo-metrics-registry/src/test/java/org/apache/dubbo/metrics/registry/metrics/collector/RegistryMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-registry/src/test/java/org/apache/dubbo/metrics/registry/metrics/collector/RegistryMetricsSampleTest.java
dubbo-metrics/dubbo-metrics-registry/src/test/java/org/apache/dubbo/metrics/registry/metrics/model/sample/GaugeMetricSampleTest.java

Observability task: refactor GaugeMetricSample

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/MethodMetricsSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/MetricsCountSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/SimpleMetricsCountSampler.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/sampler/CountSamplerTest.java

RT metrics bugfix

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java

fix reference bean name conflicts 
这个问题之前修复过一次，情况没有考虑全面， 启动顺序不同会导致失败
eg:
```
@DubboReference
private AService aservice;
@DubboReference
private AService bservice;
@DubboReference
private BService bservice;
```
当 `AService` 扫描完成以后, 容器中为
1.  ` beanDefintions("aservice",ABeanDefinitonInfo) `
2.  ` alias ("bservice","aservice")`
扫描`BService` 时 容器中为
1. `BeanDefinitions ("bservice":BDefinitionInfo)` 
因为当扫描`BService`  执行到   ` if (beanDefinitionRegistry.containsBeanDefinition(referenceBeanName))`  这里 `referenceBeanName 值为 bservice ` 会返回false， 且`bservice `是第一次注册会直接注册到 BeanDefinitions 中
此时会出现即注册了 `AService `的alias `bservice` 又注册了 `BService`的 `beanDefinition `的`bservice `，在注入属性时会获取到错误的类型
修改判断逻辑 ,同时判断当前 `referenceBeanName `是否在`beanDefinition` 或者是否被注册为别名,
1. 存在 `beanDefinition`中时 执行旧的逻辑
2. …

fix reference bean name conflicts

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MethodMetricsInterceptor.java

abnormal time count

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

:bug: fix push metadata code meter collector location

:bug: fix push metadata code meter collector location

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/pu/TelnetDetector.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/buffer/ChannelBuffer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/buffer/DynamicChannelBuffer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyBackedChannelBuffer.java

Fix qos ByteBuf leak

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/AbstractDefaultDubboObservationConvention.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DefaultDubboClientObservationConvention.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DefaultDubboServerObservationConvention.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DubboClientContext.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DubboClientObservationConvention.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DubboObservation.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DubboServerContext.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DubboServerObservationConvention.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/observation/ObservationReceiverFilter.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/observation/ObservationSenderFilter.java
dubbo-spring-boot/dubbo-spring-boot-observability-starter/pom.xml
dubbo-spring-boot/dubbo-spring-boot-observability-starter/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/DubboObservationAutoConfiguration.java
dubbo-spring-boot/pom.xml

[dubbo-samples issue 762](https://github.com/apache/dubbo-samples/pull/762)
- add micrometer bom to observability
- optimize the structure of the package

fix: add micrometer bom to observability & optimize the structure of the package

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/event/MethodEvent.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/event/MetricsEvent.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MetricsKey.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/MethodMetricsSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MethodMetricsInterceptor.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsClusterFilter.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/metrics/collector/DefaultMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/sampler/CountSamplerTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

:bug: fix the disorder of aggregation indicators

:bug:Fix/consumer provider metrics name cover

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/InvokerCountWrapper.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ReferenceCountInvokerWrapper.java
dubbo-rpc/dubbo-rpc-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Protocol

Fix recreate client after destroy

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java

Fix https://github.com/apache/dubbo/issues/11680

Sync when destroy

---

dubbo-plugin/dubbo-security/src/main/java/org/apache/dubbo/security/cert/CertDeployerListener.java

```java
2023-03-13 15:30:55.902  INFO 8937 --- [.0/0.0.0.0:2181] o.apache.zookeeper.server.NIOServerCnxn  : Closed socket connection for client /127.0.0.1:63901 which had sessionid 0x100026f629a0000
2023-03-13 15:30:55.902 ERROR 8937 --- [           main] o.a.d.common.deploy.AbstractDeployer     :  [DUBBO] Dubbo Application[1.0](DUBBO_INTERNAL_APPLICATION) an exception occurred when handle stopping event, dubbo version: 3.2.0-beta.6-SNAPSHOT, current host: 10.201.67.59, error code: 0-14. This may be caused by , go to https://dubbo.apache.org/faq/0/14 to find instructions. 
java.lang.NullPointerException: null
at org.apache.dubbo.security.cert.CertDeployerListener.onStopping(CertDeployerListener.java:52) ~[dubbo-3.2.0-beta.6-SNAPSHOT.jar:3.2.0-beta.6-SNAPSHOT]
at …
```

Cert npe bug fix

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

fix remove unused param in method

fix remove unused param

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/PackableMethod.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCallListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/UnaryServerCallListener.java

relate https://github.com/apache/dubbo/issues/11762

Reactor tri diy exception api

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/ApplicationMetric.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MetricsKey.java

add commit id metrics

---

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

Add spring configuration for QOS function.

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java

Fix bug issue #11790

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

Tripless compressor is currently hard-coded and read from configuration.

Triple read compressor from config

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/TimeUtils.java

In TimeUtils, shutdownHook may be executed early, thus affecting the result of CI

Fix CI bugs about TimeWindow

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsReporter.java

Similar to  #11842 , the cpu indicator also has a NaN bug
```
static <T> Builder<T> builder(String name, @Nullable T obj, ToDoubleFunction<T> f) {
return new Builder<>(name, obj, f);
}
```
When using the above api, if T(obj) has no other strong references, gc will cause it to be recycled and print NaN.
We need to save a strong reference to the obj instance.

weak gc bug fix

---

dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java

Fix issue #11844  #11849. It's all because of the 'default' problem.

Fix issue #11844

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/SlidingWindow.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/aggregate/TimeWindowCounterTest.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/aggregate/TimeWindowQuantileTest.java

Fix SlidingWindow test case bug.  Tortured by this problem.

Fix SlidingWindow test case bug

---

dubbo-common/src/main/resources/security/serialize.allowlist

The pojo has field with java.util.Collections$SingletonList type when use dubbo
and then the dubbo print ERROR log:
```
11:18:31.217 [main] ERROR org.apache.dubbo.common.serialize.fastjson2.Fastjson2SecurityManager -  
[DUBBO] [Serialization Security] Serialized class java.util.Collections$SingletonList is not in allow list. 
Current mode is `WARN`, will allow to deserialize it by default. 
Dubbo will set to `STRICT` mode by default in the future. 
Please add it into security/serialize.allowlist or follow FAQ to configure it.
, dubbo version: 3.2.0-beta.4, current host: 160.6.56.171, error code: 4-21. 
This may be caused by , go to https://dubbo.apache.org/faq/4/21 to find instructions. 
```
Avoid compatibility issues when Dubbo sets to STRICT mode by default in the future. 
add these …

add classes of java.util.x into serialize.allowlist file to avoid compatibility issues in the future

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/SpringCloudServiceInstanceNotificationCustomizer.java

Only support rest convert when all servers are from spring cloud

---

dubbo-common/src/main/java/org/apache/dubbo/common/function/ThrowableSupplier.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ExecutorUtil.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/DeadlineFuture.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ClientCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ObserverToClientCallListenerAdapter.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleMessageProducer.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/UnaryClientCallListener.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/DeadlineFutureTest.java

optimize performance. decode in user thread

optimize performance. decode in user thread

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/ExchangeCodecTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCountCodecTest.java

Reject if response do not match any request

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MetricsCategory.java
dubbo-metrics/dubbo-metrics-metadata/src/main/java/org/apache/dubbo/metrics/metadata/collector/MetadataMetricsCollector.java
dubbo-metrics/dubbo-metrics-metadata/src/main/java/org/apache/dubbo/metrics/metadata/collector/stat/MetadataStatComposite.java
dubbo-metrics/dubbo-metrics-registry/src/main/java/org/apache/dubbo/metrics/registry/collector/RegistryMetricsCollector.java
dubbo-metrics/dubbo-metrics-registry/src/main/java/org/apache/dubbo/metrics/registry/event/MetricsServiceSubscribeListener.java
dubbo-metrics/dubbo-metrics-registry/src/test/java/org/apache/dubbo/metrics/registry/metrics/collector/RegistryMetricsCollectorTest.java

bugfix && add testcase

---

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidatorNew.java

#11878 
Remove simplified logic for ConstraintViolationException. The reason is as follows:
- I checked the historical submission records, but did not find the corresponding serialization issues to support the simplified logic.
- Assuming it does cause serialization issues, it's not optimal to fix it here.

Remove simplified logic for ConstraintViolationException

---

.github/workflows/build-and-test-scheduled-3.2.yml

Fix native ci for scheduled

---

.github/workflows/build-and-test-scheduled-3.1.yml

【3.2】Fix native ci

---

dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/MemorySafeLinkedBlockingQueueTest.java

[ISSUE #10020] test efficiency of MemorySafeLinkedBlockingQueue

[ISSUE #10020] test efficiency of MemorySafeLinkedBlockingQueue

---

dubbo-common/src/main/java/org/apache/dubbo/common/BatchExecutorQueue.java

fix BatchExecutorQueue bug

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ObservationSenderFilter.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/AbstractDefaultDubboObservationConvention.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DefaultDubboClientObservationConvention.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DefaultDubboServerObservationConvention.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/observation/DubboObservationDocumentation.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/observation/ObservationReceiverFilter.java
dubbo-spring-boot/dubbo-spring-boot-observability-starter/pom.xml
dubbo-spring-boot/dubbo-spring-boot-observability-starter/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/otel/OpenTelemetryAutoConfiguration.java

- `DubboClientObservationConvention` and `DubboServerObservationConvention` singleton
- rename `DubboObservation` to `DubboObservationDocumentation`
- add `dubbo-common` to `dubbo-spring-boot-observability-starter`

chore: some tracing-related optimizations

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java

binary search weights Fixes 11776

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MethodMetricsInterceptor.java

🐛 if it has exception processing request need end too.

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java

The current PR is a complement to PR #11517,  implements provider-side load checking.

Provider side payload checking

---

dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.Cluster
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.filter.ClusterFilter

Due to changes in the location of a and b, the configuration file of the corresponding spi will also change.

fix: fix ObservationSenderFilter and MetricsClusterFilter spi config

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/model/ConditionRuleParser.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshAppRuleListener.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/config/model/ScriptRule.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/model/TagRuleParser.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParserTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshAppRuleListenerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleManagerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouterTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/config/YamlPropertySourceFactory.java
dubbo-dependencies-bom/pom.xml
dubbo-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesMeshEnvListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java

Bump snakeyaml from 1.32 to 2.0

---

dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/MemorySafeLinkedBlockingQueueTest.java

Disable some test cases

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/sample/CounterMetricSample.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/DefaultMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsReporter.java

:bento: try change application metrics to counter

:bento: try change application metrics to counter

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/person/Ageneric.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/person/Bgeneric.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/person/Cgeneric.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/person/Dgeneric.java
dubbo-common/src/test/java/org/apache/dubbo/common/model/person/PersonGenericInfo.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java

PojoUtils support generic class with return data no classname

pojoutil support generic

---

dubbo-xds/pom.xml

feat: lowwer version

---

dubbo-common/src/main/java/org/apache/dubbo/common/deploy/ApplicationDeployListener.java
dubbo-common/src/main/java/org/apache/dubbo/common/deploy/DeployListener.java
dubbo-common/src/main/java/org/apache/dubbo/common/deploy/DeployListenerAdapter.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ExporterDeployListener.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/MultiInstanceTest.java
dubbo-plugin/dubbo-security/src/main/java/org/apache/dubbo/security/cert/CertDeployerListener.java

Add onInitialize Support

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

Metrics bug of metadata push/subscribe

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLBuilderTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLStrParserTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/url/URLParamTest.java

Related with https://github.com/apache/dubbo/pull/11385
Fix https://github.com/apache/dubbo/issues/10804

Fix URLParam decode default value

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/listener/InjvmExporterListener.java

```
(16:54:21) WARNING:  [DUBBO] Unexpected error occurred when destroy invoker of ReferenceConfig(null)., dubbo version: 3.2.0.7-aliyun, current host: 11.122.233.162, error code: 5-3. This may be caused by , go to https://dubbo.apache.org/faq/5/3 to find instructions. 
(16:54:21) java.lang.NullPointerException
(16:54:21) 	at org.apache.dubbo.rpc.listener.InjvmExporterListener.removeExporterChangeListener(InjvmExporterListener.java:125)
(16:54:21) 	at org.apache.dubbo.rpc.cluster.support.wrapper.ScopeClusterInvoker.destroy(ScopeClusterInvoker.java:101)
(16:54:21) 	at org.apache.dubbo.registry.client.migration.MigrationInvoker.destroy(MigrationInvoker.java:329)
(16:54:21) 	at org.apache.dubbo.config.ReferenceConfig.destroy(ReferenceConfig.java:246)
(16:54:21) 	at …
```

Fix removeExporterChangeListener NPE

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionHandler.java

fix the bug of reconnect

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/PackableMethod.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

triple serialize check

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

tri serial check

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ClientsProvider.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ExclusiveClientsProvider.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/SharedClientsProvider.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvailableTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java

Fix Dubbo ReferenceCount OOM

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/FrameworkExecutorRepository.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/InternalServiceConfigBuilder.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultMetricsServiceExporter.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java

Set isolated executor for internal services

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityConfigurator.java
dubbo-common/src/main/resources/security/serialize.allowlist
dubbo-common/src/test/resources/security/serialize.allowlist
dubbo-plugin/dubbo-qos/src/test/resources/security/serialize.allowlist
dubbo-remoting/dubbo-remoting-api/src/test/resources/security/serialize.allowlist
dubbo-remoting/dubbo-remoting-netty/src/test/resources/security/serialize.allowlist
dubbo-remoting/dubbo-remoting-netty4/src/test/resources/security/serialize.allowlist
dubbo-rpc/dubbo-rpc-api/src/test/resources/security/serialize.allowlist
dubbo-rpc/dubbo-rpc-dubbo/src/test/resources/security/serialize.allowlist
dubbo-rpc/dubbo-rpc-triple/src/test/resources/security/serialize.allowlist
dubbo-serialization/dubbo-serialization-fastjson2/src/test/resources/security/serialize.allowlist
dubbo-serialization/dubbo-serialization-hessian2/src/test/resources/security/serialize.allowlist

Deny allow

---

dubbo-dependencies-bom/pom.xml
dubbo-xds/pom.xml

M1 support

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java

Add the code removed by "Feature/3.2 rest protocol provider (#11640)"

Fixed the observable collection thread pool indicator

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MethodMetricsInterceptor.java

Metrics bug fix

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/stub/UnaryStubMethodHandler.java

fix https://github.com/apache/dubbo/issues/12076

fix tri stub exception

---

dubbo-demo/dubbo-demo-triple/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-rpc/dubbo-rpc-triple/pom.xml
dubbo-xds/pom.xml
pom.xml

Refactor pb version

---

dubbo-common/src/main/java/org/apache/dubbo/config/nested/ExporterConfig.java
dubbo-spring-boot/dubbo-spring-boot-observability-starter/dubbo-spring-boot-observability-autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/ObservabilityUtils.java
dubbo-spring-boot/dubbo-spring-boot-observability-starter/dubbo-spring-boot-observability-autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/exporter/zipkin/ZipkinAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-observability-starter/dubbo-spring-boot-observability-autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/exporter/zipkin/ZipkinConfigurations.java

fix: bugfix of tracing zipkin npe when start

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/QosConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-plugin/dubbo-qos-api/src/main/java/org/apache/dubbo/qos/api/QosConfiguration.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/permission/DefaultAnonymousAccessPermissionChecker.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/permission/DefaultAnonymousAccessPermissionCheckerTest.java

QoS Support anonymous command allow list

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/PathAndInvokerMapper.java

fix comments in org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper#getRestMethodMetadata

fix comments

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/PathMatcher.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/RequestMetadata.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/ServiceRestMetadata.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/rest/api/JaxrsUsingService.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/rest/jaxrs/JaxrsRestDoubleCheckTest.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/PathAndInvokerMapper.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestRPCInvocationUtil.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/handler/NettyHttpHandler.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/JaxrsRestProtocolTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/rest/RestDemoForTestException.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/rest/RestDemoServiceImpl.java

405 && differnt httpmethod  path  doubleCheck   
https://github.com/apache/dubbo/issues/12142
@AlbumenJ

fix 405 && differnt httpmethod  path  doubleCheck

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java

Polish some  comments and logs

Polish comments and logs

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosConnectionManager.java

Follow #11262, disable cache

---

dubbo-demo/dubbo-demo-xml/dubbo-demo-jaxrs-rest-consumer/pom.xml
dubbo-demo/dubbo-demo-xml/dubbo-demo-jaxrs-rest-consumer/src/main/java/org/apache/dubbo/demo/rest/api/RestConsumer.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-jaxrs-rest-consumer/src/main/java/org/apache/dubbo/demo/rest/api/annotation/DubboServiceAnnotationServiceConsumer.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-jaxrs-rest-provider/pom.xml
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-consumer/pom.xml
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-consumer/src/main/java/org/apache/dubbo/demo/rest/api/SpringMvcRestConsumer.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-consumer/src/main/java/org/apache/dubbo/demo/rest/api/config/DubboConfig.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-consumer/src/main/java/org/apache/dubbo/demo/rest/api/consumer/SpringRestDemoServiceConsumer.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-consumer/src/main/resources/spring/rest-consumer.xml
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-provider/pom.xml
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-provider/src/main/java/org/apache/dubbo/demo/rest/api/SpringMvcRestProvider.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-provider/src/main/java/org/apache/dubbo/demo/rest/api/config/DubboConfig.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-provider/src/main/java/org/apache/dubbo/demo/rest/api/impl/SpringRestDemoServiceImpl.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-spring-mvc-rest-provider/src/main/resources/spring/rest-provider.xml
dubbo-demo/dubbo-demo-xml/pom.xml

add spring mvc rest demo
@AlbumenJ

add spring mvc rest demo

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java

Fix npe occurs during client graceful offline.

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/Pack.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/PackableMethod.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/PackableMethodFactory.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/UnPack.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/WrapperUnPack.java
dubbo-distribution/dubbo-all/pom.xml
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/DefaultPackableMethodFactory.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/PbArrayPacker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethodFactory.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ReflectionAbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/StubAbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.model.PackableMethodFactory
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/call/StubServerCallTest.java

support packable method extension

packable method extension

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyChannelHandler.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServerHandler.java

Fix https://github.com/apache/dubbo/issues/12202

Fix port unification channel leak

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/NettyHttpRestServer.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/netty/ssl/SslContexts.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/netty/ssl/SslServerTlsHandler.java

rest netty server add tls
@AlbumenJ

rest netty server add tls

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Ignore some keys registered to registry

---

.artifacts
dubbo-test/dubbo-test-modules/src/test/java/org/apache/dubbo/dependency/FileTest.java

Fix the dubbo-config-spring6 module is lost

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/utils/UrlUtils.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/utils/UrlUtilsTest.java

Default heartbeat configurable

---

dubbo-dependencies-bom/pom.xml

Bump fastjson2 version from 2.0.29 to 2.0.31

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java

Issue Number: close https://github.com/apache/dubbo/issues/12248

Bugfix when generic call in bean mode

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboConfigConfiguration.java

fix: fix mutiple tracing config

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityConfigurator.java
dubbo-common/src/main/resources/security/serialize.allowlist
dubbo-common/src/test/java/com/service/Params.java
dubbo-common/src/test/java/com/service/Service.java
dubbo-common/src/test/java/com/service/User.java
dubbo-common/src/test/java/com/service/UserService.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/SerializeSecurityConfiguratorTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolSecurityWrapper.java

Update level check

---

dubbo-demo/pom.xml
dubbo-test/pom.xml

Remove self used dubbo-bom

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/exception/mapper/ExceptionMapper.java

…recursively search the base class (#12245)

fix When the exception handling class cannot be obtained, it should recursively search the base class(#12245)

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java

Fix version detect

---

dubbo-dependencies-bom/pom.xml
dubbo-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/util/KubernetesConfigUtils.java
dubbo-kubernetes/src/test/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscoveryTest.java

- upgrade kubernetes-client to 6.6.0.
- Due to the removal of the `rolling timeout` in 6.5.0, we also need to make corresponding changes.
resolve #12259

chore: upgrade kubernetes-client to 6.6.0

---

.github/workflows/build-and-test-pr.yml
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/isolation/api/ApiIsolationTest.java

Update zk version

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2SerializerFactory.java

Fix allow non-serializable check

---

.artifacts
dubbo-common/src/main/java/org/apache/dubbo/config/nested/ExporterConfig.java
dubbo-distribution/dubbo-bom/pom.xml
dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/pom.xml
dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/ObservabilityUtils.java
dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/exporter/otlp/OtlpAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/src/main/resources/META-INF/spring.factories
dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
dubbo-spring-boot/dubbo-spring-boot-observability-starters/dubbo-spring-boot-tracing-otel-otlp-starter/pom.xml
dubbo-spring-boot/dubbo-spring-boot-observability-starters/pom.xml
dubbo-test/dubbo-dependencies-all/pom.xml

- add `dubbo-spring-boot-tracing-otel-otlp-starter`
- add `OtlpAutoConfiguration` to exporter.
samples: [https://github.com/apache/dubbo-samples/pull/844](https://github.com/apache/dubbo-samples/pull/844)
otlp arch:
result:

feat: add dubbo-spring-boot-tracing-otel-otlp-starter

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Support disable 2.6.x url configurators

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityManager.java

Support set default serialize check status

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetricsConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ExporterDeployListener.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

Metrics and Metadata Service Export when needed

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java
dubbo-common/src/test/java/org/apache/dubbo/common/url/URLParamTest.java

URLParamMap support toString

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java

Fix netty4 server close timeout

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java

Fix PojoUtils NPE problem

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeSecurityConfigurator.java

Skip scan object class

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java

Fix alibaba AbstractLoadBalance compact

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/MetricThreadPoolExhaustedListener.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/MetricsCountSampleConfigurer.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/MetricsCountSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/SimpleMetricsCountSampler.java
dubbo-metrics/dubbo-metrics-prometheus/src/test/java/org/apache/dubbo/metrics/prometheus/PrometheusMetricsThreadPoolTest.java

After several refactorings, some old code is no longer needed, so clean it up

Metrics Code clean

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java

Fix NPE if name not match in PojoUtils

---

dubbo-distribution/dubbo-all/pom.xml
pom.xml

see https://docs.oracle.com/en/java/javase/17/docs/specs/man/javadoc.html#additional-options-provided-by-the-standard-doclet

Javadoc ingore missing excpetion

---

dubbo-rpc/dubbo-rpc-triple/pom.xml

Override the maven-javadoc-plugin configuration that depends on the pass

---

dubbo-demo/dubbo-demo-triple/pom.xml

Skip demo javadoc

---

dubbo-plugin/dubbo-security/pom.xml
dubbo-xds/pom.xml

Skip security and xds module  javadoc plugin

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java

Add alibaba RpcContext getInvocation compact

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java

Enhance generic filter logs

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/RtStatComposite.java

fix invocation.getServiceKey maybe null

fix invocation.getServiceKey maybe null

---

dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/beans/factory/annotation/ReferenceAnnotationWithAotBeanPostProcessor.java
dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/beans/factory/annotation/ServiceAnnotationWithAotPostProcessor.java
dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/utils/AotUtils.java
dubbo-config/dubbo-config-spring6/src/test/java/org/apache/dubbo/config/spring6/utils/AotUtilsTest.java
dubbo-config/dubbo-config-spring6/src/test/java/org/apache/dubbo/config/spring6/utils/DemoService.java
dubbo-config/dubbo-config-spring6/src/test/java/org/apache/dubbo/config/spring6/utils/HelloRequest.java
dubbo-config/dubbo-config-spring6/src/test/java/org/apache/dubbo/config/spring6/utils/HelloRequestSuper.java
dubbo-config/dubbo-config-spring6/src/test/java/org/apache/dubbo/config/spring6/utils/HelloResponse.java
dubbo-config/dubbo-config-spring6/src/test/java/org/apache/dubbo/config/spring6/utils/Person.java
pom.xml

Fixed the issue of superclass and filed not being loaded automatically in the native serialization config scenario

---

dubbo-plugin/dubbo-security/pom.xml

Update grpc version

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Filter.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Result.java

Fix alibaba Filter / Result Compact

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java

Fix invoker recovery

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/LazyTargetInvocationHandler.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/LazyTargetSource.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java

Use Dubbo Proxy instead of Spring Proxy

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ToStringUtils.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/AccessLogData.java

fix build string error

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/cache/CacheFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/cache/support/AbstractCacheFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/common/DelegateURL.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/common/URL.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/common/serialize/Serialization.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/common/threadpool/ThreadPool.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/common/utils/UrlUtils.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/monitor/Monitor.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/monitor/MonitorFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/NotifyListener.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/Registry.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/RegistryFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/AbstractRegistry.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/AbstractRegistryFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/FailbackRegistry.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/remoting/Transporter.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invoker.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Protocol.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/ProxyFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/Configurator.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/ConfiguratorFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/LoadBalance.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/Router.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/RouterFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/RuleConverter.java

Fix https://github.com/apache/dubbo/issues/12376
1. Introduce DelegateURL
2. Create DelegateURL instead of alibaba URL
3. Fix LoadBalance invoker convert

Introduce DelegateURL to proxy apache URL to alibaba URL

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/FilterChainBuilder.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Filter.java

Check if return AsyncRpcResult in Filter

---

dubbo-common/src/main/java/org/apache/dubbo/common/deploy/ApplicationDeployer.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Exporter.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/multiple/exportprovider/MultipleRegistryCenterExportProviderIntegrationTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Exporter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/listener/ListenerExporterWrapper.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractExporter.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocol.java

Register services after module started

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ReferenceCache.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/CompositeReferenceCache.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/SimpleReferenceCache.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/MockReferenceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/XxxMockReferenceConfig.java

Check reference after register

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandlerTest.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/test/resources/META-INF/spring/dubbo-context.xml

Fix https://github.com/apache/dubbo/issues/12473

Resolve conflicts of spring bean

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/event/DubboModuleStateEvent.java

Publish Module deployer state event

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/PageServlet.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboSpringInitCustomizerHolder.java
dubbo-demo/dubbo-demo-interface/src/main/java/org/apache/dubbo/demo/rest/api/JaxRsRestDemoService.java

I have corrected all the spelling mistakes I found
sytle--style , programing--programming, anntation--annotation , diffrent--different 
- [] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.

Correcting spelling mistakes

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/ThreadlessExecutor.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/ThreadlessExecutorTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java

Fix long time await in ThreadlessExecutor

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

Check registry in checkAndUpdateSubConfigs

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosConnectionManager.java

Add some nacos connection logs

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/PathMatcher.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/ServiceRestMetadata.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/PathMatcherTest.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/PathAndInvokerMapper.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestRPCInvocationUtil.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/constans/RestConstant.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/handler/NettyHttpHandler.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/JaxrsRestProtocolTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/rest/TestGetInvokerService.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/rest/TestGetInvokerServiceImpl.java

export path matcher invoker to user
@CrazyHZM

Feature/dubbo3.2 export path matcher&invoker to user

---

.artifacts
dubbo-distribution/dubbo-bom/pom.xml
dubbo-test/dubbo-dependencies-all/pom.xml
dubbo-test/dubbo-test-modules/src/test/java/org/apache/dubbo/dependency/FileTest.java

fix dependency check

---

dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

Support Reference check timeout

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java

Support client gracefully shutdown

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProtocol.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProxyProtocol.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestProtocol.java

Fix https://github.com/apache/dubbo/issues/12476

Fix AbstractProxyProtocol compatibility

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/BiStreamServerCallListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ClientCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ObserverToClientCallListenerAdapter.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ServerStreamServerCallListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/UnaryClientCallListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/UnaryServerCallListener.java

Support set actual content length to inv/res attributes

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
pom.xml

In native scenarios, Compiler and Proxy are set to jdk by default 

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

fix issue https://github.com/apache/dubbo/issues/12526
remove duplicate names in url methods param
I test on my local env

fix issue#12526

---

README.md

The path is wrong, modify the correct path.
Modify the path described in the document.

docs: Add path to cd dubbo-samples/1-basic/dubbo-samples-api in the README.md.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryNotifier.java

Fix Registry Notification use same event time

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java

Fix config center properties log level

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/ScopeClusterInvoker.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

Fix https://github.com/apache/dubbo/issues/12545

Fix local invoke consumer url override

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java

StaticDirectory should throw destroyed exception instead of IndexOutOfBoundsException after destroyed.
```
java.lang.IndexOutOfBoundsException: null
at org.apache.dubbo.rpc.cluster.router.state.BitList.get(BitList.java:268) ~
at org.apache.dubbo.rpc.cluster.directory.StaticDirectory.getInterface(StaticDirectory.java:65) ~
at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.getInterface(AbstractClusterInvoker.java:100) ~
at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:69) ~
```

Cache interfaceClass in advance to prevent IndexOutOfBoundsException

---

dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/filter/AuthenticationExceptionTranslatorFilter.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/filter/ContextHolderAuthenticationPrepareFilter.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/filter/ContextHolderAuthenticationResolverFilter.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/model/SecurityScopeModelInitializer.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/utils/SecurityNames.java

Check if jackson2 security dependency existed

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java

Skip check ignored extensions

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invocation.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcInvocation.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceInstance.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invocation.java

Add transient to some overrided field

---

dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

Disable register if registry disable register

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/multiple/exportprovider/MultipleRegistryCenterExportProviderIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/single/exportprovider/SingleRegistryCenterExportProviderIntegrationTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryScopeModelInitializer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/ExporterFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/ReferenceCountExporter.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Fix registry repeat export same service

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/common/Constants.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcException.java

Fix alibaba Rpc compact

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/AbstractRetryTask.java

Change retry times to forever

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

Skip catch SkipFailbackWrapperException in NacosRegistry

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

Read heartbeat from util when recreate url in ExchangeClient

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java

remove some unnecessary check and code

remove unnecessary code

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

Disable subscribe nacos legacy name in 3.3

---

dubbo-dependencies-bom/pom.xml

Revert "Bump netty4_version from 4.1.92.Final to 4.1.94.Final"

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/ScopeClusterInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Pretty invokers toString format

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/MethodStatComposite.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/ServiceStatComposite.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/collector/DefaultCollectorTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java
dubbo-metrics/dubbo-metrics-metadata/src/test/java/org/apache/dubbo/metrics/metadata/MetadataMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-registry/src/test/java/org/apache/dubbo/metrics/registry/metrics/collector/RegistryMetricsCollectorTest.java

Temporally remove fill zero in metrics due to performance issue

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientReconnectTest.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ClientReconnectTest.java

Set minimal reconnect period as `60s` even heartbeat is smaller than `60s`

Update minimal reconnect period

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ByteAccessor.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java

ByteAccessor support customize RpcResult

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java

Fix shutdown timeout override

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-plugin/dubbo-qos-api/src/main/java/org/apache/dubbo/qos/api/CommandContext.java

Enhance CommandContext toString

---

dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/ObjectInput.java

Enhance logs

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Request.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/RequestTest.java

Use random id

---

dubbo-metadata/dubbo-metadata-definition-protobuf/src/main/java/org/apache/dubbo/metadata/definition/protobuf/ProtobufTypeBuilder.java

Enhance protobuf builder logs

---

dubbo-common/src/main/java/org/apache/dubbo/common/resource/GlobalResourcesRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/FrameworkExecutorRepository.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractCacheManager.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/FastJson2Serialization.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2Serialization.java

Wait executor terminated & Remove some usage of default model

---

dubbo-common/src/main/java/org/apache/dubbo/config/nested/AggregationConfig.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/TimeWindowCounter.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MetricsSupport.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/event/DefaultSubDispatcher.java

Enhance metrics

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/filter/ServiceInvokeRestFilter.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/handler/NettyHttpHandler.java

The Response Filter and Response Interceptor handle exceptions

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Request.java

Support skip use secure random id

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java

Check if initialized for ReferenceBean

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/ResteasyContext.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/filter/ResteasyRequestContainerFilterAdapter.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/filter/ResteasyResponseContainerFilterAdapter.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/filter/ServiceInvokeRestFilter.java

Write the MediaType of Response in the result

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java

Fix anyMethodParameter using consumer first. (#12640)

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ProviderAppStateRouter.java

Fix https://github.com/apache/dubbo/issues/12540

Skip warn if provider app and consumer app are the same

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Tag key remove error

---

dubbo-metadata/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/rest/AbstractNoAnnotatedParameterProcessor.java
dubbo-metadata/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/rest/ArgInfo.java
dubbo-rpc/dubbo-rpc-rest/pom.xml
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestInvoker.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/annotation/ParamParserManager.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/annotation/consumer/inercept/RequestHeaderIntercept.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/annotation/param/parse/provider/BodyProviderParamParser.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/annotation/param/parse/provider/HeaderProviderParamParser.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/annotation/param/parse/provider/NoAnnotationParamProviderParamParser.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/HttpMessageCodecManager.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/HttpMessageDecode.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/ByteArrayCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/JsonCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/MultiValueCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/ResteasyResponseCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/StringCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/TextCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/XMLCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/util/DataParseUtils.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/util/NoAnnotationBodyParseUtil.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DataParseUtilsTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DemoService.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DemoServiceImpl.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/HttpMessageCodecManagerTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/NoAnnotationRestProtocolTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/User.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/noannotation/NoAnnotationDemoService.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/noannotation/NoAnnotationDemoServiceImpl.java

add rest provider body multipart  json that JsonUtils supports ut
@AlbumenJ @chickenlj

add rest provider body multipart  json that JsonUtils supports ut

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/LockUtils.java

Fix compact with spring 3.2.x

---

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

CuratorWatch unwatch , childListener is null

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Remove -1 delay usage

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Check if delay is -1 before property for manual publish

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

Fix register failed if re-register service discovery

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboInfraBeanRegisterPostProcessor.java

PutAll configs to application environment instead of override for spring properties

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/PathAndInvokerMapper.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/pair/InvokerAndRestMethodMetadataPair.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/JaxrsRestProtocolTest.java

#12802 
fix 动态修改rest接口配置，reExport 过程报错
@CrazyHZM

Feature/fix rest3.2 re export path double check exception

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java

Make sure method name when sendMessage error

Fix method name

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java

Generic call by gson support null args

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/CallbackConsumerContextFilter.java
dubbo-monitor/dubbo-monitor-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java

Fix #12773 Callback mode rpc context loss.

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/BaseOffline.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/GracefulShutdown.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Service offline speedup

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/identifier/MetadataIdentifier.java

Add toString to MetadataIdentifier

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

Only judge true isn't accurate

Use ProtocolUtils.isGeneric judge generic type

---

CHANGES.md
README.md
dubbo-spring-boot/dubbo-spring-boot-autoconfigure/README.md

I have corrected all the spelling mistakes I found

Correcting the document content

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/DefaultSerializeClassChecker.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/Fastjson2SecurityManager.java

Update log level for serialization check

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Fix Spring Listener order

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModelConstants.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/BaseOffline.java

Support keep running on spring closed with properties

---

dubbo-dependencies-bom/pom.xml

Bump fastjson2 version from 2.0.38 to 2.0.39

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/event/MetricsEventBus.java

🚑 add more metrics catch

---

dubbo-spring-boot/dubbo-spring-boot-actuator/README.md

Update README.md to fix a spell error

---

README.md

Fix readme.md for dubbo version

---

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

Fix https://github.com/apache/dubbo/issues/12927

Fix injvm params error

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClientTest.java

Fix shouldReconnect check

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java

Fix static directory metrics label

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java

enhance application discovery toString

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java

Check before init agg metrics

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/SimpleMetricsCountSampler.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/sample/ThreadRejectMetricsCountSampler.java

Fix conflict of 3.3

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanManager.java

Ignore start if scope model is LifeCycleManagedExternally

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java

Cleanup resoruce if qos start failed

---

dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/AbstractServerHttpChannelObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/h12/AbstractServerTransportListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/h12/grpc/GrpcHttp2ServerTransportListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/h12/http1/DefaultHttp11ServerTransportListener.java

fix h1 and grpc status code

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java

Support ignore refresh config

---

dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/JsonCodec.java
dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/JsonPbCodec.java
dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/JsonPbCodecFactory.java
dubbo-remoting/dubbo-remoting-http12/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.http12.message.HttpMessageCodecFactory

fix pb class not found

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/ResteasyContext.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/filter/ResteasyRequestContainerFilterAdapter.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/filter/ResteasyResponseContainerFilterAdapter.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/intercept/ResteasyWriterInterceptorAdapter.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/filter/ServiceInvokeRestFilter.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/filter/context/FilterContext.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/filter/context/RestFilterContext.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/handler/NettyHttpHandler.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/JaxrsRestProtocolTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/filter/TraceRequestAndResponseFilter.java

fix SerializationException

---

dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/restclient/HttpClientRestClient.java

Fix rest protocol NPE when using apache-http-client (#12916)

---

dubbo-native/src/main/java/org/apache/dubbo/aot/generate/AotProcessor.java

Ignore class loading failure when native is compiled

---

dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/JsonCodec.java
dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/JsonPbCodec.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/h12/grpc/GrpcCompositeCodec.java

1.fix pojo dependency protobuf class
2.json array args

fix pojo dependency protobuf class

---

dubbo-config/dubbo-config-spring/src/test/resources/META-INF/isolation/dubbo-provider.xml

Fix test cases in scheduled test

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

Fix triple generic invoke

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/MetricsConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetricsConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/DefaultMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsReporter.java

Support disable metrics init and sync

---

dubbo-common/src/main/java/org/apache/dubbo/common/logger/ErrorTypeAwareLogger.java

Add Javadoc of ErrorTypeAwareLogger.

---

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/filter/ValidationFilter.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidatorNew.java
dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/support/jvalidation/JValidatorTest.java
dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/support/jvalidation/mock/JValidatorTestTarget.java

Update jvalidator to support parameter name retrieval

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailSafeClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvokerTest.java

Fix unit test cases

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/TimeWindowCounter.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java

Fix qps time window unit

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java

Fix code style

---

.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/release-test.yml
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/isolation/dubbo-consumer.xml
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/aggregate/SlidingWindowTest.java

Fix uts on 3.2

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/release-test.yml
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/NettyClientToServerTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ActiveLimitFilterTest.java

Enhance unit test cases from scheduled tasks

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java

Fix generic array being changed

---

dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ReplierDispatcherTest.java

Enhance unit test cases in netty4

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2FactoryManager.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2SerializerFactory.java

Fix Hessian Serializer Factory concurrent issue

---

dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportTest.java

Enhance AbstractMetadataReportTest test case

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ReferenceCountInvokerWrapper.java

Fix invoker ignored to destroy when unlock failed

---

dubbo-plugin/pom.xml

Fix native module

---

dubbo-plugin/dubbo-plugin-loom/pom.xml

Fix dubbo-plugin-loom module groupId

---

dubbo-plugin/dubbo-plugin-loom/pom.xml
dubbo-plugin/pom.xml

Fix loom project pom

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/InternalServiceConfigBuilder.java

Fix https://github.com/apache/dubbo/issues/13133

Skip refresh registry config for internal service

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/MetricsConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetricsConfig.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsReporter.java

Support customize collector sync period

---

dubbo-dependencies-bom/pom.xml

Update to curator 5 by default in dependencies bom

---

dubbo-registry/dubbo-registry-multiple/src/test/java/org/apache/dubbo/registry/multiple/MultipleRegistry2S2RTest.java
dubbo-registry/dubbo-registry-zookeeper/pom.xml

Fix test cases run on jdk 8/11 in dubbo-registry-zookeeper
https://github.com/apache/dubbo/actions/runs/6439418270/job/17487260033

Update zookeeper registry dependencies

---

dubbo-plugin/dubbo-plugin-loom/src/main/java/org/apache/dubbo/common/threadpool/support/loom/VirtualThreadPool.java

Fix VirtualThreadPool apache license

---

dubbo-config/dubbo-config-spring/pom.xml
dubbo-configcenter/dubbo-configcenter-zookeeper/pom.xml

Fix zk dependency in metadata-report and config-center

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java

Add registry info to notify message.
For example:

Enhance application-level registry notify message

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/release-test.yml

https://dlcdn.apache.org/zookeeper/

Update zk address in workflow

---

.github/workflows/build-and-test-pr.yml

Update candidate version in actions workflow

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/TripleGoAwayHandler.java

Fix unable to receive go away frame

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/JAXRSClassConstants.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/ParamType.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/RestMetadataConstants.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/jaxrs/FormBodyParameterProcessor.java
dubbo-metadata/dubbo-metadata-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.rest.AnnotatedMethodParameterProcessor
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DemoService.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DemoServiceImpl.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/JaxrsRestProtocolTest.java

rest jboss @Form annotation support
@CrazyHZM

jboss @Form support

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/aot/TripleReflectionTypeDescriberRegistrar.java

Update TripleClientHandler to TripleGoAwayHandler

Fix TripleReflectionTypeDescriberRegistrar Compilation Failure

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java

Fix MigrationRule changing when load consumer default value

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/request/NettyRequestFacade.java

Compatible with lowercase request headers

fix: lowerCase header

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Fix service key params when remove service instance listener

---

dubbo-plugin/pom.xml

Follow https://github.com/apache/dubbo/pull/13266

Fix lost dubbo-compiler module

---

dubbo-plugin/pom.xml
dubbo-rpc/dubbo-rpc-triple/pom.xml

Fix dubbo-rpc-triple module compile failed 

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Fix MappingListener override in ServiceDiscoveryRegistry

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/filter/DubboContainerResponseContextImpl.java

Change the log level when the rest entity is changed

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

extract variables

---

dubbo-cluster/pom.xml

Fix https://github.com/apache/dubbo/actions/runs/6719173029/job/18260558947

Fix unit tests failed on JDK8

---

dubbo-dependencies-bom/pom.xml

Update com.alibaba.fastjson2:fastjson2: 2.0.41 -> 2.0.42

---

dubbo-build-tools/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper-curator5/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
dubbo-dependencies/pom.xml
dubbo-distribution/pom.xml
pom.xml

Support spotless

---

pom.xml

Spotless excludes licenseheader

---

.artifacts
dubbo-distribution/dubbo-bom/pom.xml
dubbo-test/dubbo-dependencies-all/pom.xml

Fix dubbo-spring-boot-configuration-metadata-compatible check

---

.github/workflows/build-and-test-pr.yml

Fix ci action name

---

dubbo-maven-plugin/pom.xml
dubbo-maven-plugin/src/main/java/org/apache/dubbo/maven/plugin/protoc/DubboProtocCompilerMojo.java
dubbo-maven-plugin/src/main/resources/version-matrix.properties
dubbo-plugin/dubbo-compiler/README.md

After merged 
```xml
<plugin>
<groupId>org.apache.dubbo</groupId>
<artifactId>dubbo-maven-plugin</artifactId>
<version>${dubbo.version}</version>
<executions>
<execution>
<goals>
<goal>compile</goal>
</goals>
</execution>
</executions>
</plugin>
```

Enhance compiler configuration

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ReflectionServiceDescriptor.java
dubbo-compiler/src/main/resources/Dubbo3InterfaceStub.mustache
dubbo-compiler/src/main/resources/Dubbo3TripleInterfaceStub.mustache
dubbo-compiler/src/main/resources/Dubbo3TripleStub.mustache

fix https://github.com/apache/dubbo/issues/13142
and the https://github.com/apache/dubbo/pull/13155 can merge

fix tri stub unary method overload

---

pom.xml

Follow https://github.com/apache/dubbo/pull/13416

Fix spotless check style failed for generated triple sources

---

pom.xml

Follow https://github.com/apache/dubbo/pull/13416

Fix spotless check style failed for generated auth sources

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanSupport.java

Fix https://github.com/apache/dubbo-samples/issues/1017

Fix attributes is not passed by BeanDefinition

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/build-and-test-scheduled-3.3.yml
.github/workflows/release-test.yml

Move integration test cases into apache/dubbo-integration-cases

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2FactoryManager.java

Related with https://github.com/apache/dubbo/issues/13504

Fix potential NPE in Hessian2FactoryManager

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/filter/ResteasyRequestContainerFilterAdapter.java

release the ByteBuf of the DubboPreMatchContainerRequestContext's NettyHttpRequest field

---

.github/ISSUE_TEMPLATE/bug_report.md

Change bug issue label to need-triage

---

dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/pom.xml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/pom.xml

Fix native demo logback dependency

---

dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/api/ExecutableDescriber.java
dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/api/ExecutableMode.java
dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/api/MemberCategory.java
dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/api/TypeDescriber.java
dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/generate/ReflectConfigMetadataRepository.java
dubbo-plugin/dubbo-native/src/main/java/org/apache/dubbo/aot/generate/ReflectionConfigWriter.java
pom.xml

Fix aot license

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java

fix complete already

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/extension/resteasy/intercept/ResteasyStatusCodeInterceptor.java
dubbo-rpc/dubbo-rpc-rest/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.protocol.rest.filter.RestResponseInterceptor
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/ResteasyResponseTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/rest/RestDemoService.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/rest/RestDemoServiceImpl.java

resteasy response status code support

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java

Fix https://github.com/apache/dubbo/issues/13560

Fix delay publish deadlock

---

dubbo-plugin/dubbo-compiler/src/main/resources/Dubbo3TripleStub.mustache
dubbo-plugin/dubbo-compiler/src/main/resources/ReactorDubbo3TripleStub.mustache

related to https://github.com/apache/dubbo/issues/13348

Triple Stub path compatibility

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java

Exclude `UseJavaPackageAsPath` to parameters

---

dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java

Fix  MultipleRegistry  cache file  error name #13603

---

dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper-curator5/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
pom.xml

Upgrade apache parent version 27 to 31.
