apache/dubbo

dubbo-admin/pom.xml, dubbo-demo/dubbo-demo-api/pom.xml, dubbo-demo/dubbo-demo-consumer/pom.xml, dubbo-demo/dubbo-demo-consumer/src/main/assembly/conf/dubbo.properties, dubbo-demo/dubbo-demo-provider/pom.xml, dubbo-demo/dubbo-demo-provider/src/main/assembly/conf/dubbo.properties, dubbo-demo/pom.xml, dubbo-simple/dubbo-monitor-simple/pom.xml, dubbo-simple/dubbo-monitor-simple/src/main/assembly/conf/dubbo.properties, dubbo-simple/dubbo-registry-simple/pom.xml, dubbo-simple/pom.xml, pom.xml
Update dependencies:
xstream:   1.4.1 => 1.4.8
fastjson:  1.1.8 => 1.2.4
zookeeper: 3.3.3 => 3.4.6
=> Fix building for 2.4.11

dubbo-admin/src/main/java/com/alibaba/dubbo/governance/web/common/interceptor/RestfuleUrlRewriter.java
This is a small bug that results in a ClassCastException. See [this page](https://stackoverflow.com/questions/5690351/java-stringlist-toarray-gives-classcastexception) for a discussion on this kind of issue.
=> Avoid ClassCastException

dubbo-common/src/main/java/com/alibaba/dubbo/common/URL.java
移除path字符串开头的“/”代码没有起效，应该修改移除while这段代码或后移this.path的赋值
=> 修正URL.java中构造函数中用于移除path开头的“/”的代码

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/FailoverClusterInvoker.java
fix method name typo in AbstractClusterInvoker from "checkWheatherDestoried" to "checkWhetherDestroyed"
=> fix typo of method

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/dump.sh
[dump.sh](https://github.com/alibaba/dubbo/blob/master/dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/dump.sh#L15)
<pre>
PIDS=`ps -f | grep java | grep "$CONF_DIR" |awk '{print $2}'`
</pre>
in ubuntu 16.04 `ps -f ` is nothing
<pre>
To see every process on the system using standard syntax:
ps -e
ps -ef
ps -eF
ps -ely
</pre>
=> fix #402 `ps -f` is nothing, standard syntax: `ps -ef`

dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryDirectory.java
detail: see https://github.com/alibaba/dubbo/issues/286
=> 优化consumer找不到provider时的提示内容，当前提示容易误导使用者服务被禁用forbid

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/RpcStatus.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/ExecuteLimitFilter.java
修复executes属性（ExecuteLimitFilter）在高并发时无法真正限制某个接口或方法使用线程数的bug。
参见：http://manzhizhen.iteye.com/blog/2386408
这个bug只有在高并发的情况下容易出现（比如并发大于100），问题其实主要在于“计数器和阈值的比较”和“计数器加1”不是一个原子操作，会产生竞态条件的问题，所以可改用信号量来解决这个问题。
微信/手机：18668225833
=> 修复executes属性（ExecuteLimitFilter）在高并发时无法真正限制某个接口或方法使用线程数的bug

dubbo-common/src/main/java/com/alibaba/dubbo/common/serialize/support/dubbo/Builder.java
修复 com.alibaba.dubbo.common.serialize.support.dubbo.Builder#newObjectBuilder 存在死循环的风险
=> fix:#558 修复 Builder#newObjectBuilder 存在死循环的风险

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/TimeoutFilter.java
I always get logs like this:  invoke time out. method: getListarguments .....  
it's a little confused
=> add space , optimize log output

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchanger.java, dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/ChannelWrappedInvoker.java
bugfix: 服务器端回调没有必要再发heartbeat了，因为它和正常的调用是共享同一个底层的channel。
=> bugfix: 服务器端回调没有必要再发heartbeat

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java
bugfix: 计算一致性哈希的时候使用了invoker.getUrl().toFullString()，这个toFullString里包含一个服务暴露时候的时间戳，那么一个provider的再次暴露时间戳就变了，一致性哈希的节点也会改变，改成用address更合理些。另外就是修正一些IDE warning。
=> bugfix: 一致性哈希负载均衡bug

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractConfig.java
使用dubbo过程中有一个比较头疼的限制，那就是AbstractConfig中的MAX_LENGTH，它的值是100。
我们公司内部经常会通过Filter来在dubbo中做一些“埋点”处理，比如输出监控、日志、接入分布式跟踪系统等，所以在dubbo中配置5、6个Filter类是常有的事，加起来字符数是一百多，所以启动时却被AbstractConfig中的MAX_LENGTH给限制住了，所以希望能在新的版本中，将这个值给放宽，不知道改成200可否？谢谢。
=> 希望能调大AbstractConfig中对配置值长度的限制（MAX_LENGTH）

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/codec/ExchangeCodec.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/AbstractCodec.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/ExceedPayloadLimitException.java
bugfix:超过payload的限制就表示请求或者响应都很大了，结果这里将响应会打到日志，然后还会发送回consumer，这样来几下应用…就要OOM了
=> bugfix:将超过payload限制的异常区分出来

dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java
当前telnet 调用时，对泛型参数中pojo对象时，不支持，
见issue #345 
修复该bug，只修改一行代码
=> 修改：telent 支持泛型参数json调用

dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryProtocol.java
这里每个服务export的时候都会订阅一个OverrideListener，那么configurators节点发生变动的时候，每个服务的OverrideListener都会触发，那每个服务的OverrideListener去修改自己就好了，为什么要把bounds里全拿出来呢？还增加了出bug的几率
=> 简化OverrideListener的逻辑

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java
框架默认会检查服务是否存在，ReferenceConfig 中check 时null时则是true，而注解中的默认值为false，导致向spring解析时，对ReferenceBean 的check值没有给值，默认为处理为true，导致标签check功能失效
=> 修改默认检查服务错误的问题

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/proxy/wrapper/StubProxyFactoryWrapper.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/support/MockInvoker.java
=> Fix typo implemention -> implementation

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/PojoUtils.java
当参数有泛型时，得到的参数类型不是Class类型而是ParameterizedType，则原代码会导致使用json反序列化后的类型，如果字段的实际参数与json反序列化默认参数不符的话将会报错，列入字段的类型为Set<XXX>，而json反序列化后的类型为List<XXX>
=> 修复参数有泛型时类型转化出错

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
Fix 'start.sh' waits indefinitely when specified the 'dubbo.protocol.host' parameter.
=> 修复当设置了"dubbo.protocol.host"参数后启动脚本无限等待的问题

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/listener/ListenerInvokerWrapper.java
The operator '+' has a higher operation priority than '?:'. A NPE will be thrown if getUrl() returns null, which is not expected.
=> NPE bug fixed.

dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/validation/ValidationParameter.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/validation/ValidationService.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/validation/ValidationServiceImpl.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/validation/ValidationTest.java, dubbo-filter/dubbo-filter-validation/src/main/java/com/alibaba/dubbo/validation/MethodValidated.java, dubbo-filter/dubbo-filter-validation/src/main/java/com/alibaba/dubbo/validation/support/jvalidation/JValidator.java
=> 增加MethodValidated注解的测试用例  及对MethodValidated使用场景和用法的说明注释

dubbo-monitor/dubbo-monitor-api/src/main/java/com/alibaba/dubbo/monitor/support/AbstractMonitorFactory.java, dubbo-monitor/dubbo-monitor-default/src/main/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitorFactory.java, dubbo-monitor/dubbo-monitor-default/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.monitor.MonitorFactory
https://github.com/alibaba/dubbo/issues/190 fix class DubboMonitorFactory name spelling
fix class name
dubbo/dubbo-monitor/dubbo-monitor-default/src/main/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitorFactory.java
=> fix class DubboMonitorFactory  name spelling for #190 

hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/SerializerFactory.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/SerializerFactoryTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/TestClass.java
SerializerFactory是从hession中移植过来的类，之前版本的_cachedSerializerMap、_cachedDeserializerMap和_cachedTypeDeserializerMap均为hashmap，获取Serializer（getSerializer方法）和Deserializer时，锁住整个hashmap，锁粒度太大。现在改成ConcurrentHashMap。
hessian 4.0.38中也已经将这两个hashmap替换为ConcurrentHashMap。
=> 获取Serializer和Deserializer时，高并发情况下线程block

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/NetUtils.java
fix dubbo default Log bug, default wrong local ip output is 127.0.0.1 
fix address printed error in log
=> Error in getting local address for Dubbo Log

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/router/condition/ConditionRouterTest.java
Fix condition router to process default.xxx vaule in url.
Modify test case of conditon router, add default.xxx=yyy parameter in url, add route codition xxx=yyy.
Modify condition router. Try to get default.xxx value when xxx is null.
Start two providers, one with configuration <dubbo:provider xxx="yyy" />.
Add condition router  "=> xxx=yyy".
Start one consumer, all request should send to provide whit  configuration <dubbo:provider xxx="yyy" />.
=> [Dubbo-1201] Fix condition router

hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/JavaDeserializer.java
RPC调用反序列化过程中，如果对象的成员变量的类型为java.sql.Time，且其值为NULL，则抛出NPE。
添加了必要的非空检查
=> bugfix: throw a NPE in deserialization process when one property of java.sql.Time type happens to be null

pom.xml
Fix [issues](https://github.com/alibaba/dubbo/issues/1284)
Support `MetaspaceSize` and `MaxMetaspaceSize` vm args on java 8+
=> [Dubbo-1284] Fix UT warning message when running on Java 9

dependencies-bom/pom.xml, pom.xml
Fix #1283 Ensure we can build Dubbo on Java 9
1. Update maven-javadoc-plugin version
2. Disable doclint by default and adapt to new maven-javadoc-plugin format
3. Update fastjson version
=> [Dubbo-1283] Ensure we can build Dubbo on Java 9 

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java
Use custom annotations we can rename the annotation as more obvious name and add many default configs.
So I think support custom annotations is necessary.
Signed-off-by: Bo Cai charpty@gmail.com
请您查看: https://github.com/alibaba/dubbo/issues/1279
=> [Dubbo-1279]Allow @Reference to support custom annotations

hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/AbstractDeserializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/AbstractHessianInput.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/CollectionDeserializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/Deserializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/Hessian2Input.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/JavaDeserializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/MapDeserializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/SerializerFactory.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Hessian2StringShortTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Hessian2StringShortType.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/PersonType.java
Fix hessian2 serialized short, byte is converted to int bug
for example:
if we test deserialize mode 'Hessian2StringShortType'
`
public class Hessian2StringShortType implements Serializable {
Map<String, Short> stringShortMap;
Map<String, Byte> stringByteMap;
Map<String, PersonType> stringPersonTypeMap;
public Hessian2StringShortType(){
}
}
public class PersonType implements Serializable {
String name;
int age;
double money;
short p1;
byte  p2;
List<Short> p3;
public PersonType(String name, int age, double money, short p1, byte p2, List<Short> p3) {
this.name = name;
this.age = age;
this.money = money;
this.p1 = p1;
this.p2 = p2;
this.p3 = p3;
}
@Override
public boolean equals(Object o) {
if (this == o)
return true;
if (o == null || getClass() != o.getClass())
return false;
PersonType …
=> Fix hessian2 serialized short, byte is converted to int bug

dubbo-rpc/dubbo-rpc-thrift/src/test/java/com/alibaba/dubbo/rpc/protocol/thrift/AbstractTest.java, dubbo-rpc/dubbo-rpc-thrift/src/test/java/com/alibaba/dubbo/rpc/protocol/thrift/ThriftProtocolTest.java
fixed travis-ci failed because of test cases. see: com.alibaba.dubbo.rpc.protocol.thrift.AbstractTest
dubbo-rpc-thrift/src/test/java/com/alibaba/dubbo/rpc/protocol/thrift/AbstractTest.java
``` java
-    static final int PORT = 30660;
+    protected int PORT = NetUtils.getAvailablePort();
+    TServerTransport serverTransport;
+
protected void init() throws Exception {
-        TServerTransport serverTransport = new TServerSocket(PORT);
+
+        serverTransport = new TServerSocket(PORT);
+        try{
+            if(serverTransport != null){
+                // release port if used
+                serverTransport.close();
+            }
+        }catch (Exception e) {
+            // ignore
+        }
```
should start ci test
Follow this checklist to help us incorporate your …
=> [Dubbo-ci failed] fixed travis-ci failed because of test cases.

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/tps/DefaultTPSLimiter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/tps/StatItem.java, dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/filter/tps/StatItemTest.java
Currently, when we check if is allowable in ```StatItem```, we have two unnecessary arguments which are not used in the method. So we can remove them.
=> Remove redundant arguments for StatItem#isAllowable

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/DecodeHandler.java
We can simplify string concatenation in log without ```StringBuilder``` cause a single naive string concatenation cost is also cheap.
=> Simplify string concatenation in log

dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-rpc/dubbo-rpc-hessian/src/main/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocol.java, dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocolTest.java, dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianService.java, dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianServiceImpl.java
add hessian.overload.method to support method overload default is false
add hessian2.request to support request protocol version default is version 1
=> add optional parameter to support hessian protocol method overload and request protocol version

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
Currently, we'll instantiate the load balance with a default instance if no invokers found. However, we don't need to use it. 
Closes #1297
=> Do not instantiate load balance if there is no invokers (#1297)

dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java
```"Unsupported request: " + message == null ? null : (message.getClass().getName() + ": " + message)``` will always results ```(message.getClass().getName() + ": " + message)``` because ```+``` is higher priority than ```==```.
=> Fix build string bug

dubbo-plugin/dubbo-qos/src/main/java/com/alibaba/dubbo/qos/command/impl/Ls.java
Fix typo. Change from `Provier` to `Provider`
=> Fix typo for method name

dubbo-rpc/dubbo-rpc-default/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/ImplicitCallBackTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Hessian2StringShortTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/TestClass.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/beans/Hessian2StringShortType.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/beans/PersonType.java
refactor hessian_lite test case 
`hessian-lite/src/test/` test case modify
```
cd hessian-lite/
mvn test
verify if success  
```
or 
`travis ci `run success
=> fix hessian lite test case fail bug

README.md
update readme to add some details
update readme to add some details
update readme to explain dubbo-ops project and user/admin manuals.
update readme to explain dubbo-ops project and user/admin manuals.
=> update readme to add some details

NOTICE, dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/schema/AnnotationBeanDefinitionParser.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/context/annotation/provider/DefaultHelloService.java, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-annotation-consumer.xml, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-annotation-provider.xml, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-consumer.xml, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-provider.xml, dubbo-rpc/dubbo-rpc-thrift/src/test/resources/dubbo-demo-consumer.xml, dubbo-rpc/dubbo-rpc-thrift/src/test/resources/dubbo-demo-provider.xml, dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/rest/rest-consumer.xml, dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/rest/rest-provider.xml, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/Deserializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/MapDeserializer.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/beans/BaseUser.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/beans/GrandsonUser.java
add apache license
Files that do not contain  `"Apache Software Foundation"` strings
use `shell script`  to find files that do not contain  `"Apache Software Foundation"` strings：
```
cd dubbo
find . -type f -ctime 0| xargs grep -L "Apache Software Foundation"
```
=> add ASF license head

hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/LocaleHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/LocaleSerializer.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/LocaleSerializerTest.java
see #1411 
Java Locale.toString() split language, country and variant with char `\_`.
but not support the extentions, because of truncate `\_#.*` in the commit.
=> Fix #1411 Java Locale use '_' split language, country, variant.

dubbo-remoting/dubbo-remoting-grizzly/src/main/java/com/alibaba/dubbo/remoting/transport/grizzly/GrizzlyChannel.java, dubbo-remoting/dubbo-remoting-grizzly/src/main/java/com/alibaba/dubbo/remoting/transport/grizzly/GrizzlyClient.java, dubbo-remoting/dubbo-remoting-grizzly/src/main/java/com/alibaba/dubbo/remoting/transport/grizzly/GrizzlyCodecAdapter.java, dubbo-remoting/dubbo-remoting-grizzly/src/main/java/com/alibaba/dubbo/remoting/transport/grizzly/GrizzlyHandler.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/com/alibaba/dubbo/remoting/transport/mina/MinaChannel.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/com/alibaba/dubbo/remoting/transport/mina/MinaClient.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/com/alibaba/dubbo/remoting/transport/mina/MinaCodecAdapter.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/com/alibaba/dubbo/remoting/transport/mina/MinaHandler.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/com/alibaba/dubbo/remoting/transport/netty4/logging/FormattingTuple.java
Fix typo from `Disconnectd` to `Disconnected`
Fix typo from `trimemdLen` to `trimmedLen`
=> Fix typo for remoting module

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/MonitorConfig.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-monitor/dubbo-monitor-api/src/main/java/com/alibaba/dubbo/monitor/support/MonitorFilter.java, dubbo-monitor/dubbo-monitor-default/src/main/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitor.java
fix #1510 
1.  dubbo monitor collection missing the `group` `version` `dubbo` parameters
2. dubbo monitor interval default set to 60s and can't override by outside setting
1. dubbo monitor parameters add `group`, `version`,`dubbo` parameters
2. monitor interval can be override by outside setting
XXXX
=> [Dubbo-1510] dubbo monitor missing parameters

.travis.yml, dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/ReflectUtils.java, pom.xml
add java9 in ci
use jacoco
fix reflection issue
ci pass
coverage in codecov.io
close #1521
=> [dubbo-1521]add java 9 in travis yml

.codecov.yml
Exclude `dubbo-demo` project when calc coverage
Add ignore config for codecov
CI Passs
=> exclude dubbo-demo when calc coverage

dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/filter/tps/StatItemTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/support/RpcUtilsTest.java
In dubbo-rpc-api module:
1.  Since junit.framework.Assert are deprecated since Junit 4 and other test case classes in this module have already use org.junit.Assert for instead, it is necessary to update related codes in StatItemTest  and RpcUtilsTest.
2.  Make codes more easy to read
In dubbo-rpc-api module:
1. Use org.junit.Assert instead of junit.framework.Assert(@Deprecated since Junit 4)
2. Use assertTrue and other assert methods through static import to make codes easier to read
Test cases run with success
=> Mirror improvement for test cases in dubbo-rpc-api module

dubbo-monitor/dubbo-monitor-default/src/main/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitor.java
fix #1439
change monitor log level to **Debug**
=> [Dubbo-monitor] change monitor log level

dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ServiceConfig.java
Fix exception stack trace during provider demo start.
When running the provider demo locally, the provider will try to connect to the ip specified in the registry url in order. In the demo code, a multicast address is specified, however, there is no need to connected to the multicast address since it will eventually failed. The failure of connecting to that address logs an warn message with exception trace. Although there is no harm, it will still make user confused.
This pull request just skip that connection if registry address is a multicast address.
Verified locally to confirm that the exception trace is no longer logged.
- [] Write necessary unit-test to verify your logic correction, more mock a little …
=> [Dubbo-1619] Fix exception stack trace during provider demo start.

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
```
url.getPort() != address.getPort() ||
!NetUtils.filterLocalHost(url.getIp()).equals(NetUtils.filterLocalHost(host));
```
There is no need to compare address to confirm whether they are consumer or not in RpcContext.
the remote address comes from url and compare with url.
RpcContext
=> [Dubbo-RpcContext] Simplify check consumer side in RpcContext

NOTICE, all/pom.xml, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/StickyTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/loadbalance/LoadBalanceTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/router/file/FileRouterEngineTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/FailSafeClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/FailbackClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/FailfastClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/ForkingClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/MergeableClusterInvokerTest.java, dubbo-filter/dubbo-filter-cache/src/test/java/com/alibaba/dubbo/cache/filter/CacheFilterTest.java, dubbo-registry/dubbo-registry-zookeeper/src/test/java/com/alibaba/dubbo/registry/zookeeper/ZookeeperRegistryTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/com/alibaba/dubbo/remoting/transport/AbstractCodecTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/filter/CompatibleFilterFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/filter/ContextFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/filter/EchoFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/filter/ExceptionFilterTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/FutureFilterTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/ChangeTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/CurrentTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/InvokerTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/LogTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/PortTelnetHandlerTest.java, pom.xml
use mockito to replace easymock
Remove dependency for easymock and jmockit
Add dependency for mockito
Migrate easymock test to mockito test base on mockito doc (https://github.com/mockito/mockito/wiki/Mockito-vs-EasyMock)
CI Pass (https://travis-ci.org/diamondblack/incubator-dubbo/builds/371112027)
=> use mockito to replace easymock and jmockit

.codecov.yml
Add test coverage check for pull request
+ modify codecov configuration for pull request only
+ set threshold as 0.1%
+ reviewed https://codecov.io/gh/apache/incubator-dubbo/pulls. for small change, the coverage change is round 0.01%--0.06%. As discussed in mail list, considering small change, I put threshold as 0.1%
Codecov config is valid.
=> Add test coverage check for pull request and set threshold as 0.1%

hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/Hessian2Input.java
compare with hessian4(4.0.37) and figure out why 
hessian4(4.0.37) performs much better than hessian-lite(3.2.2) in deserialization.
Hessian2Input
unit test pass
performance test pass
=> [Dubbo-1659] Optimize_hessian_desr_performance

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/execution/ExecutionChannelHandler.java
fixes #1089, make ExecutionDispatcher meets dubbo-user-book
In dubbo-user-book, chapter 6.4, 
> execution: Only request message will be dispatched to thread pool. Other messages like response, connect, disconnect, heartbeat will be directly executed by I/O thread.
But the old codes does NOT meet the description above, this pr aims to meet the description.
XXXX
=> fixes #1089, make ExecutionDispatcher meet dubbo-user-book

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/ConfigUtils.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractInterfaceConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/Greeting.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/GreetingLocal1.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/GreetingLocal2.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/GreetingLocal3.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/GreetingMock1.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/GreetingMock2.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockCluster.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockFilter.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockInvokerListener.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockProxyFactory.java, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.Filter, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.InvokerListener, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.ProxyFactory, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.cluster.Cluster
part1 for https://github.com/apache/incubator-dubbo/issues/1683
unit test for AbstractConfigTest, finish appendProperties, appendParameters, and appendAttributes
=> unit test for AbstractConfigTest

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractInterfaceConfig.java
fix issue1731: checkMultiExtension in com.alibaba.dubbo.config.AbstractInterfaceConfig should be in setter instead of getter
- com.alibaba.dubbo.config.AbstractInterfaceConfig
=> fix issue 1731

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/ExecutorUtil.java
change isShutdown to isTerminated
=> fix isShutdown always return true

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java
1. Use loadBalance policy when providers less 2
2. Fix AbstractClusterInvokerTest OutOfMemoryError
1. Remove the following code fragment in AbstractClusterInvoker.java :
```java
-        // If we only have two invokers, use round-robin instead.
-        if (invokers.size() == 2 && selected != null && !selected.isEmpty()) {
-            return selected.get(0) == invokers.get(0) ? invokers.get(1) : invokers.get(0);
-        }
```
2. Add clear invocation operation after invoking in AbstractClusterInvokerTest.java : 
```
Mockito.clearInvocations(invoker1, invoker2, invoker3, invoker4, invoker5);
```
All test cases are pass.
=> fix #934 #1756 use loadBalance policy to choose invoke when providers less 2

dubbo-remoting/dubbo-remoting-netty/src/main/java/com/alibaba/dubbo/remoting/transport/netty/NettyServer.java
Fix #1744 
Enable `TCP_NODELAY` for netty 3 server implementation
The accepted channel's socket in server side returns true when calling java.net.Socket#getTcpNoDelay
=> [Dubbo-1744] Enable tcp no delay for netty 3 server implementation

dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/RegistryConfigTest.java
unit test for RegistryConfigTest
=> unit test for RegistryConfigTest

hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Hessian1StringShortTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Hessian2EnumSetTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Hessian2StringShortTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/HessianJavaSerializeTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/LocaleSerializerTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/base/SerializeTestBase.java
fix hessian-lite spelling mistake
Only TestCases are changed
testcase all pass
=> fix hessian-lite spelling mistake

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/AnnotationBean.java
Remove unnecessary null check.
=> Remove unnecessary null check.

dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/ExtensionLoader.java
Such logic already exists in findAnnotationName.Remove duplicate code
ExtensionLoader Remove logical repeat code
1.start DubboDemoProvider
2.start DubboDemoConsumer
=> Such logic already exists in findAnnotationName

dubbo-common/src/main/java/com/alibaba/dubbo/common/json/GenericJSONConverter.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/json/JSONTest.java
fix #906 and add deserialize support
XXXXX
XXXXX
=> add Locale serialize & deserialize support

dependencies-bom/pom.xml, dubbo-remoting/dubbo-remoting-http/pom.xml
Upgrade tomcat version to 8.5.31, which fix #1254 
* Upgrade tomcat version to 8.5.31
* Remove dependency to tomcat-embed-logging-juli since it is no longer needed.
Unit test passed.
=> [Dubbo-1254] Upgrade tomcat version to 8.5.31 #1254

dubbo-filter/dubbo-filter-validation/pom.xml, dubbo-filter/dubbo-filter-validation/src/test/java/com/alibaba/dubbo/validation/filter/ValidationFilterTest.java, dubbo-filter/dubbo-filter-validation/src/test/java/com/alibaba/dubbo/validation/support/jvalidation/JValidationTest.java, dubbo-filter/dubbo-filter-validation/src/test/java/com/alibaba/dubbo/validation/support/jvalidation/JValidatorTest.java, dubbo-filter/dubbo-filter-validation/src/test/java/com/alibaba/dubbo/validation/support/jvalidation/mock/JValidatorTestTarget.java, dubbo-filter/dubbo-filter-validation/src/test/java/com/alibaba/dubbo/validation/support/jvalidation/mock/ValidationParameter.java, pom.xml
Add unit tests for dubbo-filter-validation module, in order to increase the overall test coverage.
more details, please refer to #1687
=> [Dubbo-1687]Add unit tests for dubbo-filter-validation module

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/WrappedChannelHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/all/AllChannelHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/connection/ConnectionOrderedChannelHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/execution/ExecutionChannelHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/message/MessageOnlyChannelHandler.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/com/alibaba/dubbo/remoting/transport/netty/ClientReconnectTest.java
Extracting public code to the parent class
=> Extracting public code to the parent class

dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation/AnnotationConsumer.java, dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation/AnnotationProvider.java, dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation/dubbo-consumer.properties, dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/annotation/dubbo-provider.properties, dubbo-test/pom.xml
Fix annotation demo fails to start.
update dubbo-test-examples.
1. start AnnotationProvider
2. start AnnotationComsumer
- [] Make sure there is a [GITHUB_issue](https://github.com/alibaba/dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test …
=> [Dubbo-fixed annotation demo fail to start].

dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocolTest.java
Fix #1667 #1727  unstable hessian protocol unit test
Add `hessian.overload.method` to url.
Unit test passed.
=> [Dubbo-1667] Fix unstable hessian protocol unit test. #1667

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java
fix issue #677: There is a potential deadlock in DubboProtocol#getSharedClient
com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol
=> issue#677: There is a potential deadlock in DubboProtocol#getSharedClient

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/com/alibaba/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java
optimize zk create method.
if we create path /dubbo/XxxService/providers/dubbo....
we should check it's parent path exist or not first.
but when we create path  /dubbo/XxxService/providers
we should check the path exist or not first.
doSubscribe method invoke this every time.
Can reduce the number,  access to zk.
AbstractZookeeperClient create.
=> optimize_zk_create

dependencies-bom/pom.xml, dubbo-rpc/dubbo-rpc-webservice/pom.xml, dubbo-rpc/dubbo-rpc-webservice/src/main/java/com/alibaba/dubbo/rpc/protocol/webservice/WebServiceProtocol.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/com/alibaba/dubbo/rpc/protocol/webservice/DemoService.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/com/alibaba/dubbo/rpc/protocol/webservice/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/com/alibaba/dubbo/rpc/protocol/webservice/User.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/com/alibaba/dubbo/rpc/protocol/webservice/WebserviceProtocolTest.java
update CXF to latest version 3.2.4 and add test case for webservice protocol
update CXF to latest version 3.2.4 and add test case for webservice protocol
1.Running test case
2.Verifying #1560
=> update CXF to latest version and add test case for webservice protocol

dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/DubboAppenderTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/ExecutorUtilTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/HolderTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/IOUtilsTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/JVMUtilTest.java
issue#1682: Enhance the test coverage part-4
modified:   dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/DubboAppenderTest.java
modified:   dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/ExecutorUtilTest.java
modified:   dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/HolderTest.java
modified:   dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/IOUtilsTest.java
modified:   dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/JVMUtilTest.java
=> issue#1682: Enhance the test coverage part-4

dubbo-bootstrap/src/main/java/org/apache/dubbo/bootstrap/DubboBootstrap.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/DubboShutdownHook.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ProtocolConfig.java, dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/initializer/DubboApplicationListener.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/initializer/DubboApplicationListenerTest.java, dubbo-container/dubbo-container-api/src/main/java/com/alibaba/dubbo/container/Main.java, dubbo-container/dubbo-container-spring/pom.xml, dubbo-container/dubbo-container-spring/src/main/java/com/alibaba/dubbo/container/spring/SpringContainer.java
Improve compatibility for graceful shutdown.
The implementation fo #1763 lack consideration for compatibility.
* Create a dedicated class DubboShutdownHook, and make it singleton.
* Restore ProtocolConfig#destroyAll() for compatabitility.
* Register DubboShutdownHook in static initialization of AbstractConfig.
Unit test passed.
=> Improve graceful shutdown

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/extension/SpringExtensionFactory.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/extension/BeanForContext2.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/extension/SpringExtensionFactoryTest.java
also see #1456 .
Spring spi support inject by type. Not necessary to support spring 2.5 or lower.
SpringExtensionFactory:
1. getBean by name
2. getBean by type
SpringExtensionFactoryTest
=> [Dubbo-SPI] Spring spi support inject by type

dubbo-rpc/dubbo-rpc-memcached/src/test/java/com/alibaba/dubbo/rpc/protocol/memcached/MemcachedProtocolTest.java, dubbo-rpc/dubbo-rpc-redis/pom.xml, dubbo-rpc/dubbo-rpc-redis/src/test/java/com/alibaba/dubbo/rpc/protocol/redis/IDemoService.java, dubbo-rpc/dubbo-rpc-redis/src/test/java/com/alibaba/dubbo/rpc/protocol/redis/RedisProtocolTest.java, dubbo-rpc/dubbo-rpc-redis/src/test/resources/META-INF/dubbo/internal/com.alibaba.dubbo.common.serialize.Serialization, dubbo-rpc/dubbo-rpc-rest/src/test/java/com/alibaba/dubbo/rpc/protocol/rest/DemoService.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/com/alibaba/dubbo/rpc/protocol/rest/IDemoService.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/com/alibaba/dubbo/rpc/protocol/rest/RestProtocolTest.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/com/alibaba/dubbo/rpc/protocol/rest/RpcExceptionMapperTest.java
add test for dubbo-rpc-redis & dubbo-rpc-rest
For #1697 
there is one module dubbo-rpc-memcached still in progress, I'm trying to find a solution to mock memcached.
CI Pass
=> [Dubbo-1697] add test for dubbo-rpc-redis & dubbo-rpc-rest

.codecov.yml, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/ConfigTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/ServiceBeanTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/extension/SpringExtensionFactoryTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/schema/DubboNamespaceHandlerTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/status/DataSourceStatusCheckerTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/status/SpringStatusCheckerTest.java, dubbo-config/dubbo-config-spring/src/test/resources/com/alibaba/dubbo/config/spring/consumer-notification.xml, dubbo-config/dubbo-config-spring/src/test/resources/com/alibaba/dubbo/config/spring/delay-fixed-time.xml, dubbo-config/dubbo-config-spring/src/test/resources/com/alibaba/dubbo/config/spring/multi-monitor.xml, dubbo-config/dubbo-config-spring/src/test/resources/com/alibaba/dubbo/config/spring/provider-multi.xml, dubbo-config/dubbo-config-spring/src/test/resources/com/alibaba/dubbo/config/spring/provider-with-module.xml, dubbo-config/dubbo-config-spring/src/test/resources/com/alibaba/dubbo/config/spring/provider-with-monitor.xml
Add test for dubbo spring config module
Close #1684
+ ignore AnnotationBean in codecov
+ replace junit.framework.Assert; to org.junit.Assert;
+ add unit test
CI Pass
somehow even master branch fail in my fork repo... I guess travis ci has some issue.
Hope pull request CI can pass in dubbo repo travis ci.
=> [Dubbo-1684] add unit test for dubbo spring config

dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/mock/MockProxyFactory.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/ProxyFactory.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/GenericFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/GenericImplFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/protocol/AbstractProxyProtocol.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/proxy/AbstractProxyFactory.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/proxy/wrapper/StubProxyFactoryWrapper.java, dubbo-rpc/dubbo-rpc-hessian/pom.xml, dubbo-rpc/dubbo-rpc-hessian/src/main/java/com/alibaba/dubbo/rpc/protocol/hessian/DubboHessianURLConnectionFactory.java, dubbo-rpc/dubbo-rpc-hessian/src/main/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocol.java, dubbo-rpc/dubbo-rpc-hessian/src/main/java/com/alibaba/dubbo/rpc/protocol/hessian/HttpClientConnectionFactory.java, dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocolTest.java, dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianService.java, dubbo-rpc/dubbo-rpc-hessian/src/test/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianServiceImpl.java, dubbo-rpc/dubbo-rpc-http/pom.xml, dubbo-rpc/dubbo-rpc-http/src/main/java/com/alibaba/dubbo/rpc/protocol/http/HttpProtocol.java, dubbo-rpc/dubbo-rpc-http/src/main/java/com/alibaba/dubbo/rpc/protocol/http/HttpRemoteInvocation.java, dubbo-rpc/dubbo-rpc-http/src/test/java/com/alibaba/dubbo/rpc/protocol/http/HttpProtocolTest.java, dubbo-rpc/dubbo-rpc-http/src/test/java/com/alibaba/dubbo/rpc/protocol/http/HttpService.java, dubbo-rpc/dubbo-rpc-http/src/test/java/com/alibaba/dubbo/rpc/protocol/http/HttpServiceImpl.java, dubbo-rpc/dubbo-rpc-rest/pom.xml, dubbo-rpc/dubbo-rpc-rest/src/test/java/com/alibaba/dubbo/rpc/protol/rest/RestProtocolTest.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/com/alibaba/dubbo/rpc/protol/rest/RestService.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/com/alibaba/dubbo/rpc/protol/rest/RestServiceImpl.java
The corresponding issues are #1768, #19  This PR support generic invocation in HttpProtocol/HessianProtocol, and pass attachments HttpRemoteInvocation and through http headers from consumer to provider.
To export additional GenericService in HessianProtocol/HttpProtocol for supporting normal/nativejava/bean types of generic invocation.
Add RpcContext attachments to Http Header and HttpRemoteInvocation attributes.
HttpProtocolTest/HessianProtocolTest is the corresponding unit tests.
=> support generic invoke and attachment for http/hessian protocol

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
ConsistenthashLoadbalance get the wrong method name when using generic invoke.
Use RpcUtils.getMethodName() instead invocation.getMethod().
=> [Dubbo-1123]Get the real methodname to support consistenthash for generic invoke

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ServiceConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/mock/TestProxyFactory.java, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.ProxyFactory
Support use custom proxy to generate invoker on provider side.
1. dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ServiceConfig.java
2. Unit tests
Add related test case.
=> support proxy for provider side. #67

dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/LogHelperTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/LogTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/LogUtilTest.java
#1682: Enhance the test coverage part-4 : dubbo-common/src/main/java/com/alibaba/dubbo/common/status(store|threadpoolutils) modules
dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/LogHelperTest.java
dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/LogTest.java
dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/LogUtilTest.java
=> unit test tracked by issue#1682

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
fixed #1879 
change `ps -f` to `ps -ef`, Because ps -f channot find any process。
=> fixed start.sh ps -f cannot find any process#1879

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/util/PropertySourcesUtils.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/util/PropertySourcesUtilsTest.java
In the case of spring boot.
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-placeholders-in-properties
```properties
app.name=MyApp
app.description=${app.name} is a Spring Boot application
dubbo.application.name=${app.name}
```
```java
Caused by: java.lang.IllegalStateException: ApplicationConfig.application == null
at com.alibaba.dubbo.config.AbstractConfig.appendParameters(AbstractConfig.java:245)
at com.alibaba.dubbo.config.AbstractConfig.appendParameters(AbstractConfig.java:180)
at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:303)
at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)
at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBean …
```
=> support placeholders in properties.

dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/StackTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/StringUtilsTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/UrlUtilsTest.java
#1682: Enhance the test coverage part-4 : dubbo-common/src/main/java/com/alibaba/dubbo/common/status(store|threadpoolutils) modules
dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/UrlUtilsTest.java
XXXXX
=> unit test for UrlUtils

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/NetUtils.java
issue#1431: here is a StackOverflow bug? dubbo version 2.5.9, FailsafeLogger.appendContextMessage() > NetUtils.getLocalAddress()
dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/NetUtils.java
=> [Dubbo-1431] here is a StackOverflow bug? dubbo version 2.5.9, FailsafeLogger.appendContextMessage() > NetUtils.getLocalAddress()

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.bat, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
see #1330 
- Support `MetaspaceSize` and `MaxMetaspaceSize ` in java8+
In linux and windows I use shell or batch to get java version by `java -fullversion`, you can see it in commit.
In the commit ,you can find I use `JAVA_8_VERSION="180"` to compare java vesion. The reasion is that java version naming rule change in java 9.
> `java -fullversion` output example  
- in jdk1.7 -> java full version "1.7.0_79-b15"
- in jdk1.7 -> java full version "1.8.0_152-b16"
- in jdk9 -> java full version "9.0.4+11"
I find many `dos` symbol in `start.sh`, if you run `start.sh` in linux, it may be a problem. I use `dos2unix` cmd to format the file.
Test result in windows 
- jdk9
- jdk1.8
- jdk1.7
=> [Dubbo-1330] Fix Support MetaspaceSize and MaxMetaspaceSize vm args in java8+

dubbo-filter/dubbo-filter-validation/src/main/java/com/alibaba/dubbo/validation/support/jvalidation/JValidator.java
在高并发情况下（QPS大于1000），RPC调用发起线程validation操作阻塞在`Class.forName(methodClassName, false, Thread.currentThread().getContextClassLoader())`上，特别是在与spring boot一起使用时，TomcatEmbeddedWebappClassLoader加载methodClass通常是耗时操作，不使用分组的情况下methodClass通常不存在
=> 添加method class缓存

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java
issue#1915: java.net.BindException happens when delay-expose-service is enabled.
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java
=> [1915]: java.net.BindException happens when delay-expose-service is enabled.

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
#1944 Enhance IDE support for custom spring namespace elements (dubbo)
Enhance IDE support for custom spring namespace elements (dubbo)
=> [Dubbo-1927]: Enhance IDE support for custom spring namespace elements (dubbo)

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/GreetingCommand.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/HttpCommandDecoderTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/TelnetCommandDecoderTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/HelpTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/LsTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/OfflineTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/OnlineTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/QuitTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/TestRegistryFactory.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/protocol/QosProtocolWrapperTest.java, dubbo-plugin/dubbo-qos/src/test/resources/META-INF/services/org.apache.dubbo.registry.RegistryFactory
issue#1689: Enhance the test coverage part-10 : dubbo-plugin module
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/protocol/QosProtocolWrapperTest.java
=> [dubbo-1689]: Enhance the test coverage part-10 : dubbo-plugin module

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServerHandler.java
set heartbeat flag when client channel active (netty4), issue: https://github.com/apache/incubator-dubbo/issues/1996
1. org.apache.dubbo.remoting.transport.netty4.NettyClientHandler#channelActive
2. org.apache.dubbo.remoting.transport.netty4.NettyClientHandler#channelInactive
trigger handler event.
Enable netty4 transporter,  client connect to remote server, org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#connected should be triggered.
=> [Dubbo- netty4 nettyclienthandler should trigger heartbeat handler] fix heartbeat when channel active

dubbo-compatible/README.md
add README
dubbo-compatible/README.md
=> add README for compatible module

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboLazyConnectTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/IDemoService.java
fix  unit test `DubboInvokerAvilableTest & DubboLazyConnectTest` class not found "hi"
1. Replace url path "hi" to "org.apache.dubbo.rpc.protocol.dubbo.IDemoService"
2. Move "org.apache.dubbo.rpc.protocol.dubbo.IDemoService" to the top
unit test passed
- [] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
=> [Dubbo- unit test class not found] fix class not found "hi"

dependencies-bom/pom.xml, dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/pom.xml, dubbo-config/dubbo-config-spring/pom.xml, dubbo-demo/dubbo-demo-consumer/pom.xml, dubbo-demo/dubbo-demo-provider/pom.xml, dubbo-monitor/dubbo-monitor-default/pom.xml, dubbo-registry/dubbo-registry-default/pom.xml, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Transporter.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyTransporter.java, dubbo-remoting/dubbo-remoting-netty/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.Transporter, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatHandlerTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientReconnectTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientsTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyClientTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyStringTest.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyTransporter.java, dubbo-remoting/dubbo-remoting-netty4/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.Transporter, dubbo-remoting/dubbo-remoting-p2p/pom.xml, dubbo-rpc/dubbo-rpc-dubbo/pom.xml, dubbo-rpc/dubbo-rpc-thrift/pom.xml
…lt option for transporter
issue#2029: upgrade netty4 to the latest release and make it the default option for transporter 
dependencies-bom/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
dubbo-config/dubbo-config-api/pom.xml
dubbo-config/dubbo-config-spring/pom.xml
dubbo-demo/dubbo-demo-consumer/pom.xml
dubbo-demo/dubbo-demo-provider/pom.xml
dubbo-monitor/dubbo-monitor-default/pom.xml
dubbo-registry/dubbo-registry-default/pom.xml
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Transporter.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatHandlerTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientReconnectTest.java …
=> [dubbo-2029]: upgrade netty4 to the latest release and make it the default option for transporter 

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Service.java
issue#2063: @Service(register=false) is not work
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Service.java
XXXXX
=> [dubbo-2063]: @Service(register=false) is not work

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContext.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
* Docs in AsyncContext
* Make the future final which is in the constructor of AsyncRpcResult because of using in a inner class.
=> Docs in AsyncContext

pom.xml
Fix the error "Element linkXRef is not allowed here" reported by Intellij IDEA  2018.1.6 (Utimate Edition).
The  linkXRef element isn't defined as parameter in the "check" goal but in the "checkstyle" goal and the "checkstyle-aggregate" goal,  according to the plugin.xml of  maven-checkstyle-plugin:3.0.0.
See https://maven.apache.org/plugins/maven-checkstyle-plugin/plugin-info.html  for details.
Remove the  linkXRef element in root pom.
CI passed
=> Remove pom element linkXRef

dubbo-common/src/main/java/com/alibaba/dubbo/common/Version.java
fix protocol version compatibility
dubbo-common/.../Version.java
XXXXX
=> fix protocol version compatibility on 2.6.x

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
fix protocol version compatibility
dubbo-common/.../Version.java
XXXXX
=> fix protocol version compatibility on master

.travis.yml
Enable checkstyle and rat plugin in travis, fix #2129
`./mvnw clean package -Dcheckstyle.skip=false -Drat.skip=false`
Travis check license header and code style automatically.
=> [Dubbo-2129]Enable checkstyle and rat plugin in travis

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/CompatibleTypeUtils.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/CompatibleTypeUtilsTest.java
support char[] for generic invoke
dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/CompatibleTypeUtils.java
add testcase
=> support char[] for generic invoke #2003

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/CompatibleTypeUtilsTest.java
support char[] for generic invoke
dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/CompatibleTypeUtils.java
add testcase
=> support char[] for generic invoke, #2003

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java
Add reconnection lock to control only one thread can can reconnect method.
This will avoid problem in this case:
Thread A reconnecting, and success, then send msg.
Thread B reconnecting but invoke disconnect. Then the Thread A will send msg fail because of Thread B's disconnecting call.
The issue is here:
https://github.com/apache/incubator-dubbo/issues/944
=> Fix a bug when client reconnect

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/ForkingClusterInvoker.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/ForkingClusterInvokerTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/protocol/AbstractInvoker.java
* Binding attachments into invocation so that a rpc invoke have a same invocation
* Fix a bug that the ForkingClusterInvoker don't clear attachment when a rpc invoke is over.
=> Binding attachment before a clusterInvoker invoke.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvokerTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
* Binding attachments into invocation so that a rpc invoke have a same invocation
* Fix a bug that the ForkingClusterInvoker don't clear attachment when a rpc invoke is over.
=> Binding attachment before a clusterInvoker invoke. 

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
Fixed a bug described in [Dubbo-1765](https://github.com/apache/incubator-dubbo/issues/1765)
If the provider is temporarily unavailable, the reference bean initialization will failed with exception. However, the initialized flag will be set to true, which will cause spring to hold a NULL_OBJECT cache. The subsequent call will always get a null instance.
This change will allow the consumer to obtain the correct instance when provider become available.
- Set initialized=false in ReferenceConfig when provider is not available.
unit test passed
=> [Dubbo-1765] Fix ReferenceBean initialization issue

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractInterfaceConfig.java
same fix on monitor in 2.6.x
because there is bug which willl block shutdown progress in 2.5.x and it was fixed in 2.6.3.
related: #2110 
=> fix subscription when enable monitor

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/DubboAppenderTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java, dubbo-common/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, dubbo-demo/dubbo-demo-consumer/src/main/java/org/apache/dubbo/demo/consumer/Consumer.java, dubbo-demo/dubbo-demo-provider/src/main/java/org/apache/dubbo/demo/provider/Provider.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java, dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java
Add ipv6 support for Dubbo #2064 
* Support parsing ipv6 address in url
* Support ipv6 multicast network
* ipv6 support is available if `java.net.preferIPv6Addresses` is set to `true`
How to test ipv6 support:
dubbo-demo-provider.xml
```xml
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
xmlns="http://www.springframework.org/schema/beans"
xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">
<dubbo:application name="demo-provider"/>
<dubbo:registry address="multicast://FF02:0:0:0:0:0:0:FC:1234"/>
<dubbo:protocol name="dubbo" port="20880"/>
<bean id="demoService" …
```
=> [Dubbo-2064] Ipv6 support

dubbo-common/src/main/java/com/alibaba/dubbo/common/Version.java
solve compatible issue with dubbo 2.5.9, 2.5.10
upgrade the protocol version to 2.0.2/20002
related to #2174 
=> solve compatible issue with dubbo 2.5.9, 2.5.10

dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractConfigTest.java
fix ut unstable
dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractConfigTest.java
mvn test pass
=> fix ut unstable

dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/UrlUtilsTest.java
目前程序支持配置不包含协议头的地址。
问题场景：有时候url已经配置好了‘?backup’，只是没有写协议头。此时如果再一次按照原方案解析，会多拼接出来backup这样的错误信息，而且报的错误不明显，根本不知道哪里做了如上配置，需要查看dubbo实现逻辑才能推断该怎么配置这一段。
本次升级建议：如果在url中，有程序处理拼接的url参数‘?’的，直接不做任何处理。(‘?’在当前逻辑里是拼接backup用的特殊符号。)
问题示例：
127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183   --> 127.0.0.1:2181?backup=127.0.0.1:2182?backup=127.0.0.1:2183
=> 解析用户定义的URL时，当前太过粗暴，做下优雅调整

dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java
#2177
Add Unit Test for org.apache.dubbo.registry.support.AbstractRegistry
To see the new add unit test file at : dubbo-registry/dubbo-registry-api/src/test/java/org.apache.dubbo.registry.support/AbstractRegistryTest.java.
From Baiji, Term 268, Team 3, Issue #2177, Q2
=> [Dubbo-issue-2177] Add Unit Test for org.apache.dubbo.registry.support.AbstractRegistry #2177

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/zkclient/ZkclientZookeeperClient.java
Add timeout config for zookeeper registry
Fix #2191
Close #1743
Read timeout config from url and set to client
CI pass
=> [Dubbo-2191] add timeout config to zookeeper client

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RpcContextFilter.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/RestProtocolTest.java
Judge null for key and value in attachment in RpcContextFilter.
If not, NullPointerException will be thrown in RpcContextFilter in some case.
Fix #2127 : https://github.com/apache/incubator-dubbo/issues/2127#issuecomment-408344327
=> Judge null for key and value in attachment in RpcContextFilter.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java
修复使用FailoverCluster泛化调用时因为methodName得不到配置的重试次数
#2108 
使用FailoverCluster进行泛化调用,FailoverClusterInvoker可以根据泛化的具体方法得到配置的重试次数。
=> FailoverClusterInvoker 使用泛化调用时，拿取正确的方法名称。

dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistry.java, dubbo-serialization/dubbo-serialization-api/src/test/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistryTest.java, dubbo-serialization/dubbo-serialization-fst/src/main/java/org/apache/dubbo/common/serialize/fst/FstFactory.java, dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/CompatibleKryo.java, dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/utils/AbstractKryoFactory.java, dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/utils/ReflectionUtils.java, dubbo-serialization/dubbo-serialization-kryo/src/test/java/org/apache/dubbo/common/serialize/serialization/AbstractSerializationTest.java
Fixes #2178 
CompatibleKryo
KryoSerializationTest
=> [Dubbo-2178] leave jdk standard classes to kryo, use the default registered serializer by kryo.

dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java
Fix issue #2177 By BaiJi  the 269th team 3
The following branches have been Unit Tested:
org.apache.dubbo.registry.support.AbstractRegistry#register
org.apache.dubbo.registry.support.AbstractRegistry#unregister
org.apache.dubbo.registry.support.AbstractRegistry#subscribe
org.apache.dubbo.registry.support.AbstractRegistry#unsubscribe
org.apache.dubbo.registry.support.AbstractRegistry#recover
org.apache.dubbo.registry.support.AbstractRegistry#notify
=> [Dubbo-2177]Fix the issue: Supplementary unit test #2177 team 3

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/protocol/QosProtocolWrapperTest.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
Serval qos enhancement
* Not to accept foreign ip by default.
* Log if fail to start qos server. #2046
* Fix typo.
* Simplify dubbo.xsd and sync with compatible version.
Tested locally.
- [] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
=> Qos enhancement

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
Take the following case:
```java
@SPI("nop")
public interface DynamicConfigurationFactory {
@Adaptive({"key1", "key2"})
DynamicConfiguration getDynamicConfiguration(URL url);
}
```
```properties
zookeeper=org.apache.dubbo.config.dynamic.support.archaius.ArchaiusDynamicConfigurationFactory
archaius=org.apache.dubbo.config.dynamic.support.archaius.ArchaiusDynamicConfigurationFactory
apollo=org.apache.dubbo.config.dynamic.support.apollo.ApolloDynamicConfigurationFactory
nop=org.apache.dubbo.config.dynamic.support.nop.NopDynamicConfigurationFactory
```
1. Give a URL:
```
dubbo://0.0.0.0/xxx.DemoService?key2=notexists
```
There is no extension named `notexists`, so it will throw an IllegalStateException. But with this PR, getAdaptiveExtension() will return the `nop` extension by default.
=> Increase availability, make @Adaptive try default extension when the specified one couldn't be found.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java
Optimize init loadbalance before 'doSelect' method called
Part of this pr:
https://github.com/apache/incubator-dubbo/pull/2156
=> Optimize init loadbalance.

dubbo-common/src/main/java/org/apache/dubbo/common/timer/HashedWheelTimer.java, dubbo-common/src/main/java/org/apache/dubbo/common/timer/Timeout.java, dubbo-common/src/main/java/org/apache/dubbo/common/timer/Timer.java, dubbo-common/src/main/java/org/apache/dubbo/common/timer/TimerTask.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/timer/HashedWheelTimerTest.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java, dubbo-rpc/dubbo-rpc-thrift/src/test/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodecTest.java
HashedWheelTimer to check timeout future
The class about HashedWheelTimer is from netty which with header like : 
```
/*
* Copyright 2012 The Netty Project
*
* The Netty Project licenses this file to you under the Apache License,
* version 2.0 (the "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at:
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations
* under the License.
*/
```
It will decrease circulate times compared to the old …
=> HashedWheelTimer

.travis.yml, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterFactory.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Transporter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/InvokerListener.java, dubbo-rpc/dubbo-rpc-hessian/src/main/java/org/apache/dubbo/rpc/protocol/hessian/HttpClientConnectionFactory.java, pom.xml
Enable checkstyle and rat plugin for travis CI
XXXXX
XXXXX
=> Enable checkstyle and rat plugin for travis CI

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
[Dubbo-1814]" add xml configuration of dubbo.service.shutdown.wait " to ensure gracefully close.
=> [Dubbo-issue1814][ Baiji-9] Add .xml configuration of graceful close

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannelTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/header/MockChannel.java
Add unit test for HeaderExchanngeChannel
/incubator-dubbo/dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchanngeChannelTest.java
=> [Dubbo-2352][Baiji-3]Add unit test for HeaderExchanngeChannel (#2352)

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/AbstractConfigurator.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvokerTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
Minor code refactoring, no functional change. All of them are reported by IntelliJ IDEA.
* remove unnecessary null check
* fix typo
* code simplification
* etc.
It should have no functional change.
=> Minor code refactoring

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/Response.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/DefaultFuture.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
When the server goes down un-normally, return the unfinished requests directly.
The current way is to wait until timeout.
PR for master is here:
https://github.com/apache/incubator-dubbo/pull/2185
=> Direct return when the server goes down unnormally.

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/support/DemoService.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/support/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/InvokerTelnetHandlerTest.java
* fix issue #2218
* add some unit tests
take #2218 back to 2.6.x
XXXXX
XXXXX
=> fix telnet invoke NPE #2218 (#2273)

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/ChannelEventRunnable.java
Fix #2424 
Add missing `break` statement in ChannelEventRunnable#run
=> [Dubbo-2424] Fix switch-case fall through in ChannelEventRunnable

.travis.yml, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/UrlUtilsTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/GenericServiceTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/cache/CacheTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/ConfigTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/com/alibaba/dubbo/remoting/transport/netty/NettyClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/com/alibaba/dubbo/remoting/transport/netty4/ClientReconnectTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/PortTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/com/alibaba/dubbo/rpc/protocol/webservice/WebserviceProtocolTest.java
add cache for travis, fix ut for stable
ut pass.
=> add cache for travis, fix ut for stable

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/CompatibleTypeUtils.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/CompatibleTypeUtilsTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/PojoUtilsTest.java
fix PojoUtil realize type convert not support subclasses of 'java.util.date' #2499 
merge to 2.6.x
The type convert was modified to support the 'java.util.date' subclass
org.apache.dubbo.common.utils.CompatibleTypeUtils.java
org.apache.dubbo.common.utils.PojoUtilsTest.java
org.apache.dubbo.common.utils.CompatibleTypeUtilsTest.java
=> [Dubbo-2499-2.6.x]fix PojoUtil realize type convert not support subclasses of 'java.util.date' #2499

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/CompatibleTypeUtilsTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
fix PojoUtil realize type convert not support subclasses of 'java.util.date' #2499 
The type convert was modified to support the 'java.util.date' subclass
org.apache.dubbo.common.utils.CompatibleTypeUtils.java
org.apache.dubbo.common.utils.PojoUtilsTest.java
org.apache.dubbo.common.utils.CompatibleTypeUtilsTest.java
=> [Dubbo-2499]fix PojoUtil realize type convert not support subclasses of 'java.util.date' #2499

.travis.yml, pom.xml
add jdk11 to travis ci
java11 is coming: http://openjdk.java.net/projects/jdk/11/
.travis.yml
ci success
=> add jdk11 to travis ci

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/web-fragment.xml
Per xsd, web fragment's name should be a valid java identifier (can have a underscore but not a hyphen).
change `-` to `_` in name element in web-fragment.xml.
n.a.
=> [Dubbo-2471] Fix invalid name issue in web-fragment.xml

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
to make to code more standard and clear
Just move constant field to Constants class and "/" will use Constants.PROTOCOL_SEPARATOR.
Thanks
=> code promote: move constant field to Constants class

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
fix https://github.com/apache/incubator-dubbo/issues/2323
the AsyncRpcResult should store the copy of the context
=> [Dubbo-2323]the AsyncRpcResult should store the copy of the context #2323

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java
Remove method.async of provider url to avoid that consumer use async value from provider.
Fix issue:
https://github.com/apache/incubator-dubbo/issues/2321
Related pr:
https://github.com/apache/incubator-dubbo/pull/2322
=> Remove method.async of provider url.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/MockInvokersSelector.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java, dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/MetricName.java, dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/Statistics.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java, dubbo-registry/dubbo-registry-default/src/main/java/org/apache/dubbo/registry/dubbo/DubboRegistry.java, dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Request.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java, dubbo-remoting/dubbo-remoting-grizzly/src/main/java/org/apache/dubbo/remoting/transport/grizzly/GrizzlyClient.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/org/apache/dubbo/remoting/transport/mina/MinaClient.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyChannel.java, dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/java/CompactedObjectInputStream.java
=> 解决了代码规范问题：在if/else/for/while/do语句中必须使用大括号

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/filter/CacheFilter.java, dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/filter/CacheFilterTest.java
当前CacheFilter存在无法缓存null值问题
但是某些rpc接口被设计成可能返回空值（比如跟据用户名查询用户信息接口，如果查询不到，返回null）
static class ValueWrapper {
private final Object value;
public ValueWrapper(Object value){
this.value = value;
}
public Object get() {
return this.value;
}
}
XXXXX
=>  Support for caching null values

dubbo-compatible/src/test/java/org/apache/dubbo/generic/GenericServiceTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ExplicitCallbackTest.java
fix #2533, set timeout to 3000
XXXXX
XXXXX
=> fix #2533, set timeout to 3000

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/initializer/DubboApplicationContextInitializerTest.java
fix #2560, use target/test-classes as the basedir
XXXXX
XXXXX
=> fix #2560, use target/test-classes as the basedir

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveBalanceTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalanceTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalanceTest.java
Now the select is select a random one when there are several least active invokers and all of them are in warm up.
After this pr, it will select also by weight and warm up.
And fix a bug when two invoker's active is same and weight not same.
issue:
https://github.com/apache/incubator-dubbo/issues/904
=> Optimize leastActiveSelect and weight test case

dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryFactoryTest.java
=> AbstractRegistryFactory Unit Test: destroyAll method

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/loadbalance/LoadBalanceTest.java
Optimize LeastActiveLoadBalance and add weight test case.
related pr to master:
https://github.com/apache/incubator-dubbo/pull/2172
related issue:
https://github.com/apache/incubator-dubbo/issues/2540
=> Optimize LeastActiveLoadBalance and add weight test case.

release.sh
This script can help to do the releasing work simply, just use: `./release.sh git@github.com:apache/incubator-dubbo.git 2.6.5-release`, then the script will git clone the remote branch to local, build it, deploy it if necessary, it's depend on your choice.
XXXXX
XXXXX
=> update release script

dubbo-serialization/dubbo-serialization-api/pom.xml, dubbo-serialization/dubbo-serialization-fastjson/pom.xml, dubbo-serialization/dubbo-serialization-fst/pom.xml, dubbo-serialization/dubbo-serialization-hessian2/pom.xml, dubbo-serialization/dubbo-serialization-jdk/pom.xml, dubbo-serialization/dubbo-serialization-kryo/pom.xml
Fix incorrect descriptions for dubbo-serialization module.
Simple fix which doesn't need test.
=> Fix incorrect descriptions for dubbo-serialization module.

dubbo-serialization/dubbo-serialization-api/pom.xml, dubbo-serialization/dubbo-serialization-fastjson/pom.xml, dubbo-serialization/dubbo-serialization-fst/pom.xml, dubbo-serialization/dubbo-serialization-hessian2/pom.xml, dubbo-serialization/dubbo-serialization-jdk/pom.xml, dubbo-serialization/dubbo-serialization-kryo/pom.xml
Fix incorrect descriptions for dubbo-serialization module for 2.6.x.
pr for master is here:
https://github.com/apache/incubator-dubbo/pull/2620
=> Fix incorrect descriptions for dubbo-serialization module for 2.6.x.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java
fix:https://github.com/apache/incubator-dubbo/issues/2578
Optimize RoundRobinLoadBalance
=> Optimize RoundRobinLoadBalance

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ls.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Offline.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Online.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/LsTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/OfflineTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/OnlineTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerMethodModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ProviderMethodModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ProviderModel.java
reusing those model in rpc module.
the refactor is very safe with unit test convering.
=> [Dubbo] move the classes of model from config to rpc-api for reusing

pom.xml
JaCoCo Maven goals used to work on single modules only: Tests are executed within the module and contributed coverage only to code within the same module.
Dubbo is a multi module project which combine by api and their implements, current configuration is not suitable for Dubbo. Coverage reports were created for each module separately. 
In order to get right test coverage, we can use new goal `maven goal jacoco:report-aggregate`. This report aggregates coverage data across Maven modules.
Change maven configuration. 
CI pass and coverage increase.
=> Jacoco aggregate report

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java
fix issue: https://github.com/apache/incubator-dubbo/issues/2522 & https://github.com/apache/incubator-dubbo/issues/2194
1. `org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor#generateReferenceBeanCacheKey` fix caching issues
All test should be passed.
=> [Dubbo -fix annotation bug] Fix @Reference bug

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/ExchangeCodecTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/transport/codec/DeprecatedExchangeCodec.java
#1903: Our customized serialization id exceeds the maximum limit, now it cannot work on 2.6.2 anymore
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/ExchangeCodecTest.java
=> fix issue1903

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java
… of invoke of the getWeight method of the AbstractLoadBalance
XXXXX
XXXXX
XXXXX
=> 【Code Optimization】Optimize the doSelect method of RandomLoadBalance

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/codec/ExchangeCodec.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/CodecSupport.java, dubbo-remoting/dubbo-remoting-api/src/test/java/com/alibaba/dubbo/remoting/codec/ExchangeCodecTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/com/alibaba/dubbo/remoting/transport/codec/DeprecatedExchangeCodec.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboCodec.java
merge issue 1903's fix from 2.7.0 to 2.6.x
dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/codec/ExchangeCodec.java
dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/CodecSupport.java
dubbo-remoting/dubbo-remoting-api/src/test/java/com/alibaba/dubbo/remoting/codec/ExchangeCodecTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/com/alibaba/dubbo/remoting/transport/codec/DeprecatedExchangeCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboCodec.java
XXXXX
=> merge issue 1903's fix from 2.7.0 to 2.6.x

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessor.java
quartz初始化的Bean没有beanName，beanName=null，走这段代码的时候报空指针了。
org.springframework.boot.autoconfigure.quartz.AutowireCapableBeanJobFactory类的createJobInstance方法中使用this.beanFactory.initializeBean(jobInstance, null);初始化的Bean，其beanName=null。
XXXXX
XXXXX
XXXXX
=> 解决与quartz集成报错问题

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
issue2016: Consumer throws RpcException after RegistryDirectory notify in high QPS
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
XXXXX
=> issue2016: Consumer throws RpcException after RegistryDirectory notify in high QPS

FAQ.md
fix typo error in FAQ
change "Dubbo support to specify" to "Dubbo supports specifying" in FAQ
change "Dubbo support to specify" to "Dubbo supports specifying" in FAQ
NA
=> [Dubbo-2683] Fix typo error in FAQ

dubbo-all/pom.xml, dubbo-bom/pom.xml, dubbo-dependencies-bom/pom.xml, dubbo-distribution/pom.xml, dubbo-serialization/dubbo-serialization-protostuff/pom.xml
fix pom for protostuff serialization
dubbo-all/pom.xml
dubbo-bom/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-distribution/pom.xml
dubbo-serialization/dubbo-serialization-protostuff/pom.xml
XXXXX
=> fix pom for protostuff serialization

CHANGES.md
Add the release note into changes.md
Add the release note into changes.md
=> 2.6.5 release changes.md 

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/AbstractTimerTask.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatTimerTask.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/ReconnectTimerTask.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartBeatTaskTest.java
polish the code for https://github.com/apache/incubator-dubbo/pull/2658
dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/AbstractTimerTask.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatTimerTask.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/ReconnectTimerTask.java …
=> polish the code for pull request 2658

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
isDelay 方法目前返回值如下：
- true: delay == null || delay == -1，表示不延迟导出服务
- false: delay > 0，表示延迟导出服务
我觉得 isDelay  方法返回值如下时，更合理一些：
- true: 延迟导出服务
- false: 无需延迟导出服务
Fix the wrong meaning of the method isDelay
=> 重构 ServiceBean 的 isDelay 方法，使其更符合语义

CHANGES.md
replace pr link with issue link
replace pr link with issue link
=> modify 2.6.5 release log (replace pr link with issue link)

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java
optimize code detail
1. replace ServiceAnnotationBeanPostProcessor.registerServiceBean(...) log.isInfoEnabled to log.isWarnEnabled
2. simplify ExtensionLoader.createAdaptiveExtensionClassCode() some code segment
1. dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
2. dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java
=> optimize ExtensionLoader and ServiceAnnotationBeanPostProcessor some  code segment

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ReferenceConfigTest.java
merge pull request #1999 into 2.6.x branch 
XXXXX
XXXXX
=> fix referenceBean initialization issue

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java
Tests in PortTelnetHandlerTest fail when ran after the ones in DubboProtocolTest even when there’s no bug in the code. Tests in DubboProtocolTest open new ports and servers in DubboProtocol, and tests in PortTelnetHandlerTest implicitly assume no such new ports and servers. The changes ensures DubboProtocolTest closes all the newly opened ports and servers after all tests finish running, so later tests in PortTelnetHandlerTest do not fail.
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java
XXXXX
=> Fixing flaky tests in PortTelnetHandlerTest

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractMethodConfigTest.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java
issue:
https://github.com/apache/incubator-dubbo/issues/2427
=> Add 'forks' config into xml config

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractMethodConfig.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractMethodConfigTest.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/ConfigTest.java
Add forks support for ForkingCluster.
related pr:
https://github.com/apache/incubator-dubbo/pull/2568
=> Add forks support for ForkingCluster.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
fix issue #2748 
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
XXXXX
=> [DUBBO-2748]: Provider should disable mock configuration

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java
Test ChangeTelnetHandlerTest.testChangeServiceNotExport fails when run after the ones in ReferenceCountExchangeClientTest even when there’s no bug in the code. Tests in ReferenceCountExchangeClientTest open new ports and servers in DubboProtocol, and tests in testChangeServiceNotExport implicitly assume no such new ports and servers. The changes ensures ReferenceCountExchangeClientTest closes all the newly opened ports and servers after all tests finish running.
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java
XXXXX
=> Fixing flaky test in ChangeTelnetHandlerTest

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractConfig.java
Fix issue [#2757](https://github.com/apache/incubator-dubbo/issues/2757) that ReferenceBean refers service more than once when debugging.
Please visit [http://t.cn/EAhta27](http://t.cn/EAhta27) for more detail
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
=> Fix the bug that ReferenceBean refers service more than once when debugging.

dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/support/jcache/JCacheFactoryTest.java
JCacheFactoryTest tests fail when run in a different order. This fix changes the port of the URL for testJCacheGetExpired so the two tests' caches do not map to the same location.
dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/support/jcache/JCacheFactoryTest.java
=> Changing URL so tests can run in any order

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/ConfigTest.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/context/annotation/provider/HelloServiceImpl.java
merge pull request #2418  to 2.6.x to fix #2353
dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/ConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/context/annotation/provider/HelloServiceImpl.java
XXXXX
=> [DUBBO-2418]: merge pull request #2353 to 2.6.x to fix #2353

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
fix #2762 
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
XXXXX
=> [DUBBO-2762]: [Dubbo - qos-http] stopServer should be invoked ?

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java
fix #2777 
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java
XXXXX
=> [DUBBO-2777]: heartbeat threads blocks process shutdown

dubbo-common/src/main/java/org/apache/dubbo/common/Parameters.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java
Use `CollectionUtils.toStringMap` to reduce duplicate code in `Parameters`, and use Java 8 type inference for collections.
XXXXX
XXXXX
=> Improvement on Parameters and CollectionUtils

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java, dubbo-common/src/test/java/org/apache/dubbo/common/version/VersionTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
fix typos
- dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
- dubbo-common/src/test/java/org/apache/dubbo/common/version/VersionTest.java
- dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
=> [Fix] fix typos

dubbo-rpc/dubbo-rpc-dubbo/pom.xml, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java
See Issue #2758 
DubboProtocolTest.testDubboProtocolWithMina fails when run by itself. The test tries to create a mina server, but mina is not supported. This pull request adds a dependency on dubbo-remoting-mina for the module so mina can be supported when the test runs.
dubbo-rpc/dubbo-rpc-dubbo/pom.xml b/dubbo-rpc/dubbo-rpc-dubbo/pom.xml
=> [Dubbo-2758] Adding dependency on dubbo-remoting-mina for tests in dubbo-rpc-dubbo

PULL_REQUEST_TEMPLATE.md, dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/AnnotationBean.java
fix typo of field
rename "filed" into "field" in java code and PULL_REQUEST_TEMPLATE.md file
=> fix typo of field

dubbo-remoting/dubbo-remoting-p2p/src/test/java/org/apache/dubbo/remoting/p2p/support/FileNetworkerTest.java
What is the purpose of the change
Fix issue-2838
Brief changelog
Fix FileNetworkerTest failure
Verifying this change
Run UT on windows platform
issue 
https://github.com/apache/incubator-dubbo/issues/2838
=> Fix UT failed on windows with FileNetworkerTest

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouterTest.java
the class ConditionRouter and TagRouter implement duplicate superclass Comparable
/dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/condition/ConditionRouter.java
/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java
run all the test case about the two functions，and their functions are all right
=> remove the duplicate superclass of TagRouter and ConditionRouter

dubbo-cluster/src/test/resources/log4j.xml, dubbo-config/dubbo-config-api/src/test/resources/log4j.xml, dubbo-config/dubbo-config-spring/src/test/resources/log4j.xml, dubbo-container/dubbo-container-spring/src/test/resources/log4j.xml, dubbo-demo/dubbo-demo-consumer/src/main/resources/log4j.properties, dubbo-demo/dubbo-demo-provider/src/main/resources/log4j.properties, dubbo-registry/dubbo-registry-api/src/test/resources/log4j.xml, dubbo-registry/dubbo-registry-default/src/test/resources/log4j.xml, dubbo-remoting/dubbo-remoting-api/src/test/resources/log4j.xml, dubbo-rpc/dubbo-rpc-dubbo/src/test/resources/log4j.xml
Fix log4j pattern layout
XXXXX
XXXXX
=> Fix log4j pattern layout

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
Optimize getExtensionClass method.
Just return the class instead of throwing exception.
org.apache.dubbo.common.extension.ExtensionLoader#getExtensionClass just has one caller that is hasExtension. So it will not effect other logic.
=> Optimize getExtensionClass method.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java
Graceful shutdown enhancement in Spring.
AbstractConfig has added a DubboShutdownHook  in  its constructed function，but when we used spring, SpringExtensionFactory also added a ApplicationListener  to invoke DubboShutdownHook when spring fired ContextClosedEvent.
This seems to have  a problem。  AbstractConfig‘s DubboShutdownHook  will invoke when the application shutdown,  at the same time spring boot shutDownhook will invoke  to close the context。
when the application closing ，dubbo will make sure all the request has return ，if a request used bean in spring ， this bean will close by context。 it will throw error，so in spring ，we should  make  sure dubbo shutdown before  spring  destory its beans。
我怕我英文没有表达清楚，用中文简单描述一下。正好也在解决这个问题，当我的应用在使用spring boot 时，spring boot 会注册一个shutdownhook 来关闭 …
=> Graceful shutdown enhancement in Spring

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java
1. Simplify the code logic of the method AbstractClusterInvoker#reselect，make it more easy to understand.
2. Minor modification for code style.
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java
=> Simplify the code logic of the method AbstractClusterInvoker#reselect.

dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryDirectoryTest.java
add RegistryDIrectory UT 
/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryDirectoryTest.java
UT pass
=> enhance unit test

README.md
there is some dubbo-sample hyperlink which links to 404 page
README.md
=> change ReadME dubbo-sample hyperlink

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/TelnetHandlerAdapter.java
I have noticed that [dubbo's Documentation](https://dubbo.incubator.apache.org/en-us/docs/user/references/xml/dubbo-protocol.html) says there is a telnet config in protocol to config Supported telnet commands,but it seems does not work,Let's make it work again.
make telnet work again.
XXXXX
=> make telnet config work again

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectoryTest.java
Improve UT grammar and remove unnecessary braces.
No functional change to code.
* Improve UT grammar
* remove unnecessary braces.
N/A
=> Improve UT grammar and remove unnecessary braces.

dubbo-common/src/test/java/org/apache/dubbo/common/concurrent/CompletableFutureTaskTest.java
trying to re-enable testCustomExecutor
update UT
start UT
=> re-enable testCustomExecutor

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/StickyTest.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
There are test-order dependencies in org.apache.dubbo.rpc.cluster.StickyTest. testStickyNoCheck fails when run after testStickyForceCheck. The tests depend on the same LoadBalance instance, which enters a different state after testStickyForceCheck runs, which then results in testStickNoCheck to fail when it runs.
The proposed fix introduces a method in ExtensionLoader to reset cached ExtensionLoader instances, for testing purposes only. StickyTest can then use this method to reset the ExtensionLoader for LoadBalance between test runs.
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/StickyTest.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
=> Fixing test-order dependency in org.apache.dubbo.rpc.cluster.StickyTest

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParserTest.java
Release resource after use in ConfigParserTest
The `yamlStream` should be closed after test method.
run unit tests
=> Release resource after use in ConfigParserTest

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java
delete unused logic
/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java
/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java
XXXXX
=> optimize the RoundRobinLoadBalance and MockClusterInvoker

pom.xml
fixes #2864
fix build failure
update dubbo-common/pom.xml
build with `release` profile
`./mvnw package -DskipTests -Pjava8-vm-args -Prelease`
=> [Dubbo-2864] Fix build failed with -Prelease

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/support/DemoService.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/support/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokerTelnetHandlerTest.java
Fix telnet can not find method with enum type
For example:
method:   Type getType(Type type);
When I invoke it in telnet , like 'invoke getType("High")', InvokeTelnetHandler#isMatch always return false;
Run the test:
org.apache.dubbo.rpc.protocol.dubbo.telnet.InvokerTelnetHandlerTest#testInvokeByPassingEnumValue
=> Fix telnet can not find method with enum type

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/ArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/BooleanArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/ByteArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/CharArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/DoubleArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/FloatArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/IntArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/ListMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/LongArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/MapMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/MergerFactory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/SetMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/ShortArrayMerger.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/merger/ResultMergerTest.java
This patch can standardize semantics of all mergers :  merge arguments can be null , and all the others should have same type . 
For ArrayMerger , as its argument type is  Object[]... items ,  so we can avoid checking whether item[i] is
an Array . Also , in order to avoid problems like 
```
class Person{};
class Teacher extends Person{};
Person[] a= {new Person()};
Teacher[] b= {new Teacher()};
Object[] result = ArrayMerger.INSTANCE.merge(a,b);
```
we can require all elements to have the same type , al least the user should pass in the same type
For MergerFactory , if the required class is not in cache , we can throw an user friendly Exception 
For test case , I add some exception case , and fix an ArrayMerger case , also add some null argument
test case . …
=> [Dubbo 2926] standardize semantics of all mergers,enhance mergeFactory and testcases

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/PropertySourcesUtils.java
* Dubbo version: 2.6.0
* Operating System version: Red Hat Enterprise Linux Server release 6.3
* Java version: 1.8.0_92
Spring Boot使用外部配置文件,没有起作用,还是使用的包内application.properties
=> fix issue-2948:spring boot external config invalid

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/AbstractRetryTask.java
The default value is 3. 
Limiting the number of retries prevents memory leaks in some extreme cases.
=> Limit the times of registry retry.

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ActiveLimitFilterTest.java
Solves the problem of 'ActiveLimitFilter' consumer concurrency limit #2328
adjust the concurrency limit of 'ActiveLimitFilter' to calculate atomicity by Semaphore
org.apache.dubbo.rpc.filter.ActiveLimitFilter
org.apache.dubbo.rpc.RpcStatus
=> [Dubbo-2328]Fix the concurrency limit of 'ActiveLimitFilter' to calculate atomicity

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java
This patch can make random choose in LoadBalance more robust . 
As the getWeight method in AbstractLoadBalance uses System.currentTimeMillis(),
so in the random choose stage of  RandomLoadBalance ,the weight may change 
as System.currentTimeMillis() will get new time stamp.
simplified a little bit code in LeastActiveLoadBalance  
make getweight always return weight above zero 
Also add comments for AbstractLoadBalance 
org.apache.dubbo.rpc.cluster.loadbalance.AbstractLoadBalance
org.apache.dubbo.rpc.cluster.loadbalance.RandomLoadBalance
org.apache.dubbo.rpc.cluster.loadbalance.LeastActiveLoadBalance
org.apache.dubbo.rpc.cluster.loadbalance.RoundRobinLoadBalance
=> make loadbalance robust, add comments

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
extract the resolve file logic
/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
ut passed
=> optimize the ReferenceConfig logic

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
…mel-case fix issues  #2973
Pull request for fix the issues for #2973
change CallbackServiceCodec which method referOrdestroyCallbackService Name to referOrDestroyCallbackService
incubator-dubbo/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
XXXXX
=> CallbackServiceCodec method Name Camel-Case Fix #2973

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ActiveLimitFilterTest.java
Fix potential concurrency issue in a simpler way for ActiveLimitFilter and ExecuteLimitFilter. The original changes are: d0e41e8733d0837653e5b2281f6d4b9f9508c2c1 and 2fad342ce1bd6afe683b001d063c82fb89237b48. The semaphores introduced on RpcStatus are a little bit confusing.
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java
XXXXX
=> fix potential concurrency issue in a simpler way for ActiveLimitFilter and ExecuteLimitFilter

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcResult.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcResultTest.java
Fix #619
Recur this bug in https://github.com/zhaixiaoxiang/dubbo-examples/tree/master/hessian-npe-demo
Fix Consumer will generate wrong stackTrace when provider throws exception with empty stackTrace. Please see https://www.yuque.com/fa902k/id5z6r/sr041v
update:
org.apache.dubbo.rpc.RpcResult
add:
org.apache.dubbo.rpc.RpcResultTest
=> [Dubbo-619] Fix consumer will generate wrong stackTrace

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java
enhance shutdown hook in spring, make sure shutdown hook always work in spring, no matter spring framework registers shutdown hook or not.
XXXXX
XXXXX
=> enhance shutdown hook in spring

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/status/ThreadPoolStatusChecker.java
Removing null validation because a null check is not needed before using instanceof
XXXXX
XXXXX
XXXXX
=> Removing null validation because a null check is not needed

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouterFactory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java, dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/ClassUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/io/StreamUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayInputStream.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/Assert.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConfigUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/qos/command/CommandContext.java, dubbo-compatible/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/CompatibleServiceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/Cache.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/CommandContext.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/decoder/TelnetCommandDecoder.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/CommandContextTest.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Response.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyBackedChannelBuffer.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyBackedChannelBuffer.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContext.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContextImpl.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/tps/DefaultTPSLimiter.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java
=> Fixing typos

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
'continue' statement is unnecessary as the last statement in a loop
XXXXX
XXXXX
- [] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
=> 'continue' statement is unnecessary as the last statement in a loop

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvokerTest.java, dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
1.limit the size of the map,default is 1000. can config by key failcapacity
2.retry period,default is 100.can config by key retries.
3.shutdown the timer when destroyed
The issues:
https://github.com/apache/incubator-dubbo/issues/2425
=> Fix FailbackClusterInvoker one risk of memory leak #2425

dubbo-common/src/main/java/org/apache/dubbo/common/utils/Assert.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/AssertTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandler.java
Assert check for proxy object and readbility enhancement for 
1.ConsumerModel.java
2.InvokeTelnetHandler.java
3.ListTelnetHandler.java
Assert check and readbility enhancement for 
1.ConsumerModel.java
2.InvokeTelnetHandler.java
3.ListTelnetHandler.java
Running UT
=> readability enhancement and assert check for proxy object #3032

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/file/FileRouterFactory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
=> Code review around AbstractConfiguratorListener

dubbo-demo/dubbo-demo-consumer/src/main/resources/META-INF/spring/dubbo-demo-consumer.xml
Making changes in dubbo-demo-consumer.xml to use multicast as provider is configured to multicast. So that dubbo demo user can use the sample without any external configuration.
Making changes in dubbo-demo-consumer.xml to use multicast as provider is configured to multicast. So that dubbo demo user can use the sample without any external configuration.
Running locally dubbo-demo provider and consumer and seeing the request-response messages.
=> change the configurtion to work default with multicast address

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
Replace existing hard coded values for dubbo-config below classes
dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
Along with hard coded value replacement have done small refactoring to use java stream and lambda.
Hard coded value replacement of few dubbo-config java classes and small refactoring.
I have run all the …
=> replace hard coded values with constants and small refactor

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Configurator.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/AbstractConfigurator.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
=> Code review

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/AnnotationBean.java
delete useless code
delete useless code
XXXXX
duplicate code
XXXXX
=> Update AnnotationBean.java delete duplicate code

README.md
=> add twitter follow

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractInterfaceConfigTest.java
=> polish code, avoid dup code

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/zkclient/ZkclientZookeeperClient.java
add log in ZkclientZookeeperClient.java
XXXXX
XXXXX
=> Add log in ZkclientZookeeperClient.java

NOTICE
=> [Dubbo-3111] Change NOTICE file to embracing the new year fix #3111

dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/pom.xml
Fix compile error
Previous console output:
```
./mvnw clean install -DskipTests
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for
org.apache.dubbo:dubbo-demo-xml-consumer:[unknown-version]: Could not find
artifact org.apache.dubbo:dubbo-demo:pom:2.7.0-SNAPSHOT and
'parent.relativePath' points at wrong local POM @ line 19, column 13
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)'
must be unique: org.apache.dubbo:dubbo-metadata-definition:jar -> duplicate
declaration of version ${project.parent.version} @
org.apache.dubbo:dubbo-metadata-report-api:[unknown-version],
/root/codes/incubator-dubbo/dubbo-metadata-report/dubbo-metadata-report-api/pom.xml,
line 71, column 21 …
```
=> Fix compile error

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/AbstractMonitorFactory.java, dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java, dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
enhance dubbo-monitor module javadoc #2997 
/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/AbstractMonitorFactory.java
/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java
/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
unit test passed
=> enhance monitor module javadoc

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/AbstractRouter.java, dubbo-common/src/main/java/org/apache/dubbo/common/logger/Logger.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/MethodDefinition.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/ServiceDefinition.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/TypeDefinition.java, dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/support/AbstractMetadataReport.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/org/apache/dubbo/remoting/transport/mina/MinaServer.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java, dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
=> code optimization

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConfigCenterConfigTest.java
=> fix prefix, use hypher case instead of camel case

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractInterfaceConfigTest.java
=> avoid dup refresh for registry config

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/ReconnectTimerTask.java
optimize ReconnectTimerTask's log output
XXXXX
XXXXX
=> optimize ReconnectTimerTask's log output

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
1、modify some log describe
2、use java8 lambda expression 
/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
XXXXX
=> add some small optimize

dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/identifier/MetadataIdentifier.java, dubbo-metadata-report/dubbo-metadata-report-api/src/test/java/org/apache/dubbo/metadata/identifier/MetadataIdentifierTest.java, dubbo-metadata-report/dubbo-metadata-report-zookeeper/src/test/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReportTest.java
Modify metadata node path in zookeeper.   The path as follow：  
/dubbo/metadata/interfaceName/version/group/provider/applicationName or  
/dubbo/metadata/interfaceName/version/group/consumer/applicationName
=> modify metadata node path in zookeeper

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/SimpleAsyncRpcResult.java
* Check future status before get(), return the default value if not completed yet.
* Add comment to announce AsyncRpcResult as unstable and should only be used internally.
* AsyncRpcResult
run `dubbo-samples-async`
=> [Dubbo-3169]Check future status before get(), return default value if not completed yet.

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestProtocol.java
As Luo's advice,
The jax-rs annoations should be preferred to implemation class as the reasons below
1) compatible to old dubbo version
2) Dubbo REST provider can be used without using of Dubbo Conumser for REST (User may access the rest API from JS client directly).
3) Interface should be kept clean without the pullation of REST annoatation.
=> prefer jax-rs annotation on impl and compatible with old version

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-container/dubbo-container-api/src/main/java/org/apache/dubbo/container/Main.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/logging/MessageFormatter.java
some printStackTrace()  forgot use logger to replace
such as 
XXXXX
=> Optimize the code:  some printStackTrace()  forgot use logger to replace

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java
Optimize code: remove unnecessary judgment code.
The method has been judged as null logic at the very beginning.
=> Optimize code: remove unnecessary judgment code.

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
fix CallbackServiceCodec.java exportOrunexportCallbackService method issue.
1. method exportOrunexportCallbackService throw NullPointerException when parameter url is null;
2. private field need camel writing.
method exportOrunexportCallbackService code: 
String group = url.getParameter(Constants.GROUP_KEY);
=> Optimize the code: fix CallbackServiceCodec.java exportOrunexportCallbackService method issue.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Router.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/AbstractRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mock/MockInvokersSelector.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/Router.java, dubbo-compatible/src/test/java/org/apache/dubbo/rpc/cluster/CompatibleRouter2.java, dubbo-compatible/src/test/java/org/apache/dubbo/rpc/cluster/NewRouter.java, dubbo-compatible/src/test/java/org/apache/dubbo/rpc/cluster/RouterTest.java
Extract compareTo impl to Router interface and concrete Router only responsible for provide priority.
Add default compareTo implementation to Router interface
remove compateTo from impl class
=> Extract compareTo impl to Router interface and concrete Router only responsible for provide priority.

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-common/src/main/java/org/apache/dubbo/common/Parameters.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/RegistryConfig.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
modify some typos
org.apache.dubbo.config.AbstractInterfaceConfig
org.apache.dubbo.config.RegistryConfig
XXXXX
=> modify some typos

dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java
optimize the Apollo extension of Config-Center SPI
ApolloDynamicConfiguration
https://github.com/apache/incubator-dubbo-samples/tree/samples-for-2.7.0-SNAPSHOT/dubbo-samples-configcenter/dubbo-samples-configcenter-apollo
=> optimize apollo extension

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/Router.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/directory/AbstractDirectory.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/AbstractRouter.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/MockInvokersSelector.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/script/ScriptRouter.java, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/tag/TagRouter.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/loadbalance/LoadBalanceTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/router/tag/TagRouterTest.java, dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Service.java, dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/AnnotationBean.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-default/src/test/java/com/alibaba/dubbo/registry/dubbo/RegistryDirectoryTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java
Import old TagRouter into 2.6.x
This feature is merged at 2.7.x
=> [Dubbo - 2.6.x TagRouter Feature] Import old TagRouter into 2.6.x

dubbo-rpc/dubbo-rpc-redis/src/test/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocolTest.java
Unit Test about auth test in RedisProtocolTest.java is disabled, bring it back.
RedisProtocolTest.java
enable `testAuthRedis ` and `testWrongAuthRedis `
UT pass
=> Bring back redis auth UT

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
Optimize code: Fix Constructor to determine illegal logic problems
Util class PojoUtils has Constructor to determine illegal logic problems。
=> Optimize code: Fix Constructor to determine illegal logic problems

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
fix return type for method getMethodParameter in URL class
fix return type for method getMethodParameter in URL class
has verified
=> Fix return type for method getMethodParameter

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java
use StandardCharsets.UTF_8 instead of literal 'UTF-8' and remove the useless exception handling 
use StandardCharsets.UTF_8 instead of literal 'UTF-8'
has verified
=> use standardcharset.utf-8 instead of literal

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ShutdownTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.telnet.TelnetHandler, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ShutdownTelnetHandlerTest.java
Add shutdown command for telnet
Add shutdown command for telnet , let user can shutdown the application from telnet
XXXXX
=> Add shutdown command for telnet

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
further enhancement for pull request #3297, also fix an issue introduced in this pull request
XXXXX
XXXXX
=> further enhancement for pull request #3297, also fix an issue introduced in this pull request

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/AbstractTimerTask.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java
We should cancel the timeout when the client or server is close to guarantee that our tasks will not be too much.
=> Optimize heartbeat

dubbo-serialization/dubbo-serialization-protostuff/src/main/java/org/apache/dubbo/common/serialize/protostuff/ProtostuffObjectInput.java, dubbo-serialization/dubbo-serialization-protostuff/src/main/java/org/apache/dubbo/common/serialize/protostuff/ProtostuffObjectOutput.java, dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/protostuff/ProtostuffSerializationTest.java
Loop reference test pass on protostuff
Change ProtobufIOUtil to GraphIOUtil
see https://github.com/protostuff/protostuff/issues/258
XXXXX
=> [Dubbo-master] Fix fail when loop reference test on protostuff

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java
Fix timeout filter not work in async way.
=> Fix timeout filter not work in async way.

dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/integration/MetadataReportService.java, dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/support/AbstractMetadataReport.java
Due to java memory model, the field should be `volatile`
make field `volatile`
XXXXX
=> Fix double-checked locking

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
Refresh invocation's attachments in each invoke.
Fix bug:
https://github.com/apache/incubator-dubbo/issues/2981
=> Refresh invocation's attachments in each invoke.

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java, dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java, dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java, dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java
=> optimize outbound event and some format

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Configurator.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/AbstractRouter.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Protocol.java, dubbo-compatible/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/CompatibleReferenceBeanBuilder.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotationInjectedBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilder.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperTransporter.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperTransporter.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/zkclient/ZkclientZookeeperTransporter.java
add @Override annotation for override method
add @Override annotation for override method
XXXXX
=> add @Override annotation for override method

all/pom.xml
Download the shade source， and add some log or you can directly debug:
org.apache.maven.plugins.shade.mojo.ShadeMojo#execute
The dubbo.jar will generate from some jars including dubbo.jar itself.
When you run `mvn clean install -DskipTests` , it willl work well.  Because the original dubbo.jar is deleted.
After that if you run `mvn install -DskipTests`, it will merge two part files . one part  is from many other jar(netty, netty4, mina etc.), and one is from dubbo.jar.  The shade plugin will merge this file into one.(org.apache.maven.plugins.shade.resource.AppendingTransformer in pom.xml)
```
netty=com.alibaba.dubbo.remoting.transport.netty.NettyTransporter
netty4=com.alibaba.dubbo.remoting.transport.netty4.NettyTransporter
mina=com.alibaba.dubbo.remoting.transport.mina.MinaTransporter …
```
=> fix #2842.  remove duplicate SPI definitions

dubbo-all/pom.xml, dubbo-container/dubbo-container-api/pom.xml, pom.xml
fix #2842. remove duplicate SPI definitions for 2.7.x
=> fix #2842. remove duplicate SPI definitions for 2.7.x

dubbo-config/dubbo-config-spring/src/test/resources/META-INF/dubbb-provider.properties, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/GenericFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/GenericImplFilterTest.java
=> fix org.apache.dubbo replace com.alibaba.dubbo

dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/ArrayTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/CollectionTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/EnumTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/MapTypeBuilder.java
Review code of TypeDefinitionBuilder
1. use init method to init builds' list
@cvictory Would u pls have a look?
=> Review code of TypeDefinitionBuilder

README.md
fix the package name
fix the package name
XXXXX
=> package's name is error

dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/textui/TKvTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/textui/TLadderTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/textui/TTableTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java
=> fix some unit test failed

dubbo-monitor/dubbo-monitor-default/src/test/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitorTest.java
Although branch `2.6.x` haven't support jdk11 yet, I think we can still backport this patch (#3327) on it.
DubboMonitorTest is under different package for 2.6.x, so a separated PR is needed.
Update `DubboMonitorTest.java`
UT pass on branch 2.6.x
=> Backport patch for #3327

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProxyProtocol.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/org/apache/dubbo/rpc/protocol/webservice/WebserviceProtocolTest.java
When modifying the configuration through override, you need to re-expose the newly modified service.
Compare the new url with the old url. If they are the same, they will be directly fetched from the collection. If they are different, re-create an export.
fix https://github.com/apache/incubator-dubbo/issues/900
XXXXX
XXXXX
=> [Dubbo-900] Fix 通过 override 修改 hessian协议的提供者的配置 不生效 #900

dubbo-compatible/src/test/java/org/apache/dubbo/generic/GenericServiceTest.java, dubbo-compatible/src/test/java/org/apache/dubbo/service/ComplexObject.java, dubbo-metadata-report/dubbo-metadata-definition/src/test/java/org/apache/dubbo/metadata/definition/service/ComplexObject.java
Fix invalid self-assignment.
- modify parameter name to match class member name (for `setInnerA2` and `setInnerB2`)
- replace `Set` with `List` to insure item order (make UT pass)
- fix a typo in method name (`createComplextObject` -> `createComplexObject`)
XXXXX
=> Fix self assignment

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java, dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java
Fixes #2423
MulticastRegistry
NetUtils
Run demos using the multicast registry.
Check MulticastRegistryTest UT
=> [Dubbo-2423] Multicast demo fails with message "Can't assign requested address".

dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java
在使用redis做为注册中心时，发现服务不能引用
CollectionUtils.isEmptyMap(values)改为if (!CollectionUtils.isEmptyMap(values)) 
XXXXX
=> 应该是非空才循环，不然会导致在使用redis注册中心时消费者引用不到服务

.travis.yml, dubbo-cluster/src/test/resources/log4j.xml, dubbo-common/src/main/java/org/apache/dubbo/common/utils/DubboAppender.java, dubbo-common/src/test/resources/log4j.xml, dubbo-registry/dubbo-registry-default/src/test/resources/log4j.xml, dubbo-remoting/dubbo-remoting-netty/src/test/resources/log4j.xml, dubbo-rpc/dubbo-rpc-api/src/test/resources/log4j.xml, dubbo-rpc/dubbo-rpc-dubbo/src/test/resources/log4j.xml, dubbo-serialization/dubbo-serialization-test/src/test/resources/log4j.xml
limit console output of unit test
Fix #3361
Make DubboAppender extends from FileAppender
Tweak unit test log path
UT pass and Travis log size drop to about 1.5MB
for local environment there should be a `dubbo.log` file contains unit test log.
=> [Dubbo-3361] Make DubboAppender extends from FileAppender

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java, dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/support/AbstractMetadataReport.java, dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java
Small improvments, including:
* use `ThreadLocalRandom` instead of `Random`
* use try-with-resource to avoid explicit resource management
* fix duplicate code
XXXXX
XXXXX
=> [Enhancement] Use ThreadLocalRandom and try-with-resource

README.md
* The link of Dubbo samples is outdated, update them
* fix a typo, from `eco system` to `ecosystem`
XXXXX
XXXXX
=> Update Dubbo samples' link and fix a typo

dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/support/ActivateComparator.java
[dubbo-3309] fix #3309 
When all active implementation classes of a SPI interface are sorted (Activate Comparator), and when the implementation classes of the SPI interface not only implement the SPI interface, but also other non-SPI interfaces, if the SPI interface is not in the first place of the implements, the function of before and after will fail.
get the specified SPI interface modifier.
XXXXX
=> Activate SPI sort

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
extract method ：cacheWrapperClass
extract method ：cacheAdaptiveClass
extract method ：cacheActivateClass
extract method ：saveInExtensionClasses
extract method ：cacheNames
(names != null && names.length > 0)，is always true, remove it
XXXXX
XXXXX
XXXXX
=> refactor loadClass method

dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java
implement pull request #3412 on master branch
XXXXX
XXXXX
=> implement pull request #3412 on master branch

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java, dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java, dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistryTest.java
Remove unused duplicated method
Remove unused method `org.apache.dubbo.registry.zookeeper.ZookeeperRegistry#appendDefaultPort` and move the unit tests to `org.apache.dubbo.common.URLTest`, which has the same method and is used and missing a unit test
CI pass
=> remove duplicated unused method and move unit test

dubbo-container/dubbo-container-api/src/main/java/org/apache/dubbo/container/Container.java, dubbo-container/dubbo-container-api/src/main/java/org/apache/dubbo/container/Main.java, dubbo-container/dubbo-container-log4j/src/main/java/org/apache/dubbo/container/log4j/Log4jContainer.java, dubbo-container/dubbo-container-logback/src/main/java/org/apache/dubbo/container/logback/LogbackContainer.java, dubbo-container/dubbo-container-spring/src/main/java/org/apache/dubbo/container/spring/SpringContainer.java
Fixes #2994
This code change is to enhance the java doc for dubbo-container module for which issue was created at https://github.com/apache/incubator-dubbo/issues/2994
XXXXX
XXXXX
XXXXX
=> [Dubbo-Container] Fix Enhance the java doc of dubbo-container module

dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/ClassUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/CtClassBuilder.java, dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JavassistClassInfo.java, dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JavassistCompiler.java, dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/ClassUtilsTest.java
refactor javassist compiler: extract class CtClassBuilder
so the compile process is much more clearer
XXXXX
XXXXX
=> refactor javassist compiler: extract class CtClassBuilder

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
isSetter: test if a method is a setter: public, one parameter, starts with "set"
getSetterProperty: get property for setter, for instance setVersion return "version"
XXXXX
XXXXX
XXXXX
=> extract 2 methods: isSetter and getSetterProperty

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
Add delay export test case #3447
Add delay export test case #3447
UT
=> Add delay export  test case

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestProtocol.java
=> [Dubbo-3237]fix connectionMonitor in RestProtocol seems not work #3237

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
=> extract method to cache default extension name

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java
Enhancement
org.apache.dubbo.common.extension.ExtensionLoader
XXXXX
=> [Enhancement]: language level migration

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
=> Branch refactor version

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestProtocol.java
- use `Map#computeIfAbsent` to replace check-and-create
- use lambdas to replace annonymous inner types
XXXXX
XXXXX
XXXXX
=> [Enhancement]: RestProtocol

dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryProtocol.java
=> apply #3295 to 2.6 branch

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/directory/MockDirInvocation.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invocation.java, dubbo-compatible/src/test/java/org/apache/dubbo/cache/CacheTest.java, dubbo-compatible/src/test/java/org/apache/dubbo/service/MockInvocation.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/AddressListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invocation.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationInitListener.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerMethodModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ProviderMethodModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ProviderModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ServiceMetadata.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvocation.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ImplicitCallBackTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokerTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/RestProtocolTest.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protol/rest/RestProtocolTest.java
- add a attributeMap to Invocation
-  rename the varibale name NAME_ID_MAP
-  add a method for class CodecSupport
- import servicemetada and associated it with models class
=> Mostly modification to satisfy more complexing support scenrio such as service Level model

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ReferenceConfigCacheTest.java
fix issue#1293: A question for ReferenceConfigCache.
XXXXX
XXXXX
=> fix issue#1293: A question for ReferenceConfigCache.

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
Refactor `RegistryDirectory` to reduce loop times.
`classifyUrls(categoryUrls, UrlUtils::isProvider)` will loop over the `urls`, and calling it multiple times will loop over it multiple times, while `Collectors.groupingBy` will only loop over it once
`org.apache.dubbo.registry.integration.RegistryDirectory`
XXXXX
=> [Enhancement]: refactor categorizing with Collectors.groupingBy

dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/CollectionTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/MapTypeBuilder.java
FindBugs-3.0.1 ([http://findbugs.sourceforge.net/](http://findbugs.sourceforge.net/)) reported two DMI_INVOKING_TOSTRING_ON_ARRAY warnings on master:
```
DMI_INVOKING_TOSTRING_ON_ARRAY: Invocation of toString on actualTypeArgs in org.apache.dubbo.metadata.definition.builder.CollectionTypeBuilder.build(Type, Class, Map) At CollectionTypeBuilder.java:[line 50]
DMI_INVOKING_TOSTRING_ON_ARRAY: Invocation of toString on actualTypeArgs in org.apache.dubbo.metadata.definition.builder.MapTypeBuilder.build(Type, Class, Map) At MapTypeBuilder.java:[line 49]
```
The description of this bug is as follows:
> USELESS_STRING: Invocation of toString on an array (DMI_INVOKING_TOSTRING_ON_ARRAY)
> The code invokes `toString` on an array, which will generate a fairly useless result such as `[C@16f0472`. …
=> Fix invocation of toString on an array

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderConsumerRegTable.java
FindBugs-3.0.1 ([http://findbugs.sourceforge.net/](http://findbugs.sourceforge.net/)) reported a WMI_WRONG_MAP_ITERATOR warning on master:
```
WMI_WRONG_MAP_ITERATOR: org.apache.dubbo.registry.support.ProviderConsumerRegTable.getProviderWrapper(URL, Invoker) makes inefficient use of keySet iterator instead of entrySet iterator At ProviderConsumerRegTable.java:[line 77]
```
The description of this bug is as follows:
> WMI: Inefficient use of keySet iterator instead of entrySet iterator (WMI_WRONG_MAP_ITERATOR)
> This method accesses the value of a `Map` entry, using a key that was retrieved from a `keySet` iterator. It is more efficient to use an iterator on the `entrySet` of the map, to avoid the `Map.get(key)` lookup.
[http://findbugs.sourceforge.net/bugDescriptions.html#WMI_WRONG_MAP_ITE …
=> Fix inefficient use of keySet iterator instead of entrySet iterator

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
Boolean class use method toString() instead of String.valueof()
String.valueof() will executes the null check first.
```
public static String valueOf(Object obj) {
return (obj == null) ? "null" : obj.toString();
}
```
But we've already done it manually.
```
public void setMock(Boolean mock) {
if (mock == null) {
setMock((String) null);
} else {
setMock(mock.toString());
}
}
```
So I think we just need toString() method.
=> Boolean class use method toString() instead of String.valueof()

dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/telnet/support/TelnetHandlerAdapter.java
=> Apply #2925 to branch 2.6.x

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java, dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java
Related issue #3106 
XXXXX
XXXXX
=> [Dubbo-3106]Make getRegistered return unmodifiable collection. #3106

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ProviderConfig.java
Fix accidentally check in ProviderConfig.setDispathcher()
see [issue](https://github.com/apache/incubator-dubbo/issues/3518)
=> Fix accidentally check exchanger in setDispatcher()(#3518)

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java
fix ScriptRouter中的CompiledScript应该缓存？ #390
XXXXX
XXXXX
=> fix ScriptRouter中的CompiledScript应该缓存 #390

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RpcContextFilter.java
fix context filter's bug:
`String value = entry.getKey();` -> `String value = entry.getValue();`
=> fix context filter's bug

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ServiceMetadata.java
remove getAttributeMap of ServiceMetada
XXXXX
XXXXX
=> remove getAttributeMap of ServiceMetada

dubbo-compatible/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Reference.java
fix issue #195: @Reference check=false不生效
XXXXX
XXXXX
=> fix issue #195: @Reference check=false不生效

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java
fix issue #208: 异步泛化调用设置setOnreturn无效 2.5.3版本, should also fix #3408, #3163, 
XXXXX
XXXXX
=> fix issue #208: 异步泛化调用设置setOnreturn无效 2.5.3版本

dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitorFactory.java
fix issue #274: monitor的cluster一定是failsafe的，而且无法修改
XXXXX
XXXXX
=> fix issue #274: monitor的cluster一定是failsafe的，而且无法修改

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java
fix issue #538: 关于dubbo中获取本机IP的问题
also allow register local ip to registry from both consumer and provider for better development experience, by default NetUtil#getLocalAddress will return a possible public IP.
XXXXX
XXXXX
=> fix issue#538: 关于dubbo中获取本机IP的问题

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/AddressListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
allow addressListner to return new addressList for filtering
XXXXX
XXXXX
=> allow addressListner to return new addressList for filtering

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AppendParametersComponent.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
add AppendParametersComponent to dynamically add some parameters / check config
- add new SPI AppendParametersComponent
- when ServiceConfig/ReferenceConfig init, AppendParametersComponents will init and check
=> [Feature] add AppendParametersComponent

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Router.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/AbstractRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/AppRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ListenableRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ServiceRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mock/MockInvokersSelector.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java
fix issue https://github.com/apache/incubator-dubbo/issues/3302
remove useless implement and the duplicate compareTo logic,use getPriotity instead.
=> Optimize compareTo in Router to guarantee consistent behaviour.

dubbo-rpc/dubbo-rpc-rmi/src/main/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocol.java, dubbo-rpc/dubbo-rpc-rmi/src/main/java/org/apache/dubbo/rpc/protocol/rmi/RmiRemoteInvocation.java, dubbo-rpc/dubbo-rpc-rmi/src/test/java/org/apache/dubbo/rpc/protocol/rmi/DemoService.java, dubbo-rpc/dubbo-rpc-rmi/src/test/java/org/apache/dubbo/rpc/protocol/rmi/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-rmi/src/test/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocolTest.java
fix RMI protocol doesn't support generic invocation. #2779
XXXXX
XXXXX
=> Rmi support generic

dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java
Fixes #3236, terminate when tomcat server fails to start.
Set system property before start tomcat server.
=> [Dubbo-3236]  terminate when tomcat server fails to start.

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitorFactory.java
Replace magic string with `Constants`
XXXXX
XXXXX
=> [CLEAN-UP] Replace magic string with constants

README.md
文档不正确，运行时会缺少依赖
增加dubbo的pom文件。zookeeper/curator-framework的依赖。因为dubbo-dependencies-bom当中声明curator-framework时去除了zookeeper的版本，所以外部还需要额外机上zookeeper的依赖包。
XXXXX
=> dubbo-parent是头文件不包含依赖。替换成dubbo, 同时增加zk连接的依赖。

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java
Dump TagRouterRule since the TagRouterRule can be changed to `null` by ConfigCenter.
Since his Issue[1] does not give a stack trace, I am not sure that his problem is caused by this.
[1] https://github.com/apache/incubator-dubbo/issues/3533
=> Dump TagRouterRule

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Reference.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
follow up for issue #195
XXXXX
XXXXX
=> follow up for issue 195

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/config/ConfigurationUtilsTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/StringUtilsTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
Fixes #3367, fail to parse config text with white space
XXXXX
XXXXX
=> [Dubbo-3367], fail to parse config text with white space

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java, dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryDirectoryTest.java
=> [Dubbo-3555] check if remoteGroup is empty or not to fix 3555

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/NetUtils.java, dubbo-registry/dubbo-registry-multicast/src/main/java/com/alibaba/dubbo/registry/multicast/MulticastRegistry.java, dubbo-registry/dubbo-registry-multicast/src/test/java/com/alibaba/dubbo/registry/multicast/MulticastRegistryTest.java
The same issue as #3317 for master.
XXXXX
XXXXX
=> Multicast ipv6 support for branch 2.6.x

dubbo-all/pom.xml, dubbo-bom/pom.xml, dubbo-configcenter/dubbo-configcenter-consul/pom.xml, dubbo-configcenter/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfigurationFactory.java, dubbo-configcenter/dubbo-configcenter-consul/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.configcenter.DynamicConfigurationFactory, dubbo-configcenter/pom.xml, dubbo-dependencies-bom/pom.xml, dubbo-metadata-report/dubbo-metadata-report-consul/pom.xml, dubbo-metadata-report/dubbo-metadata-report-consul/src/main/java/org/apache/dubbo/metadata/store/consul/ConsulMetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-consul/src/main/java/org/apache/dubbo/metadata/store/consul/ConsulMetadataReportFactory.java, dubbo-metadata-report/dubbo-metadata-report-consul/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.store.MetadataReportFactory, dubbo-metadata-report/pom.xml, dubbo-registry/dubbo-registry-consul/pom.xml, dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java, dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistryFactory.java, dubbo-registry/dubbo-registry-consul/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.RegistryFactory, dubbo-registry/pom.xml, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
support consul on 2.7 #983 
XXXXX
XXXXX
=> Consul support

dubbo-bom/pom.xml, dubbo-common/src/test/java/org/apache/dubbo/common/config/ConfigurationUtilsTest.java, dubbo-dependencies-bom/pom.xml, dubbo-registry/dubbo-registry-etcd3/pom.xml, dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdRegistry.java, dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdRegistryFactory.java, dubbo-registry/dubbo-registry-etcd3/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.RegistryFactory, dubbo-registry/dubbo-registry-etcd3/src/test/java/org/apache/dubbo/registry/etcd/EtcdRegistryTest.java, dubbo-registry/pom.xml, dubbo-remoting/dubbo-remoting-etcd3/pom.xml, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/AbstractRetryPolicy.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/ChildListener.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/EtcdClient.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/EtcdTransporter.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/RetryPolicy.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/StateListener.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClient.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdTransporter.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/RetryLoops.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/RetryNTimes.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/option/Constants.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/option/OptionUtil.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/support/AbstractEtcdClient.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.etcd.EtcdTransporter, dubbo-remoting/dubbo-remoting-etcd3/src/test/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientTest.java, dubbo-remoting/dubbo-remoting-etcd3/src/test/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapperTest.java, dubbo-remoting/pom.xml
This pull request add the support for etcd as registry. #808 
1. merge code from https://github.com/dubbo/dubbo-registry-etcd into incubator-dubbo.
2. Update all the unit test from Junit 4 to Junit 5
3. Remove all the author info
4. Fix some typo
Note that unit tests are disabled by default, because there is no embedded etcd server. If you would like to run the unit test, you need to start an etcd server locally.
Write a demo application and verified provider and consumer could work with etcd as reigstry.
=> [Dubbo-808] Support etcd registry

CHANGES.md, README.md
because dubbo-ops has been renamed to dubbo-admin, this patch updates their references
CHANGES.md
README.md
=> rename dubbo-ops to dubbo-admin

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClient.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java
1.  service node may be lost at startup.
2. Separate push notifications and keepalive threads.
ci passed.
=> fix some etcd3 registry bugs.

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java
Fix when qos is disable,log will print every time where protocol.export() and protocol.refer()
change qos server thread number 1;
Fix when qos is disable,log will print every time where protocol.export() and protocol.refer()
change qos server thread number 1;
XXXXX
=> Fix when qos is disable,log will print every time.

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
=> fix heartbeat internal

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboConfigConfigurationRegistrar.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubbo.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboConfig.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/SpringStatusChecker.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilderTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboConfigTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/provider/DemoServiceImpl.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/status/SpringStatusCheckerTest.java
- Change the default behavior of @EnableDubboConfig.multiple(): #3193
- `@Reference` NPE issue #3429
- `@Reference` service throws UndeclaredThrowableException : #3386
- `SpringStatusChecker` executes errors on non-XML Spring configuration : #3615
=> Enhancement and Bugfix in 2.7.1 ( Part 1 )

dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdRegistry.java
polish code and fix some documentation errors
org.apache.dubbo.registry.etcd.EtcdRegistry
XXXXX
=> polish code and fix some documentation errors

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/tps/DefaultTPSLimiter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/tps/StatItem.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/tps/DefaultTPSLimiterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/tps/TpsLimitFilterTest.java
optimize DefaultTpsLimiter
1. Replace AtomicInteger with LongAdder,  LongAdder is better than  AtomicInteger When multi-threaded.
2. Fix  when change rate value， it is not effective.
UT
=> optimize DefaultTpsLimiter

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ProviderMethodModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ProviderModel.java
add more information for  ProviderMethodModel
ProviderMethodModel add parameterClasses and genericParameterTypes property
=> improve:ProviderMethodModel add parameterClasses

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyCodecAdapter.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/DubboTelnetDecodeTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/LocalEmbeddedChannel.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/MockChannel.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/MockChannelHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/MockHandler.java
Add unit test for unpack and stick pack of dubbo and telent
NettyCodecAdapter.java
DubboTelnetDecodeTest.java
LocalEmbeddedChannel.java
MockChannel.java
MockChannelHandler.java
MockHandler.java
run unit test
=> Add unit test for unpack and stick pack of dubbo and telent

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java, dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/support/jvalidation/JValidatorTest.java, dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/support/jvalidation/mock/JValidatorTestTarget.java
Add unit test of JValidator; clean code of JValidator
1.JValidatorTest and relative test class
2.JValidator
XXXXX
=> Unit test of JValidator; Clean code of JValidator

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
Remove magic number 5 in CacheListener
To remove magic number 5 found in line 92 of org.apache.dubbo.configcenter.support.zookeeper.CacheListener#childEvent.
fix #3625 
Add a static constant.
XXXXX
=> [Dubbo-3625] Remove magic number 5 in CacheListener

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java, dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
=> [Dubbo-3744]Create constants for 'hash.names' and 'hash.arguments' (#3744)

dubbo-serialization/dubbo-serialization-fastjson/src/main/java/com/alibaba/dubbo/common/serialize/fastjson/FastJsonObjectInput.java, dubbo-serialization/dubbo-serialization-fastjson/src/test/java/com/alibaba/dubbo/common/serialize/fastjson/FastJsonObjectInputTest.java, dubbo-serialization/dubbo-serialization-fastjson/src/test/java/com/alibaba/dubbo/common/serialize/fastjson/model/Organization.java
修复fastjson序列的问题，有三层泛型以上时序列化报错 如：A\<B\<C\>\>
修复fastjson序列的问题，有三层泛型以上时序列化报错 如：A\<B\<C\>\>
三层泛型以上 会序列化成JSONArray 或者 JSONObject导致获取对象时发生强转异常
： Class1 cannot be cast to Class2
=> fix fastjson serialize type

dubbo-serialization/dubbo-serialization-api/pom.xml
remove redundant dependence of third-party jar packages in dubbo-serialization -api modules #3762
XXXXX
XXXXX
=> [Dubbo-3762]remove redundant dependence 

dubbo-serialization/dubbo-serialization-fastjson/src/main/java/org/apache/dubbo/common/serialize/fastjson/FastJsonObjectInput.java, dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/fastjson/FastJsonObjectInputTest.java, dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/Organization.java
修复fastjson序列的问题，有三层泛型以上时序列化报错 如：A<B<C>>
修复fastjson序列的问题，有三层泛型以上时序列化报错 如：A<B<C>>
三层泛型以上 会序列化成JSONArray 或者 JSONObject导致获取对象时发生强转异常
： Class1 cannot be cast to Class2
some issues https://github.com/apache/incubator-dubbo/pull/3767
=> fix fastjson serialization with generic return type

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcResult.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcResultTest.java
Fix #619 , and PR #2956 is not enough in the following use case:
In souche.com, we add 'trace' function in dubbo, such as in FailoverClusterInvoker.doInvoke, we get stackTrace from exception to log detail exception info using the following:
`org.apache.commons.lang3.exception.ExceptionUtils.getStackTrace(result.getException())`
The above sentence will result the same problem with issue #619 .
So, we should solve this in decode stage.
#619 这个问题, PR #2956 貌似已经解决了, 但是我们公司(souche.com)在对dubbo加全链路埋点时, 还是遇到了之前的问题, 因为 #2956 是在InvokerInvocationHandler.invoke()方法的invoker.invoke(invocation)后解决了问题, 但是我们在FailoverClusterInvoker.doInvoke()方法里坐全链路埋点时, 为了能取到异常栈的信息, 用了如下的语句:
`org.apache.commons.lang3.exception.ExceptionUtils.getStackTrace(result.getException())`
导致了异常栈又出问题了..
所以应该在decode后, …
=> [Dubbo-619] Fix #619 and PR #2956 is not enough

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ProviderConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/RegistryConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
replace hard code strings with constants in config module.
the following hard code strings had been replaced:
- in ServiceConfig:
"revision" -> Constants.REVISION_KEY
"registry" -> Constants.REGISTRY_KEY
- in RegistryConfig:
"username" -> Constants.USERNAME_KEY
"password" -> Constants.PASSWORD_KEY
"file" -> Constants.FILE_KEY
"client" -> Constants.CLIENT_KEY
- in ReferenceConfig:
"revision" -> Constants.REVISION_KEY
"methods" -> Constants.METHODS_KEY
"client" -> Constants.CLIENT_KEY
- in ProviderConfig:
"contextpath" -> Constants.CONTEXTPATH_KEY
"status" -> Constants.STATUS_KEY
- in AbstractInterfaceConfig
"logstat" -> Constants.LOGSTAT_PROTOCOL
"local" -> Constants.LOCAL_KEY
"cluster" -> Constants.CLUSTER_KEY
"proxy" -> Constants.PROXY_KEY
"filter" -> Constants.FILE_KEY
"listener" -> …
=> [Dubbo-3795] replace hard code strings with constants in config moudule

dubbo-compatible/src/main/java/com/alibaba/dubbo/config/annotation/Service.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Service.java
Make `dynamic` default true to promise that the url will delete from zk whenever provider shutdown.
Fix issue:
https://github.com/apache/incubator-dubbo/issues/3785
=> Fix issue 3785

dubbo-all/pom.xml, dubbo-bom/pom.xml, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java, dubbo-dependencies-bom/pom.xml, dubbo-distribution/pom.xml, dubbo-rpc/dubbo-rpc-jsonrpc/pom.xml, dubbo-rpc/dubbo-rpc-jsonrpc/src/main/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcProtocol.java, dubbo-rpc/dubbo-rpc-jsonrpc/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.rpc.Protocol, dubbo-rpc/dubbo-rpc-jsonrpc/src/test/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcProtocolTest.java, dubbo-rpc/dubbo-rpc-jsonrpc/src/test/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcService.java, dubbo-rpc/dubbo-rpc-jsonrpc/src/test/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcServiceImpl.java, dubbo-rpc/pom.xml, dubbo-test/pom.xml
add a new protocol JSON-RPC. The changes were moved from the origin repository: https://github.com/apache/incubator-dubbo-rpc-jsonrpc
=> Add JSON-RPC protocol

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java
In the process of using Dubbo, there are many scenarios where the Provider needs to know the applicationName of the Consumer (not just the Consumer IP). For example, I want to output the upstream caller to the log file and want to limit the flow according to the upstream application. Or downgrade, want to use the upstream application for arson drills, etc., so we usually add Filter to achieve (for example, DubboAppContextFilter in Sentinel, which is specifically done on the Consumer side: https://github.com/alibaba/Sentinel/ Blob/6bb4ff21dadde00c9453a5f57d030d55f87b71a8/sentinel-adapter/sentinel-dubbo-adapter/src/main/java/com/alibaba/csp/sentinel/adapter/dubbo/DubboAppContextFilter.java), so I also hope that Dubbo can put this inside Simple things have been done …
=> RpcContext新增remoteApplicationName字段

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
Complete xsd definition of ConfigCenterConfig to get rid of warning from IDE.
=> Complete xsd definition for ConfigCenterConfig.

README.md, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringCache.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringMap.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/jcache/JCache.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/lru/LruCache.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/threadlocal/ThreadLocalCache.java, dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/AbstractValidation.java, dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/CollectionTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/EnumTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/builder/MapTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/MethodDefinition.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/ServiceDefinition.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/TypeDefinition.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/util/ClassUtils.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Filter.java
=> polish code and fix (#3761)

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/support/Parameter.java
see issue described here https://github.com/apache/incubator-dubbo/issues/3682
XXXXX
XXXXX
=> Revert #3688 config-center-config

dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryProtocolTest.java
Currently some tests in RegistryProtocolTest do not use the RegistryProtocol.getRegistryProtocol() method to get the singleton RegistryProtocol instance. These tests directly create new instances of RegistryProtocol, which changes the singleton to point to the newly created instance. Doing so leads to tests in test class to fail when run in certain orders. For example, running the tests [testNotifyOverride_notmatch, testExportUrlNull, testNotifyOverride] in that exact order leads to testNotifyOverride to fail.
The proposed change is to have every test use the RegistryProtocol.getRegistryProtocol() method to get the same instance of RegistryProtocol.
dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryProtocolTest.java
=> Use singleton RegistryProtocol in tests

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
resolve #3746 
When `IOException` is thrown in `org.apache.dubbo.registry.support.AbstractRegistry#doSaveProperties`, which is usually unrecoverable (permission denied, path not exists or no free disk space) it will retry infinitely, this patch tries to resolve this issue by stop retrying when `IOException` occurs.
org.apache.dubbo.registry.support.AbstractRegistry
XXXXX
=> [DUBBO-3746] Bugfix: infinite loop in AbstractRegistry when IOException. fix #3746

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ProviderConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractServiceConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java
fix bug
issue: https://github.com/apache/incubator-dubbo/issues/3841
make protocols a mutable list (a concrete ArrayList)
XXXXX
=> make protocols a mutable list (a concrete ArrayList)

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailsafeClusterInvoker.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/MockResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Filter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/CompatibleFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ConsumerContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExceptionFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcResultTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/CompatibleFilterFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ExceptionFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/GenericFilterTest.java, dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodec.java, dubbo-rpc/dubbo-rpc-thrift/src/test/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodecTest.java
Rename some variables to avoid possible confusion between Result and AppResponse.
XXXXX
XXXXX
=> Rename some variables to avoid possible confusion between Result and AppResponse.

dubbo-serialization/dubbo-serialization-gson/pom.xml
fix #3903 
/dubbo-serialization/dubbo-serialization-gson/pom.xml
mvn package
=> [Dubbo-3903] Fix maven package error of dubbo-serialization-gson

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Result.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AbstractResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Filter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Result.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolFilterWrapper.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ExceptionFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/GenericImplFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MyInvoker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ChannelWrappedInvoker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/FutureAdapter.java, dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftInvoker.java
Make Result a type of CompletionStage.
XXXXX
XXXXX
=> Result implements future.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Reference.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/builders/AbstractInterfaceBuilder.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/builders/AbstractServiceBuilder.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/InvokerSideConfigUrlTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
Fixes #3875, support using the following on consumer side:
`<dubbo:parameter key="dubbo.tag" value="groupA"/>`
Related issue https://github.com/apache/incubator-dubbo/issues/3359
XXXXX
XXXXX
=> [Dubbo-3875] dubbo TagRouter does not work with dubbo:parameter.

dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java
defensive check to solve issue #3923
XXXXX
XXXXX
=> [DUBBO-3923] defensive check to solve issue #3923

dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
#3826 
Auth support for redis metadata report. 
Redis registry has auth, but none of redis metadata report. 
org.apache.dubbo.metadata.store.redis.RedisMetadataReport
add `testAuthRedisMetadata` and `testWrongAuthRedisMetadata` to `RedisMetadataReportTest`
UT pass
=> [Dubbo-3826] Auth support for redis metadata report

dubbo-configcenter/dubbo-configcenter-etcd/pom.xml, dubbo-configcenter/dubbo-configcenter-etcd/src/test/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfigurationTest.java, dubbo-dependencies-bom/pom.xml
fix https://github.com/apache/incubator-dubbo/issues/3631
XXXXX
XXXXX
=> etcd3 integration test api

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
Revert "Merge pull request #3520, fix #538 polish the process of deciding the ip to bind."
This reverts commit ade0cd70 (#3520)
Revert this change to address issue #3802
XXXXX
XXXXX
=> [DUBBO-3802]: roll back change made by 3520

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveBalanceTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvokerTest.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java, dubbo-common/src/test/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtilTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/support/AbstractEtcdClient.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProtocol.java
fix https://github.com/apache/incubator-dubbo/issues/3933
XXXXX
XXXXX
=> fix typo in dubbo

dubbo-dependencies-bom/pom.xml, dubbo-registry/dubbo-registry-consul/pom.xml, dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java, dubbo-registry/dubbo-registry-consul/src/test/java/org/apache/dubbo/registry/consul/ConsulRegistryTest.java
complete lookup method of consul registry and add integration test. see https://github.com/apache/incubator-dubbo/issues/3890
XXXXX
Also check this in ConsulRegistryTest.testLookup()
XXXXX
=>  complete lookup method of consul registry and add integration test

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/MockInvoker.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/MockProtocol.java
=> [DUBBO-3713]: org.apache.dubbo.rpc.support.MockInvoker#getInterface should not return null

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
https://github.com/apache/incubator-dubbo/issues/3952
fixed this bug
provider's delay has not set in serviceconfig 
set provider's delay in  serviceconfig 
=> fixed provider set delay NullPointerException

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
a follow up for #3957
XXXXX
XXXXX
=> [DUBBO-3952]: Dubbo 2.7.1 ： delay export function doesn't work, 

dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java
hi, Ian @beiwei30  as we discussed in https://github.com/apache/incubator-dubbo/pull/3906, this is a follow up. we choose to use http ttl check for consul heartbeat, rather than TCP check. And this works perfectly.
XXXXX
XXXXX
=> consul enhancement

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java, dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java
1. filter network interface in NetUtils 
2. remove the useless attribute in ApplicationConfig
=> improve NetUtils

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
#3242: switch from CopyOnWriteArrayList to regular list in order to avoid potential UnsupportedOperationException
XXXXX
XXXXX
=> [DUBBO-3242]: switch from CopyOnWriteArrayList to regular list in order to avoid potential UnsupportedOperationException

dubbo-metadata-report/dubbo-metadata-report-etcd/pom.xml
change  `2.7.2-SNAPSHOT` to `revision` in pom.xml of dubbo-metadata-report-etcd, otherwise there are maven package failures as following:
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.dubbo:dubbo-metadata-report-etcd:2.7.2-SNAPSHOT: Could not find artifact org.apache.dubbo:dubbo-metadata-report:pom:2.7.2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 22, column 13
@ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.dubbo:dubbo-metadata-report-etcd:2.7.2-SNAPSHOT (~/gh-incubator-dubbo/dubbo-metadata-report/dubbo-metadata-report-etcd/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for …
```
=> use revision in pom.xml of dubbo-metadata-report-etcd

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
https://github.com/apache/incubator-dubbo/issues/3638
Fixed bug in this issue
Modified the original error logic
ServiceConfig<DemoServiceImpl> service = new ServiceConfig<>();
ApplicationConfig applicationConfig = new ApplicationConfig("dubbo-demo-api-provider");
service.setVersion("1.0.1");
service.setProtocol(new ProtocolConfig("injvm"));
service.setApplication(applicationConfig);
//service.setScope("local");
service.setInterface(DemoService.class);
service.setRef(new DemoServiceImpl());
service.export();
ReferenceConfig<DemoService> reference = new ReferenceConfig<>();
reference.setVersion("1.0.1");
reference.setProtocol("injvm");
//reference.setScope("local");
reference.setApplication(applicationConfig);
reference.setInterface(DemoService.class);
DemoService serviceImpl = …
=> fixed injvm export and refer

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
=> Sort added router list before set the 'routers' field of the RouterChain

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
=> [DUBBO-3537]: dubbox升级dubbo版本的兼容性问题

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
=> [DUBBO-3994]: Need to enhance DecodeableRpcResult error message

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
the change proposed in #3568 is reasonable, port it into main trunk
XXXXX
XXXXX
=> [DUBBO-3991]: port #3568 into main trunk

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java, dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-common/src/main/java/org/apache/dubbo/common/Version.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/Constants.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClient.java, dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/Constants.java, dubbo-serialization/dubbo-serialization-avro/src/main/java/org/apache/dubbo/common/serialize/avro/AvroSerialization.java, dubbo-serialization/dubbo-serialization-fastjson/src/main/java/org/apache/dubbo/common/serialize/fastjson/FastJsonSerialization.java, dubbo-serialization/dubbo-serialization-fst/src/main/java/org/apache/dubbo/common/serialize/fst/FstSerialization.java, dubbo-serialization/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/GsonSerialization.java, dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2Serialization.java, dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/java/CompactedJavaSerialization.java, dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/java/JavaSerialization.java, dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/nativejava/NativeJavaSerialization.java, dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/KryoSerialization.java, dubbo-serialization/dubbo-serialization-native-hession/src/main/java/org/apache/dubbo/serialize/hessian/Hessian2Serialization.java, dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufSerialization.java, dubbo-serialization/dubbo-serialization-protostuff/src/main/java/org/apache/dubbo/common/serialize/protostuff/ProtostuffSerialization.java, dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/avro/AvroSerializationTest.java
issue #3137: step 1
XXXXX
XXXXX
=> [DUBBO-3137]: Seperate Constants.java into some SubConstants Class - step 1

dubbo-common/src/main/java/org/apache/dubbo/common/constants/ClusterConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/FilterConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/MetadataReportConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/MonitorConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
issue #3137: step 2
XXXXX
XXXXX
=> [DUBBO-3137]: step2 - seperate constants for cluster, common, filter, monitor, and registry

dubbo-common/src/main/java/org/apache/dubbo/common/constants/ConfigConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/RemotingConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/RpcConstants.java
issue #3137: step 2
XXXXX
XXXXX
=> [DUBBO-3137]: step2 - seperate constants for config, remoting, rpc

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java
fix RpcInvocation can't pass attributes
change RpcInvocation and GenericFilter
=> Fix Invocation attributes

dubbo-common/src/main/java/org/apache/dubbo/common/io/StreamUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayInputStream.java, dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/GenericJSONConverter.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/J2oVisitor.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/Yylex.java, dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/LogTelnetHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractCodec.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/LogTelnetHandler.java, dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/io/RandomAccessByteArrayOutputStream.java
Signed-off-by: jimin.jm <slievrly@163.com>
optimize array code style
optimize array code style
CI
=> optimize array code style

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AvailableCluster.java
The anonymous class used in AvailableCluster's constructor has a equal explicit class, we can use the explicit one to replace the anonymous one.
XXXXX
XXXXX
=> use equal explicit class to replace anonymous class

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/model/User.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
fix #4007
XXXXX
org.apache.dubbo.common.utils.PojoUtilsTest#test_has_no_nullary_constructor_pojo()
=> fix telnet not work in some scene (#4007)

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/integration/MetadataReportService.java, dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/support/AbstractMetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/support/Constants.java, dubbo-metadata-report/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
issue #3137 : move MetadataReportConstants back into metata-report-api module
XXXXX
XXXXX
=> [DUBBO-3137]: move MetadataReportConstants back into metata-report-api module

dubbo-common/src/main/java/org/apache/dubbo/common/constants/RemotingConstants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/codec/TelnetCodec.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/connection/ConnectionOrderedChannelHandler.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/PerformanceServerTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartBeatTaskTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/transport/codec/DeprecatedTelnetCodec.java, dubbo-remoting/dubbo-remoting-grizzly/src/main/java/org/apache/dubbo/remoting/transport/grizzly/GrizzlyCodecAdapter.java, dubbo-remoting/dubbo-remoting-http/pom.xml, dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/org/apache/dubbo/remoting/transport/mina/MinaCodecAdapter.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyCodecAdapter.java
issue #3137:
start to review RemotingConstants suitable to move back to its own module.
XXXXX
XXXXX
=> [DUBBO-3137]: step4 - start to review RemotingConstants

dubbo-compatible/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/CompatibleServiceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java
=> [DUBBO-3778]: Annotation mode cannot set service parameters in 2.7.0

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
Fixes https://github.com/apache/incubator-dubbo/issues/3669
RegistryProtocol.export()
XXXXX
=> [Dubbo-3669]do local export before register any listener.

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
Recently, some pressure tests were performed on the rpc inside the music163. I found that YGC did not perform well during the pressure measurement process. One of the reasons is that the lifetime of `TimeoutCheckTask` is relatively long (currently it will survive `timeout`).
I try to shorten its life cycle to get better GC performance. It seems that my modification is successful. Now `TimeoutCheckTask` will be removed when the request returns.
The purpose of this pr is to submit this optimization item to dubbo.
=> Shorten the life cycle of Timeout to get a better gc effect.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
ReferenceConfigCache is able to initialize ReferenceConfig for multiple times. It cannot set initialize to false once subscribe throws exception. 
```
ReferenceConfigCache cache = ReferenceConfigCache.getCache();
DemoService demoService = (DemoService) cache.get(reference);
System.out.println(demoService.sayHello("hi"));
```
Set initialized to true after the init finished. Currently, initialized has not been changed to false, if refprotocol.refer throws exception.
```
if (urls.size() == 1) {
invoker = refprotocol.refer(interfaceClass, urls.get(0));
}
```
1. Start consumer without provider, it should throw exception from cache.get(reference).
2. Start consumer with provider, it shows result from the invocation.
Note:
Found another existing issue, that the urls would cause OOM once retries …
=> ReferenceConfig initialized not changed to false once subscribe throws exception

.gitignore, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AsyncToSyncInvoker.java
when I do stress testing, I found that the latest of version 3.0-dev with low performance for qps and rt, actually very impressive low compare to 2.7.1.
the main problem is about those two classes.
=> performance improve for DefaultFuture and AsyncToSyncInvoker

README.md
https://github.com/apache/incubator-dubbo/issues/4108
XXXXX
XXXXX
=> rm incubating word

dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/support/ServiceInstanceRegistry.java
do not ignore empty value when we construct servicename
XXXXX
XXXXX
XXXXX
=> fix for #4111

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
manually merge #4085 and #4087
XXXXX
XXXXX
=> Performance tuning for TimeoutTask in DefaultFuture

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
fix issue #4107 
when client retry init reference, clear registry urls to avoid OOM.
the registry url contains timestamp value, it can not change urls from list to set. 
do clear urls when in create remote proxy 
do clear urls when create remote proxy
=> [Dubbo-2.7.2] fix registery urls increase forever when recreate reference proxy

dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClient.java
=> fix issue https://github.com/apache/incubator-dubbo/issues/4115

README.md, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
XXXXX
fix for #4111
do not ignore empty value when we construct servicename
XXXXX
=> fix for #4111 do not ignore empty value when we construct servicename

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java
=> add miss-deleted snippet from #2956

pom.xml
Creating [a jenkins job](https://builds.apache.org/job/Apache%20Dubbo/job/apache-dubbo-snapshot-deployment/) for deploying snapshot version to apache maven repo.
In order to make everything works well, we need prevent release deploy for this job, so try to add a enforce plugin rule to check all version is snapshot version.
modify pom.xml and add new enforce plugin
CI pass with
```
./mvnw clean validate -Psnapshot-ci-deploy
```
=> [CI] Add enforce maven plugin to do snapshot version check

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
fix for #4175: ServiceConfigurationListener should override ProviderConfigurationListener
XXXXX
XXXXX
=> fix for #4175: ServiceConfigurationListener should override ProviderConfigurationListener

README.md
reverse url of python
reverse url of python
reverse url of python
XXXXX
=> reverse url of python

dubbo-common/src/test/java/org/apache/dubbo/common/config/EnvironmentConfigurationTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/config/InmemoryConfigurationTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/config/SystemConfigurationTest.java
Signed-off-by: jimin.jm <slievrly@163.com>
[Test] add test for EnvironmentConfiguration、InmemoryConfiguration、SystemConfiguration
[Test] add test for common-config
CI
=> [Test] add test for common-config

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/main/java/org/apache/dubbo/common/URLBuilder.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
completely remove 'default.' prefix check to reduce string allocation.
XXXXX
XXXXX
=> performance tuning: completely remove 'default.' prefix check.

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ConsumerContextFilter.java
cache host_name to avoid repeat address resolve.
XXXXX
XXXXX
=> performance tuning: avoid repeated address resolving.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/model/TagRouterRule.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/TagRouterTest.java
Fix NPE when the TagRouterRule addresses config is null #4218
Fix NPE when the TagRouterRule addresses config is null #4218
XXXXX
=> [Dubbo-4218] Fix NPE when the TagRouterRule addresses config is null (#4218)

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/AbstractTimerTask.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
=> Performance tuning: keep heartbeat updated in io thread to avoid race condition.

dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/java/org/apache/dubbo/demo/provider/DemoServiceImpl.java, dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/MockChannel.java, dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/MockedClient.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/ExchangeChannel.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/Main.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/PerformanceClientFixedTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/PerformanceClientTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannelTest.java, dubbo-remoting/dubbo-remoting-mina/src/test/java/org/apache/remoting/transport/mina/ClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ClientToServerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ChannelWrappedInvoker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java, dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftInvoker.java, dubbo-rpc/dubbo-rpc-thrift/src/test/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodecTest.java
=> Default future from jeff-lv

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
将URL类中的默认值，修改为用三目运算符使用。减少冗余代码！
=> 1. 将URL中的默认值使用三目运算符表示。

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringMap.java
Signed-off-by: slievrly <slievrly@163.com>
[Dubbo-4323] fix use AtomicInteger instead of volatile to inc
fix #4323 
use AtomicInteger instead of volatile to inc
ci
=> [Dubbo-4323]fix use AtomicInteger instead of volatile to inc

dubbo-common/src/main/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtil.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSONArray.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSONObject.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderInvokerWrapper.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyHelper.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/DubboTelnetDecodeTest.java
Signed-off-by: jimin.jm <slievrly@163.com>
remove unnecessary null check  before instance of
remove unnecessary null check  before instance of
ci
=> remove unnecessary null check  before instance of

dubbo-all/pom.xml
fix issue #4355
the value of include node in dubbo-all/pom.xml is different from value in module
<include>org.apache.dubbo:dubbo-serialization-protobuf-json</include>
<dependency>
<groupId>org.apache.dubbo</groupId>
<artifactId>dubbo-serialization-protobuf-json</artifactId>
<scope>compile</scope>
<optional>true</optional>
</dependency>
change one node value in dubbo-all/pom.xml 
change one node value in dubbo-all/pom.xml 
- [x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
=> [Dubbo-4355] Fix dubbo.jar do not contain "serialization-protobuf-json" module issue

dubbo-all/pom.xml
Merge change from release-branch to master branch
=> [Dubbo-4355] Fix dubbo.jar do not contain "serialization-protobuf-json" module issue (#4356)

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
[https://github.com/apache/dubbo/issues/4299](url)
Fix NPE when PojoUtils realize Null element in collection
XXXXX
=> [Dubbo-4299]Fix NPE when PojoUtils realize Null element in collection(#4299)

dubbo-common/src/main/java/org/apache/dubbo/common/constants/QosConstants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
=> fix qos configuration cannot work. #4377

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
=> fix empty protocol for nacos. #4294.

dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilder.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/MethodDefinition.java, dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/TypeDefinition.java, dubbo-metadata-report/dubbo-metadata-definition/src/test/java/org/apache/dubbo/metadata/definition/MetadataTest.java
fix issue #4370
add more information to serviceMetaData.
1. Init parameters field in MethodDefinition when build ServiceDefinition
2. Add typeBuilderName to TypeDefinition to show which builder build this type.
1. user shoule get method parameter like this
```
MethodDefiniton method = serviceDefitnion.getMethods().get(0);
List<TypeDefinition> types = method.getParameters();
but now shold get typeDefinition from serviceDefinition
List<String> typeNames = Arrays.asList(methodDefinition.getParameterTypes());
List<TypeDefinition> types =  serviceDefinition.getTypes().stream().filter(a
- >typeNames.contains(a.getType())).collect(Collectors.toList());
```
2. When typeDefinition be built，we set typeBuilderName field in TypeDefition.class.
Follow this checklist to help us incorporate your …
=> [Dubbo-4370]  Add more data to serviceMetaData

dubbo-common/src/main/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtil.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSONArray.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSONObject.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/pom.xml, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderInvokerWrapper.java, dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyHelper.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/DubboTelnetDecodeTest.java
=> fix empty protocol in consul registry. #4294

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AsyncToSyncInvoker.java
fixes https://github.com/apache/dubbo/issues/4279
XXXXX
XXXXX
=> Observation of performance degradation when running under JDK 8

dubbo-common/src/main/java/org/apache/dubbo/common/beanutil/JavaBeanSerializeUtil.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSONArray.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSONObject.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/remoting/RemotingException.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/remoting/exchange/ResponseCallback.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/remoting/exchange/ResponseFuture.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/FutureAdapter.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/pom.xml, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/ProviderInvokerWrapper.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyHelper.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/FutureAdapter.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/DubboTelnetDecodeTest.java
=> fix zipkin compatible. #3728

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcException.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java
=> duplicate decrease for ExecuteLimitFilter onError

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistryFactory.java
=> fix bug about nacos

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
have searched the issues of this repository and believe that this is not a duplicate.
I have checked the FAQ of this repository and believe that this is not a duplicate.
Environment
Dubbo version: 2.6.6
Operating System version: *nix
Java version: 1.7+
Expected Result
throw new IOException("Unknown result flag, expect '0' '1' '2' '3' '4' '5', get " + flag);
Actual Result
throw new IOException("Unknown result flag, expect '0' '1' '2', get " + flag);
since dubbo add new type for class dubbocodec for issue #1843
we should also change the exception message .
For example, if dubbo provides new protocol version(higher than 2.0.2) .then the high version dubbo invoke the lower version dubbo[2.0.2] with no support codec ,then the lower version dubbo throws ioexception with incorrect message.
So we …
=> Dubbo throws IoException with error message while decoding fail

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AsyncToSyncInvoker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
Fix #4435 
1. Assume that service have sayHello and sayHi method. The sync timeout for sayHello is 1000, but not 800. We have to get method timeout for AsyncToSyncInvoke call. 
```
<dubbo:reference id="demoService" interface="com.ctrip.Demo" timeout="1000">
<dubbo:method name="sayHello">
<dubbo:parameter key="timeout" value="800"/>
</dubbo:method>
</dubbo:reference>
```
2. For the CompletableFuture, it will throw TimeoutException for negative timeout value.
XXXXX
XXXXX
=> support method and positive timeout for sync

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
make code clear and unity as other StringUtils method used in class DubboBeanDefinitionParser
use StringUtils.isNotEmpty(id) instead of id != null && id.length() in DubboBeanDefinitionParser.JAVA at line 97
XXXXX
=> [Dubbo-4437]Use StringUtils.isNotEmpty() method in DubboBeanDefinitionParser

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
Fix MulticastSocket setInterface choose an unreachable address
Try with multicast demo, get an exception as follow
```
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:58390,suspend=y,server=n -javaagent:/Users/hsk/Library/Caches/IntelliJIdea2018.2/captureAgent/debugger-agent.jar=file:/private/var/folders/68/y1kr9bfs183b887sz8tmqm_c0000gn/T/capture.props -Dfile.encoding=UTF-8 -classpath "/Users/hsk/githome/github/dubbo/dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/target/classes:/Users/hsk/githome/github/dubbo/dubbo-demo/dubbo-demo-interface/target/classes:/Users/hsk/githome/github/dubbo/dubbo-registry/dubbo-registry-multicast/target/classes:/Users/hsk/githome/github/dubbo/dubbo-registry/dubbo-registry-api …
```
=> Fix MulticastSocket setInterface choose an unreachable address

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvokerTest.java
I've analysed your codebase and noticed that `org.apache.dubbo.rpc.support.MockInvoker` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.
=> Add unit tests for org.apache.dubbo.rpc.support.MockInvoker

dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/pom.xml, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml
Add nacos dependencies to dubbo-demo
Add nacos dependencies to dubbo-demo
Maven test passed
=> Add nacos dependencies to dubbo-demo

dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/identifier/MetadataIdentifier.java, dubbo-metadata-report/dubbo-metadata-report-api/src/test/java/org/apache/dubbo/metadata/identifier/MetadataIdentifierTest.java
Make sure metadata key contain ":" when version and group is empty.
=> make metadata key contain : when version and group is empty

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
Delete unused code
**First PR**
=> [Dubbo-4479]Delete unused code. defaultPort can not be null. #4479

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboCodec.java
issues:
https://github.com/apache/dubbo/issues/3951
https://github.com/apache/dubbo/issues/3698
related-pr:
https://github.com/apache/dubbo/pull/2656
Since we have no reason make the method first line before decode!
We can see code from   @liangfei0201 below
```java
// decode request.
Request req = new Request(id);
req.setVersion("2.0.0");
req.setTwoWay((flag & FLAG_TWOWAY) != 0);
if ((flag & FLAG_EVENT) != 0) {
req.setEvent(Request.HEARTBEAT_EVENT);
}
try {
Object data;
if (req.isHeartbeat()) {
data = decodeHeartbeatData(channel, deserialize(s, channel.getUrl(), is));
} else if (req.isEvent()) {
data = decodeEventData(channel, deserialize(s, channel.getUrl(), is));
} else {
DecodeableRpcInvocation inv;
if (channel.getUrl().getParameter(
Constants.DECODE_IN_IO_THREAD_KEY, …
```
=> Dubbo throws exception when use java serializer

dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java
=> fix length of array is never negative

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
remove duplicate code in AbstractConfig.java to make brief and clean
remove code ClassUtils.isPrimitive(method1.getReturnType()) in AbstractConfig.java at line 653
ClassUtils.isPrimitive(method1.getReturnType()) is already judge in method MethodUtils.isGetter
=> [dubbo-4491]remove duplicate code in AbstractConfig.java

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
Fix `Future<?> future = com.alibaba.xxx.RpcContext.getFuture(); ` can not get the right Future instance.
=> fix RpcContext compatible problem

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ClusterUtilsTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/consumer/ConsumerConfiguration.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/consumer/test/TestConsumerConfiguration.java
Fixes https://github.com/apache/dubbo/issues/4525
XXXXX
XXXXX
=> [Dubbo-4525] fix Clusterutils.mergeurl, make sure specific keys from provider side not override by that from consumer.

dubbo-compatible/src/test/java/org/apache/dubbo/config/MethodConfigTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
rename convertMethodConfig2AyncInfo method name to convertMethodConfig2AsyncInfo
=> fix convertMethodConfig2AyncInfo spelling error

dubbo-dependencies-bom/pom.xml
fix #4575 
Upgrade to use fastjson 1.2.58
UT pass
=> [Dubbo-4575] Upgrade to use fastjson 1.2.58

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboConfigConfiguration.java
设置属性dubbo.provider.metrics.，里面的值无法放入url参数列表里
添加了`@EnableDubboConfigBinding(prefix = "dubbo.metrics", type = MetricsConfig.class)`
```properties
dubbo.metrics.protocol=dubbo
dubbo.metrics.port=20880
```
=> #4497 设置属性dubbo.provider.metrics.，里面的值无法放入url参数列表里

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
fix #4134 and #4125
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
XXXXX
=> issue#4314: ZookeeperDynamicConfiguration will be busy wait if zk is unavailable

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
Micro refactoring
Modifiers order changed
XXXXX
=> [Dubbo-4570] Fix RegistryProtocol.DestroyableExporter modifiers order

dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java, dubbo-common/src/test/java/org/apache/dubbo/common/io/BytesTest.java
fix https://github.com/apache/dubbo/issues/4402
add guard clause for len=0 in method `base642bytes`
=> [Dubbo] Fix StringIndexOutOfBoundsException when len=0 #4402

dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java
isMetaMethod can be a public method using in all module, there is already a class MethodUtils,
so it may be useful moving isMetaMethod to MethodUtils.class
move AbstractConfig.class method isMetaMethod to MethodUtils.class
- [] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
=> move AbstractConfig.class method isMetaMethod to MethodUtils.class

dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java
我发现在调用被代理的方法时，使用的参数名是该方法自身定义的旧的参数名，然而我们在生成代理类的过程中重载该方法时已经将参数名重新定义为arg为首，index为尾的参数名，例如arg0,arg1...。当使用旧的参数名调用被代理方法时，编译会出现错误，因为我们的局部变量之中已经不存在旧的参数名了，所以在调用被代理方法时应该使用新的参数名。
I found that when calling the proxy method, the parameter name used is the old parameter name defined by the method itself. However, when we overload the method in the process of generating the proxy class, we have redefined the parameter name as arg first and index tail, such as arg0, arg1.... When the proxy method is called with the old parameter name, compilation errors occur because the old parameter name does not exist in our local variables, so we should use the new parameter name when calling the proxy method.
XXXXX
XXXXX
=> fix bug about the generateReturnAndInvocation method of the class AdaptiveClassCodeGenerator

dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java
follow up for pull request #4339
XXXXX
XXXXX
=> follow up for pr#4339, remove the space

dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java, dubbo-common/src/test/java/org/apache/dubbo/common/io/BytesTest.java
Fixes #4514
This change fixes `Bytes.base642bytes(String, int, int, char[])` by adjusting `num` and `rem` variables when required, similar to `Bytes.base642bytes(String, int, int, String)`.
A new test case was added in `BytesTest.java`
=> [Dubbo] Fixed IndexOutOfBoundsException in base642bytes(String, int, int, char[])

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestProtocol.java
Configured PoolingHttpClientConnectionManager in RestProtocol may not work.
```java
PoolingHttpClientConnectionManager connectionManager = new PoolingHttpClientConnectionManager();
// 20 is the default maxTotal of current PoolingClientConnectionManager
connectionManager.setMaxTotal(url.getParameter(CONNECTIONS_KEY, HTTPCLIENTCONNECTIONMANAGER_MAXTOTAL));
connectionManager.setDefaultMaxPerRoute(url.getParameter(CONNECTIONS_KEY, HTTPCLIENTCONNECTIONMANAGER_MAXPERROUTE));
if (connectionMonitor == null) {
connectionMonitor = new ConnectionMonitor();
connectionMonitor.start();
}
connectionMonitor.addConnectionManager(connectionManager);
// ...
CloseableHttpClient httpClient = HttpClientBuilder.create()
.setKeepAliveStrategy((response, context) -> {
HeaderElementIterator it = new …
```
=> unused connectionManager in RestProtocol

dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufObjectInput.java, dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufObjectOutput.java
=> Followup for #4632, use standard protobuf json format to write byte[].

dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/support/AbstractRegistryFactory.java, dubbo-registry/dubbo-registry-api/src/test/java/com/alibaba/dubbo/registry/support/AbstractRegistryFactoryTest.java
修复注册中心域名解析导致的单点问题，参考：#2545
修复由于域名解析成同一个注册中心的不同IP导致创建多个Registry对象的问题。
将如下代码：
https://github.com/apache/incubator-dubbo/blob/e6b0bc8a856abd7f2d7a2e0f06ccc78dc90e2e0a/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java#L88
改为：
https://github.com/apache/incubator-dubbo/blob/7a48fac84b14ac6a21c1bdfc5958705dd8dda84d/dubbo-compatible/src/main/java/com/alibaba/dubbo/common/URL.java#L498-L500
org.apache.dubbo.registry.supportAbstractRegistryFactory
=> 修复注册中心域名解析导致的单点问题，参考：#2545

dubbo-common/src/main/java/org/apache/dubbo/common/utils/IOUtils.java
same as https://github.com/apache/dubbo/pull/3427, fix bug #3420
=> [Dubbo-3420] check EOF of inputstream in IOUtils.write

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java, dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/FutureAdapter.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/SimpleRegistryExporter.java, dubbo-metadata-report/dubbo-metadata-definition-protobuf/src/main/java/org/apache/dubbo/metadata/definition/protobuf/ProtobufTypeBuilder.java, dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/SimpleRegistryExporter.java, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceName.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/StatusTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ChangeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ShutdownTelnetHandler.java, dubbo-rpc/dubbo-rpc-hessian/src/main/java/org/apache/dubbo/rpc/protocol/hessian/HessianProtocol.java, dubbo-rpc/dubbo-rpc-http/src/main/java/org/apache/dubbo/rpc/protocol/http/HttpProtocol.java, dubbo-rpc/dubbo-rpc-jsonrpc/src/main/java/org/apache/dubbo/rpc/protocol/jsonrpc/JsonRpcProtocol.java, dubbo-rpc/dubbo-rpc-xml/src/main/java/org/apache/dubbo/xml/rpc/protocol/xmlrpc/XmlRpcProtocol.java, dubbo-rpc/dubbo-rpc-xml/src/main/java/org/apache/dubbo/xml/rpc/protocol/xmlrpc/XmlRpcProxyFactoryBean.java, dubbo-serialization/dubbo-serialization-protobuf-json/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/MapValue.java
optimize some code styles
1.Object 的 equals 方法容易抛出空指针异常，方法的调用方需使用确定值的对象（或常量）来调用 equals 方法
2.所有的覆写方法，必须加@Override 注解
=> optimize some code styles

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
for Issue: #4682 
This is not an issue, but the update of referenceCount log.
=> update referenceCount log

dubbo-compatible/src/test/java/org/apache/dubbo/filter/LegacyInvoker.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/PerformanceClientFixedTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/BlockMyInvoker.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MyInvoker.java
=> [Dubbo-4685] Improve if-block from if(hasException == false) to if (!hasException)

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/AnnotationUtils.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessorTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/provider/DemoServiceImpl.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/src/main/java/org/apache/dubbo/demo/consumer/comp/DemoServiceComponent.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/src/main/resources/spring/dubbo-consumer.properties, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/src/main/java/org/apache/dubbo/demo/provider/DemoServiceImpl.java
https://github.com/apache/dubbo/issues/4571
The configuration method parameter is not set when the Service annotation is initialized.
XXXXX
=> Fixed Service annotation method parameters are not in effect

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilder.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/AnnotationUtils.java
@Reference auto-wires the instance of generic interface
see #4594
=> @Reference auto-wires the instance of generic interface #4594

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java, dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistryTest.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
=> [Dubbo-4588]block the zookeeper connect process util the connection is established

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
fix #4556 
modify:dubbo/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
=> [Dubbo-4556] fix dubbo startup is slow

dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
`isBlank` is not the same as `isEmpty`
=> fix StringUtils#isBlank

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/FailedNotifiedTask.java
- Fix name of FailedNotifiedTask, The purpose is to repair the log like:
`Final failed to execute task  retry subscribe...` to `Final failed to execute task  retry notify...` while the FailedNotifiedTask run at https://github.com/apache/dubbo/blob/1173b400949ceccc76182f7df9b39d35290d9148/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/AbstractRetryTask.java#L109-L130.
Fix name of FailedNotifiedTask
unnecessary
=> Fix name type for FailedNotifiedTask

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
Make code of process callback of method cleaner in DubboBeanDefinitionParser
DubboBeanDefinitionParser.java
XXXXX
=> Optimize logic of DubboBeanDefinitionParser.java

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ClusterUtilsTest.java
fix use generic invocation via API , lost "version" value
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java
- https://github.com/apache/dubbo/issues/4784
=> Fix use generic invocation via API , lost "version" value [#4784]

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/config/YamlPropertySourceFactory.java
=> Simplify code with Lambda

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
=> replace hardcode with regex pattern

dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/pom.xml, dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/pom.xml
=> [Dubbo-4765] fix demo dependencies

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java
The provider's timestamp may be bigger than local machine's timestamp, if this happens, uptime will be negative, then weight will use the default value configured, it breaks the warm up.
This PR tries to fix this.
=> Fix warm up issue when provider's timestamp is bigger than local machine's timestamp.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalanceTest.java
When execute getWeight method, whether uptime is larger than Integer.MAX_VALUE is unnecessary.
modify:
AbstractLoadBalance.java
add:
AbstractLoadBalanceTest.java
XXXXX
=> Remove useless if check of max value of Integer

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RpcContextFilter.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/RestProtocolTest.java
=> fix #4898: Dubbo-Attachments header in REST protocol doesn't allow '=

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java
in case of methodStatus.active is already equals Integer.MAX_VALUE, methodStatus.active.incrementAndGet() will become Integer.MIN_VALUE
avoid potential value out of bounds
=> considering methodStatus.active == Integer.MAX_VALUE

dubbo-configcenter/dubbo-configcenter-apollo/pom.xml, dubbo-configcenter/dubbo-configcenter-apollo/src/test/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfigurationTest.java, dubbo-configcenter/dubbo-configcenter-apollo/src/test/resources/META-INF/app.properties, dubbo-configcenter/dubbo-configcenter-apollo/src/test/resources/mockdata-dubbo.properties, dubbo-dependencies-bom/pom.xml
Signed-off-by: slievrly <slievrly@163.com>
add Apollo config center mock test
[Test] add Apollo config center mock test
XXXXX
=> add Apollo config center mock test

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceName.java
bugfix: serviceName split return the wrong size of segments  when group or version is empty
bugfix: serviceName split return the wrong size of segments 
XXXXX
=> nacos-registry:serviceName split error

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java
ref to #4828
I just add concurrentHashSet to avoid checking persistent node exist
=> dubbo zookeeper registry too slow

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/Constants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
fix #4771
AbstractServiceConfig.java
XXXXX
=> [Dubbo-4771]fix protocol register set false not work

dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/MethodUtilsTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractReferenceConfigTest.java
also see https://github.com/apache/dubbo/pull/4593
XXXXX
XXXXX
=> Fix #4248, AbstractConfig.java-getMetaData set default depend on getmethod sequence

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ConsumerContextFilter.java
make sure RpcContext.getContext().getRemoteApplication() returns provider's app name on client side. It may useful when a custom filter is implemented. 
a follow up for pull request #4722
XXXXX
XXXXX
=> make remote application effect on consumer side too

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
fix #4793
NacosRegistry.java
fix issue 4793, add toUrlWithEmpty emthod like ZookeeperRegistry.java, when the provider number become 0, generate an url with empty protocol.
has been test
=> [Dubbo-4793]make RegistryDirectory can refresh the invokers when providers number become 0 when using nacos registry

dubbo-dependencies-bom/pom.xml, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
add a new generic type "raw.return" to reduce  unnecessary result convert. effective for hessian serialization only
=> optimize generic invoke

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
The threshold of an HashMap is the product of current capacity and load factor.
Threshold = (Current Capacity) * (Load Factor)
For example, if the HashMap is created with initial capacity of 16 and load factor of 0.75f, then threshold will be,
Threshold = 16 * 0.75 = 12
That means, the capacity of the HashMap is increased from 16 to 32 after the 12th element (key-value pair) is added into the HashMap.
=> avoid resize

dependencies-bom/pom.xml
upgrade fastjson to 1.2.60 for security problem
https://help.aliyun.com/noticelist/articleid/1060052050.html?spm=a2c4g.789213612.n2.8.ddd861419LgwrZ
https://github.com/qixiaobo/fastjson-oom
=> upgrade fastjson to 1.2.60

dubbo-remoting/dubbo-remoting-mina/src/test/java/org/apache/remoting/transport/mina/ClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ClientReconnectTest.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/DemoService.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/DemoServiceImpl.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/MockResult.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ReplierDispatcherTest.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/RpcMessage.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/RpcMessageHandler.java
Because of the  commits linked to the wrong user, I resubmitted a pr and continued #4957  @htynkn
=> Change main method under dubbo-remoting-api to standard test

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java
=> fix some typos

dubbo-rpc/dubbo-rpc-native-thrift/src/main/java/org/apache/dubbo/rpc/protocol/nativethrift/ThriftProtocol.java
fix https://github.com/apache/dubbo/issues/4445
XXXXX
Start a Thrift service in container and invoke from outside.
1.  https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-thrift
2. https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-docker
=> [Dubbo-4445] Fix native-thrift cannot run within docker instance  #4445

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
fix #4341
when set dubbo.registry.simplified true. the dubbo.service.register won't take effect because of the register key was simplified and will use default value true;
boolean register = **registeredProviderUrl**.getParameter("register", true);
change providerUrl here
=> fix register config not take effect because of url simplified

dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilder.java
Fix https://github.com/apache/dubbo/issues/4984
XXXXX
XXXXX
=> [Dubbo-4984]Fix: type definition for String class

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java
1. run provider
2. debug consumer
3. let the provider offline in registry center
4. in consumer, just org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeChannel#close() get called
fix #4694 
consumer return quickly, when the provider interrupts abnormally
- [√] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [√] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull …
=> [Dubbo-4694] Fix consumer can't return quickly, when the provider interrupts abnormally #4694

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
Fixes #4340 
Split `findException` into two sperate functions, with one called before loading and another called after loading.
=> [Dubbo-4340]Throws exception whenever SPI extensions are in abnormal status during loading.

pom.xml
=> [Dubbo-4331] Improve api doc #4331

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessorTest.java
as #5049 mentioned, when `@Service(protocol = "dubbo1")` is annotated on a class, the provider starts failed, `dubbo1` is the `id` property of `ProtocolConfig`.
```java
@Bean
public ProtocolConfig config1() {
ProtocolConfig config = new ProtocolConfig();
config.setId("dubbo1");
config.setName("dubbo");
config.setPort(20880);
return config;
}
```
The failure cause is `dubbo1` is not an name or alias of `ProtocolConfig` bean.
When using xml way:
```xml
<dubbo:application name="demo-provider"/>
<dubbo:registry address="zookeeper://127.0.0.1:2181"/>
<dubbo:protocol name="dubbo" id="dubbo1"/>
<bean id="demoService" class="org.apache.dubbo.demo.provider.DemoServiceImpl"/>
<dubbo:service interface="org.apache.dubbo.demo.DemoService" ref="demoService" protocol="dubbo1"/>
```
xml config with` id` …
=> [Dubbo-5049]support @Bean on Config class to config id as alias

dubbo-metadata-report/dubbo-metadata-report-etcd/src/test/java/org/apache/dubbo/metadata/store/etcd/EtcdMetadataReportTest.java
both `testStoreProvider()` and `testStoreConsumer()` are unstable, and it is more likely failed in travis.
The assumption we made that the operation should be done in 1s in async mode may fail.
Bring back `testStoreProvider()`
Use EtcdMetadataReport in sync mode for UT
ut pass
=> Stabilize EtcdMetadataReportTest

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java
CollectionUtils类toStringMap方法没有检查 pairs 参数是否为空 in #5100.
添加如下代码
if (pairs == null || pairs.length == 0) {
return parameters;
}
resolve #5100
=> 修复 CollectionUtils类toStringMap方法没有检查 pairs 参数是否为空.

dubbo-metadata-report/dubbo-metadata-definition-protobuf/src/main/java/org/apache/dubbo/metadata/definition/protobuf/ProtobufTypeBuilder.java, dubbo-metadata-report/dubbo-metadata-definition-protobuf/src/test/java/org/apache/dubbo/metadata/definition/protobuf/ProtobufTypeBuilderTest.java, dubbo-metadata-report/dubbo-metadata-definition-protobuf/src/test/java/org/apache/dubbo/metadata/definition/protobuf/model/GooglePB.java, dubbo-metadata-report/dubbo-metadata-definition-protobuf/src/test/resources/protobuf/GooglePB.proto
#5082 
PrtobufTypeBuilder parse google Protobuf object contain bytesList or bytesMap will return null and 
log an exception.
example proto file may like this
```
syntax = "proto2";
package org.apache.dubbo.metadata.definition.protobuf.model;
message PBRequestType {
optional bytes msg = 7;
repeated bytes bytesList = 10;
map<string, bytes> bytesMap = 11;
}
```
This type shoule be parse and should not throw Exception.As some compatibility logic could be 
added by who want to use the serviceDefinition.
org.apache.dubbo.metadata.definition.protobuf.ProtobufTypeBuilder
modify some Test
=> [Dubbo-5082] Enhance ProtobufTypeBuilder support generate type definition which contains Bytes List or Bytes Map

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java, dubbo-serialization/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectInput.java
+ gson 协议处理异常的时候会有bug
-  GsonJsonObjectInput->public Object readObject() throws IOException->return gson.fromJson(json, String.class);
-  gson 并不具备fastjson的异常解析能力,可以通过反序列化直接得到Throwable,并且这里序列话的直接是String
-  到处理异常结果的时候DecodeableRpcResult->handleException
*  Object obj = in.readObject();  这里会直接出错,因为反序列化的是个json
*  就算上边不出错,等到if (!(obj instanceof Throwable) 这个判断也会直接抛错
=> Fixes a bug in gson's deserialization feature

README.md
The example service method name is `sayHi` everywhere in the example except in the interface where it is `sayHello`.
The Java sample source is already correct, so the typo seems to only be in the README: https://github.com/apache/dubbo-samples/blob/master/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/api/GreetingsService.java
=> README: Fix typo in example code

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
生效
```
<dubbo:registry
address="zookeeper://username:pwd@ip:port"
group="xxx"/>
```
不生效
```
<dubbo:registry
address="zookeeper://ip:port"
username="username"
password="pwd"/>
```
resolve https://github.com/apache/dubbo/issues/5076
=> dubbo:registry标签 username & password 生效

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java, dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/StateListener.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperTransporter.java, dubbo-remoting/dubbo-remoting-zookeeper/src/test/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperTransporterTest.java
related https://github.com/apache/dubbo/pull/5126
=> fix re-register can not work when curator session expires.

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/service/GenericServiceTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/validation/ValidationTest.java
在GenericServiceTest 发现有此描述
@disabled("Keeps failing on Travis, but can not be reproduced locally."
原因是Application是全局变量，在不同的test里 同时set不同的Application会产生错误。
此类对泛型应用和泛型实现有一定测试回归价值，所以去掉了@disabled，并都使用同一个Application
修复ValidationTest中dubbo的拼写错误
合并到master分支
XXXXX
=> fix GenericServiceTest failing on Travis to master

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
#5225
ReferenceConfig prints too much of logs when init frequently
ReferenceConfig.class
only do config check when reference should be  init().
when it is initialized ,skip check logic to prevent reference form performce  reducing.
=> [Dubbo-5225]fix ReferenceConfig prints too much of logs when init frequently

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
Fix #5237 
fix  NetUtils#isPreferIPV6Address()
XXXXX
=> [DUBBO-5237] fix NetUtils#isPreferIPV6Address() always return false 

dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportFactoryTest.java
It's unstable under multiple network adapters.
Make it stable.
=> [Dubbo-5304]fix unstable ut `AbstractMetadataReportFactoryTest`

dubbo-common/src/main/java/org/apache/dubbo/common/utils/Stack.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/StackTest.java
=> [Dubbo-5215] get & set & remove in org.apache.dubbo.common.utils.Stack take no consideration that index plus mSize is negative

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
The codes are not thread-safe, 
"
ret = makeWrapper(c);
WRAPPER_MAP.put(c, ret);
"
should be replaced by
"            
WRAPPER_MAP.putIfAbsent(c, makeWrapper(c));
ret = WRAPPER_MAP.get(c);
"
as the key may be put into the map twice.
Futuhermore,the codes can also be replaced by lambda expression
=> concurrent cache bug fix

dubbo-registry/dubbo-registry-nacos/src/main/java/com/alibaba/dubbo/registry/nacos/NacosRegistry.java, dubbo-registry/dubbo-registry-nacos/src/main/java/com/alibaba/dubbo/registry/nacos/NacosRegistryFactory.java
nacos客户端默认设置weight=1.0
而dubbo权重默认设置的是100,
dubbo通过``NacosRegistry``注册服务时没有设置,导致权重获取bug
=> fix NacosRegistry weight missing issue

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml, dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java
issue: #5179 
When using Nacos registry & metadatastore & configcenter, we can pass some parameters in the url, such as:
```
nacos://127.0.0.1:8848?namespace=dubbo&clusterName=DEFAULT&namingLoadCacheAtStart=true
```
Some parameters can be recognized, while some others can't like `namingLoadCacheAtStart`.
In my use case, the config item `namingLoadCacheAtStart=true` is very important to let naocs load local cache files to avoid the crash of Nacos cluster. It will ensure the stability of application.
param lack of passing by,  add default value for NAMEING_LOAD_CACHE_AT_START of naocs
- org.apache.dubbo.registry.nacos.util.NacosNamingServiceUtils
- org.apache.dubbo.configcenter.support.nacos.NacosDynamicConfiguration
- org.apache.dubbo.metadata.store.nacos.NacosMetadataReport
=> [Dubbo-5401] FIx the problem: nacos param lack of passing by,  add default value for NAMEING_LOAD_CACHE_AT_START of naocs

dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
precompile regex pattern to avoid compile multiple times
Pass the **org.apache.dubbo.common.utils.StringUtilsTest#testParseParameters**
=> Enhance StringUtils#parseParameters

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
Fixes https://github.com/apache/dubbo/issues/4621
```xml
public String getColonSeparatedKey() {
StringBuilder serviceNameBuilder = new StringBuilder();
serviceNameBuilder.append(this.getServiceInterface());
append(serviceNameBuilder, VERSION_KEY, false);
append(serviceNameBuilder, GROUP_KEY, false);
return serviceNameBuilder.toString();
}
```
=> Fix getColonSeparatedKey does not work in 'URL simplified' mode.

dubbo-registry/dubbo-registry-eureka/src/main/java/org/apache/dubbo/registry/eureka/EurekaServiceDiscovery.java
fix, eureka InstanceInfo.InstanceStatus should be OUT_OF_SERVICE when unregister
change InstanceInfo.InstanceStatus from UP to OUT_OF_SERVICE when unregister
=> fix:eureka InstanceInfo.InstanceStatus should be OUT_OF_SERVICE when unregister

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/ThreadlessExecutor.java, dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AsyncToSyncInvoker.java
Threadless executor is a mechanism introduced in 2.7.5 to optimize the thread model on the consumer side.
related issue https://github.com/apache/dubbo/issues/2013
=> Enhance consumer side thread model: threadless executor

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
When user does not specify any ProtocolConfig or RegistryConfig, the auto-generated Regsitry and Protocol should be added to ConfigManager
=> add auto-generated Regsitry and Protocol to ConfigManager

dubbo-common/src/main/java/org/apache/dubbo/common/BaseServiceMetadata.java, dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceMetadata.java
Rename ServiceDescriptor to BaseServiceMetadata to avoid name confusion.
=> Rename ServiceDescriptor to BaseServiceMetadata

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/SelectTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.remoting.telnet.TelnetHandler, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/support/DemoService.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/support/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/support/Man.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/InvokerTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/telnet/SelectTelnetHandlerTest.java
Environment
Dubbo version: 2.6.6
Operating System version: *nix
Java version: 1.7
When we use complex arguments, in telnet mode , we need use jsonArray to parse.
But in our code ,someone try to resolve an overwrite problem ,so make an issue #257
then @beiwei30 try to fix this issue use this code below 27917f2
The code will make the default method not take effect.
The code before like this
```java
private static Method findMethod(Exporter<?> exporter, String method, List<Object> args) {
Invoker<?> invoker = exporter.getInvoker();
Method[] methods = invoker.getInterface().getMethods();
Method invokeMethod = null;
for (Method m : methods) {
if (m.getName().equals(method) && m.getParameterTypes().length == args.size()) {
if (invokeMethod != null) { // 重载
if …
```
=> Dubbo 2.6.x cannot found correct method with telnet command

dubbo-rpc/dubbo-rpc-rmi/src/main/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocol.java
fixes #5563 
1.dubbo-rpc/dubbo-rpc-rmi/src/main/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocol.java
=> [Dubbo-5563] fix useless null check in RmiProtocol

dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/Constants.java, dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/optimized/KryoSerialization2.java, dubbo-serialization/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufSerialization.java
fix bug
2020-01-07 16:03:12.180 ERROR 14400 --- [erverWorker-3-2] o.a.d.remoting.transport.CodecSupport    :  [DUBBO] Serialization extension org.apache.dubbo.common.serialize.kryo.optimized.KryoSerialization2 has duplicate id to Serialization extension org.apache.dubbo.common.serialize.kryo.KryoSerialization, ignore this Serialization extension, dubbo version: 2.7.5, current host: 127.0.0.1
2020-01-07 16:03:12.181 ERROR 14400 --- [erverWorker-3-2] o.a.d.remoting.transport.CodecSupport    :  [DUBBO] Serialization extension org.apache.dubbo.common.serialize.protobuf.support.GenericProtobufJsonSerialization has duplicate id to Serialization extension org.apache.dubbo.common.serialize.protobuf.support.GenericProtobufSerialization, ignore this Serialization extension, dubbo version: 2.7.5, …
=> fix reuse ID

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Filter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/ListenableFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/CompatibleFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExceptionFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolFilterWrapper.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ActiveLimitFilterTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java
fix #5619 
This pr is to fix the bug that is not compatible with the previous listenable filter in version 2.7.5, but if this pr is used, it will not be compatible with the filter created by the  listener declared in 2.7.5. I think this should be regarded as an urgent bug-fix.
@chickenlj What do you think?  Is there any other way to solve this problem perfectly?
=> backward compatible with ListenableFilter

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java
For PR: #5531 
Connection is able to share for lazy connection.
TCP    0.0.0.0:20880          0.0.0.0:0              LISTENING       16660
TCP    10.xx.xx.151:20880     10.xx.xx.151:53785     ESTABLISHED     16660
TCP    10.xx.xx:53785     10.xx.xx.151:20880     ESTABLISHED     19704
TCP    [::]:20880             [::]:0                 LISTENING       16660
=> [Dubbo-5531] fix lazy connection not share in some circumstance.

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java
switch from IdentityHashMap to HashMap
XXXXX
XXXXX
=> should not use IdentityHashMap, otherwise cannot use method object to get

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/filter/ValidationFilter.java
=> issue5432: avoid of serialization exception for javax.validation.ConstraintViolationException

dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java
enhance consul registry to support matching url between consumer and provider
XXXXX
XXXXX
=> enhance consul registry to support matching url between consumer and provider

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyEventLoopFactory.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
alternative impl for PR #4493
XXXXX
XXXXX
=> support epoll on linux, alternative impl of PR#4493

dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
我们知道可以给Provider的业务处理线程池设置类型和size（见ThreadPool扩展点），在org.apache.dubbo.common.constants.CommonConstants中我们定义了THREADPOOL_KEY、THREAD_NAME_KEY、THREADS_KEY等，但唯独THREAD_NAME_KEY的值threadname在dubbo.xsd中没有设定，我想应该是漏了，导致我们无法给线程池设置想要的名字。所以此PR是为了解决这个问题。
We know that you can set the type and size of the Provider's business processing thread pool (see the ThreadPool extension point). In org.apache.dubbo.common.constants.CommonConstants we define THREADPOOL_KEY, THREAD_NAME_KEY, THREADS_KEY, etc., but only the value of THREAD_NAME_KEY The threadname is not set in dubbo.xsd, I think it should be missed, which prevents us from setting the desired name for the thread pool. So this PR is to solve this problem.
=> Make THREAD_NAME_KEY work

dubbo-all/pom.xml, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
我发现一个可能一直存在的问题，就是我们的token机制没有被正确使用，我之前使用的dubbo-2.5.3版本就有这个问题，最近我在使用dubbo-2.7.5版本时发现这个问题仍然存在。
I found a problem that may have existed all the time, that is, our token mechanism has not been used correctly. This problem existed in dubbo-2.5.3, which I used before. Recently, when I used dubbo-2.7.5, I found that this problem still exists.
现象：
当token设置成true时，provider没有将token的UUID正确注入到注册中心的bug，例如：
Phenomenon:
When the token is set to true, the provider does not correctly inject the UUID of the token into the bug in the registry, for example:
`<dubbo:provider token="true" filter="SystemParamProviderFilter,DLProviderFilter,MetricsProviderFilter"/>`
我在provider端暴露了一个dubbo协议的接口：com.manzhizhen.dubbo.api.Dubbo1Service，结果我在注册中心上（zookeeper）看到的结果如下：
I exposed an interface of Dubbo protocol on the …
=> Fixed a bug where the provider did not correctly inject the token

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java
In concurrent cases, more then one `WeightedRoundRobin` instance may be constructed, so should get the latest `WeightedRoundRobin` from the map
get weightedRoundRobin from map after putIfAbsent
run the test case:`org.apache.dubbo.rpc.cluster.loadbalance.RoundRobinLoadBalanceTest`
=> fix: get weightedRoundRobin from map after putIfAbsent

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml
Fix bug with metadata-type not work since 2.7.5 describe in issue #5667
Also see https://github.com/apache/dubbo/pull/5695
=> fix specifying metadata type cannot work

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
Fixed NPE  caused by metadataServiceExporter not being initialized when executing `ShutdownHookCallbacks`
=> check the metadataServiceExporter when exec ShutdownHookCallbacks

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java, dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java
refactor generic invoke support
* A better way to collect interfaces in `AbstractProxyFactory#getProxy`
* fix https://github.com/apache/dubbo/issues/5479
=> [Dubbo-5479] refactor generic invoke support

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
I found a refactoring opportunity on Dubbo project.
I believe the checkStubAndLocal method can be improved. This method calls ReflectUtils.forName() method 4 times and ConfigUtils class 4 times.
I am proposing a reduction in the amount of calls.
Regards
=> [Dubbo] Refactoring to remove feature envy

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
Fix typo `CHARECTER` -> `CHARACTER`.
I have searched in opened PR.
Fell free to close it if it has be included in other PRs or It is not expected to change.
Only rename `SPLIT_IPV4_CHARECTER `&`SPLIT_IPV6_CHARECTER `
to `SPLIT_IPV4_CHARACTER `&`SPLIT_IPV6_CHARACTER `.
These two private variables do not affect the other methods or classes except `getRandomPort `.
The current test case 'NetUtilsTest' is enough.
=> [Dubbo-fix]  fix typo `CHARECTER` -> `CHARACTER`

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java, dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java
Once we are going to extend the serialization, write direct to Hessian InputStream/OutputStream is high efficient on the memroy. 
Currently, the InputStream/OutputStream is not exported. The change is going to export the InputStream/OutputStream from Hessian2ObjectInput and Hessian2ObjectOutput.
```
private final Hessian2ObjectOutput delegate;
protected ProtobufObjectOutput(OutputStream os) {
this.delegate = new Hessian2ObjectOutput(os);
}
void writeBytesForPBObject(Object obj, Class clazz) throws IOException {
try (OutputStream os = delegate.getOutputStream()) {
if (obj instanceof MessageLite) {
try {
((MessageLite) obj).writeTo(os);
} catch (IOException e) {
throw new RuntimeException("Google PB序列化失败，序列化对象的类型为" + obj.getClass().getName(), e);
}
}
}
}
```
Follow this checklist to help us …
=> export hessian InputStream&OutputStream for pb stream

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java, dubbo-monitor/dubbo-monitor-api/src/test/java/org/apache/dubbo/monitor/support/MonitorFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Filter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/ListenableFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/CompatibleFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExceptionFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolFilterWrapper.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ActiveLimitFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/CompatibleFilterFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ExceptionFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/GenericFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/GenericImplFilterTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java
related: https://github.com/apache/dubbo/pull/5639 #5623
=> Filter refactor, keep all callback methods inside Filter.Listener

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
=> fix metadata config does not take effect

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
In some cases, such as dubbo admin, reading and writing cache files caused by frequent service changes can cause excessive CPU load. This pr add a switch to turn off cache URLs locally.
=> add a switch to turn off cache URLs locally

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
fixes #5797 
set EXTENSION_LOADERS/EXTENSION_INSTANCE default size to 64.
XXXXX
=> [Dubbo-5797]set EXTENSION_LOADERS/EXTENSION_INSTANCE default size to 64.

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AsyncToSyncInvoker.java
In `AsyncToSyncInvoker`, when `ExecutionException` happens, only `TimeoutException` and `RemotingException` are handled and wrapped as `RpcException` and re-throw. The problem here is other exception will be swallowed silently.
wrap other exception in `RpcException` and rethrow.
XXXXX
=> throw unknown exception

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
My program as a `consumer` gets the Invoker by dynamically calling the `ReferenceConfig.get` method. If the `provider` restarts frequently in a short period of time, my program memory will continue to grow.
The problem occurs when the `ReferenceConfig.createProxy` method is abnormal and the `invoker.destroy` method is not executed to destroy resources and cause a memory leak.
=> Invoker deactivation should be destroyed in ReferenceConfig

dubbo-configcenter/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-consul/src/test/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfigurationTest.java
=> Fix consul, getproperty return null if key does not match a value.

dubbo-remoting/dubbo-remoting-grizzly/src/main/java/org/apache/dubbo/remoting/transport/grizzly/GrizzlyTransporter.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyTransporter.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyTransporter.java
change variable name for `NettyTransporter`
actually, these are `handler` not `listener`
=> Fix variable name  in NettyTransporter

dubbo-common/src/main/java/com/alibaba/dubbo/common/Constants.java, dubbo-common/src/main/java/com/alibaba/dubbo/common/store/support/SimpleDataStore.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/AbstractClient.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/WrappedChannelHandler.java, dubbo-remoting/dubbo-remoting-api/src/test/java/com/alibaba/dubbo/remoting/handler/WrappedChannelHandlerTest.java
If you want to share one single thread pool for all services and requests, configure like this:
```xml
<dubbo:consumer threadpool="fixed" threads="700">
<dubbo:parameter key="share-threadpool" value="true"/>
</dubbo:consumer>
```
There's no strict rules for which strategy is the best, every strategy has its pros and cons, just pick the one that is suitable for your case. Sharing the same fixed-size thread pool can be very helpful for Consumers working as a proxy.
=> add new thread pool strategy for Consumer, allow all service calls to share the same thread pool.

dubbo-dependencies-bom/pom.xml
https://github.com/alibaba/fastjson/releases/tag/1.2.68
在1.2.68中引入一个safeMode的配置，配置safeMode后，无论白名单和黑名单，都不支持autoType。
=> upgrade fastjson to 1.2.68

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/event/ThreadPoolExhaustedEvent.java, dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/event/ThreadPoolExhaustedEventListenerTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/event/ThreadPoolExhaustedEventTest.java
publish ThreadPoolExhaustedEvent when thread pool is exhausted
fix https://github.com/apache/dubbo/issues/5957
add ThreadPoolExhaustedEvent and publish it in AbortPolicyWithReport.rejectedExecution method
run ThreadPoolExhaustedEventTest、ThreadPoolExhaustedEventListenerTest
=> [feature] publish ThreadPoolExhaustedEvent when thread pool exhausted

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java
去掉代码里多余的一次判断
第一次进入for循环的时候会进入 if (leastActive == -1 || active < leastActive) 里面 因为leastActive 初始值为-1 , 进入else if (active == leastActive)逻辑时上面for循环的i肯定是大于0的,因此无需判断i>0了.
原有的单元逻辑都能通过.
=> Fix a redundant judgment code

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java
To make sure the number of selected invoker is as specified in the parameter of "forks".
In the previous version, there was no guarantee that enough invokers were selected because of the “if” statement. It can only ensure that the loop is executed “forks” times.
XXXXX
=> correct the number of selected invoker

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
fix #5855 
delete `finalizerGuardian`
=> [Dubbo-5855] ReferenceConfig(null) is not DESTROYED when FINALIZE

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/proxy/AbstractProxyFactory.java
修正 2.6.x 版本中， AbstractProxyFactory 类的 getProxy(Invoker<T> invoker, boolean generic) 函数的一个小问题
按照既定的逻辑，interfaces 数组的前两个位置应该放的是接口类和 EchoService 类，也就是说 type 应该从第三个位置即 interfaces[2] 开始放，但是此处是从 interfaces[1] 开始放的。如果 types 不为 null，EchoService.class 将会被意外覆盖。
XXXXX
=> EchoService.class will lose if the 'types' not null

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
Set  target type property of reference bean definition can avoid reference bean early initialization 
when define reference bean in xml.
The reason is spring will  try to create factory bean instance to look what factory bean create if spring can't get target type from bean definition.
set target type property for  reference bean definition when parse dubbo bean definition.
=> set target type property for reference bean definition

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
- Polish ClassUtils.
- I try add a log to https://github.com/apache/dubbo/blob/317e62f73fd0a9bac4b34eb8b2c31bbae591ef91/dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java#L382-L387
like this:
```java
public static Set<Class<?>> getAllInterfaces(Class<?> type, Predicate<Class<?>>... interfaceFilters) {
System.out.println("getAllInterfaces of " + (type == null ? "null" : type.getName()));
if (type == null || type.isPrimitive()) {
return emptySet();
}
...
}
```
Run  test case https://github.com/apache/dubbo/blob/master/dubbo-common/src/test/java/org/apache/dubbo/convert/multiple/StringToBlockingDequeConverterTest.java
Output:
```
getAllInterfaces of org.apache.dubbo.common.convert.multiple.StringToBlockingDequeConverter
getAllInterfaces of …
```
=> [Dubbo-Optimization]: polish ClassUtils

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
com.alibaba.dubbo.rpc.RpcContext getAttachment(String, String) cannot work properly for some other middlewares integrating with Dubbo.
=> fix alibaba RpcContext setAttachment(String,String)

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandlerTest.java, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/demo-provider.properties, dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/demo-provider-properties.xml
It does not work in Dubbo 2.7.6 
```java
@Configuration
@PropertySource("classpath:/META-INF/demo-provider.properties")
@ImportResource(locations = "classpath:/org/apache/dubbo/config/spring/demo-provider.xml")
static class XmlConfiguration {
}
```
=> [Enhancement] Resolving the placeholders of XML BeanDefinition in the Configuration Class

dubbo-common/src/test/java/org/apache/dubbo/common/config/configcenter/AbstractDynamicConfigurationTest.java
fixes [#6093 ]
configuration.publishConfig默认方法不再抛出异常，默认返回false，所以单元测试需要同步修改
本地已完成测试
=> 1、configuration.publishConfig returns false，without throw exception

dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/FailbackRegistry.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/Directory.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
Replace lambda expressions with method references to improve code simplicity.
=> Lambda replaced with method reference

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalance.java, dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.LoadBalance, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalanceTest.java
Add new loadbalance strategy based on response time.
LeastActiveRoadBalance will not work properly when the performance of servers are quite different. The worst provider may have reached limit, then the best one may still free.
This strategy is much similar to the LeastActiveRoadBalance, but chooses response time of success calls instead of active connection. 
We calculate the estimated response time from the product of active connection and succeeded average elapsed time, which means the time this call need to wait, and then choose the least one. If there are multiple invokers and the weights are not the same, then random according to the total weight. If there are multiple invokers and the same weight, then randomly called.
ShotestResponseLoadBalanceTest shows that shortest estimated …
=> add new loadbalance strategy

dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java, dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Method.java
1、support for merger when use @Method or @DubboReference
2、Delete unnecessary 'return' comments, Cause the check to failed
fixes [#6090 ]
修改@method、@DubboReference，增加merger；
因为ReferenceConfig、MethodConfig都是继承自AbstractConfig，AbstractConfig中包含merger属性，所以注解中增加merger后，创建config时会进行填充
我已经完成测试
=> support for merger when use @Method or @DubboReference

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java, dubbo-common/src/test/java/org/apache/dubbo/common/version/VersionTest.java
Fix: version numbers published by developers that have higher numbers than the official versions are considered as new protocol compatible, which is not always true.
=> fix protocol version compatibility

dubbo-all/pom.xml, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParserTest.java, dubbo-cluster/src/test/resources/urlJsonArray.json
Support URL Configurators with JsonArray in Dynamic Configuration
such as
``` json
[
"override://0.0.0.0/com.xx.Service?category=configurators&timeout=6666&disabled=true&dynamic=false&enabled=true&group=dubbo&priority=1&version=1.0"
]
```
=> [Dubbo-DynamicConfig] compatible configurators url with type JsonArray in ConfigCenter

dubbo-dependencies-bom/pom.xml
https://help.aliyun.com/noticelist/articleid/1060343604.html?spm=a2c4g.789004748.n2.6.3f576141SGmGhG
fastjson采用黑白名单的方法来防御反序列化漏洞，导致当黑客不断发掘新的反序列化Gadgets类时，在autoType关闭的情况下仍然可能可以绕过黑白名单防御机制，造成远程命令执行漏洞。经研究，该漏洞利用门槛较低，可绕过autoType限制，风险影响较大。阿里云应急响应中心提醒fastjson用户尽快采取安全措施阻止漏洞攻击。
fastjson <=1.2.68
fastjson sec版本 <= sec9
fastjson >=1.2.69
fastjson sec版本 >= sec10
=> upgrade fastjson to 1.2.70

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java
Make Nacos protocol support service discovery
fix #6226 
Using `NamingUtils` to decode `serviceName` get from Nacos which is actually `serviceNameWithGroup` in `Instance`.
=> [Dubbo-6226] fix nacos service name associated with group name

dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java
i have check object `a1` and `a2` carefully, their predecessor `o1`,`o2` had `NPE` check, and in this method context , no more where have changed them, so , object `a1` and `a2` always not be null.
dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java
=> maybe we can remove null judge in this case

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java
1. Consumer process starts first with check='false' set
<dubbo:reference check="false" />
=> fix NPE when check=false is set and provider is empty.

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilder.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/builder/CollectionTypeBuilder.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/builder/TypeBuilder.java, dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/definition/Test3TypeBuilder.java, dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/definition/TestTypeBuilder.java, dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilderTest.java, dubbo-metadata/dubbo-metadata-api/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.definition.builder.TypeBuilder
=> fix #6306.  support TypeBuilder sort

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
Find small typo in [CommonConstants.java](https://github.com/apache/dubbo/blob/6478ac9781bfc4cadfe070df5206d4b4a2a9b75d/dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java#L115-L123)
https://github.com/apache/dubbo/blob/7447f3372d960ce9d73331ad6c16d34448853b51/dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java#L115
https://github.com/apache/dubbo/blob/7447f3372d960ce9d73331ad6c16d34448853b51/dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java#L123
1. Fix typo from `TIMEOUT_ATTACHENT_KEY` to `TIMEOUT_ATTACHMENT_KEY`
2. Fix typo from `PROPERTIES_CHAR_SEPERATOR` to `PROPERTIES_CHAR_SEPARATOR`
XXXXX
=> fix typo in CommonConstants

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/InMemoryWritableMetadataService.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/RemoteWritableMetadataService.java
Fix export provider error, change to catch throwable, handle NoClassDefFoundError
In org.apache.dubbo.metadata.store.InMemoryWritableMetadataService.publishServiceDefinition() and org.apache.dubbo.metadata.store.RemoteWritableMetadataService.publishProvider(), call the org.apache.dubbo.metadata.definition.ServiceDefinitionBuilder.build(java.lang.Class<?>) method, where NoClassDefFoundError may occur, So you need to catch the throwable in the outer layer, otherwise it will be difficult to find  the root cause of class loading failure
Please review this pull request, thank you
=> Fix export provider error, change to catch throwable, handle NoClassDefFoundError

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/InMemoryWritableMetadataService.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
加固 关于CVE-2020-1948 的问题修复。
通过简单的修改CVE-2020-1948的POC示例，我在dubbo-2.7.7中再次复现了该问题。
1. 使用 https://github.com/apache/dubbo-spring-boot-project 最新的2.7.7的TAG分支。
2. 其他poc内容参照：https://blog.csdn.net/caiqiiqi/article/details/106934770，但修改其中POC的部分代码：
```
resp = client.send_request_and_return_response(
service_name='org.apache.dubbo.spring.boot.demo.consumer.DemoService',
method_name='rce',
args=[toStringBean])
```
修改为
```
resp = client.send_request_and_return_response(
service_name='org.apache.dubbo.spring.boot.sample.consumer.DemoService',
method_name='$invoke',
service_version='1.0.0',
args=[toStringBean])
```
注入的恶意代码ExploitMac.java依然会被执行。
1. DecodeableRpcInvocation解码时，对$invoke、$invokeAsync、$echo等特殊方法进行参数描述的校验，防止外部输入不合法的参数类型。
=> DecodeableRpcInvocation增加入参类型校验

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Configurator.java
* It seems will clear configurators when override's size is null or empty, like:
Fisrt loop: override's size is not null, add a element to `configurators`.
Second loop :override's size is null ,will clear `configurators`.
Third loop :override's size is null , add a element to `configurators`.
XXXXX
XXXXX
=> Delete useless logic

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ArgumentCallbackTest.java
Serivce with callback throw exception : `Not found exported service` when serviceUrl has bind.port paramater.
When a Callback service is exported. it use the `port` of `bind.port` paramater in Url . but when callback is received it never use `bind.port`.
#1289 related .  Serivce with callback throw "Not found exported service" when serviceUrl has bind.port paramater. 
=> [Dubbo-2.7.7] Fix callback throw "Not found exported service" when serviceUrl has bind.port paramater.

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java
Currently, some tests like the one in JavassistProxyFactoryTest fails if the RpcContext set by RpcContextTest.testAsync is not removed. Specifically, tests like JavassistProxyFactoryTest.testGetInvoker will see the following failure without the proposed fix (when JavassistProxyFactoryTest.testGetInvoker is run after RpcContextTest.testAsync).
```
JavassistProxyFactoryTest>AbstractProxyTest.testGetInvoker:68 expected: <java.lang.Object@294425a7> but was: <aa>
```
The proposed change is to have RpcContextTest.testAsync remove the RpcContext like RpcContextTest.testGetContext when it is done.
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java
=> Removing RpcContext after test finishes.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java
Related issue: https://github.com/apache/dubbo/issues/6082
Save memory usage in `TagRoute#route()` method.  
In default call, none invokers will be filtered by `TagRouter`, but `TagRouter` will create a new `List<Invoker<T>>` when every RPC comes. We can use a pre-loop to check whether there have any changes in origin list. If not, we can return origin list directly, otherwise a new `List<Invoker<T>>` will be created.  
In default circumstance, the time complexity is same with original code, but the space complexity is more less than original's.  
=> Save memory usage in TagRouter

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/FailoverClusterInvoker.java
=> [Dubbo-2.6.x]fix #6369, Consumer can't set correct retries via generic invocation

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubbo.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboConfig.java
The comment is wrong, which is easy to cause misunderstanding。
org.apache.dubbo.config.spring.context.annotation.EnableDubboConfig#multiple
org.apache.dubbo.config.spring.context.annotation.EnableDubbo#multipleConfig
The default value is true but the comment is false
=> Incorrect comments about multipleConfig

dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java
fix the problem: Rest Protocol can't work when use Tomcat 8.0.x as Web Container which is described by issue #6399
TomcatHttpServer.java
When we start Tomcat server by program for embedded Tomcat with version **8.0.x**，
We **can't** set the connector by following steps:
1. create a connector using the code: _**new Connector("org.apache.coyote.http11.Http11NioProtocol")**_;
2. set appropriate property for the created connector , eg: **_connector.setPort(url.getPort()), connector.setProperty("","")_**;
3. set the ready connector to tomcat , eg: **_tomcat.setConnector(connector)_**;
We **should** set the connector as follow:
1. got a connector by tomcat's method，pseudocode is :  **_Connector connector = tomcat.getConnector()_**;
2. set appropriate property for the connector returned by …
=> [Dubbo-2.7.7] Fix problem: Rest Protocol can't work when use Tomcat 8.0.x as Web Container

dubbo-dependencies-bom/pom.xml, dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
there are still two subject project is using 2.7.8 which will fail CI deployment.
a issue is raised https://github.com/apache/dubbo/issues/6530 for future investigate.
=> update all version to 2.7.9-SNAPSHOT

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistryFactory.java
fix #6568 
Remove parameters in registry url cache key except namespace when cache NacosRegistry
XXXXX
=> [Dubbo-6568], remove unnecessary parameter in registry cache key when cache NacosRegistry

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/AbstractDynamicConfiguration.java, dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/TreePathDynamicConfiguration.java
fix NPE when AbstractDynamicConfiguration#execute return null because of Exception while required return type is boolean
fix npe
=> [Dubbo-6575] Fix #6575,avoid NPE when calling AbstractDynamicConfiguration#execute

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/FutureAdapter.java
=> Backward compatibility: com.alibaba.dubbo.rpc.protocol.dubbo.FutureAdapter missing constructor.

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
enhance url's equals() method by ignoring 'timestamp' key, to fix #4587 
=> fix issue#4587: enhance url equals

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java
Prevent RpcStatus#begincount int overflow in extreme cases
防止极端情况下RpcStatus#beginCount int 溢出
XXXXX
XXXXX
=> Prevent RpcStatus#begincount int overflow in extreme cases

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TokenFilter.java
…rovider token check, the token value called by consumer will be printed out in the exception information
In order to facilitate the consumer to better locate the failure of provider token check, the token value called by consumer will be printed out in the exception information
为了方便consumer更好的定位provider token 检查失败的问题，在异常信息中将consumer调用的token值打印出来
XXXXX
XXXXX
=> token filter add consumer token info

README.md
Fixed typo, grammatical, punctuations, and semantic coherence to improve readability and content quality.
To improve the readability, content quality of the README.md file.
Fixed typo, grammatical, punctuations, and semantic coherence.
Doesn't impact the main codebase, and is entirely limited to the README.md file.
=> [Dubbo] Proofread README.md file with multiple fixes

dubbo-common/src/main/java/org/apache/dubbo/common/timer/HashedWheelTimer.java
发现所有分支皆有此问题，则提交到主分支
#6820 
#6808 
bug 所在文件 https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/timer/HashedWheelTimer.java
出现问题的方法:
private boolean isWindows() { return System.getProperty("os.name", "").toLowerCase(Locale.US).contains("win"); }
问题产生原因：
1.waitForNextTick() 中无限调用 isWindows();
2.toLowerCase(Locale.US) 将急速产生 char[] 对象。导致内存占用过高。
解决方案：
` private static boolean isWindows = System.getProperty("os.name", "").toLowerCase(Locale.US).contains("win");
private boolean isWindows() {
return isWindows;
}`
close #6820
=> improve isWindows method in HashedWheelTimer

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/model/SerializablePerson.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
Getting the default value of boolean is incorrect, resulting in an error in the PojoUtils#newInstance method, if the construction method of the instantiated object requires the boolean type
let 'bool' to 'boolean'
I modified the PojoUtilsTest#test_Map_List_pojo test case to add the construction method of SerializablePerson to the boolean type
issue: https://github.com/apache/dubbo/issues/6854
=> fix boolean data type issue for Pojoutils.java#getDefaultValue

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/event/listener/PublishingServiceDefinitionListenerTest.java
- Add `ApplicationModel` reset before test case.
The reason is new version of environment will cause order difference of test cases, and some test cases will pollute the static environment like `ApplicationModel` and `Spring`.
=> [Unit Test] Fix error in PublishingServiceDefinitionListenerTest

README.md
URLs in readmes pointing to samples are broken.
Simple fix to 4 urls.
Open old/new in browser
=> Fix samples urls in README

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
fix #4597
dubbo.protocol.host 的格式检查中,增加: 如果以"["开头并以"]"结尾,则检查是否是IPv6地址,其他的按原方式检查
dubbo.protocol.host="[IPv6]"
=> fix host parse issue with ipv6 format

README.md
to fix broken link in readme
2 sample urls and 3 guide link
=> fixed broken link in readme

README.md
fixed broken links in <README.md>  from issue: #7031 
include:   
1. build status svg, change domain from .org to .com
2. `Architecture` img link
3. link of `Your first Dubbo application`
=> fixed broken links in <README.md>

dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java
fix the constant name in LFUCache
ensure the legibility of code
XXXXX
=> fix the constant name in LFUCache

.github/workflows/build-and-test.yml, .github/workflows/unit-test.yml, dubbo-common/src/test/java/org/apache/dubbo/common/config/configcenter/file/FileSystemDynamicConfigurationTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/config/MultipleServicesWithMethodConfigsTest.java
- Use matrix build workflow
- remove 3rd party step dependency due to apache limit
- add integration test base on dubbo-samples
=> [Unit Test] Use matrix build workflow & Add Integration Test

.github/workflows/build-and-test.yml
=> Add Dubbo-Spring-Boot build for github actions

.github/workflows/build-and-test.yml
Fix dubbo cache being overwritten problem
Merge dubbo cache and dubbo-spring-boot-project cache
XXXXX
=> improve dubbo cache and job depends

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
提供者和消费者之间的心跳，Request和Response的Data都为null：
```
//org.apache.dubbo.remoting.exchange.support.header.HeartbeatTimerTask#doTask
Request req = new Request();
req.setVersion(Version.getProtocolVersion());
req.setTwoWay(true);
req.setEvent(HEARTBEAT_EVENT);//HEARTBEAT_EVENT = null
```
```
//org.apache.dubbo.remoting.exchange.support.header.HeartbeatHandler#received
Response res = new Response(req.getId(), req.getVersion());
res.setEvent(HEARTBEAT_EVENT);//HEARTBEAT_EVENT = null
```
当提供者和消费者数量非常大时，每个节点都需要发送/接受大量的心跳Requet和Response，这些Requet、Response也会和服务调用一样经过serialize+encode、decode+deserialize，而其中的serialize/deserialize需要消耗过多的CPU资源。
这个优化的目的是对于心跳Requet/Response跳过serialize/deserialize处理，serialize改为赋值为null对象的序列化后字节，deserialize改为直接赋值null。
在CodecSupport中增加getNullBytesOf(Serialization …
=> Heartbeat skip serialize and deserialize

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/InterfaceCompatibleRegistryProtocol.java
Fix error in issue: #7132
Handle scenario where serviceDiscoveryInvoker is null
Run tests under `dubbo-samples/dubbo-samples-metadata-report/dubbo-samples-metadata-report-local-xml`
=> [Dubbo-7132] Handle scenario where serviceDiscoveryInvoker is null #7132

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrapStartStopListener.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapApplicationListener.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapStartStopListenerSpringAdapter.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/event/DubboBootstrapStatedEvent.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/event/DubboBootstrapStopedEvent.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.config.bootstrap.DubboBootstrapStartStopListener
增加 DubboBootstrapStartStopListener 来对外通知 DubboBootstarp 的启动停止回调扩展；
向Spring环境抛出DubboBootstarp 的启动停止事件。
#7150
=> 增加DubboBootstrap启动停止事件扩展

dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilderTest.java
- add `providedBy` parameter in `DubboReference`
- make `services`  deprecated
=> [3.0] Add provided-by paramater for DubboReference

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/ProtocolFilterWrapper.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockProviderRpcExceptionTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/InvokerSideConfigUrlTest.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/model/MethodDefinition.java, dubbo-metadata/dubbo-metadata-api/src/test/resources/META-INF/dubbo/jax-rs-service-rest-metadata.json, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/OnlineApp.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/OnlineInterface.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/RegistryFactoryWrapperTest.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/SimpleRegistryFactory.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtilsTest.java, dubbo-rpc/dubbo-rpc-api/pom.xml, dubbo-rpc/dubbo-rpc-dubbo/pom.xml, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/support/DemoService.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/support/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-grpc/pom.xml, dubbo-rpc/dubbo-rpc-injvm/pom.xml, dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocolTest.java, dubbo-rpc/dubbo-rpc-rest/pom.xml, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/RestProtocolTest.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java, dubbo-rpc/dubbo-rpc-triple/src/main/proto/triple_wrapper.proto
Fix test cases in the following modules :
- dubbo-qos
- dubbo-metadata-api
- dubbo-config-api
- dubbo-rpc-*
- dubbo-registry-api
Fix some bugs :
- invalid filter for consumer in rpc interface refer ( make remote rpc context fetch available )
- unused import in dubbo-rpc-triple
- add asf license header in dubbo-rpc-triple
=> [UT] Fix unit-test cases in 3.0

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/rest/UserService.java, dubbo-rpc/dubbo-rpc-redis/src/main/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocol.java
which will fail the ci.
I really wonder, why the lib maintainers let such checkstyle-breaking pr merged in?
Do you really see the output of maven?
=> [DUBBO-47] remove unused imports.

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DynamicConfigurationServiceNameMapping.java
bug: String.format have wrong number of parameters.
=> [DUBBO-54] bug: String.format have wrong number of parameters.

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReportTest.java
Fix 'java.io.FileNotFoundException' when 'dump.directory' not exists
Try to create if not exists, if can't be created, use 'user.home' as dump directory. 
Link to issue: [#7178](https://github.com/apache/dubbo/issues/7178)
=> [Dubbo-7178] Fix 'java.io.FileNotFoundException' when 'dump.directory' not exists

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
ZoneAwareClusterInvoker在选择注册中心时，使用配置的loadbalance，而不使用service属性中的loadbalance。
To fix #6481 
当配置了多个注册中心时，ZoneAwareClusterInvoker会使用LoadBalance对多个注册中心进行一次筛选。
原是使用当前服务对应的loadbalance，当服务配置了自己的loadbalance时，ZoneAwareClusterInvoker就错误选择了服务的loadbalance区筛选注册中心。
现改为由LOADBALANCE_AMONG_REGISTRIES配置项的loadbalance（默认random）。
=> [Dubbo-6481]Fix Extended LoadBalance ran 2 times during service call

.gitattributes
Add .gitattributes file to prevent file formatting in Windows platform
=> Add gitattributes to prevent file formatting

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
=> Remove parameters from registryUrl to prevent config pollution

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringMap.java, dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/support/expiring/ExpiringCacheFactoryTest.java
reduce unnecessary check.
move the check of timeToLiveMillis out of the loop.
run the test case `org.apache.dubbo.cache.support.expiring.ExpiringCacheFactoryTest`
=> move the check of timeToLiveMillis out of the loop

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java
Improve error message of create extension failure, avoid a large number of unrelated extension loading failure errors 
Display related error message by name when create extension is failed.
No extraneous errors are displayed when loading a non-existent extension.
=> improve error message of create extension failure

dubbo-filter/dubbo-filter-cache/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.cache.CacheFactory
Without this configuration,LFU policy configuration will not be available.
fix LFU policy configuration not be available.
Add configuration in file -
\dubbo\dubbo-filter\dubbo-filter-cache\src\main\resources\META-INF\dubbo\internal\org.apache.dubbo.cache.CacheFactory
XXXXX
=> fix LFU policy configuration not be available.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
Remove timestamp from key to prevent the creation of multiple registries
每次调用getRegistry 都会创建新的Registry.造成会生成大量的HostReactor(里边又有serviceInfoMap),造成内存泄露.
问题的原因是没有删除时间戳(dubbo2 生成的key,不会包含时间戳).
正常使用不会有问题,但是会随着时间的发展oom
NacosRegistryFactory 中的 createRegistryCacheKey 获取的是 toFullString ,因此也不可能过滤(但也可以修改这里)
我们这里修改时间戳,是认为这算一个比较公共的属性 
XXXXX
XXXXX
=> fix AbstractRegistryFactory bug

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java
The test `org.apache.dubbo.rpc.RpcContextTest.testObject` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test. (See [PR #6314](https://github.com/apache/dubbo/pull/6314) for an example of how this could cause issues)
In `RpcContextTest.testObject()`, call `RpcContext.removeContext()` to clear remove the RPC context when the test finishes.
This fixes https://github.com/apache/dubbo/issues/6996 .
=> Remove RPC context in RpcContextTest.testObject

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/FilterNode.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolFilterWrapper.java
Currently, `ProtocolFilterWrapper$1` often appears in the exception stack, and users will be confused.  `ProtocolFilterWrapper$1` needs to be extracted as a separate class.
=> refactor ProtocolFilterWrapper$1 to FilterNode

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java
=> [ISSUE-#6999] Remove repeat action of register DubboBootstrapApplicationListener

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java, dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepository.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepositoryTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ThreadNameTest.java
目前社区版本消费者端的executor线程池是按提供者的Port的做了共享，当一个提供者下线时，AbstractClient就会将executor销毁，造成后续处理ChannelState.DISCONNECTED事件，以及消费者再调用其他提供者时无可用的executor，就会重新在创建一个executor，这个模式会导致#7054 所描述的问题。
同时考虑到消费者维护N个executor的开销，因此将消费者端的executor改为全局1个，在节点shutdown时再销毁。
1，DefaultExecutorRepository分配executor时，消费者的key使用Integer.MAX_VALUE，保证消费者使用1个executor，提供者保持原装（按协议的port分配executor）；同时getExecutor()内不再createExecutor，当executor为null则直接降级返回SHARED_EXECUTOR；
2，AbstractClient在close0时不关闭其持有的executor；
3，DubboBootstrap.destroy()时销毁ExecutorRepository；
=> [Dubbo-7054]消费者端Executor改为全局共享，不再按提供者Port共享。

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/ReflectUtilsTest.java
Add TypeVariable support for ReflectUtils
Fix #7040
Interface example:
``` java
public interface TypeClass<T> {
CompletableFuture<T> getGenericFuture();
}
```
=> Fix ReflectUtils not support generic call with Future

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
The test `org.apache.dubbo.config.ServiceConfigTest.testProxy` is not idempotent and fails if run twice in the same JVM, because each of the tests pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by these tests.
Reset `TestProxyFactory.count` to 0 at the end of `ServiceConfigTest.testProxy()`.
Link to issue: https://github.com/apache/dubbo/issues/7107
=> [Dubbo-7107] Reset TestProxyFactory.count after ServiceConfigTest.testProxy

dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java
2.6.x provider url like `default.group=default.test&default.version=default.1.0.0`
=> Interoperability with 2.6.x provider urls having "default.xxx" keys

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
The test `org.apache.dubbo.rpc.filter.AccessLogFilterTest.testInvokeException` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
In `AccessLogFilterTest.testInvokeException()`, call `DubboAppender.clear()` to clear all the logs from the log list when the test finishes.
This change fixes https://github.com/apache/dubbo/issues/6992
=> [Dubbo-6992] Clear DubboAppender in AccessLogFilterTest

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java
fix Exception stack information acquisition optimization #6984
=> fix Exception stack information acquisition optimization #6984

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java, dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
Hi,
I saw that both ServiceConfig and ReferenceConfig use similar variables. I believe that a good solution is to move these variables to a common class.
=> Group variables into a common class

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/AccessLogData.java
Hi everyone,
I discovered an opportunity to improve Dubbo. I believe that the buildAccessLogData method should be in the AccessLogData class because it uses only operations from that class.
=> Refactoring (move method) to AccessLogData class

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java
repair org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker#selectMockInvoker 's annotation,
According to org.apache.dubbo.rpc.cluster.router.mock.MockInvokersSelector#route ,directory.list() will return a list of normal invokers if Constants.INVOCATION_NEED_MOCK is absent or not true in invocation, rather than present
=> repair MockClusterInvoker#selectMockInvoker annotation

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReportInstance.java
=> [ISSUE-#7259] Separate metadataReport cache file base by application dimension.

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Request.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
fix #6960 npe。
垃圾处理器非常擅长处理这种稍纵即逝的对象，没有必要做这个优化，反而导致了npe。
=> [Dubbo-6960] fix bug: avoid npe when encode request

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/Constants.java, dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/TreePathDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-etcd/src/main/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfiguration.java
#6606 
Fix ConfigCenter namespace read bug in apollo, etcd and so on.
修复apollo、etcd等配置中心读取namespace错误的bug。
use org.apache.dubbo.common.constants.CommonConstants#CONFIG_NAMESPACE_KEY instead of org.apache.dubbo.common.config.configcenter.Constants#CONFIG_NAMESPACE_KEY.
在apollo、etcd等配置中心的实现中，使用org.apache.dubbo.common.constants.CommonConstants#CONFIG_NAMESPACE_KEY 来替换org.apache.dubbo.common.config.configcenter.Constants#CONFIG_NAMESPACE_KEY，确保自配置的配置中心namespace可以正确读取。
All unit tests have passed.
=> [DUBBO-2.7.8]Fix DynamicConfiguration namespace property read bug when use custom namespace

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
fix issue #6463 : start.sh can't work when dubbo.properties contain commented dubbo.protocol.port  property
dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
When configure the port of dubbo protocol in dubbo.properties file, start.sh will parse dubbo.properties using sed and get the dubbo protocol port number, then determine whether the application starts successfully by checking whether the port is opened.
But the mechanism of parsing dubbo protocol port isn't rigorous, when my dubbo.properties contains commented dubbo.protocol.port like this:
**#dubbo.protocol.port=20943
dubbo.protocol.port=20945**
start.sh will get wrong port number, and can't work normally.
=> [Dubbo-6463] fix issue: start.sh can't work when dubbo.properties contain commented dubbo.protocol.port  property

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/config/configcenter/file/FileSystemDynamicConfigurationTest.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
- Remove parameters from registryUrl to prevent config pollution ( Related with #7189 )
- Change to `url.getRemoteApplication()` for `TagRouter`
- Distint `MigrationRuleHandler` with timestamp
=> Fix it in Dubbo 3.0

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractExporter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProxyProtocol.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboExporter.java, dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/DubboHandlerRegistry.java, dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmExporter.java
fix DubboHandlerRegistry#removeService NPE issue.
see more detail from https://github.com/apache/dubbo/issues/6856.
XXXXX
XXXXX
=> fix 6856 DubboHandlerRegistry#removeService NPE issue.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
DubboBootstrap.destroy calls DubboShutdownHook.destroyProtocols repeatedly.
see more detail form #7302 
XXXXX
XXXXX
=> fix DubboBootstrap.destroy calls DubboShutdownHook.destroyProtocols repeatedly

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java
Below is exception from dubbo-samples
```text
2021-03-02T05:24:01.2519009Z Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'greeter': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: registerServiceWatcher create path=/services/demo-provider fail.
2021-03-02T05:24:01.2523291Z 	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:185)
2021-03-02T05:24:01.2528113Z 	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
2021-03-02T05:24:01.2532435Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance( …
```
=> fix zk service discovery, create parent node if absent

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
fix AbstractRegistryFactory#getRegistry and destroyAll methods compete for locks in multiple threads
see  https://github.com/apache/dubbo/issues/7265
XXXXX
XXXXX
=> fix #7265 AbstractRegistryFactory#getRegistry and destroyAll methods compete for locks in multiple threads

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/PojoUtilsForNonPublicStaticTest.java
=> [ISSUE-#6904] Fix reflect invoke error in org.apache.dubbo.common.utils.PojoUtils#generalize

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java, dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocolTest.java
Solve local exposure, the server opens the token, and the client call fails.
see more detail from https://github.com/apache/dubbo/issues/7024
XXXXX
XXXXX
=> Solve local exposure, the server opens the token, and the client call fails

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java
Fix  overrided RPCContext  persudo headers that causes request failure
XXXXX
XXXXX
=> [Dubbo3-Triple] Remove rpc context to avoid http2 headers override

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
fix org.apache.dubbo.common.URL#equals.
After comparing the parameters, the method will skip the following branches
fix the override method "equals" will skip branches after comparing the parameters in org.apache.dubbo.common.URL#equals
1. delete the code "retuen true" in line 1702 , inorder to continue the following comparing
2. add unit test
successfully continue the following comparing
=> Fix the override method "equals" will skip branches in org.apache.dubbo.common.URL#equals

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultRegistryClusterIdentifier.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
Use api, application-level service discovery model startup error 
see more detail from #7351 
XXXXX
XXXXX
=> solve use api, application-level service discovery model startup error 

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
For-#7339.
Didn't judge check in serviceDiscoveryRegistry, it should take over by ReferenceConfig.checkInvokerAvailable
=> [ISSUE-#7339] Didn't judge check in serviceDiscoveryRegistry

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java
#7315
unboxing boolean and refactor method filterInvoker
1.org.apache.dubbo.rpc.cluster.router.tag.TagRouter#isForceUseTag 
Boolean.valueOf -> Boolean.parseBoolean
2.org.apache.dubbo.rpc.cluster.router.tag.TagRouter#filterInvoker
refactor in stream
3.org.apache.dubbo.rpc.cluster.router.tag.TagRouter#filterUsingStaticTag
remove param(result) initial  value
=> fix #7315 redundant box for boolean and refactor method filterInvoker

pom.xml
I am trying to build Dubbo on ARM64 hardware and there are some test failures due to a usage of old versions of some test dependencies:
```
/tmp/1614937941285-0/redis-server-2.8.19: 1: ELF: not found                                                                                                                                                    
/tmp/1614937941285-0/redis-server-2.8.19: 2: Syntax error: word unexpected (expecting ")")             
/tmp/1614937941372-0/redis-server-2.8.19: 1: ELF: not found                                                                                                                                                    
/tmp/1614937941372-0/redis-server-2.8.19: 2: Syntax error: word unexpected (expecting ")") …
```
=> Update test dependencies and Maven plugins

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
Fix QOS Ready command return OK when DubboBootstrap is not ready
Fix issue: #7332
M dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
Only change one line, which initializes `ready` as `false` instead of `true`.
=> [Dubbo-7332] Fix QOS Ready command

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java
to fix something wrong with MergeableClusterInvoker#7359
As MergeableClusterInvoker was used, when 'resultList.size() == 1', there would be an error msg "AppResponse represents an concrete business response, there will be no status changes, you should get internal values directly." The reason is that the resultType would be "AppResponse", in org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster.InterceptorInvokerNode#invoke method's "return clause" the exception would be thrown. 
XXXXX
=> to fix something wrong with MergeableClusterInvoker

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
- Dubbo version: 2.7.8
```
public class DecodeableRpcResult{
public void setObjectAttachments(Map<String, Object> map) {
this.attachments = map == null ? new HashMap<>() : map;
}
}
```
DecodeableRpcResult解码的时候使用`setObjectAttachments`会丢失已经在IO线程解码的部分参数，例如input,output。
该方法应该替换为
```
public void addObjectAttachments(Map<String, Object> map) {
if (map == null) {
return;
}
if (this.attachments == null) {
this.attachments = new HashMap<>();
}
this.attachments.putAll(map);
}
```
=> DecodeableRpcResult解码参数丢失

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java, dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java
Change-Id: I4fce78be15179722fea1fa645495783c60b28573
Signed-off-by: yuandm <yuandm@foxmail.com>
fix OOM when deserializing data
XXXXX
XXXXX
=> fix OOM issue for Hessian2ObjectInput and Hessian2ObjectOutput

dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocal.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReportTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/support/cached/CachedThreadPoolTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/support/eager/EagerThreadPoolExecutorTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/support/eager/EagerThreadPoolTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/CollectionUtilsTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConfigUtilsTest.java
in java8,new Method[0] is better than new Method[methods.size()],you can learn about this from the below url:
https://shipilev.net/blog/2016/arrays-wisdom-ancients/
=> Optimize code in dubbo-common

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
polish DubboBootstrap
- use `Collections.singletonList` instead of `Arrays.asList`
- replace some lambda expressions to method reference to improve code readability.
Run test cases.
=> [Dubbo-Optimization]: polish DubboBootstrap

dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/LFUCacheTest.java
review #5734
- Rename constants to represent what it means:
DEFAULT_LOAD_FACTOR -> DEFAULT_CAPACITY
DEFAULT_EVICTION_CAPACITY -> DEFAULT_EVICTION_FACTOR
- Refactor codes:
```java
if (map.containsKey(key)) {
node = map.get(key);
if (node != null) {
CacheNode.withdrawNode(node);
}
node.value = value;
freqTable[0].addLastNode(node);
map.put(key, node);
}
```
- Add test case `org.apache.dubbo.common.utils.LRUCacheTest#testErrorConstructArguments`.
Run test case `org.apache.dubbo.common.utils.LRUCacheTest`
=> [Dubbo-fix]: polish LFUCache

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
Currently dubbo.protocol.keepAlive does not work on the server side. The purpose of this commit is to use this parameter as a configurable parameter. Please review this pr, thank you
=> Make keepalive parameters configurable on server

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ready.java
XXXXX
qos "ready" common add check service status feature.
[https://github.com/apache/dubbo/issues/7331](url)
XXXXX
=> [ISSUE-#7331] Ready common add check service is start success (#7331)

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
We should consider using Invocation inside the framework and restrict the use of RpcContext only when interacting with end-users.
=> Fix #7311, try put rpc contex attachments into invocation for Filters may have put new values.

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/DubboConfigInitializationPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBeanManager.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
Improve reference bean definition and prepare logic, fix injection problems of PropertyPlaceholderConfigurer
* Set bean definition property value as optional
* use `getBeanDefinition` instead of `getMergedBeanDefinition`, fix injection problems of PropertyPlaceholderConfigurer
* Prepare all reference beans in spring context, avoid missing instances initialized earlier (before `DubboConfigInitializationPostProcessor` is loaded)
Run dubbo-demo-property-configurer  (may be added to samples in the future)
=> Improve reference bean definition and prepare logic

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
For-[#7375](https://github.com/apache/dubbo/issues/7375)
=> [Dubbo-7375]fix url add repeatedly

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/DubboConfigInitializationPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBeanManager.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
Fix reference cache problem. 
Reference annotation may re-inject after prepare reference bean, reuse the cache as much as possible, and reinitialize the referenceConfig if it is not found
XXXXX
check issue: https://github.com/apache/dubbo/issues/6000
=> improve reference cache
