dubbo-rpc/dubbo-rpc-redis/src/main/java/com/alibaba/dubbo/rpc/protocol/redis/RedisProtocol.java
修改RedisProtocol.java 抛出的异常信息，把memecached改为redis，代码135行和167行
=> 修改抛出的异常信息，把memecached改为redis，代码135行和167行

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/AnnotationBean.java
=> @Reference在方法级别注入失败

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ProtocolConfig.java, dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/support/AbstractRegistry.java, dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/support/AbstractRegistryFactory.java, dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/support/FailbackRegistry.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/AbstractServer.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/protocol/AbstractInvoker.java
- 修复注册中心 unexport 的并发问题
- 修复关闭过程中，拿到的线程池为 null 的问题
- 修复关闭过程中，拿到的 futures 为 null 的问题
=> fix:修复优雅停机问题

dubbo-common/src/test/java/com/alibaba/dubbo/common/extensionloader/ext3/UseProtocolKeyExt.java
修改测试单元中，UseProtocolKeyExt接口，第31行注释“ // protocol 吸在第一个”改为“ // protocol key在第一个”
=> Mod(UseProtocolKeyExt) : 修改注释

.travis.yml, dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/configurator/AbstractConfigurator.java, dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryProtocol.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/ContextFilter.java, dubbo-rpc/dubbo-rpc-redis/src/main/java/com/alibaba/dubbo/rpc/protocol/redis/RedisProtocol.java
issue#492: fix async penetrate in rpc chain
=> issue#28: fix override configuration problem

dubbo-common/src/main/java/com/alibaba/dubbo/common/serialize/support/dubbo/Builder.java, dubbo-filter/dubbo-filter-cache/src/main/java/com/alibaba/dubbo/cache/support/lru/LruCache.java
fix:LruCache accessOrder 没设置为 true 的问题
=> fix:LruCache accessOrder 没设置为 true 的问题

dubbo-common/src/main/java/com/alibaba/dubbo/common/serialize/support/dubbo/Builder.java, dubbo-filter/dubbo-filter-cache/src/main/java/com/alibaba/dubbo/cache/support/lru/LruCache.java
=> fix:移除 LruCache 多余的同步块

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/PojoUtils.java
fix: PojoUtils有几个问题 1. Enum和普通类型的处理应该是不同的。 2.没有setter的时候取field，但是只取了public field 3. 如果一个类只有私有构造函数是不支持的 4. 返回值丢掉了
=> fix: 修复泛调用使用的PojoUtils的几个问题

dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java
这里存在并发问题，如果并发调用ReferenceConfig.get有可能创建多个client出来。我们有些场景是直接用ReferenceConfig API来创建client，而不是使用spring的方式，这样就存在这个问题了
=> bugfix: 这里存在并发问题，如果并发调用ReferenceConfig.get有可能创建多个client出来

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/stop.sh
=> 修改监控服务脚本支持不同终端重启服务 

dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/loadbalance/LoadBalanceTest.java
detail see: https://github.com/alibaba/dubbo/pull/300
=> Fix unit test of leastactive loadbalancer

dubbo-simple/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/SimpleMonitorService.java
[SimpleMonitorService.write](https://github.com/alibaba/dubbo/blob/master/dubbo-simple/dubbo-monitor-simple/src/main/java/com/alibaba/dubbo/monitor/simple/SimpleMonitorService.java#L192)
consumer可能==null
<pre>
consumer = statistics.getParameter(CONSUMER);
int i = consumer.indexOf(':');
</pre>
fix
<pre>
int i = consumer == null ? -1 : consumer.indexOf(':');
</pre>
=> fix #404 int i = consumer.indexOf(':'); when consumer==null

dubbo-cluster/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.rpc.cluster.Merger
fix merger spelling mistke
https://github.com/alibaba/dubbo/issues/922
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.rpc.cluster.Merger
=> #922 修改merger拼写错误

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
fix issue #941 修改 start.sh `127.0.0.1`为'127.0.0.1'
dubbo/dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
XXXX
=> fix issue #941 bug

dubbo-demo/dubbo-demo-consumer/src/main/java/com/alibaba/dubbo/demo/consumer/Consumer.java, dubbo-demo/dubbo-demo-provider/src/main/java/com/alibaba/dubbo/demo/provider/Provider.java
修复在无线网环境下运行demo ，产生 Can't assign requested address 错误
=> fix: 运行demo的时候，连接无线网，默认会获取IPv6 地址，导致报错

dubbo-plugin/dubbo-qos/src/main/java/com/alibaba/qos/server/Server.java, dubbo-plugin/dubbo-qos/src/main/java/com/alibaba/qos/server/handler/LocalHostPermitHandler.java
fix qos port can only configure by System property problem
now get property by ConfigUtils
it can work
=> fix:fix qos port can only configure by System property problem

dubbo-admin/src/main/java/com/alibaba/dubbo/governance/sync/RegistryServerSync.java, dubbo-admin/src/main/webapp/WEB-INF/templates/governance/layout/default.vm, dubbo-admin/src/main/webapp/WEB-INF/templates/governance/screen/applications/index.vm, dubbo-admin/src/main/webapp/WEB-INF/templates/governance/screen/providers/index.vm, dubbo-admin/src/main/webapp/WEB-INF/templates/governance/screen/redirect.vm, dubbo-admin/src/main/webapp/WEB-INF/templates/governance/screen/services/index.vm, dubbo-admin/src/main/webapp/WEB-INF/templates/sysinfo/layout/default.vm, dubbo-admin/src/main/webapp/WEB-INF/templates/sysinfo/screen/dumps/index.vm, dubbo-admin/src/main/webapp/WEB-INF/templates/sysinfo/screen/redirect.vm
Fix some bugs find in dubbo-admin
1. Fixed #466, use relative path when redirect
2. Fixed #972, promotion error of 'batch recover' on 'application' tab
3. Fix dubbo-admin, cache refresh problem when service changed
Mostly web redirect change, verify by deploy dubbo-admin and visit on browser.
=> Fix some bugs reported in dubbo-admin

hessian-lite/pom.xml, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/BigIntegerDeserializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/EnumSetHandler.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/EnumSetSerializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/DurationHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/InstantHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/Java8TimeSerializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/LocalDateHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/LocalDateTimeHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/LocalTimeHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/MonthDayHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/OffsetDateTimeHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/OffsetTimeHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/PeriodHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/YearHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/YearMonthHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/ZoneIdHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/ZoneIdSerializer.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/ZoneOffsetHandle.java, hessian-lite/src/main/java/com/alibaba/com/caucho/hessian/io/java8/ZonedDateTimeHandle.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Hessian2EnumSetTest.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/Type.java, hessian-lite/src/test/java/com/alibaba/com/caucho/hessian/io/java8/Java8TimeSerializerTest.java
I18N effort for dubbo code base - hessian-lite #1075
* All comments of the codes in hessian-lite module
=> Add apache licence

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractConfig.java
Rename "suffixs" and usage in abstract config to correct "suffixes" as suggested in issues.  
Renamed and refactored suffixes to correct plural usage
Refactored usages.
=> [Dubbo-1159] Fix suffixes in abstract config

dubbo-registry/dubbo-registry-multicast/src/main/java/com/alibaba/dubbo/registry/multicast/MulticastRegistry.java, dubbo-registry/dubbo-registry-redis/src/main/java/com/alibaba/dubbo/registry/redis/RedisRegistryFactory.java
- fix redis RedisRegistryFactory create Multi-instance RedisRegistry
- fix multicast registry ignore empty list, add a empty protocol to fix it
=> bugfix:fix redis and multicast registry offline fail

dubbo-remoting/dubbo-remoting-http/pom.xml, dubbo-remoting/dubbo-remoting-http/src/test/java/com/alibaba/dubbo/remoting/http/TestUtil.java, dubbo-remoting/dubbo-remoting-http/src/test/java/com/alibaba/dubbo/remoting/http/jetty/JettyHttpBinderTest.java, dubbo-remoting/dubbo-remoting-http/src/test/java/com/alibaba/dubbo/remoting/http/tomcat/TomcatHttpBinderTest.java
add unit test for jetty http binder and tomcat http binder
=> add unit test for jetty http binder and tomcat http binder

dubbo-remoting/dubbo-remoting-netty4/src/main/java/com/alibaba/dubbo/remoting/transport/netty4/NettyChannel.java
fix disconnect is not work right
=> Channel.close() in netty4 is async, so reconnect() don't connected

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java
原代码用到的是SortMap.firstKey()
1.1  isEmpty会查找一次
1.2  firstKey又会查找一次
1.3  get(key)还会找一次值.
可以简单通过NavigableMap.firstEntry()一次查找拿到值。
=> Reducing search times in selectForKey(hash) 

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/util/PropertySourcesUtils.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/util/PropertySourcesUtilsTest.java
#1399  fix number type is lost in yaml config file
Remove String type filter when read yaml file data
Run referenced unit test
=> fix number type is lost in yaml config file

dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/cache/CacheTest.java, dubbo-filter/dubbo-filter-cache/src/main/java/com/alibaba/dubbo/cache/CacheFactory.java, dubbo-filter/dubbo-filter-cache/src/main/java/com/alibaba/dubbo/cache/filter/CacheFilter.java, dubbo-filter/dubbo-filter-cache/src/main/java/com/alibaba/dubbo/cache/support/AbstractCacheFactory.java
fix [#1362](https://github.com/alibaba/dubbo/issues/1362)
=> [Dubbo-#1362] cache provider always lru cache

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchangeClient.java
=> fix heartbeat spelling error

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/util/PropertySourcesUtils.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/util/PropertySourcesUtilsTest.java
merge #1401 to 2.5.x branch 
modified files in #1401 
CI pass
=> merge issue 1401 to 2.5.x

README.md
add d English&Chinese doc link
add English&Chinese doc link in readme
add English&Chinese doc link in readme
=> Update Readme to add English&Chinese doc link

README.md
change the project path for travis ci and codecov
TRADME.md
The travis status of README.md  page shows normal
=> change the project path for travis ci and codecov

dubbo-common/src/main/java/com/alibaba/dubbo/common/URL.java
correct the comments in URL class
correct the protocol description for file url
correct the protocol description for file url
=> comments in URL class are incorrect

README.md
=> update readme #1488

.travis.yml
update travis_wait 30min to prevent travis timeout
update travis_wait 30min to prevent travis timeout
update travis_wait 30min to prevent travis timeout
only affect ci
=> update travis_wait 30

dependencies-bom/pom.xml
Upgrade spring version.
Upgrade spring version to 4.3.16.RELEASE
UT passed.
=> Upgrade spring version to 4.3.16.RELEASE.

dependencies-bom/pom.xml, dubbo-registry/dubbo-registry-multicast/src/test/java/com/alibaba/dubbo/registry/multicast/MulticastRegistryFactoryTest.java, dubbo-registry/dubbo-registry-multicast/src/test/java/com/alibaba/dubbo/registry/multicast/MulticastRegistryTest.java, dubbo-registry/dubbo-registry-redis/pom.xml, dubbo-registry/dubbo-registry-redis/src/test/java/com/alibaba/dubbo/registry/redis/RedisRegistryTest.java, dubbo-registry/dubbo-registry-zookeeper/pom.xml, dubbo-registry/dubbo-registry-zookeeper/src/test/java/com/alibaba/dubbo/registry/zookeeper/ZookeeperRegistryTest.java
add more unit test for registry modules
+ add embedded redis to support redis registry unit test
+ add unit test for zookeeper registry 
+ add unit test for Multicast registry 
CI Pass
=> add more unit test for registry modules

dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/ExtensionLoader.java
- Break old "loadFile" into pieces, improve readability.
- Remove some unnecessary code.
- Some typo fix.
In conclusion, this change has no actual effects, just some code improvement.
=> Method extraction & Unnecessary code remove & Typo fix

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ProtocolConfig.java, dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/AnnotationBean.java, dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java
1. fix jvm shutdown gracefully bug, including annotation bean and server running state error. see: https://github.com/apache/incubator-dubbo/issues/1606
1. `com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeServer#close(int)`, solve the problem of the dubbo unable to sleep thread.
2. `com.alibaba.dubbo.config.spring.AnnotationBean#destroy`，solve the use of annotations can not elegantly stop the scene.
1. DubboInvokerAvilableTest#test_normal_channel_close_wait_gracefully
=> [Dubbo-shutdown gracefully]  fix shutdown gracefully.

PULL_REQUEST_TEMPLATE.md
fix typo of pull request template, see: https://github.com/apache/incubator-dubbo/issues/1604#issuecomment-383612778
=> [Dubbo- pull request template typo] update pr template.

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/execution/ExecutionChannelHandler.java
a follow up for pull request https://github.com/apache/incubator-dubbo/pull/1449
enhance comments, javadoc and logging message for ExecutionChannelHandler
=> enhance comments, javadoc and logging message for ExecutionChannelHandler

dubbo-serialization/dubbo-serialization-hessian2/src/test/java/com/alibaba/dubbo/common/serialize/serialization/AbstractSerializationTest.java, dubbo-serialization/dubbo-serialization-jdk/src/test/java/com/alibaba/dubbo/common/serialize/serialization/AbstractSerializationTest.java, dubbo-serialization/dubbo-serialization-jdk/src/test/java/com/alibaba/dubbo/common/serialize/serialization/NativeJavaSerializationTest.java, dubbo-serialization/dubbo-serialization-kryo/src/test/java/com/alibaba/dubbo/common/serialize/serialization/AbstractSerializationTest.java
optimize unit test for serialization hession2/jdk/kryo
modified:   dubbo-serialization-hessian2/src/test/java/com/alibaba/dubbo/common/serialize/serialization/AbstractSerializationTest.java
modified:   dubbo-serialization-jdk/src/test/java/com/alibaba/dubbo/common/serialize/serialization/AbstractSerializationTest.java
new file:   dubbo-serialization-jdk/src/test/java/com/alibaba/dubbo/common/serialize/serialization/NativeJavaSerializationTest.java
modified:   dubbo-serialization-kryo/src/test/java/com/alibaba/dubbo/common/serialize/serialization/AbstractSerializationTest.java
All unit test cases are pass.
=> optimize unit test for serialization hession2/jdk/kryo

.codecov.yml, dubbo-common/src/test/java/com/alibaba/dubbo/common/concurrent/ExecutionListTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/concurrent/ListenableFutureTaskTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/io/BytesTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/io/StreamUtilsTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/io/UnsafeByteArrayInputStreamTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/io/UnsafeByteArrayOutputStreamTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/io/UnsafeStringReaderTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/io/UnsafeStringWriterTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/logger/LoggerAdapterTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/logger/LoggerFactoryTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/logger/LoggerTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/logger/slf4j/Slf4jLoggerTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/logger/support/FailsafeLoggerTest.java, dubbo-common/src/test/resources/META-INF/dubbo/internal/com.alibaba.dubbo.common.logger.LoggerAdapter, dubbo-common/src/test/resources/md5.testfile.txt
Improve unit test for common module.
```
dubbo-common/src/main/java/com/alibaba/dubbo/common/concurrent
dubbo-common/src/main/java/com/alibaba/dubbo/common/io
dubbo-common/src/main/java/com/alibaba/dubbo/common/json
dubbo-common/src/main/java/com/alibaba/dubbo/common/logger
```
Close #1681 
+ Add test for concurrent, io and logger.
+ Json module is deprecate since last year, ignore it in codecov config
CI Pass https://travis-ci.org/diamondblack/incubator-dubbo/builds/372700464
=> [Dubbo-1681] add test for dubbo common module

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractMethodConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractReferenceConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/AbstractServiceConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockExporterListener.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockLoadBalance.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/com/alibaba/dubbo/config/AbstractReferenceConfigTest.java, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.ExporterListener, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.cluster.LoadBalance
unit test for AbstractMethodConfig, AbstractReferenceConfig, AbstractServiceConfig
=> unit test for dubbo-config-api

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ArgumentConfig.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ApplicationConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ArgumentConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ConsumerConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MethodConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockCodec.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockDispatcher.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockExchanger.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockProtocol2.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockStatusChecker.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockTelnetHandler.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockThreadPool.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockTransporter.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ModuleConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MonitorConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ProtocolConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ProviderConfigTest.java, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.common.status.StatusChecker, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.common.threadpool.ThreadPool, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.remoting.Codec, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.remoting.Dispatcher, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.remoting.Transporter, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.remoting.exchange.Exchanger, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.remoting.telnet.TelnetHandler, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.rpc.Protocol
part of unit test for config-api module
unit test for config-api module
=> Config api unit test

dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/MockRegistryFactory.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/RegistryConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/ServiceConfigTest.java, dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/com.alibaba.dubbo.registry.RegistryFactory
=> unit test for ServiceConfig

dubbo-monitor/dubbo-monitor-api/src/test/java/com/alibaba/dubbo/monitor/support/AbstractMonitorFactoryTest.java, dubbo-monitor/dubbo-monitor-api/src/test/java/com/alibaba/dubbo/monitor/support/MonitorFilterTest.java, dubbo-monitor/dubbo-monitor-default/src/test/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitorFactoryTest.java, dubbo-monitor/dubbo-monitor-default/src/test/java/com/alibaba/dubbo/monitor/dubbo/DubboMonitorTest.java, dubbo-monitor/dubbo-monitor-default/src/test/java/com/alibaba/dubbo/monitor/dubbo/StatisticsTest.java
Add unit test for monitor module
Close #1688 
Add test for dubbo-monitor-api
Add test for dubbo-monitor-default
CI PASS https://travis-ci.org/diamondblack/incubator-dubbo/builds/375168584
=> add test for monitor module

dubbo-common/src/main/java/com/alibaba/dubbo/common/status/Status.java, dubbo-common/src/main/java/com/alibaba/dubbo/common/status/support/LoadStatusChecker.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/status/StatusTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/status/support/LoadStatusCheckerTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/status/support/MemoryStatusCheckerTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/status/support/StatusUtilsTest.java
unit test for com.alibaba.dubbo.common.status.support
=> unit test for com.alibaba.dubbo.common.status.support

dubbo-common/src/test/java/com/alibaba/dubbo/common/store/support/SimpleDataStoreTest.java
=> unit test for SimpleDataStore

dubbo-common/src/test/java/com/alibaba/dubbo/common/threadpool/support/cached/CachedThreadPoolTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/threadpool/support/eager/EagerThreadPoolTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/threadpool/support/fixed/FixedThreadPoolTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/threadpool/support/limited/LimitedThreadPoolTest.java
make thread-pool unit test stable
=> make unit test stable

dubbo-common/src/main/java/com/alibaba/dubbo/common/json/GenericJSONConverter.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/json/JSONTest.java, dubbo-registry/dubbo-registry-zookeeper/src/main/java/com/alibaba/dubbo/registry/zookeeper/ZookeeperRegistry.java
fix zk unsubscribe issue
unsubscribe zk registry
XXXXX
=> zk Unsubscribe issue

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/dispatcher/ChannelEventRunnable.java
ChannelState branch prediction optimization
More details: https://gist.github.com/hengyunabc/40d6a671d329067faea87258301e80a8
XXXXX
=> ChannelState branch prediction optimization.

dubbo-registry/dubbo-registry-redis/src/main/java/com/alibaba/dubbo/registry/redis/RedisRegistry.java
Issue#1830: dbindex support in redis
com.alibaba.dubbo.registry.redis.RedisRegistry
=> issue#1830: dbindex support in redis

dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryProtocol.java
remove validation key in provider's url, #1386 
XXXXX
XXXXX
=> Validation

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/ReflectUtils.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/ReflectUtilsTest.java
#1682: Enhance the test coverage part-4 : dubbo-common/src/main/java/com/alibaba/dubbo/common/status(store|threadpoolutils) modules
dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/ReflectUtils.java
dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/ReflectUtilsTest.java
=> unit test for ReflectUtils

dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/RegistryService.java, dubbo-registry/dubbo-registry-multicast/src/main/java/com/alibaba/dubbo/registry/multicast/MulticastRegistry.java, dubbo-registry/dubbo-registry-multicast/src/test/java/com/alibaba/dubbo/registry/multicast/MulticastRegistryTest.java
Add unit tests for MulticastRegister. 
Fix #1691 , the MulticastRegister parts.
* Add unit tests for MulticastRegister
* add some comments to methods
* fix some typo
=> [Dubbo-1691] Add unit tests for MulticastRegister #1691

dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/StackTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/StringUtilsTest.java
#1682: Enhance the test coverage part-4 : dubbo-common/src/main/java/com/alibaba/dubbo/common/status(store|threadpoolutils) modules
dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/StackTest.java
dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/StringUtilsTest.java
=> unit test for Stack and StringUtils

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java
support protocol config for reference annotation
support protocol config for reference annotation
com.alibaba.dubbo.config.spring.beans.factory.annotation.AnnotationPropertyValuesAdapterTest
=> Support protocol config for reference annotation

.travis.yml, pom.xml
add add java10 in travis dot yml
https://github.com/apache/incubator-dubbo/issues/1521
.travis.yml
pom.xml
ci pass
=> add java10 in travis dot yml

dubbo-common/src/main/java/com/alibaba/dubbo/common/threadpool/support/eager/EagerThreadPoolExecutor.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/threadpool/support/eager/EagerThreadPoolExecutorTest.java
fix exception handle bugs
1. throw Throwable
2. throw RejectedExecutionException with AbortPolicyWithReport msg
XXXXX
=> fix swallow exception and disable  AbortPolicyWithReport function.

dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TKvTest.java, dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TLadderTest.java, dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TTableTest.java, dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TTreeTest.java
issue#1689: Enhance the test coverage part-10 : dubbo-plugin module, unit test for text
dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TKvTest.java
dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TLadderTest.java
dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TTableTest.java
dubbo-plugin/dubbo-qos/src/test/java/com/alibaba/dubbo/qos/textui/TTreeTest.java
=> [dubbo-1689]: Enhance the test coverage part-10 : dubbo-plugin module, unit test for text

dubbo-remoting/dubbo-remoting-p2p/pom.xml
fix old groupId
dubbo-remoting/dubbo-remoting-p2p/pom.xml
=> fix old groupId

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContext.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContextImpl.java
* fix a bug when the provider write a throwable into aysnc context
* sth doc
* simple code
=> Fix a bug when the provider write a throwable into aysnc context

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
fix #1925 
remove redundant comparison 
remove redundant comparison 
=> fix #1925 

dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/GreetingCommand.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/HttpCommandDecoderTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/TelnetCommandDecoderTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/HelpTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/LsTest.java
unit test for dubbo-pluign, tracked by issue#1689
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/GreetingCommand.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/HttpCommandDecoderTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/TelnetCommandDecoderTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/HelpTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/LsTest.java
=> [dubbo-1689]: Enhance the test coverage part-10 : dubbo-plugin module

dubbo-rpc/dubbo-rpc-redis/src/main/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocol.java
Secure release of redis connections #1986 
Secure release of redis connections
RedisProtocol.java
=> [Dubbo-1986]optimize redis connection release

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
rename access log in unit test from 'alibaba' to 'alibaba.log' 
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
XXXXX
=> rename access log in unit test from 'alibaba' to 'alibaba.log' 

bom/pom.xml, dependencies-bom/pom.xml, pom.xml
change maven parent from sonatype to apache
```xml
<parent>
<groupId>org.apache</groupId>
<artifactId>apache</artifactId>
<version>19</version>
</parent>
```
Check you can deploy SNAPSHOT version to apache repository.
=> change maven parent from sonatype to apache

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
rename log file from alibaba to custom-access
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
XXXXX
=> rename log file from alibaba to custom-access

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/FutureAdapter.java
Fix a bug which make isDone method infinite-loop
=> Fix a bug which make isDone method infinite-loop

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Service.java
improve javadoc, and annotation's default value
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/annotation/Service.java
XXXXX
=> [dubbo-2072]: need javadoc and articles for spring annotation use.

dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/annotation-version-consumer.xml
remove the verison property that is no use, you can see issue  #1929
=> [dubbo-1929]: remove the verison property that is no use (#1929)

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
The ExchangeChannel will be used in a inner class.
Optimize it to final.
=> Optimize code style.

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
fix unstable test case
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
XXXXX
=> fix unit test failure

README.md
correting the demo code in readme
correting the demo code in readme
correting the demo code in readme
Verified.
=> [dubbo-parent] Fix  demo code error in readme file

all/pom.xml
Because dubbo use netty4 as the default transport, so upgrade netty dependency for dubbo-all
dubbo-all/pom.xml
XXXXX
=> upgrade netty for dubbo-all

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java
=> change the  log level

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java
fix typos
fix typos in ContextFilter.java line: 48
change from `mreged` to `merged` 
no
=> fix typos in ContextFilter.java

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
=> solve compatible issue with dubbo 2.5.9, 2.5.10

dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/Activate.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/Activate.java
deprecated unused method for Activate
dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/Activate.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/Activate.java
unit test pass
=> deprecated unused method for Activate #2180

dubbo-serialization/dubbo-serialization-api/pom.xml, dubbo-serialization/dubbo-serialization-hessian2/pom.xml
replace hard coded version number of hessian-lite
replace hard coded version number of hessian-lite
incubator-dubbo/dubbo-serialization/dubbo-serialization-api/pom.xml
incubator-dubbo/dubbo-serialization/dubbo-serialization-hessian2/pom.xml
unit test pass
=> [Dubbo-#2136] replace hard coded version number of hessian-lite

all/pom.xml, bom/pom.xml, distribution/pom.xml, dubbo-common/pom.xml, dubbo-serialization/dubbo-serialization-jdk/pom.xml, dubbo-test/pom.xml
Replace hard-coded hessian-lite version with maven property.
Fix #2136
Only some pom.xml files
`mvn clean compile` 
=> [Dubbo-2136], replace hard-coded hessian-lite version with maven property.

.travis.yml, dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/RegistryConfigTest.java
fix ut stable, #2227
dubbo-config/dubbo-config-api/src/test/java/com/alibaba/dubbo/config/RegistryConfigTest.java
ut pass
=> fix ut stable, #2227

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java, dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java
fix retries to 2, #2162
dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java
ut pass
=> fix retries to 2, #2162

.travis.yml
change travis ci configuration
.travis.yml
XXXXX
=> change travis ci configuration

.travis.yml, dubbo-all/pom.xml, dubbo-config/dubbo-config-spring/src/test/resources/applicationContext.xml, dubbo-config/dubbo-config-spring/src/test/resources/webapps/test/WEB-INF/web.xml, dubbo-config/dubbo-config-spring/src/test/resources/webapps/test2/WEB-INF/web.xml, dubbo-config/dubbo-config-spring/src/test/resources/webapps/test3/WEB-INF/web.xml, dubbo-metrics/dubbo-metrics-api/pom.xml, dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/MetricManagerTest.java, dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/MetricNameTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/HttpCommandDecoderTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/decoder/TelnetCommandDecoderTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/HelpTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/LsTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/OfflineTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/OnlineTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/QuitTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/TestRegistryFactory.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/protocol/QosProtocolWrapperTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/HttpProcessHandlerTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/LocalHostPermitHandlerTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/QosProcessHandlerTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/TelnetProcessHandlerTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ClassLoaderFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/proxy/AbstractProxyTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/proxy/jdk/JdkProxyFactoryTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/LocalException.java
1. remote dubbo-all javadoc plugin
2. add license info to test source file
dubbo-all/pom.xml
**/src/test/
XXXXX
=> remote dubbo-all javadoc plugin

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractInterfaceConfig.java
refering from subscription in monitoring lack of several important parameters. like:
```
dubbo=2.5.7&interface=com.alibaba.dubbo.monitor.MonitorService&pid=2366&timestamp=1532170822721
```
it missed two important parameters at least:
> application
> register.ip
which it will take trouble in admin-console.
add missing parameters
the final subscription will be like:
```
consumer://192.168.40.90/com.alibaba.dubbo.monitor.MonitorService?application=yim-consumer&category=consumers&check=false&dubbo=2.0.1&interface=com.alibaba.dubbo.monitor.MonitorService&pid=2867×tamp=1532173971611
```
=> [Dubbo-2110]Fix subscript MonitorService lack of parameters in monitoring

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/support/DemoService.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/support/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokerTelnetHandlerTest.java
=> fix telnet invoke NPE #2218

dubbo-common/pom.xml, dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java, dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j2/Log4j2Logger.java, dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j2/Log4j2LoggerAdapter.java, dubbo-common/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.logger.LoggerAdapter, dubbo-common/src/test/java/org/apache/dubbo/common/logger/LoggerAdapterTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/logger/slf4j/Slf4jLoggerTest.java, dubbo-dependencies-bom/pom.xml
#1713 
to add log4j2 for dubbo.
add log4j2 framework.
=> add log4j2 extension

dubbo-dependencies-bom/pom.xml
https://github.com/apache/incubator-dubbo/issues/2134
=> #2134 Fix dependency conflict issue for com.alibaba:dubbo-rpc-thrift

LICENSE, dubbo-common/src/main/java/org/apache/dubbo/common/timer/HashedWheelTimer.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
supplemental change for PR#1973
- add necessary content in LICENSE
- move utility method from StringUtils to ClassHelper
XXXXX
=> supplemental change for pull request 1973

dubbo-bom/pom.xml
Set Dubbo root pom as parent also for BOM module. 
=> [Dubbo-BOM] Changed parent pom to Dubbo root

.travis.yml
fix travis code coverage problem
.travis.yml
XXXXX
=> fix travis cov

README.md
Update several outdated link in README.md.
Update README.md
=> Update several documentation links

dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java
typo
prvoiderService->providerService; connectSkiped->connectSkipped
none
=> typo: prvoiderService->providerService; connectSkiped->connectSkipped

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/LeastActiveLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java
A little change, replace `Random` with `ThreadLocalRandom` .
Use of `ThreadLocalRandom` rather than shared `Random` objects in concurrent programs will typically encounter much less overhead and contention.
Use of `ThreadLocalRandom` is particularly appropriate when multiple tasks .
replace `Random` with `ThreadLocalRandom` in `LeastActiveLoadBalance` and `RandomLoadBalance`.
reuse the test case already exist.
=> [Dubbo-random enhance] replace Random with ThreadLocalRandom

pom.xml
upgrade javadoc to 3.0.1
XXXXX
XXXXX
=> upgrade javadoc to 3.0.1

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ApplicationConfig.java, dubbo-plugin/dubbo-qos/src/main/java/com/alibaba/dubbo/qos/protocol/QosProtocolWrapper.java, dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryProtocol.java
take #2153 back to 2.6.x
XXXXX
XXXXX
=> Qos enhancement

all/pom.xml
remove dubbo-all javadoc plugin
XXXXX
XXXXX
=> remove dubbo-all javadoc plugin

dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/override-multi-protocol.xml
=> remove a redundant '>'

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/CommandContext.java
code style format to make code more standard
=> format code style

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
fix #2446 
Service Interface 采用 Invocation Interface 的 ClassLoader 进行加载
org.apache.dubbo.common.utils.ReflectUtils
org.apache.dubbo.rpc.support.RpcUtils
=> [Dubbo-2446]Fix ClassNotFoundException when load Service Interface by parent ClassLoader

.github/ISSUE_TEMPLATE/dubbo-issue-report-template.md
fix some wording issue.
XXXXX
XXXXX
XXXXX
=> fix wording issue in dubbo-issue-report-template.md

.travis.yml, dubbo-common/src/test/java/org/apache/dubbo/common/utils/UrlUtilsTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/GenericServiceTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/cache/CacheTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientReconnectTest.java, dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyClientToServerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/PortTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/org/apache/dubbo/rpc/protocol/webservice/WebserviceProtocolTest.java
#2492 
#2490
#2484
#2482
#2462
#2460
XXXXX
XXXXX
=> fix stable problem for unit cases

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java, dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/delay-fixed-time.xml, dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/delay-on-initialized.xml, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ChangeTelnetHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokerTelnetHandlerTest.java
change unit test port
XXXXX
XXXXX
=> change unit test port

dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/web-fragment.xml, dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/annotation-consumer.xml, dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/override-multi-protocol.xml, dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/provider-multi.xml
1. fix some xsd issue by adding schema location so it can pass xsd validation
2. web fragment cannot have '-' in its name; change it to '_'
=> fix some xsd error

dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/serialization/AbstractSerializationPersonFailTest.java, dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/serialization/AbstractSerializationPersonOkTest.java, dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/serialization/Hessian2SerializationTest.java, dubbo-serialization/dubbo-serialization-jdk/src/test/java/org/apache/dubbo/common/serialize/serialization/AbstractSerializationPersonFailTest.java, dubbo-serialization/dubbo-serialization-jdk/src/test/java/org/apache/dubbo/common/serialize/serialization/AbstractSerializationPersonOkTest.java, dubbo-serialization/dubbo-serialization-jdk/src/test/java/org/apache/dubbo/common/serialize/serialization/CompactedJavaSerializationTest.java, dubbo-serialization/dubbo-serialization-jdk/src/test/java/org/apache/dubbo/common/serialize/serialization/JavaSerializationTest.java, dubbo-serialization/dubbo-serialization-jdk/src/test/java/org/apache/dubbo/common/serialize/serialization/NativeJavaSerializationTest.java, dubbo-serialization/dubbo-serialization-kryo/src/test/java/org/apache/dubbo/common/serialize/serialization/AbstractSerializationPersonFailTest.java, dubbo-serialization/dubbo-serialization-kryo/src/test/java/org/apache/dubbo/common/serialize/serialization/AbstractSerializationPersonOkTest.java
Fix typos in serialization unit tests: persion -> person
XXXXX
XXXXX
=> Fix typos in serialization unit tests

README.md, dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java
#2507: Dubbo 's ExtensionLoader may be can't find custom Extension
honor thread context class loader and system class loader in extension loader.
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassHelper.java
XXXXX
=>  #2507: Dubbo 's ExtensionLoader may be can't find custom Extension

dubbo-remoting/dubbo-remoting-mina/src/test/java/org/apache/remoting/transport/mina/MinaClientToServerTest.java, dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/NettyClientToServerTest.java
=> set ut timeout to 3000

README.md, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/DataSourceStatusChecker.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/SpringStatusChecker.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/status/DataSourceStatusCheckerTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/status/SpringStatusCheckerTest.java
Fix #2516: Remove getSpringContext() from org.apache.dubbo.config.spring.ServiceBean
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/DataSourceStatusChecker.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/SpringStatusChecker.java
=>  issue#2516: Remove getSpringContext() from org.apache.dubbo.config.spring.ServiceBean

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ListTelnetHandlerTest.java
fix #2532, change different port
XXXXX
XXXXX
=> fix #2532, change different port

.travis.yml
fix #2558 , rm java 9 and 10 on travis
XXXXX
XXXXX
=> rm java 9 and 10 on travis

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java
=> code format

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/initializer/DubboApplicationContextInitializerTest.java
fix #2560, use target/test-classes as the basedir
XXXXX
XXXXX
=> fix #2560, use target/test-classes as the basedir

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
=> NullPointerException

dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryFactoryTest.java
fix registry unit test failed
`org.apache.dubbo.registry.support.AbstractRegistryFactoryTest#testRegistryFactoryIpCache`
refer here: https://github.com/apache/incubator-dubbo/issues/2545
ci passed.
=> [Dubbo fix unit test] fix registry unit test failed

README.md
update lastest version to 2.6.4
XXXXX
XXXXX
=> update lastest version to 2.6.4

all/pom.xml
fix #2600, add javadoc plugin to dubbo-all module
XXXXX
XXXXX
=> fix #2600, add javadoc plugin to dubbo-all module

dubbo-all/pom.xml
fix #2600 add javadoc-plugin to dubbo-all module
XXXXX
XXXXX
=> fix #2600 add javadoc-plugin to dubbo-all module

.travis.yml
To fix issue 2605 by removing jdk9 from .travis.yml.
commit 99babae7ff6e947059fee14cc2425aead46e6be8 (HEAD -> remove-javatr 
avis-issue-2605, origin/remove-java9-travis-issue-2605)                
Author: devbox <cbolgiano625@gmail.com>                                
Date:   Mon Oct 8 10:38:47 2018 -0400                                  
Removed jdk9 from .travis.yml.
I do not have a local copy of travis ci.  I can add the results from travis ci as a comment in the PR after it is created.
^No tests written for this small contribution.
^ both tasks fail on branch 2.6.x 
^ This is a small contribution.
=> Dubbo-2605 Removed java9 from .travis.yml

dubbo-common/src/main/java/com/alibaba/dubbo/common/status/support/LoadStatusChecker.java
fix #1641, support get system load on windows.
XXXXX
XXXXX
=> fix #1641, support get system load on windows.

dubbo-common/src/main/java/org/apache/dubbo/common/status/support/LoadStatusChecker.java
fix #1641, support get system load on windows
XXXXX
XXXXX
=> fix #1641, support get system load on windows

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/initializer/DubboContextListener.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/web-fragment.xml, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/initializer/DubboApplicationContextInitializerTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/status/DataSourceStatusCheckerTest.java
…pring framework is absent
a prototype for issue #2570
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/initializer/DubboContextListener.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/web-fragment.xml
XXXXX
=> prototype for issue2570

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/transport/codec/DeprecatedExchangeCodec.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
supplemental change for issue#1903
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/CodecSupport.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/transport/codec/DeprecatedExchangeCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
=> supplemental change for issue#1903

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/protocol/AbstractInvoker.java
issue#20:  merge fix from 2.7.0 to 2.6.x
dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/protocol/AbstractInvoker.java
XXXXX
=> merge fix from 2.7.0 to 2.6.x

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/StickyTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/loadbalance/LoadBalanceTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java
The `Round Robin` balancer is not smooth with weights, such as:
A:B:C = 1:2:3
Will be:
[A, B, B, C, C, C,           A, B, B, C, C, C,         A, B, B, C, C, C,     ..........]
But we want it to be:
[A, B, C, B, C, C,           A, B, C, B, C, C,         A, B, C, B, C, C,     ..........]
which has been discuss before for performance: #2578 
reimplement `RoundRobinLoadBalance` and its unit test.
We will get more strictly balance result in unit test.
=> [Dubbo-2578]Smooth Round Robin selection

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java
Remove author info from RoundRobinLoadBalance
=> [Dubbo-2578]Remove author info

CHANGES.md
add 2.6.5 release note
edit changs.md, add 2.6.5 release note
=> release 2.6.5

dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/DisableInject.java, dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/ExtensionLoader.java, dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/Inject.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/extensionloader/ExtensionLoaderTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/extensionloader/injection/InjectExt.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/extensionloader/injection/impl/InjectExtImpl.java, dubbo-common/src/test/resources/META-INF/dubbo/internal/com.alibaba.dubbo.common.extensionloader.injection.InjectExt, dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/extension/SpringExtensionFactory.java
Fix problem reported in https://github.com/apache/incubator-skywalking/issues/1769
* Add Inject annotation
* Printing log instead of throwing Exception in SpringExtensionFactory
ExtensionLoaderTest.testInjectExtension
=> [Dubbo-2678] Add ability to turn off SPI auto injection, special support for Object type.

dubbo-common/src/main/java/org/apache/dubbo/common/extension/DisableInject.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/Inject.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/injection/InjectExt.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/injection/impl/InjectExtImpl.java, dubbo-common/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.common.extension.injection.InjectExt, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java
Fix problem reported in https://github.com/apache/incubator-skywalking/issues/1769
* Add Inject annotation
* Printing log instead of throwing Exception in SpringExtensionFactory
ExtensionLoaderTest.testInjectExtension
=> [Dubbo-2678][For Master] Add ability to turn off SPI auto injection, special support for Object type. 

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
enhance comments for ServiceBean
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
XXXXX
=> enhance comments

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServerHandler.java
XXXXX
1. org.apache.dubbo.remoting.transport.netty4.NettyServerHandler
=> [Dubbo- typo]fix typo

dubbo-plugin/dubbo-qos/src/main/java/com/alibaba/dubbo/qos/protocol/QosProtocolWrapper.java
fix #2762
dubbo-plugin/dubbo-qos/src/main/java/com/alibaba/dubbo/qos/protocol/QosProtocolWrapper.java
XXXXX
=> [DUBBO-2762]: [Dubbo - qos-http] stopServer should be invoked ?

README.md
update readme for oscine vote.
=> oschina vote

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java, dubbo-common/src/main/java/org/apache/dubbo/common/config/Configuration.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java, dubbo-configcenter/dubbo-configcenter-api/pom.xml, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/AbstractDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigChangeEvent.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigChangeType.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigType.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigurationListener.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigurationUtils.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigurationWrapper.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/DynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/support/nop/NopDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/archaius/ArchaiusDynamicConfiguration.java, dubbo-container/dubbo-container-log4j/src/main/java/org/apache/dubbo/container/log4j/Log4jContainer.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
code review and refactor for dubbo-configcenter
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/Configuration.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java
dubbo-configcenter/dubbo-configcenter-api/pom.xml
dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/AbstractDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigChangeEvent.java
dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigChangeType.java
dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigType.java …
=> code review and refactor for dubbo-configcenter

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigurationListener.java, dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/archaius/ArchaiusDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/archaius/sources/ZooKeeperConfigurationSource.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
Code review for dubbo-configcenter, focus on reformat
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/archaius/ArchaiusDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/archaius/sources/ZooKeeperConfigurationSource.java
XXXXX
=> Code review for dubbo-configcente

dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/ConfigurationUtils.java, dubbo-container/dubbo-container-log4j/src/main/java/org/apache/dubbo/container/log4j/Log4jContainer.java
Code review for ConfigurationUtils and Environment
XXXXX
XXXXX
=> Code review for ConfigurationUtils and Environment

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java
Fix #2845 
XXXXX
```
./mvnw clean package -DskipTests
./mvnw test -pl dubbo-cluster -Dtest=org.apache.dubbo.rpc.cluster.loadbalance.RoundRobinLoadBalanceTest
```
=> [Dubbo-2845] Fix OOM in UT testSelectByWeight

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java
fixed type of variable
rename "copyinvokers" into "copyInvokers" in java code
XXXXX
=> fixed typo of variable

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
Today，I find that ，if a provider do not has the method ，consumer also can  find the invoker list，
but，when it call it，the provider will throw the exception ” can not find the method“， so I think the code I have deleted is unnessesary。 It should throw exception in consumer side。
delete  code in  RegistryDirectory#doList
=> Remove unnessesary code  in RegistryDirectory#doList

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouterTest.java
add ScriptRouter test case
/dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouterTest.java
add test testRouteHostFilter and testRoute_throwException, all of them passed
=> add some ScriptRoute test case

dubbo-common/src/test/java/org/apache/dubbo/common/concurrent/CompletableFutureTaskTest.java
disable org.apache.dubbo.common.concurrent.CompletableFutureTaskTest#testCustomExecutor
XXXXX
XXXXX
=> enhance unit test

dubbo-common/src/test/java/org/apache/dubbo/common/concurrent/CompletableFutureTaskTest.java
fix https://github.com/apache/incubator-dubbo/issues/2899
=> fix CompletableFutureTaskTest#testCustomExecutor

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
=> Remove the log to putRandomPort when one protocol use random port

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java
Fix https://github.com/apache/incubator-dubbo/issues/71;
If shutdownHook has registered  in jvm , we should remove it when the jvm is shutting down。
XXXXX
=>  Fix DubboShutdownHook Memory Leak

dubbo-common/src/test/java/org/apache/dubbo/common/concurrent/CompletableFutureTaskTest.java
re-enable testCustomExecutor 
update UT
=> re-enable testCustomExecutor 

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java
enhance org.apache.dubbo.rpc.protocol.dubbo.telnet.InvokeTelnetHandler#isMatch, a follow up of #2803. 
It is unnecessary to call CompatibleTypeUtils.compatibleTypeConvert(arg, type) since PojoUtils.realize() will cover it.
XXXXX
=> enhance org.apache.dubbo.rpc.protocol.dubbo.telnet.InvokeTelnetHandler#isMatch

dubbo-common/src/main/java/org/apache/dubbo/common/json/GenericJSONConverter.java, dubbo-common/src/test/java/org/apache/dubbo/common/concurrent/CompletableFutureTaskTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/concurrent/ExecutionListTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalTest.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/zkclient/ZkclientZookeeperClient.java, dubbo-rpc/dubbo-rpc-rmi/src/main/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocol.java
=> Replace anonymous class with method reference

README.md
=> fixed involve

PULL_REQUEST_TEMPLATE.md
correct the maven cmd, otherwise it will skip test
PULL_REQUEST_TEMPLATE.md
=> should not skipTests

README.md
=> update dependencies in readme

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ActiveLimitFilterTest.java
make count work again when max <= 0
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java
=> [DUBBO-3023]: problem in ActiveLimitFilter

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java
Only change FailbackClusterInvoker$RetryTimerTask, code Optimization,only save lastInvoker.
=> FailbackClusterInvoker code Optimization

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ApplicationConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java, dubbo-demo/dubbo-demo-consumer/src/main/resources/META-INF/spring/dubbo-demo-consumer.xml, dubbo-demo/dubbo-demo-provider/src/main/resources/META-INF/spring/dubbo-demo-provider.xml
Fix spring doesn't allow setter override.
changes STH. like` setRegistry(registryLiteral)` to `setReistryIds(registryIds)`;
XXXXX
=> Fix spring doesn't allow setter override.

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
=> correct spelling error

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
=> avoid duplicated refresh for application

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
fix wrong word spelling
org.apache.dubbo.config.AbstractInterfaceConfig
XXXXX
=> fix wrong word spelling

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperTransporter.java, dubbo-remoting/dubbo-remoting-zookeeper/src/test/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperTransporterTest.java
2.7.0 , just rename some method and modify commments, import order
=> 2.7.0 , just rename some method and modify commments, import order

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
fix provicer --> provider
org.apache.dubbo.config.AbstractInterfaceConfig
XXXXX
=>  fix provicer --> provider

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Protocol.java
Make sure 2.7.0 can work with old `com.alibaba.xxx.Protocol` extension.
Add `com.alibaba.xxx.Protocol`
=> Add compatible Protocol definition

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java
remove getContext()
XXXXX
XXXXX
=> remove getContext()

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
1.Move the iteration of methods of a service config to the if block of the class have method declared not by Object
2.remove some useless parameter type
XXXXX
XXXXX
=> [Code Optimize]Optimize code of wrap a service bean

CHANGES.md
Change from `Dubbo` to `dubbo`
=> Fix typo in 2.7.0 CHANGES file

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ConfigCenterBean.java
=> remove not used import

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ConfigCenterBean.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java
=> remove unused import

dubbo-dependencies-bom/pom.xml, dubbo-metadata-report/dubbo-metadata-report-api/pom.xml
- fix duplicated maven dependency entry
- fix parent.relativePath in pom.xml
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.apache.dubbo:dubbo-dependencies-bom:pom:2.7.1-SNAPSHOT
[WARNING] 'parent.relativePath' of POM org.apache.dubbo:dubbo-dependencies-bom:2.7.1-SNAPSHOT (D:\incubator-dubbo\dubbo-dependencies-bom\pom.xml) points at org.apache.dubbo:dubbo-parent instead of org.apache:apache, please verify your project structure @ line 5, column 13
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.apache.dubbo:dubbo-metadata-report-api:jar:2.7.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.dubbo:dubbo-metadata-definition:jar -> …
```
=> Fix maven compile warning

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
fix a bug of service config that the change of protocol config 'register' cannot work on the config of dubbo service if the user does not config 'register' of dubbo service
XXXXX
XXXXX
=> fix a bug of service config

CONTRIBUTING.md
=> fix the typo of notification mail list address

dubbo-metadata-report/dubbo-metadata-report-api/src/test/java/org/apache/dubbo/metadata/store/test/JTestMetadataReport4Test.java, dubbo-metadata-report/dubbo-metadata-report-api/src/test/java/org/apache/dubbo/metadata/store/test/JTestMetadataReportFactory4Test.java
=> [Dubbo-3365]Fix compilation error fix #3365

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocol.java
Delete useless judgment.
Because
`URL tmpUrl = new URL("temp", "localhost", 0, map);`
`isJvmRefer = InjvmProtocol.getInjvmProtocol().isInjvmRefer(tmpUrl);`
XXXXX
XXXXX
=> Fix isInjvmRefer

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
=> simplify map empty judgment

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
follow up for #3376
XXXXX
XXXXX
=> follow up for #3376

README.md
=> [Dubbo-3347] Update package name in README file  fix#3347

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/override/OverrideConfigurator.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/override/OverrideConfiguratorFactory.java
modify class comment error in OverrideConfiguratorFactory and OverrideConfigurator
change AbsentConfigurator to OverrideConfigurator
=> modify class comment error

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java
=> Modify deprecated class to updated class in some comments

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java
1, remove priority field, the same as super class
2, remove getUrl method, the same as super class
3, refactor constructor, extract method: getRule, getEngine
4, refactor route, extract method: createBindings, getRoutedInvokers
XXXXX
XXXXX
XXXXX
=> refactor ScriptRouter:

pom.xml
This patch fixes issue #3186 
XXXXX
XXXXX
=> fixes #3186

pom.xml
Polish PR #3211 to finish pom.xml file clean up work
Close #3186
remove test profile
remove jvm permSize args
CI Pass
=> Polish pom.xml

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Response.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/transport/codec/DeprecatedExchangeCodec.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
error event of response (#3247)
XXXXX
XXXXX
=> event of response fix#3244

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyCodecAdapter.java
remove useless catch exception
remove useless catch exception
=> remove useless catch exception

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
remove duplicated import
remove duplicated import
XXXXX
=> remove duplicated import

dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyBackedChannelBuffer.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyBackedChannelBuffer.java
fix #2619: is there a problem in NettyBackedChannelBuffer.setBytes(...)?
XXXXX
XXXXX
=> fix #2619: is there a problem in NettyBackedChannelBuffer.setBytes(...)?

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
im not sure if is a bug
XXXXX
XXXXX
=> possibly bug fix

pom.xml
Apache parent pom version is updated to most recent one.
XXXXX
XXXXX
=> Apache parent pom version is updated to 21.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConsumerConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
Class comment error
Class comment  spelling mistakes with class ConsumerConfig
Class comment miss with class ConfigCenterConfig
Class comment error with class MetadataReportConfig
=> Class comment error

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
extract duplicated method calls to variable
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
XXXXX
=> [Enhancement]: extract duplicated method calls to variable

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
Fix typo `DOBBO` -> `DUBBO`
dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
XXXXX
=> [Enhancement]: fix typo

dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java
fix issue #1917: Condition is not properly used ?
XXXXX
XXXXX
=> fix issue #1917: Condition is not properly used ?

dubbo-dependencies-bom/pom.xml
=> bump up hessian-lite version #3423

dubbo-test/dubbo-test-examples/src/main/java/com/alibaba/dubbo/examples/redis/redis-consumer.xml
naming conventions
Same as the test case related field of memcached, recommend to fix
test case pass
=> revise the naming conventions of test case

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
avoid of using synchronized, instead, use ConcurrentMap's computeIfAbsent.
XXXXX
XXXXX
=> avoid of using synchronized.

dependencies-bom/pom.xml
=> update hessian-lite to 2.6.5

dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerMethodModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/model/ServiceMetadata.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ImplicitCallBackTest.java
make consumerModel's construct before refer
XXXXX
XXXXX
=> make consumerModel's construct before refer

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
=> fix issue #3533

dubbo-common/src/main/java/org/apache/dubbo/common/config/OrderedPropertiesProvider.java, dubbo-common/src/main/java/org/apache/dubbo/common/config/PropertiesConfiguration.java, dubbo-common/src/test/java/org/apache/dubbo/common/config/MockOrderedPropertiesProvider1.java, dubbo-common/src/test/java/org/apache/dubbo/common/config/MockOrderedPropertiesProvider2.java, dubbo-common/src/test/java/org/apache/dubbo/common/config/PropertiesConfigurationTest.java, dubbo-common/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.common.config.OrderedPropertiesProvider, dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/DynamicConfiguration.java
allow the properties config to be extend 
XXXXX
XXXXX
=> allow the properties config to be extend 

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
=> [Dubbo-3557] Fix NPE when package of interface is empty.

dubbo-common/src/main/java/org/apache/dubbo/common/timer/HashedWheelTimer.java
a more elegant way，higher efficiency。
no
yes
run the test case
=> a more elegant way

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
fix DubboCodec re-implements Codec2 #2977
XXXXX
XXXXX
=> fix DubboCodec re-implements Codec2 #2977

dubbo-container/dubbo-container-spring/src/main/java/org/apache/dubbo/container/spring/SpringContainer.java
=> [DUBBO-3476]: NullPointerException happened when using SpringContainer.getContext()

dubbo-rpc/dubbo-rpc-hessian/src/main/java/com/alibaba/dubbo/rpc/protocol/hessian/HessianProtocol.java, dubbo-rpc/dubbo-rpc-hessian/src/main/java/com/alibaba/dubbo/rpc/protocol/hessian/HttpClientConnectionFactory.java
Invalid use of BasicClientConnManager: connection still allocated #3243
XXXXX
XXXXX
=> [DUBBO-3243] Fix Invalid use of BasicClientConnManager: connection still allocated #3243

dubbo-dependencies-bom/pom.xml, dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml, dubbo-dependencies/pom.xml, pom.xml
introduce a convenient dependency for using zookeeper for #3426
XXXXX
XXXXX
=> introduce dubbo-dependencies-zookeeper

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/LogTelnetHandler.java, dubbo-rpc/dubbo-rpc-redis/src/main/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocol.java
Connections, streams, files, and other classes that implement the Closeable interface or its super-interface, AutoCloseable, needs to be closed after use.
Resources are closed properly.
XXXXX
=> Dubbo-3473 Fix Not Properly Closed Resources

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
=> typo for AccessLogFilter

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java
Refactoring that replaces snippets that refer to RpcStatus to "count" to improve the reading of the class 
ActivesLimitFilter.java
Fix #2984 
=> [Dubbo-2984] Refactoring ActivesLimitFilter (#2984)

pom.xml
workaround for issue #3646: javadoc lint issue
XXXXX
XXXXX
=> workaround for issue #3646: javadoc lint issue

dubbo-all/pom.xml
Fixes #3610.
Governance rule relies on this dependency to work.
XXXXX
XXXXX
=> [Dubbo-3610]make snakeyaml transitive, should we do this?

dubbo-distribution/src/assembly/bin-release.xml, dubbo-distribution/src/assembly/source-release.xml
=> change package name

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestProtocol.java
Null check before rest call.
getContextPath() in RestProtocol.
=> check null for path before call rest server

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboConfigBindingRegistrar.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboConfigConfigurationRegistrar.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubbo.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboConfig.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/config/DubboConfigBeanCustomizer.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/config/NamePropertyDefaultValueDubboConfigBeanCustomizer.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/SpringStatusChecker.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotationPropertyValuesAdapterTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigBindingBeanPostProcessorTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilderTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboConfigTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/provider/DemoServiceImpl.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/context/annotation/EnableDubboConfigTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/status/SpringStatusCheckerTest.java, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/config.properties
- Simplify externalized configuration of Dubbo Protocol name: #3189
=> Enhancement and Bugfix in 2.7.1 ( Part 2 )

dubbo-configcenter/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfiguration.java
support deleted and added event type.
XXXXX
XXXXX
=> enhance event type for consul configuration support

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/AbstractMonitorFactory.java, dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/DubboMonitorTest.java
Fix issue #3657 
AbstractMonitorFactoryTest.java
DubboMonitorTest.java
A : Because If I  PR them separately, it's possible that my PR may fail since the github CI may fail.
run `testMonitorFactoryGroupCache()` or `DubboMonitorTest.testCount()` many times
=> [Dubbo-3657] Fix junit test failed

dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java
Fix #3684 
Improve the checking of lease id
UT passed
=> [Dubbo-3684] Improve the checking of lease id

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java
=> [Dubbo-3682]Correct @Parameter config of field of ConfigCenterConfig

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
fix #3678 
call signalAll instead of singal
XXXXX
=> [Dubbo-3678] fix 3678

dubbo-configcenter/dubbo-configcenter-etcd/pom.xml
Remove extra tags #3741 
XXXXX
XXXXX
=> [Dubbo-3741]Remove extra tags

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/handler/QosProcessHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatHandler.java
=> format code

dubbo-bom/pom.xml, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/dump.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/restart.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/server.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.bat, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/stop.sh
add ASF license header #3721
XXXXX
XXXXX
=> add ASF license header #3721

README.md
Add building instruction to README
Add building instruction to README
Verified locally
=> Add building instruction to README

bom/pom.xml, dependencies-bom/pom.xml, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/dump.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/restart.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/server.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.bat, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh, dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/stop.sh, dubbo-test/dubbo-test-benchmark/src/main/resources/run.bat, dubbo-test/dubbo-test-benchmark/src/main/resources/run.sh, dubbo-test/dubbo-test-benchmark/src/test/resources/server/dubborpcserver.sh, dubbo-test/dubbo-test-benchmark/src/test/resources/server/dubboserver.sh, dubbo-test/dubbo-test-benchmark/src/test/resources/server/servercommon.sh
branch 2.6.x add ASF fheader #3721
XXXXX
XXXXX
=> branch 2.6.x add ASF fheader #3721

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistryFactory.java
remove duplicate code
XXXXX
XXXXX
=> remove duplicate code

dubbo-dependencies-bom/pom.xml, dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/store/MetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-consul/src/main/java/org/apache/dubbo/metadata/store/consul/ConsulMetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java, dubbo-test/dubbo-test-compatibility/dubbo-test-spring3/pom.xml, dubbo-test/dubbo-test-compatibility/pom.xml, dubbo-test/dubbo-test-integration/pom.xml, dubbo-test/pom.xml
=> [Dubbo-3812] fixed some small problems

dubbo-registry/dubbo-registry-nacos/pom.xml
Fix #3804 
Update nacos client to 1.0.0-RC3
Run `mvn license:add-third-party -Dlicense.useMissingFile` and make sure the following dependency is gone.
```
<dependency>
<groupId>org.codehaus.jackson</groupId>
<artifactId>jackson-mapper-lgpl</artifactId>
</dependency>
```
=> [Dubbo-3804] Update nacos client to 1.0.0-RC3

README.md
add type=pom for zookeeper dependencies.
XXXXX
XXXXX
=> correct maven dependencies configuration

dubbo-common/src/main/java/org/apache/dubbo/common/extension/Adaptive.java
Fix javadoc for Adaptive.value()
XXXXX
XXXXX
=> Fix javadoc for Adaptive.value()

.gitignore
ignore flatten related files.
XXXXX
XXXXX
=> ignore flatten related files.

dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java
do not filter thread pool
XXXXX
XXXXX
=> do not filter thread pool by port

README.md
Add Erlang language impementation  repository url.
=> Add Erlang Implementation

dubbo-all/pom.xml, dubbo-dependencies-bom/pom.xml, dubbo-distribution/pom.xml, dubbo-registry/dubbo-registry-nacos/pom.xml
fix #3797, also add other missing dependencies.
XXXXX
XXXXX
=> [DUBBO-3797]: dubbo-registry-nacos module is not bundled into Apache Dubbo 2.7.1

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
There is no need to use CopyOnWriteArrayList as a local variable.
XXXXX
XXXXX
=> change concurrent list  to regular list

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java
=> [DUBBO-3650]: Dubbo 2.7.0的provider无法指定客户端默认async

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/AbstractConfigurator.java
=> remove compatible key when merging #4059

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/common/Constants.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/MetricsConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/Constants.java, dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java, dubbo-monitor/dubbo-monitor-api/src/test/java/org/apache/dubbo/monitor/support/MonitorFilterTest.java, dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java, dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/MetricsFilterTest.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcConstants.java
issue #3137:  step4 - remove MonitorConstants
XXXXX
XXXXX
=> [DUBBO-3137]: step4 - remove MonitorConstants

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
same as #4040 to master
XXXXX
XXXXX
=> Shorten the life cycle of Timeout to get a better gc effect, same as #4040 to master

dubbo-configcenter/dubbo-configcenter-nacos/src/test/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfigurationTest.java, dubbo-metadata-report/dubbo-metadata-report-nacos/src/test/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReportTest.java
add some comments, fix this later when nacos support is ready
XXXXX
XXXXX
=> comment diabled nacos test

README.md
update erlang link
XXXXX
XXXXX
=> update erlang link

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
see https://github.com/apache/incubator-dubbo/pull/4129
XXXXX
XXXXX
=> optimze TimeTask in DefaultFuture

dubbo-rpc/dubbo-rpc-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
Remove useless filter declaration
XXXXX
XXXXX
=> Remove useless filter declaration

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java
the logger name was wrong
XXXXX
XXXXX
=> change logger name

dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/identifier/MetadataIdentifier.java, dubbo-metadata-report/dubbo-metadata-report-api/src/test/java/org/apache/dubbo/metadata/identifier/MetadataIdentifierTest.java
Fix #4147 
restore the metadata store key change
Local UT Passed.
=> [Dubbo-4147] restore the metadata store key change

dubbo-common/src/main/java/org/apache/dubbo/common/config/Configuration.java
delete the code that will never be reached
XXXXX
XXXXX
=> delete dead code

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/support/RpcUtils.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
avoid reflection on the critical path
XXXXX
XXXXX
=> performance tuning: avoid reflection on the critical path

dubbo-configcenter/dubbo-configcenter-api/src/main/java/org/apache/dubbo/configcenter/DynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-nacos/src/test/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfigurationTest.java, dubbo-metadata-report/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-nacos/src/test/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReportTest.java
Fix #4200 
Nacos group should be not resolved from key.
Verified locally.
=> [Dubbo-4200] Nacos group should be not resolved from key.

dubbo-rpc/dubbo-rpc-xml/src/main/java/org/apache/dubbo/xml/rpc/protocol/xmlrpc/XmlRpcProtocol.java
Standardized code
org.apache.dubbo.xml.rpc.protocol.xmlrpc.XmlRpcProtocol
Add @Override annotation
=> Standardized code

dubbo-rpc/dubbo-rpc-xml/src/main/java/org/apache/dubbo/xml/rpc/protocol/xmlrpc/XmlRpcProtocol.java
=> fix #4227 : remove duplicate @Override

dubbo-common/src/main/java/org/apache/dubbo/common/config/AbstractPrefixConfiguration.java
There is no need to invoke the Constructor Object()
XXXXX
XXXXX
=> delete useless code

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/main/java/org/apache/dubbo/common/URLBuilder.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
=> getMethodparameter refactor

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyChannel.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyCodecAdapter.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServerHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/RestProtocolTest.java
=> performance tuning: channel connect status

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/RestProtocolTest.java, dubbo-rpc/dubbo-rpc-thrift/src/test/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodecTest.java
=> performance tuning: cache service key

CHANGES.md, README.md, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/support/RpcUtils.java, dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-nacos/src/test/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfigurationTest.java, dubbo-dependencies-bom/pom.xml, dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml, dubbo-metadata-report/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java, dubbo-metadata-report/dubbo-metadata-report-nacos/src/test/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReportTest.java, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java, pom.xml
=> 2.7.2 release

Jenkinsfile, pom.xml
Add jenkinsfile for dubbo snapshot deployment
Currently existing job is configured by web ui, but it's better to use Jenkinsfile to make configuration more easy to modify. More information about Jenkinsfile, refer to https://jenkins.io/doc/book/pipeline/jenkinsfile/
The jenkins job every trigger by two conditions:
+ every two hour check git repo update, if it has new commit, will start
+ every 12 hours will run without commit check (in case first rule trigger build but travis still pending)
This job will do following step
+ check if current commit already deployed
+ check current commit status is pass (depends on travis CI result)
+ check current project is using snapshot version
+ do snapshot deployment
+ save current commit id
https://builds.apache.org/job/Apache%20Dubbo/job/apache-dubbo …
=> [CI] Add jenkinsfile for dubbo snapshot deployment

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/AddressListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
to make AddressListener provide more information
AddressListener notify method add registryDirectoryUrl parameter
=> improve:AddressListener notify method add registryDirectoryUrl parameter

dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/pom.xml, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/pom.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml
add zookeeper dependency on demo pom, so demo can easy
run only change zookeeper instead of multicast 
change demo-xml provider, consumer
demo-annotation provider and consumer pom
run zookeeper as registry correct
=> [dubbo_4350]add zookeeper maven dependency 

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/MethodConfig.java
Fix: @Method default value will be set to the field of MethodConfig 
XXXXX
XXXXX
=> [No issue] Fix: @Method default value will be set to the field of MethodConfig 

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Result.java, dubbo-monitor/dubbo-monitor-api/src/test/java/org/apache/dubbo/monitor/support/MonitorFilterTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Result.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolFilterWrapper.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ConsumerContextFilterTest.java
=> AsyncRpcResult should handle exception when registering callback.

dubbo-bom/pom.xml
=> format file: pom.xml of bom module

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ActiveLimitFilter.java
Signed-off-by: slievrly <slievrly@163.com>
synchronized local variables or parameters should be set to final
optimize synchronized obj
ci
=> synchronized local variables or parameters should be set to final

dubbo-bom/pom.xml
=> add dependency for #4408

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
fixes https://github.com/apache/dubbo/issues/4338
run https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-compatible
=> check complete status of async-result before try to update

dubbo-dependencies-bom/pom.xml
=> remove tomcat-embed-logging-juli #4400

.travis.yml
Remove oracle jdk
Remove oracle jdk
UT passed.
=> Remove oracle jdk

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java, dubbo-compatible/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java
=> RpcContext cannot getFuture after setFuture

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/FutureContext.java
fixes https://github.com/apache/dubbo/issues/4499
XXXXX
XXXXX
=> [Dubbo-4499] org.apache.dubbo.rpc.RpcContext.getFuture() cannot work in Filter.

dubbo-demo/README.md
Fix documentation error.
add -jar for java command
Review the document.
=> add -jar for java command

dubbo-dependencies-bom/pom.xml
Upgrade nacos-client dependency version to latest version
=> Upgrade nacos-client dependency version to 1.1.1

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java, dubbo-common/src/test/java/org/apache/dubbo/common/version/VersionTest.java
Fix #4551
eg. 2.6.2.1 can be recognized lower than 2.6.3
=> Optimize Version#isRelease263OrHigher check (#4551)

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
=> single variable name should be singular

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java
which introduced by #4038
XXXXX
XXXXX
XXXXX
=> Fix bug #4374 for AccessLogFilter not working

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/handler/ConnectChannelHandlerTest.java
disable future timeout tests since it breaks travis CI
XXXXX
XXXXX
=> disable future timeout tests since it breaks travis CI

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java, dubbo-common/src/test/java/org/apache/dubbo/common/version/VersionTest.java
=> Make code strong, version check compatibility. Same change as https://github.com/apache/dubbo/pull/4488

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
fix #4328
add unit-test PojoUtilsTest.testIntToBoolean
=> fix issue 4328, fix PojoUtils realize issue #4334

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
https://github.com/apache/dubbo/issues/4569
XXXXX
XXXXX
=> [dubbo_4569]optimized code(#4569)

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/RegistryConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/RegistryConfigTest.java
https://github.com/apache/dubbo/issues/4337 
change setAddress
XXXXX
=> fixed registryConfig equals

dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClient.java
=> fix bug of Etcd3Registry cancel watch #4357

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/WrappedChannelHandler.java
remove getExecutorService method cexecutor local variables
=> 1. remove getExecutorService method cexecutor local variables

pom.xml
Signed-off-by: jimin.jm <slievrly@163.com>
add some files list exclude license check
mainly include some netty and edazdarevic files
add some files list exclude license check
ci
=> add some files list exclude license check

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/AnnotatedBeanDefinitionRegistryUtils.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContextImpl.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
=> Optimize part of the code in AnnotatedBeanDefinitionRegistryUtils.java

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
ReferenceConfig and ServiceConfig can get ServiceMetadata
improve:ReferenceConfig and ServiceConfig add getServiceMetadata method
=> improve:ReferenceConfig and ServiceConfig add getServiceMetadata method

dependencies-bom/pom.xml
upgrade fastjson to 1.2.58
https://github.com/apache/dubbo/issues/4623
=> Consider to upgrade to use fastjson 1.2.58 for 2.6.x

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java, dubbo-common/src/test/java/org/apache/dubbo/common/bytecode/ProxyTest.java
=> [Dubbo-4647] The compilation of static methods should be excluded when generating the proxy

dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/src/main/java/org/apache/dubbo/demo/consumer/comp/DemoServiceComponent.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/src/main/java/org/apache/dubbo/demo/provider/DemoServiceImpl.java, dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java, dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/resources/spring/dubbo-consumer.xml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml
=> keep demo simple, and switch to use zookeeper as registry center

.travis.yml
=> try to shorten maven output to make travis build pass

.gitignore, licenseCheck.sh
Improve license check script
1. Fix unexpected file like `license-list.txt-e` generated by sed, make sure it works both under MacOS and Linux.
2. Add some library to white list, some of the licenses are tricky to decide whether it is compatible because of the versions, so I add the library to white list.
3. remove the extra new lines generated, make it clearer.
Passed my local test.
=> Improve license check script

licenseCheck.sh
1. When we check a candidate of source release, there is no maven wrapper.
2. Filter the result if a dependency does not have any dependencies.
XXXXX
Pass local test.
=> Polish license check script

dubbo-metadata-report/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
=> fetch password value from the url #4747

dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java
fix #4309: use consul with group and version
XXXXX
XXXXX
=> issue#4309: use consul with group and version

dubbo-metadata-report/dubbo-metadata-report-api/src/main/java/org/apache/dubbo/metadata/integration/MetadataReportService.java
fix #4712
XXXXX
XXXXX
XXXXX
add Thread ContextClassLoader
=>  [dubbo-4712] add Thread ContextClassLoader

README.md
fix [issue#4788](https://github.com/apache/dubbo/issues/4788):Updated some links and sample code.
=> issue fixed for some error links in README.md #4788

dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryFactoryTest.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandlerTest.java, dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/integration/swagger/DubboSwaggerApiListingResourceTest.java, dubbo-serialization/dubbo-serialization-gson/src/test/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectOutputTest.java
use correct import statement instead of import *;
XXXXX
XXXXX
=> DUBBO-cleanup: use correct import

dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/utils/AbstractKryoFactory.java
=> issue #4238: provider服务端配置serialization="kryo"自定义异常类抛错时消费端捕获不到

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/DataSourceStatusChecker.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/SpringStatusChecker.java
1. 判断字符串为空改为使用StringUtils
2. 将过多嵌套层次的if，循环改为使用卫语句
3. 增加使用lambda表达式和Optional代替for循环和判空
=> Optimize code of DubboBeanDefinitionParser.java

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/status/ThreadPoolStatusChecker.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/ChangeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/CountTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/InvokeTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/LogTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/telnet/PortTelnetHandler.java
Optimize StringBuilder#append.
=> Optimize StringBuilder#append

.mvn/wrapper/maven-wrapper.properties, .travis.yml
=> optmize maven output when run with travis

.travis.yml
=> travis config on 2.6.x

dubbo-metadata-report/dubbo-metadata-report-etcd/src/test/resources/testcontainers.properties
=> [Test] Disable docker environment check on setup

dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeStringWriter.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/TelnetUtils.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/logging/MessageFormatter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/AccessLogData.java, dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftUtils.java
Signed-off-by: slievrly <slievrly@163.com>
optimize: remove unnecessary String operations
optimize: remove unnecessary String operations
ci
=> optimize: remove unnecessary String operations

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/com/alibaba/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/com/alibaba/dubbo/remoting/zookeeper/zkclient/ZkclientZookeeperClient.java
add timeout config to zookeeper client  for  https://github.com/apache/dubbo/issues/4686
add timeout config to zookeeper client
XXXXX
=> Add timeout config to zookeeper client for 2.6.x

dubbo-metadata-report/dubbo-metadata-definition/src/main/java/org/apache/dubbo/metadata/definition/model/TypeDefinition.java
=> [DUBBO-4982] add the no-arguments construct for TypeDefinition #4982

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalanceTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvokerTest.java
=> Simplify some code where feasible

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceName.java
follow up for pr #4974: optimize imports and switch to use dubbo's StringUtils.
XXXXX
XXXXX
=> follow up for pr#4974

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/filter/CacheFilter.java
=> fix doc typo in CacheFilter.java

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/builders/AbstractReferenceBuilderTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
fixes #3629, #4926
related pr https://github.com/apache/dubbo/pull/4829
related commit 3f7430758f3a15e9b51fbdeaad7455be693579f4
XXXXX
XXXXX
=> fix set generic method error

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
=> revert #5072 by logging error msg.

dubbo-common/pom.xml, dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java, dubbo-rpc/dubbo-rpc-api/pom.xml, dubbo-serialization/dubbo-serialization-api/pom.xml, dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistry.java
remove unuseful dependencies.
dubbo-common/pom.xml
mvn clean compile
=> Simplify dubbo-common transitive dependencies

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/main/java/org/apache/dubbo/common/URLBuilder.java, dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
refactor some string operations with StringUtils
XXXXX
XXXXX
=> refactor some string operations with StringUtils

licenseCheck.sh
Add license for licenseCheck.sh
Fix #5118
Add license for licenseCheck.sh
see licenseCheck.sh
=> Add license for licenseCheck.sh

pom.xml
exclude .github folder for rat-plugin
add item in exclude list
CI pass
=> exclude .github folder for rat-plugin

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcInvocation.java
=> add back RpcInvocation

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java, dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyServer.java
=> netty3 backlog

dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyHandler.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServerHandler.java
=> [Dubbo-5170] add connected and disconnected log.

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/utils/LogUtils.java
For PR: #5255 , add license header for LogUtils.
=> add license header for LogUtils.

pom.xml
Fix ci
compiler is gradle project which we need more discuss for this one.
Currently it block CI, ignore it first
CI pass
=> ignore compiler for rat plugin

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/CommandHelper.java
CommandHelper class isn't formatted correctly, and looks like this util class need its ctor privatized 
1.Reformat the CommandHelper class 
2.Add private constructor to this class 
should not bring any side effect
=> Clean up CommandHelper class and add its private ctor

dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/Serialization.java
=> [Dubbo-5200] fix javadoc for Serialization.getContentTypeId

dubbo-dependencies-bom/pom.xml
reslove project maven dependency issue;
Now in the maven Central Repository doesn't has alibaba_spring_context_support 1.0.4-SNAPSHOT dependency,  so we need update alibaba_spring_context_support_version to 1.0.5 to reslove maven dependency issue;
=> [ISSURE] update alibaba_spring_context_support_version to 1.0.5

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/nop/NopDynamicConfiguration.java
fix typo: config centre -> config center
fix typo: config centre -> config center
only log and comments have been changed.
=> [dubbo-common] fix: typo #5445

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
=> [Dubbo Config]Remove redundant judgment

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java, dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceDescriptor.java, dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceRepository.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/StringUtilsTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/UrlUtilsTest.java, dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
* Reduce object allocation:
- Reduce `Iterator` instance allocation when get `MethodDescriptor` in `ServiceDescriptor`.
- Reduce `StringBuilder` instance allocation  and memory copy in `DecodeableRpcResult.decode()` and `DubboMonitor.send()`.
* Optimizing `String` usage for `URL` and `UrlUtils`.
* Use `Map<String, List<MethodDescriptor>>` rather than `Map<String, Set<MethodDescriptor>>` to store `methods`
* Add `Logger.isDebugEnabled()` before invoke `Logger.debug()` in `DecodeableRpcResult.decode()`
* Use `String.indexOf(char)` instead of `String.indexOf(String)` for single character string.
* Use `String.indexOf(char)` instead of `String.contains(String)` for single character string.
XXXXX
=> [Dubbo-Optimize] Simple performance optimization

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/GenericFilter.java
=> [Dubbo-5389] fix null attachment issue when consumer use generic

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
fix https://github.com/apache/dubbo/issues/4863
XXXXX
XXXXX
=> [Dubbo-4863] add switch of generic invocation with class info

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/com/alibaba/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/com/alibaba/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/com/alibaba/dubbo/remoting/zookeeper/zkclient/ZkclientZookeeperClient.java
refer to https://github.com/apache/dubbo/issues/4828
=> dubbo zookeeper registry too slow

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/javassist/JavassistProxyFactory.java
=> fix-typo-5466

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
=> fix typo:warped

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> code optimization: iniFrameworkExts

dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
=> fix typo:fro

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
Avoid map instance recreation.
=> fix potential performance drop of URL operations introduced in #4310

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java, dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
=> Fix multi protocol does not work when referencing in ProviderConfig

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
Fixes https://github.com/apache/dubbo/issues/5289
=> protocols/protocolIds and registries/registryIds, make sure only one can work.

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java
=> Fix some typos

dubbo-rpc/dubbo-rpc-http/src/main/java/org/apache/dubbo/rpc/protocol/http/HttpProtocol.java, dubbo-rpc/dubbo-rpc-http/src/main/java/org/apache/dubbo/rpc/protocol/http/HttpProtocolErrorCode.java
When a dubbo method call throw an custom exception, eg MyBizException, http protocol will output something like:
```
{"jsonrpc":"2.0","id":"1","error":{"code":0,"message":"This is custom Msg: Wrong Param","data":{"exceptionTypeName":"com.demo.exception.MyBizException","message":"This is custom Msg: Wrong Param"}}}
``` 
I can't specific the error.code value, it is always zero. So I open this pull request to custom exception error code.
add support: Custom exception error code for http protocol
1. create an example dubbo project, throw an exception which implements HttpProtocolErrorCode which return an error code like 80024
2. invoke dubbo by postman, assert the error.code value is 80024 as you set at the first step.
Follow this checklist to help us incorporate your contribution quickly and …
=> support : Custom exception error code for http protocol #5408

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
`JValidator#isPrimitives` is the same as `ReflectUtils#isPrimitives` , so use `ReflectUtils#isPrimitives` instead of `JValidator#isPrimitives`
`org.apache.dubbo.validation.support.jvalidation.JValidator`
pass the `JValidatorTest`
=> Use ReflectUtils#isPrimitives instead of JValidator#isPrimitives

dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcInvoker.java, dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcProtocol.java, dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/ReferenceCountManagedChannel.java
=> Fixes #5511, gRPC client does not update channel status accordingly as server instance status change.

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
Reduce object allocation for `URL.getAddress()`.
* Add `address` field for `URL.java`.
* Clean code.
XXXXX
=> [Dubbo-perf]: Reduce object allocation for URL.getAddress()

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
fixes https://github.com/apache/dubbo/issues/4992
=> Fix netutils log endless recursive

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
HEATBEAT_CHECK_TICK  ==》 HEARTBEAT_CHECK_TICK
XXXXX
XXXXX
=> fix typo:HEATBEAT_CHECK_TICK

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
fixes https://github.com/apache/dubbo/issues/5276
=> fix configcenter use registry timeout value.

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
Simplify collect body to make it more readable.
XXXXX
XXXXX
=> Simplify collect body by using a helper method

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/ListenableFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolFilterWrapper.java
Call Filter.onResponse on AppResponse returns.
=> call Filter.onResponse for backward compatibility.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/interceptor/ClusterInterceptor.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/interceptor/ConsumerContextClusterInterceptor.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/AbstractCluster.java
make sure the interface definition consistent with FIlter.Listener
=> Rename onReponse in ClusterInterceptor.Listener to onMessage

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/RegistryBuilder.java
paramter ==》 parameter
XXXXX
XXXXX
=> Fix typo: paramter

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/ThreadlessExecutor.java
fix ThreadlessExecutor doc comment
In the comment should be thread call this method, not thead.
XXXXX
=> fix ThreadlessExecutor doc comment

dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdServiceDiscovery.java
remove unused variable  (Issue #5537 )
remove unused variable from EtcdServiceDiscovery
XXXXX
=> [Dubbo-5537] remove unused variable in EtcdServiceDiscovery

dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
Code Refactoring 
a collection or map whose contents are never queried or accessed is useless are removed. 
Files Changed 
- DubboProtocol.java
- JdkCompiler.java
Container contents that are never accessed are removed from the source code
Build and Tested
=> [Dubbo-5554] Code Refactoring for Container contents that are never accessed #5554

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/CacheableRouterFactory.java
=> [Dubbo-5468] fix duplicate code in CacheableRouterFactory

dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistry.java, dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializationOptimizer.java, dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistryTest.java
Fix generic non-standard tips in idea
1.dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistry.java
2.dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializationOptimizer.java
3.dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistryTest.java
=> optimize : fix generic specification tips

dubbo-common/src/main/java/org/apache/dubbo/common/utils/IOUtils.java
optimize IOUtils.java "try" to "try resource"
1.dubbo-common/src/main/java/org/apache/dubbo/common/utils/IOUtils.java
=> optimize : optimize IOUtils.java "try" to "try resource"

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java
[https://github.com/apache/dubbo/blob/3211a1f9e10969c48d0193aac5825208a33296bf/dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java#L175](https://github.com/apache/dubbo/blob/3211a1f9e10969c48d0193aac5825208a33296bf/dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java#L175)
metodName ==> methodName
XXXXX
XXXXX
=> fix typo:metodName

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
Use more readable collection judgment methods
1.dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
=> optimize : modify collection judgment method

README.md
update  README.md DubboSamples url 
1. `dubbo-sample-api`  change url from 
> https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-api  
to 
> https://github.com/apache/dubbo-samples/tree/master/ **java** /dubbo-samples-api 
2. 
> cd dubbo-samples/ **java** /dubbo-samples-api
3.  `dubbo-sample-api` `README.md` change url from 
> https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-api/README.md
to
> https://github.com/apache/dubbo-samples/tree/master/ **java** /dubbo-samples-api/README.md
XXXXX
=> optimize : update README.md DubboSamples url

.travis.yml, dubbo-configcenter/dubbo-configcenter-etcd/pom.xml, dubbo-metadata/dubbo-metadata-report-etcd/pom.xml, dubbo-registry/dubbo-registry-consul/pom.xml, dubbo-remoting/dubbo-remoting-etcd3/pom.xml
=> [Dubbo-5421] skip integration test by default

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandlerTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/Constants.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java
allow AsyncMethodInfo on Invocation to override the configured AsyncMethodInfo, to give user a chance to change AsyncMethodInfo on the fly.
XXXXX
XXXXX
=> allow user to pass AsyncMethodInfo at runtime.

dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java
fix wrong comments
fix wrong comments in org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator
=> [Dubbo-5676] fix wrong comments

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ReferenceConfig.java
Allows you to customize registry load policies
=> Allows you to customize registry load policies

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
=> set replaced lazy client to available

dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh
switching cms collector to g1 https://github.com/apache/dubbo/issues/5668
XXXXX
XXXXX
=> switching cms collector to g1

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java, dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> [Dubbo-5633] fixes Provider and Consumer default config do not work

dubbo-common/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
fix #5322 
1.add `port` attribute in ConfigCenterConfig
2.When using zookeeper and ConfigCenterConfig is null, set port attribute.
3.When setting `address` attribute, set the relevant properties like `RegistryConfig`
```
if (address != null) {
try {
URL url = URL.valueOf(address);
setUsername(url.getUsername());
setPassword(url.getPassword());
updateIdIfAbsent(url.getProtocol());
updateProtocolIfAbsent(url.getProtocol());
updatePortIfAbsent(url.getPort());
updateParameters(url.getParameters());
} catch (Exception ignored) {
}
}
```
=> [dubbo-5322]When using zookeeper and ConfigCenterConfig is null,don't set port attribute.

dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulServiceDiscovery.java, dubbo-registry/dubbo-registry-consul/src/test/java/org/apache/dubbo/registry/consul/ConsulServiceDiscoveryTest.java
complete the unit test for consul service discovery module.
XXXXX
XXXXX
=> add consul service discovery test

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/AbstractConfigurator.java
optimize document specifications
1.dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/AbstractConfigurator.java
=> optimize : optimize document specifications

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
Use faster indexOf method
1.dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java
=> optimize : put single-quotes around ':' to use the faster "indexOf(char)" method.

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java
#2992 
1.dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java
Passed unit test
=> [Dubbo-2992] enhance the java doc of dubbo-common module.

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java
Alternative of https://github.com/apache/dubbo/pull/5482
=> fix monitor filter: consumer side elapsed time is negative

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryFactoryTest.java
Fix https://github.com/apache/dubbo/issues/5483
Remove registry from factory that already destroyed.
@chickenlj @qinliujie 
XXXXX
XXXXX
=> Remove registry from factory that already destroyed. #5483

dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
* ServiceBean
publish `ServiceBeanExportedEvent` and `ServiceConfigExportedEvent`
* ServiceConfig
publish `ServiceConfigExportedEvent`
=> publish event when exported.

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
Fix [issue#5446](https://github.com/apache/dubbo/issues/5446)  
I think using bean from spring instead of ref object  for injection can better supports AOP or other extended operations
**org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor**
pass **ReferenceAnnotationBeanPostProcessorTest**
=> [Dubbo-5446] fix aop issue with @Reference

dubbo-config/dubbo-config-spring/pom.xml, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java, dubbo-dependencies-bom/pom.xml
[Dubbo-5446] fix aop issue with @Reference #5454
https://github.com/apache/dubbo/issues/5446
=> Polish /apache/dubbo#5446 : With @Reference, Aop does not work

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/SelectTelnetHandler.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/InvokerTelnetHandlerTest.java
fix the issue #5707
use `Integer.parseInt(message) - 1`
=> fix #5707,SelectTelnetHandler choose error method

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java
=> [Dubbo-5606] Fix RpcContext.asyncCall return when throw RpcException

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java
=> fix:Remove unused variable parameters in AbstractProxyInvoker

dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java
``defaultProtocol`` won't be empty, because of [this](https://github.com/GungnirLaevatain/dubbo/blob/3b5dc6e53b04d313611ed907c0ba270f6ff06444/dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java#L89)
``org.apache.dubbo.common.utils.UrlUtils``
=> remove duplicate code in UrlUtils#parseURL

dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java
#2992 
1.dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java
=> [Dubbo-2992] enhance the java doc of dubbo-common module. 

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Directory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/StickyTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailSafeClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvokerTest.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvokerTest.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java, dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryDirectoryTest.java
Fixes #5684 and #5654
Multi registry load balance does not work.
=> Fixes multi-registry subscription loadbalance strategy does not work properly.

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
Comments in code blocks should be multi-line comments, not documentation comments
1.dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
=> Fix document comments in code blocks to multi-line comments

dubbo-rpc/dubbo-rpc-rmi/src/main/java/com/alibaba/dubbo/rpc/protocol/rmi/RmiRemoteInvocation.java
#3001 
1.dubbo-rpc/dubbo-rpc-rmi/src/main/java/com/alibaba/dubbo/rpc/protocol/rmi/RmiRemoteInvocation.java
=> [Dubbo-3001] enhance the java doc of dubbo-rpc module.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
=> NullPointerException fix

SECURITY.md, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSON.java, dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java, dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceDescriptor.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/MetadataReportBuilder.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboBeanUtils.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/RemoteWritableMetadataService.java, dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/AccessKeyAuthenticator.java, dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/Constants.java, dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/DefaultAccessKeyStorage.java, dubbo-plugin/dubbo-auth/src/test/java/org/apache/dubbo/auth/AccessKeyAuthenticatorTest.java, dubbo-plugin/dubbo-auth/src/test/java/org/apache/dubbo/auth/filter/ProviderAuthFilterTest.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/EventPublishingServiceDiscovery.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/SubscribedURLsSynthesizer.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/EtcdClient.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java, dubbo-remoting/dubbo-remoting-mina/src/main/java/org/apache/dubbo/remoting/transport/mina/MinaClient.java, dubbo-rpc/dubbo-rpc-native-thrift/src/test/idls/DemoService.thrift
fix some spelling incorrect
XXXXX
XXXXX
=> fix: spelling incorrect

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/CompatibleTypeUtilsTest.java
=> [Dubbo-4697] Fix PojoUtils support localdatetime,lcaldate,localtime

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/service/GenericException.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/GenericImplFilterTest.java
=> GenericException compatible with 2.6.x or lower version

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> fix config-center configured in dubbo.properties does not work.

dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcInvoker.java
fix Duplicate condition in 'if' statement inspection
[https://github.com/apache/dubbo/blob/0f4e60dca31737ea905306b1c4a3cce399536db9/dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcInvoker.java#L99-L103](https://github.com/apache/dubbo/blob/0f4e60dca31737ea905306b1c4a3cce399536db9/dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcInvoker.java#L99-L103)
XXXXX
XXXXX
=> Duplicate condition in 'if' statement inspection

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> [Dubbo-5813]prevent destroyAll method of DubboShutdownHook being invoked twice when using Spring

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> Revert "[Dubbo-5813]prevent destroyAll method of DubboShutdownHook being invoked twice when using Spring"

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> Fix destroyAll called twice

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java
=> callback onError

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/CountTelnetHandler.java
extracting duplicate code in CountTelnetHandler
=> extracting duplicate code in CountTelnetHandler

dubbo-metadata/dubbo-metadata-report-nacos/src/test/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReportTest.java
Add test case for NacosMetadataReport
1. Add test cases for  "doSaveMetadata","removeServiceMetadata","doGetExportedURLs","doSaveSubscriberData"
2. Modify codes in NacosMetadataReportTest
1. All test cases pass for NacosMetadataReportTest
=> Add test cases for NacosMetadataReport

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
=> polish code of DubboShutdownHook

dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClient.java
fix typo
fix typo in ``org.apache.dubbo.remoting.etcd.jetcd.JEtcdClient``
=> fix typo in JEtcdClient

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java
Follow up of (#5686), call getConsumerUrl.
=> Fix merge does not work.

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
Fix a potential NPE in CallbackServiceCodec.java
Add a null check for url and parameters.
=> fix a potential NPE in CallbackServiceCodec.java

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
=> remove unnecessary space

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/DoubleArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/IntArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/ListMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/LongArrayMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/MapMerger.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/SetMerger.java
Simplified code use Java8 Stream 
M       dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/DoubleArrayMerger.java
M       dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/IntArrayMerger.java
M       dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/ListMerger.java
M       dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/LongArrayMerger.java
M       dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/MapMerger.java
M       dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/SetMerger.java
---
=> use Stream to refactor some code

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
=> [Dubbo-5592] Simplify code of  getExtensionLoader method

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java, dubbo-remoting/dubbo-remoting-p2p/src/main/java/org/apache/dubbo/remoting/p2p/exchange/support/MulticastExchangeGroup.java, dubbo-remoting/dubbo-remoting-p2p/src/main/java/org/apache/dubbo/remoting/p2p/support/MulticastGroup.java
=> duplicate code in MulticastGroup.java and MulticastExchangeGroup.java

.gitignore
=> remove duplicate config  from .gitignore

dubbo-dependencies-bom/pom.xml
https://github.com/alibaba/fastjson/releases/tag/1.2.67
https://security.tencent.com/ti/update_detail/lSFmGiR1zjBZV6o4XNObXhGEXhcKt8CW
=> upgrade fastjson to 1.2.67

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java, dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
some code optimization
XXXXX
XXXXX
=> some code optimization

README.md
polish README.md  , make sure hyperlink can jump to dubbo-samples  Instead of 404
---
=> polish: README.md

dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java, dubbo-metadata/dubbo-metadata-processor/src/main/java/org/apache/dubbo/metadata/annotation/processing/rest/ServiceRestMetadataStorage.java
Fix #5876 
Remove unused variable .
Remove unused variable .
XXXXX
=> [dubbo-5876] Remove unused variable 

dubbo-all/pom.xml, pom.xml
Make the build reproducible: see Reproducible Builds https://reproducible-builds.org/
upgraded a few plugins as documented in Maven Guide to Configuring for Reproducible Builds
https://maven.apache.org/guides/mini/guide-reproducible-builds.html
you can follow the reproducibility test documented on Maven site
=> Make build reproducible

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilter.java
modify bad spell name
modify bad spell name
modify bad spell name
=> fix:bad spell name

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
collect ServiceConfig by export asynchronously  for unexport.
=> Collect services by export asynchronously

dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java
Fix unit test issue for https://github.com/apache/dubbo/pull/5935
CI pass
=> fix unit test for qos module

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoService.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceImpl.java, dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java
add some tests for [org.apache.dubbo.rpc.support.RpcUtils](https://github.com/apache/dubbo/blob/master/dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java)
test RpcUtils.getReturnType
test RpcUtils.getParameterTypes
test RpcUtils.getMethodName
=>  add some test cases for RpcUtils

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
Optimize method `NetUtils#matchIpRange`
I have searched in opened PR.
Fell free to close it if it has be included in other PRs or It is not expected to change.
1. Rename variable `ss` to `ignored` because it is never be used.
2. Simplified `condition?:true:false` -> `condition`
3. Use `StringUtils#split(String,char)` instead of `String#split(regex)`
4. Calculate `ipAddress` when it will be used immediately
The current test case 'NetUtilsTest' is enough.
=> [Dubbo-Optimization] polish NetUtils#matchIpRange

dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/LFUCacheTest.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/lfu/LfuCache.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/lfu/LfuCacheFactory.java
fix https://github.com/apache/dubbo/issues/5130
XXXXX
XXXXX
=> [Dubbo-5130] complete lfu cache proposal

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/UrlUtilsTest.java
fixes https://github.com/apache/dubbo/issues/5948
=> compatible with lower versions registering "default." keys

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java, dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java, dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java
fixes https://github.com/apache/dubbo/issues/5947
=> Fix default config does not work as expected.

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalance.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcStatus.java
to fix some concurrency problems
In some extreme cases, incrementAndGet and decrementAndGet will cause the method 
"beginCount" to returen incorrectly
if max is 10, active is 10 now，here are 3 thread, thread-b calls the metod 'endCount' to decrease the active
```
thread-a	thread-b	thread-c	active's value
increase	--------	--------	11
--------	decrease	--------	10
--------	--------	increase	11
decrease	--------	--------	10
--------	--------	decrease	9
failed 	--------	 failed 	
```
both a and c failed, but active's value is 9 now, it's less than max
let's look at this situation:
there are two thread A and B, A copied the old map to an new map, B put a new WeightedRoundRobin into the old map, and go on to try to get lock, it will failed becuase A hold the lock now, A replace the old map …
=> To fix concurrency problems in RpcStatus and RoundRobinLoadBalance

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
https://bugs.openjdk.java.net/browse/JDK-8062841
=> revert computeIfAbsent for jdk related bug

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
=> fix potential ConcurrentModificationException

codestyle/checkstyle.xml, dubbo-build-tools/pom.xml, dubbo-build-tools/src/main/resources/checkstyle-header.txt, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConfigCenterConfigTest.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/src/main/java/org/apache/dubbo/demo/consumer/comp/DemoServiceComponent.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java, dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/src/main/java/org/apache/dubbo/demo/provider/DemoServiceImpl.java, dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java, dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/generic/DemoException.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/generic/DemoService.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/generic/DemoServiceImpl.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/generic/GenericServiceTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/generic/User.java, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java, dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcProtocol.java, pom.xml
The source : https://github.com/apache/dubbo/issues/6058
=> [Enhancement] Adding a build tools module for Apache License

dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java
Support tomcat9. 
https://github.com/apache/dubbo/issues/5711
XXXXX
XXXXX
=> fix tomcat9 support. #5711

dubbo-common/pom.xml, dubbo-dependencies-bom/pom.xml
https://github.com/apache/dubbo/issues/5793
=> jdk11, No application config found or it's not a valid config!

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
fix #5978 
reproduce use git repo [dubbo-spring-boot-samples/dubbo-registry-nacos-samples](https://github.com/apache/dubbo-spring-boot-project/tree/master/dubbo-spring-boot-samples/dubbo-registry-nacos-samples)
just set 
> dubbo.registry.group=group-demo
the registryUrl contains key `group` 
we can get registryUrl from [`dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java  getUrl()`](https://github.com/apache/dubbo/blob/317e62f73fd0a9bac4b34eb8b2c31bbae591ef91/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java#L131)
``` 
modified:   dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
```
Follow this checklist to help us incorporate your …
=> [Dubbo-5978] fix nacos-registry dubbo.registry.group no effect

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/interceptor/ConsumerContextClusterInterceptor.java, dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcException.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/TimeoutCountDown.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ConsumerContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
support timeout pass and count down on the RPC call chain. 
related issue https://github.com/apache/dubbo/issues/4041
=> support timeout pass and count down on RPC call chain.

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Registry.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/ReExportTask.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java
=> Retry when re-export fails

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/file/FileSystemDynamicConfiguration.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
the synchronize monitor object should be final, to prevent the monitor object changes
modify the synchronize monitor object to final
XXXXX
=> [Dubbo-Optimization] modify the synchronize monitor object to final

dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryDirectoryTest.java
=> Revert "Fix compilation"

dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java, dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
=> fix config override with each other.

dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
address="zookeeper://127.0.0.1:2181|zookeeper://127.0.0.1:2181"
=> config center support registry multi-address format

README.md
fix README.md faile
```
public class GreetingsServiceImpl implements GreetingsService {
```
change to
```
public class GreetingServiceImpl implement GreetingService {
```
```
public class GreetingsServiceImpl implements GreetingsService {
```
change to
```
public class GreetingServiceImpl implement GreetingService {
```
=> fix typo in sample section for readme file

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
=> [Dubbo-6269]fix wrong check of InvokerListener when export a service

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
=> sync wait netty server to finish shutdown

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
fix typo
org.apache.dubbo.validation.support.jvalidation.JValidator#toUpperMethoName
org.apache.dubbo.validation.support.jvalidation.JValidator#toUpperMethodName
=> fix typo in JValidator.java

dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java
=> [Dubbo-6340]fix application cannot exit when use consul registry

dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java
=> make consul registry suppor ACL

dubbo-configcenter/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfiguration.java, dubbo-configcenter/dubbo-configcenter-consul/src/test/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfigurationTest.java
=> fix publish null value when use consul config center

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ListenableRouter.java
fix  https://github.com/apache/dubbo/issues/4822
ListenableRouter#getPriority() return priority direct.
=> [Dubbo-#4822] fix the priority of ListenableRouter were not effective

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/InMemoryWritableMetadataService.java
https://github.com/apache/dubbo/issues/6241
=> when the url is generic, the log level should be info

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/InvokerTelnetHandlerTest.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/DemoService.java, dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/DemoServiceImpl.java
=> [Dubbo-5939] Fix ClassCastException in PojoUtils

dubbo-rpc/dubbo-rpc-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
默认缺少了TpsLimterFilter的扩展点配置，我认为应该加上。
XXXXX
XXXXX
=> tps filter

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Cluster.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/ClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mock/MockInvokersSelector.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/Wrapper.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/WrapperComparator.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/ArrayUtils.java, dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/ServiceBuilder.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/builders/ServiceBuilderTest.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryInvokerWrapper.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java, dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryProtocolTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolFilterWrapper.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ProtocolListenerWrapper.java
1. Introduce ClusterInvoker to better support multiple registries subscription
2. Wrapper sort and enable/disable
3. some small fixes
=> Introduce ClusterInvoker to better support multiple registries subscription

dependencies-bom/pom.xml, dubbo-serialization/dubbo-serialization-hessian2/src/main/java/com/alibaba/dubbo/common/serialize/hessian2/Hessian2SerializerFactory.java
=> hessian whitelist

dubbo-compatible/src/main/java/com/alibaba/dubbo/common/extension/ExtensionFactory.java
fixes https://github.com/apache/dubbo/issues/6428
=> add @SPI annotation to ExtensionFactory

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
https://github.com/apache/dubbo/pull/6431
=> check invoker available status after proxy created.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> [Dubbo-6449 ]Fix NPE when unexport Metadata Service

dubbo-rpc/dubbo-rpc-webservice/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Protocol
=> fix the Spi file of WebServiceProtocol

dubbo-configcenter/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfiguration.java
fix #6504 
Get acl token from the URL, and if it's not empty, use it to initiate the consul KvClient.
1. Start consul with ACL
2. Add some kv in consul.
Config config center like this:
```xml
<dubbo:config-center address="consul://127.0.0.1:8500">
<dubbo:parameter key="token" value="your token"/>
</dubbo:config-center>
```
3.Start dubbo application, and it will get configuration from consul.
=> [Dubbo-6504]fix issue 6504, and polish some code

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/pom.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/src/main/java/org/apache/dubbo/demo/consumer/ApplicationZKConsumer.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/src/main/resources/dubbo.properties, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/src/main/resources/log4j.properties, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/src/main/resources/spring/dubbo-consumer-zk.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/pom.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/java/org/apache/dubbo/demo/provider/ApplicationZKProvider.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/java/org/apache/dubbo/demo/provider/DemoServiceImpl.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/java/org/apache/dubbo/demo/provider/GreetingServiceImpl.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/resources/dubbo.properties, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/resources/log4j.properties, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/resources/spring/dubbo-provider-zk.xml, dubbo-demo/dubbo-demo-service/pom.xml, dubbo-demo/pom.xml, dubbo-metadata/dubbo-metadata-report-zookeeper/src/main/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReport.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
1.添加zk的元数据上报实现
2.调整了下订阅时注册监听器顺序
3.添加基于元数据应用维度的测试demo
=> Dubbo3 应用级服务发现增强：元数据zk实现、demo

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
Fix #6561, error throwing exception information
change to 
c2.append(" throw new " + NoSuchPropertyException.class.getName() + "(\"Not found property \\\"\"+$2+\"\\\" field or getter method in class " + c.getName() + ".\"); }");
=> Fix #6561, error throwing exception information

dubbo-all/pom.xml, dubbo-dependencies-bom/pom.xml, dubbo-registry/dubbo-registry-kubernetes/pom.xml, dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscovery.java, dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscoveryFactory.java, dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/util/KubernetesClientConst.java, dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/util/KubernetesConfigUtils.java, dubbo-registry/dubbo-registry-kubernetes/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceDiscovery, dubbo-registry/dubbo-registry-kubernetes/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceDiscoveryFactory, dubbo-registry/dubbo-registry-kubernetes/src/test/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscoveryTest.java, dubbo-registry/dubbo-registry-kubernetes/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, dubbo-registry/pom.xml
- support register with pod annotation update
- support service discovery with Kubernetes native service
- support service modification listener with resource watch
=> add Kubernetes registry support

dubbo-common/src/main/java/com/alibaba/dubbo/common/extension/ExtensionLoader.java
=> Evacuation unnecessary example Initialization, creation Resource cost

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/pom.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/src/main/java/org/apache/dubbo/demo/consumer/ApplicationConsumer.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-consumer/src/main/resources/spring/dubbo-consumer-zk-apollo.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/pom.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/java/org/apache/dubbo/demo/provider/ApplicationProvider.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider/src/main/resources/spring/dubbo-provider-zk-apollo.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider2/pom.xml, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider2/src/main/java/org/apache/dubbo/demo/provider/ApplicationProvider2.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider2/src/main/java/org/apache/dubbo/demo/provider/GreetingServiceImpl.java, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider2/src/main/resources/dubbo.properties, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider2/src/main/resources/log4j.properties, dubbo-demo/dubbo-demo-service/dubbo-demo-service-provider2/src/main/resources/spring/dubbo-provider-zk.xml, dubbo-demo/dubbo-demo-service/pom.xml, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MappingChangedEvent.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java, dubbo-metadata/dubbo-metadata-report-zookeeper/src/main/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReport.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
1.  元数据上报优化
2. URL在应用维度下bugfix
3. 添加集成apollo的demo
4. 添加zk映射关系变化监听器
=> 元数据上报优化&url模型bugfix

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java
=> [Dubbo-master] Replace custom MD5 method with Bytes.getMD5 #6594

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
fix https://github.com/apache/dubbo/issues/6514
XXXXX
XXXXX
=> Fix code that violates convention

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java
=> fix #6529, set registry zone does not work properly.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> fix #6532, set config center group when registry group is not null.

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/config/YamlPropertySourceFactory.java, dubbo-dependencies-bom/pom.xml, dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
upgrade spring to 5.2.8.RELEASE
https://github.com/apache/dubbo/issues/6518
=> upgrade spring to 5.2.8.RELEASE

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java
Fix TagRoute unable to get remote application name
=> Fix TagRoute unable to get remote application name

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java, dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java, dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java
I found some code to simplify when using IDEA to inspect the code, so I submit a PR here.
=> Simplify code

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ProviderURLMergeProcessor.java, dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java, dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/CustomizedLoaderClassPath.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
=> same as #6075, add customized class path for javassist

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
=> [Dubbo-6778]. modify the method description

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java
update that weights and how to judge the index depend on offset
1.update that how to judge the same weight
2.update that weights and how to judge the index depend on offset
1.enhance performance
2.code is clear
XXXXX
=> update that how to judge the same weight

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/filter/CacheFilter.java
fix https://github.com/apache/dubbo/issues/6741
XXXXX
XXXXX
=> fix https://github.com/apache/dubbo/issues/6741 lur to lru

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java
fix https://github.com/apache/dubbo/issues/6728 npe
XXXXX
XXXXX
=> fix https://github.com/apache/dubbo/issues/6728 npe

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
fix https://github.com/apache/dubbo/issues/6676
XXXXX
XXXXX
=> fix https://github.com/apache/dubbo/issues/6676

dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java, dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd, dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
fix https://github.com/apache/dubbo/issues/6708 alive add
XXXXX
XXXXX
=> fix https://github.com/apache/dubbo/issues/6708 alive add

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
fix https://github.com/apache/dubbo/issues/6444 NPE
XXXXX
XXXXX
=> fix https://github.com/apache/dubbo/issues/6444 NPE

CONTRIBUTING.md
Fixed typo, grammatical, punctuations, and semantic coherence to improve readability and content quality.
To improve the readability, content quality of the CONTRIBUTING.md file.
Fixed typo, grammatical, punctuations, and semantic coherence.
Doesn't impact the main codebase, and is entirely limited to the CONTRIBUTING.md file.
=> [Dubbo] Proofread CONTRIBUTING.md file with multiple fixes

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
maybe there should be overload not override
change override to overload
change override to overload In Wrapper class
=> fix field name for Wrapper.java

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/AbstractCluster.java
=> fix comment grammar error

dubbo-common/src/main/java/org/apache/dubbo/common/BaseServiceMetadata.java, dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java, dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/ThreadlessExecutor.java, dubbo-common/src/test/java/org/apache/dubbo/common/BaseServiceMetadataTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/URLStrParserTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/ThreadlessExecutorTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepositoryTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/timer/HashedWheelTimerTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/DefaultPageTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/LogTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/MemberUtilsTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/utils/MethodUtilsTest.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/StatusTelnetHandler.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/MockTransporter.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/TransportersTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/ExchangersTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/MockExchanger.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/TelnetUtilsTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/support/ClearTelnetHandlerTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/support/ExitTelnetHandlerTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/support/HelpTelnetHandlerTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/support/StatusTelnetHandlerTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/utils/PayloadDropperTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/utils/UrlUtilsTest.java, dubbo-remoting/dubbo-remoting-api/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.Transporter, dubbo-remoting/dubbo-remoting-api/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.exchange.Exchanger
- Improve code coverage about 1 percent.
- Fix #6193 
- Fix #6192
- perfect test cases in `dubbo-common`
- perfect test cases in `dubbo-remote`
- add RunnableWrapper to manage exception in `ThreadlessExecutor`
- fix empty check in `StatusTelnetHandler `
=> [Enhancement] Improve code coverage and fix some code

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
For-[#7105](https://github.com/apache/dubbo/issues/7105)
=> [ISSUE-#7105] Replace common-lang3 StringUtils with dubbo-common StringUtils in NacosRegistry

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
For-[#7118](https://github.com/apache/dubbo/issues/7118)
=> fix memory leak of waitForRemove attribute in CacheableFailbackRegistry

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/ConnectionTest.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/EmptyProtocol.java, dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/NettyServerTest.java, dubbo-remoting/dubbo-remoting-api/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.api.WireProtocol, dubbo-remoting/dubbo-remoting-api/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.netty4.WireProtocol
=> Fix remoting-api UT of branch  3.0 

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLAddress.java
For-[#7143](https://github.com/apache/dubbo/issues/7143)
=> [Dubbo-7143]Fix memory leak for stringAddress cache

dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
update zk depends for service discovery
=> update zk depends

dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
update zk depends for service discovery
=> update zk depends of dubbo 3.0

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/SingleProtocolConnectionManager.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
=> Add :authority and :scheme to triple headers

.github/workflows/build-and-test.yml, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/AbstractAnnotationConfigBeanBuilder.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotatedInterfaceConfigBeanBuilder.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilder.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboBeanUtils.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilderTest.java
Improve getOptionalBean/getBeans,  fix dependency injection initialization problem
Fix issue: https://github.com/apache/dubbo-samples/issues/272
find beans by name, not by type,  to solve this issue: https://github.com/alibaba/spring-context-support/issues/20 , and  without affecting the spring dependency injection initialization function.
run  tests of `dubbo-samples-zipkin`  in  repo `apache/dubbo-samples`
=> [dubbo-samples - 272] Improve getOptionalBean/getBeans

dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
Add publishInstance config to ApplicationConfig
Add publishInstance configuration to ApplicationConfig which already exist in RegistryConfig.
XXXXX
=> Add publishInstance config to ApplicationConfig

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ArrayUtils.java, dubbo-metadata/dubbo-metadata-report-failover/src/main/java/org/apache/dubbo/metadata/store/failover/StrategyMetadataReport.java, dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java, dubbo-remoting/dubbo-remoting-grizzly/src/main/java/org/apache/dubbo/remoting/transport/grizzly/GrizzlyCodecAdapter.java, dubbo-rpc/dubbo-rpc-native-thrift/src/test/java/org/apache/dubbo/rpc/protocol/nativethrift/DemoService.java, dubbo-rpc/dubbo-rpc-redis/src/main/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocol.java, dubbo-rpc/dubbo-rpc-thrift/src/test/java/$__ClassNameTestDubboStub.java
I found some code can be simplified when using IDEA to inspect the code, so I submitted a PR here.
=> Simplity some code

.github/workflows/build-and-test-3.yml
- use github output to pass dubbo version
- merge dubbo-spring-boot build with dubbo build
=> Improve Github Actions Script for 3.0 branch

dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
=> [DUBBO-48] use StandardCharsets

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java
=> [DUBBO-51] change from !(==) to !=

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/CustomizedLoaderClassPath.java, dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/ConfigChangedEvent.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/RestMethodMetadata.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/ServiceRestMetadata.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
=> [DUBBO-53] add braces

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/decode/DubboTelnetDecodeTest.java
use a way to disable disabled tests that normal people will choose to use.
=> [DUBBO-77] use a way to disable disabled tests that normal people will choose to use.

dubbo-metadata/dubbo-metadata-report-failover/src/main/java/org/apache/dubbo/metadata/store/failover/FailoverMetadataReport.java, dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/LogTelnetHandler.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/TelnetUtils.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/LogTelnetHandler.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java, dubbo-rpc/dubbo-rpc-webservice/src/test/java/org/apache/dubbo/rpc/protocol/webservice/WebserviceProtocolTest.java
use StringBuilder instead of StringBuffer
=> [DUBBO-76] use StringBuilder instead of StringBuffer

dubbo-dependencies-bom/pom.xml
upgrade test container version
will fix ut in Github Actions due to invalid container registry
see https://github.com/testcontainers/testcontainers-java/issues/2763
=> upgrade test container

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java, dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/RoundRobinLoadBalanceTest.java, dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java, dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/ClassUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/J2oVisitor.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/CollectionUtils.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/ExecutorUtil.java, dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java, dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/FutureAdapter.java, dubbo-metadata/dubbo-metadata-report-failover/src/test/java/org/apache/dubbo/metadata/store/failover/FailoverMetadataReportTest.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
=> [DUBBO-73] merge same catch branches

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/CacheableFailbackRegistryTest.java, dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/MockCacheableRegistryImpl.java
Add unit test for CacheableFailbackRegistry
=> Add unit test for CacheableFailbackRegistry

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java
=> [ISSUE-#7007] Fix collection data(remote_host) at provider side in monitorFilter not right.

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ready.java
=> Rename the Cmd name of QOS command 'Ready' to ready

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/tps/DefaultTPSLimiter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/filter/tps/StatItem.java
=> 限流功能动态配置之后不生效

dubbo-compatible/src/test/java/org/apache/dubbo/generic/GenericServiceTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java
fix genericservice compatible problem. (#6123)
从2.6.x升级到2.7.x时，低版本使用ReferencConfig初始化进行泛化调用的代码，会在获取实例时收到一个ClassCastException.
#6123 
when we use generic service initilized by ReferenceConfig, if we use setGeneric(true) and do not use setInterface(Class<?> interfaceClass), then the parameter invoker in createProxy will have interface org.apache.dubbo.rpc.service.GenericService.
then AbstractProxyFactory.getProxy will return a proxy without com.alibaba.dubbo.rpc.service.GenericService, we will receive a error.
这个问题的原因是在ReferenceConfig初始化时，如果使用泛化调用，没有设置InterfaceClass并且setGeneric(true)，那么在createProxy的时候，invoker的class为org.apache.dubbo.rpc.service.GenericService。
那么在AbstractProxyFactory进行构建的时候，proxy的接口列表不会有com.alibaba.dubbo.rpc.service.GenericService，获取实例时就会报错。
the unit test with …
=> [Dubbo-#6123] Fix genericservice compatible problem

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java, dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboInvokerAvilableTest.java
Solve the problem of not sharing the shared connection under lazy mode
see more detail from https://github.com/apache/dubbo/issues/7186#issuecomment-783468064
=> Solve the problem of not sharing the shared connection under lazy mode

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
remove UnusedImports which against Checkstyle 8.9 with codestyle/checkstyle.xml ruleset
remove unused constant keys: `GROUP_KEY` and `VERSION_KEY`
~
=> remove UnusedImports

dubbo-common/src/main/java/org/apache/dubbo/common/lang/Prioritized.java
=> [ISSUE-#7247] Doc fix at Prioritized.getPriority

dubbo-config/dubbo-config-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.event.EventListener, dubbo-config/dubbo-config-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.MetadataServiceExporter
=> [ISSUE-#7252] Remove some class in spi file which is removed.

dubbo-common/src/main/java/org/apache/dubbo/common/Parameters.java, dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringMap.java
an object MUST equals to itself.
=> [DUBBO-63] an object MUST equals to itself.

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleConstant.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
=> Triple bugfix

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboConfig.java
=> [ISSUE-#7241] EnableConfigurationBeanBinding to place EnableDubboConfigBinding.

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
=> [ISSUE-#7256] Remove repetitive code about startMetadataCenter()

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigConfigurationAdapter.java
Use loadFactor 1.0 to avoid hashmap expand
XXXXX
XXXXX
=> Use loadFactor 1.0 when new a unchanged hashmap

dubbo-common/src/test/java/org/apache/dubbo/common/extension/wrapper/Demo.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/wrapper/WrapperTest.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/wrapper/impl/DemoImpl.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/wrapper/impl/DemoWrapper.java, dubbo-common/src/test/java/org/apache/dubbo/common/extension/wrapper/impl/DemoWrapper2.java, dubbo-common/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.common.extension.wrapper.Demo
add test cases for wrapper
see https://github.com/apache/dubbo/issues/6946
XXXXX
XXXXX
=> fix #6946 add test cases for wrapper

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
=> Support triple echo and fix conn bug

.gitattributes
Related with #7229
Merge to 3.0 branch
=> Add gitattributes to prevent file formatting

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientInboundHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleServerConnectionHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleServerInboundHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleUtil.java
=> Dubbo3.0-Triple Protocol: Fix mem leak

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java, dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouterFactory.java
add some comment for ConditionRouter
=> add some comment for ConditionRouter

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
=> [Dubbo3-Triple] Fix first connect failed

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java, dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
=> [Dubbo3-Triple] Fix codestyle

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java
=> Revert "[ISSUE-#6999] Remove repeat action of register DubboBootstrapApplicationListener"

.github/workflows/build-and-test-2.6.yml, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/router/tag/TagRouterTest.java, dubbo-cluster/src/test/java/com/alibaba/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java, dubbo-common/src/test/java/com/alibaba/dubbo/common/utils/IOUtilsTest.java, pom.xml
- Add Github Actions script for Dubbo 2.6.x
- Fix context pollution in `TagRouterTest`
=> Add Github Actions script for Dubbo 2.6.x

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionHandler.java
=> [Dubbo3-Triple] Fix reconnect bug

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java, dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocolTest.java
Solve local exposure, the server opens the token, and the client call fails in dubbo3.0.
see more detail from #7024 
XXXXX
XXXXX
=> Solve local exposure, the server opens the token, and the client call fails in dubbo3.0

Jenkinsfile
Fix apache ci build for snapshot
check github action for `Build And Test` with current commitId.
CI pass (verify link: https://ci-builds.apache.org/job/Dubbo/job/apache-dubbo-snapshot-deployment-tmp/)
=> fix jenkins issue

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/GrpcStatus.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleConstant.java
=> [Dubbo3-Triple] Add status and timeout support

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Cluster.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscovery.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/LoggingEventListener.java
=> Super interface shouldn't import sub interface.

dubbo-compatible/src/test/java/org/apache/dubbo/echo/EchoServiceTest.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java
fix deprecated import:  **com.alibaba.dubbo.rpc.service.EchoService**
=> fix deprecated import

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
fix #6733, multicast use valid network interface
MulticastSocket should use a valid network interface, use `getValidNetworkInterfaces` instead of `NetworkInterface.getNetworkInterfaces`.
Just modified `dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java`
```diff
@@ -471,10 +471,8 @@ public class NetUtils {
public static void setInterface(MulticastSocket multicastSocket, boolean preferIpv6) throws IOException {
boolean interfaceSet = false;
-        Enumeration interfaces = NetworkInterface.getNetworkInterfaces();
-        while (interfaces.hasMoreElements()) {
-            NetworkInterface i = (NetworkInterface) interfaces.nextElement();
-            Enumeration addresses = i.getInetAddresses();
+        for (NetworkInterface networkInterface : …
```
=> [Dubbo-6733] multicast use valid network interface

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java
=> fix redundant code

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
reduce unnecessary hashmap operation
XXXXX
XXXXX
=> reduce unnecessary hashmap operation

dubbo-common/src/test/java/org/apache/dubbo/common/config/configcenter/ConfigChangedEventTest.java, dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/registry/MockRegistryFactory.java
fix  https://github.com/apache/dubbo/issues/6749  
Brief changelog:
1.dubbo-common/src/test/java/org/apache/dubbo/common/config/configcenter/ConfigChangedEventTest.java
2.dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/registry/MockRegistryFactory.java
=> [Dubbo-6749] optimize : constant names should be all uppercase

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ServiceConfig.java
fix #6680 Dubbo qos command not work to offline provider
to set the actual group/version while just set group/version in provider or consumer
=> Dubbo qos command not work to offline provider

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java
optimize : Simplify ReflectUtils.java lambda expression
1.dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java
=> optimize : Simplify ReflectUtils.java lambda expression

dubbo-remoting/dubbo-remoting-netty4/src/main/java/com/alibaba/dubbo/remoting/transport/netty4/NettyClient.java
add socks5 proxy support for dubbo-remoting-netty4.
Check the property 'socks5ProxyHost' in com.alibaba.dubbo.remoting.transport.netty4.NettyClient.doOpen().new ChannelInitializer() {...}.initChannel(Channel), if it exists, use the  property socks5ProxyHost and socks5ProxyPort to create a Socks5ProxyHandler and add it to the first location of the ChannelPipeline
XXXXX
=> add socks5 proxy support to 2.6.x netty4 client

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture2.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleUtil.java
=> [Dubbo3-Triple] Add initinal max frame size and max concurrent stream

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java
cache Class avoid PermGen space OOM
see more detail from #6742
XXXXX
XXXXX
=> cache Class avoid PermGen space OOM

.github/workflows/build-and-test-3.yml, dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/resources/dubbo-migration.yaml, pom.xml
- upload rat result when maven run failed
- fix rat not run on Ubuntu
=> [3.0-Actions] Add rat result upload & Fix rat in Ubuntu

dubbo-build-tools/pom.xml, pom.xml
Fix apache-rat-plugin configuration error
XXXXX
run rat check under dubbo base dir :
```
mvn apache-rat:check -Drat.skip=false
```
=> Fix apache-rat-plugin configuration error

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBeanManager.java
Create reference proxy after export service in DubboBootstrap
XXXXX
Run dubbo-samples/dubbo-samples-local
=> create reference proxy after export service in DubboBootstrap

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java
=> [Dubbo3-Triple] Add triple version and group header

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java, dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
fix  codec2 SPI not work
see more detail from #6484 
XXXXX
XXXXX
=> fix  codec2 SPI not work

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java
=> refactor ZoneAwareClusterInvoker.

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java, dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
=> [Dubbo3-Triple] Set callback decode executor

dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-generic-consumer.xml, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-nacos-consumer-context.xml, dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-nacos-provider-context.xml
=> [ISSUE-#7426] Fix interface problem.

dubbo-configcenter/dubbo-configcenter-apollo/src/test/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfigurationTest.java, dubbo-configcenter/dubbo-configcenter-apollo/src/test/java/org/apache/dubbo/configcenter/support/apollo/EmbeddedApolloJunit5.java
replace ApolloDynamicConfigurationTest junit4 to junit5
see more detail from #7432 
XXXXX
XXXXX
=> replace ApolloDynamicConfigurationTest junit4 to junit5

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/metadata/MetadataServiceExporterTest.java
=> Reset ApplicationModel in MetadataServiceExporterTest

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
=> Makes latch volatile.

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
=> fix NullPointException.

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AttachmentsAdapter.java, dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvailableTest.java
fix some spelling mistake
XXXXX
XXXXX
=> fix some spelling mistake

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/AbstractConfigurator.java
AbstractConfigurator#configureIfMatch repeatedly add elements to the conditionKeys collection problem
see more detail from #7453 
XXXXX
XXXXX
=> AbstractConfigurator#configureIfMatch repeatedly add elements to the conditionKeys collection problem

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/ClusterInvoker.java, dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java, dubbo-common/src/main/java/org/apache/dubbo/common/json/JSON.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java, dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapStartStopListenerSpringAdapter.java, dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java, dubbo-container/dubbo-container-api/src/main/java/org/apache/dubbo/container/Main.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataConstants.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataService.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/identifier/ServiceMetadataIdentifier.java, dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/ClassPathServiceRestMetadataReader.java, dubbo-metadata/dubbo-metadata-definition-protobuf/src/main/java/org/apache/dubbo/metadata/definition/protobuf/ProtobufTypeBuilder.java, dubbo-metadata/dubbo-metadata-report-failover/src/main/java/org/apache/dubbo/metadata/store/failover/FailoverMetadataReport.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceURLBuilder.java, dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java, dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/EtcdClient.java, dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java, dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/logging/MessageFormatter.java, dubbo-remoting/dubbo-remoting-p2p/src/main/java/org/apache/dubbo/remoting/p2p/exchange/support/MulticastExchangeGroup.java, dubbo-remoting/dubbo-remoting-p2p/src/main/java/org/apache/dubbo/remoting/p2p/support/MulticastGroup.java, dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperTransporter.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java, dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcException.java, dubbo-serialization/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufJsonSerialization.java, dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/metadata/AbstractDubboMetadata.java
=> Fix some typo

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java, dubbo-common/src/test/java/org/apache/dubbo/common/bytecode/WrapperTest.java
Optimize performance
Use `Map` to replace redundant traversal
Run unit test
=> [Dubbo-Optimization] Remove double loop
