apache/dubbo

dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java

**Problem:**
Conditions within a test method may produce a false test outcome. Once a condition is not met, and the code block inside the condition is not executed, a false 'passed' outcome can be produced without the test ever being executed.
**Solution:**
Instead of using a conditional to control the test execution, we propose using JUnit Assumptions — a failed assumption results in a test being aborted. Assumptions are typically used whenever it does not make sense to continue executing a given test method.
**Result:**
_Before:_
```
if (address instanceof Inet6Address) {
assertThat(NetUtils.isPreferIPV6Address(), equalTo(true));
}
```
_After:_
```
assumeTrue(address instanceof Inet6Address);
assertThat(isPreferIPV6Address, equalTo(true));
```

Improved conditional test execution

---

dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java

For-#7363.
If someone need ignore check someKey.
Just add param `ignoreCheckKeys`:`secretKey `.
```
<dubbo:registry id="registry1" address="nacos://127.0.0.1:8848">
<dubbo:parameter key="username" value="nacos"/>
<dubbo:parameter key="secretKey" value="++++"/>
<dubbo:parameter key="ignoreCheckKeys" value="secretKey"/>
</dubbo:registry>
```

[ISSUE-#7363] Support a way to ignore check some key in parameters.

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

If recover subscribe, the latch in RegistryChildListenerImpl should be update.

Fix recover and zk notify concurrent problem.

---

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringMap.java

- fix expire cache bug
- Optimize code
``` java
public static void main(String[] args) {
Map<String, String> map = new ConcurrentHashMap<>();
map.put("cache.seconds", "10");
map.put("cache.interval", "10");
URL url = new URL("", "", "", "", 8888, "", map);
ExpiringCache cache = new ExpiringCache(url);
long start = System.currentTimeMillis();
boolean in = false;
boolean out10 = false;
boolean out20 = false;
while (true) {
long end = System.currentTimeMillis();
// put k,v in 5s when the programmer start
if (!in && (end - start) > 5 * 1000) {
cache.put("aaa", "aaa");
cache.put("bbb", "bbb");
log.info("put val");
in = true;
}
// get value after expire time(10s)
// but I get can get the value where is no null. wrong
if (!out10 && (end - start) > 16 * 1000) {
log.info("val = {}", …
```

fix expire cache time

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.RouterFactory
dubbo-cluster/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.RouterFactory

If users want prevent maliciout code in router script. 
step one:  define a custom security file with content
```
grant {
permission java.security.AllPermission;
};
``` 
step two:  start dubbo-consumer with system property: -Djava.security.manager -Djava.security.policy=`customFile location`.
This solution maybe decrese the application performance.

Use java box to prevent malicious code.

---

dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilderTest.java

- add providedBy parameter in DubboReference
- make services deprecated
Related #7190

[2.7] Add provided-by paramater for DubboReference

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DynamicConfigurationServiceNameMapping.java
dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisServiceDiscovery.java
dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisServiceDiscoveryFactory.java
dubbo-registry/dubbo-registry-redis/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceDiscovery
dubbo-registry/dubbo-registry-redis/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceDiscoveryFactory

- introduce empty service discovery impl for redis registry
- fix NPE in DynamicConfigurationServiceNameMapping
fix #7434

introduce empty service discovery impl for redis registry

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/migration/MigrationRule.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java

For-[#7459](https://github.com/apache/dubbo/issues/7459)

[Dubbo-7459]Fix passing wrong parameter when calling MigrationInvoker.compareAddresses()

---

dubbo-metadata/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java

fix RedisMetadataReport cluster password is null and refactor code.
see more detail from #6715
XXXXX
XXXXX

fix RedisMetadataReport cluster password is null

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

Optimize the selection of invokers in the multi-registry scenario.
In the multi-registry scenario, if a service is not under a certain registry, the invoker can be filtered out in advance.
see more detail from #7444 
XXXXX
XXXXX

Optimize the selection of invokers in the multi-registry scenario

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java

fix incorrect handling of the URLBuilder caused the wrong URL to be generated
在appItemToUrls方法中，对services进行遍历的时候，因为复用同一个URLBuilder，没有使用深拷贝，导致所有的值都追加在了一起。
serviceItemToUrls方法中，对apps遍历的时候，也是这个问题。不过因为是追加参数到url，所以后者会覆盖前者，这个并不影响功能，我只是在这个上面和appItemToUrls保持统一。
下面两张图分别是修改后和修改前的，测试程序为 ConfigParserTest#parseConfiguratorsAppMultiServicesTest

fix incorrect handling of the urlBuilder caused the wrong URL to be generated

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/test/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClientTest.java

use nodeCache to take place of treeCache.

Use nodeCache to take place of treeCache.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

fix bug for export async ignore exception
when I use wrong threadPool config that does't exist and use async export model ,such as dubbo-thread-pool as below code:
>             
ProtocolConfig protocol = new ProtocolConfig();
protocol.setName("dubbo");
protocol.setPort(12345);
protocol.setThreads(16);
protocol.setIothreads(2);
protocol.setKeepAlive(true);
//this is bad thread-pool
protocol.setThreadpool("dubbo-thread-pool");
protocol.setAccepts(4);
protocolConfigList.add(protocol); 
> 
DubboBootstrap dubboBootstrap = DubboBootstrap.getInstance();
dubboBootstrap.service(service);
dubboBootstrap.configCenter(configCenterConfig);
dubboBootstrap.registry(registryConfig);
//export by async !!!
dubboBootstrap.exportAsync();
dubboBootstrap.start();
in this situation , export operation will run …

fix bug for export async ignore exception

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/support/GroupServiceKeyCache.java

(#6391)
When the version of DubboReference is *, service reference cannot be performed. Fix the problem that the version of DubboReference is *,thanks
Support DubboReference for * can be used for service reference

Fix the DubboReference * version is invalid issue (#6391)

---

dubbo-metadata/dubbo-metadata-report-zookeeper/src/main/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReport.java

[ISSUE-#7297] When first call getServiceAppMapping, reduce once network transport.

---

dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalTest.java

The test `dubbo-common,org.apache.dubbo.common.threadlocal.InternalThreadLocalTest.testSize` is not idempotent and fails if run twice in the same JVM, because it pollutes state shared among tests. It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Issue link: [Dubbo-6935](https://github.com/apache/dubbo/issues/6935)
In `InternalThreadLocalTest.testSize()`, call `InternalThreadLocal.removeAll()` to clear all the thread local variables stored in the test run.

[Dubbo-6935] Clear all stored thread local variables in InternalThreadLocalTest.testSize

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

[ISSUE-#7479] Optimize code for loop condition.(#7479)

---

dubbo-dependencies-bom/pom.xml

upgrade javassist version to prevent warning message in jdk11
Fix #7425

[Dubbo-7425]Upgrade javassist version to 3.23.1-GA

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java

1，创建map或者list时传入原始数据的长度，避免数据量大时进行扩容
例如
` 
result = new HashMap(Math.max((int) (size/.75f) + 1, 16));
`
2，避免无意义的方法调用
例如：
~~~
Map<Object, Object> map;
// when return type is not the subclass of return type from the signature and not an interface
if (!type.isInterface() && !type.isAssignableFrom(pojo.getClass())) {
try {
map = (Map<Object, Object>) type.newInstance();
Map<Object, Object> mapPojo = (Map<Object, Object>) pojo;
map.putAll(mapPojo);
if (GENERIC_WITH_CLZ) {
map.remove("class");
}
} catch (Exception e) {
//ignore error
map = (Map<Object, Object>) pojo;
}
} else {
map = (Map<Object, Object>) pojo;
}
~~~
根据逻辑，pojo本身是一个map，又创建了一个新map来存放，无存在意义
3，其他一些优化
例如某个pojo的method取到之后，不需要再取filed，没有实际意义。

[Optimization] generic releaize and generalize. (#6189)

---

dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java

Adjust the default log priority order,  use slf4j first.
Currently using slf4j most.
Due to the priority log4j, dubbo has no log output.
`dubbo.application.logger` must be configured to take effect.

Adjust the default log priority order,  use slf4j first

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProxyProtocol.java

destroyed invokers in AbstractProxyProtocol can't be removed from list.
```
protected <T> Invoker<T> protocolBindingRefer(final Class<T> type, final URL url) throws RpcException {
final Invoker<T> target = proxyFactory.getInvoker(doRefer(type, url), type, url);
Invoker<T> invoker = new AbstractInvoker<T>(type, url) {
@Override
protected Result doInvoke(Invocation invocation) throws Throwable {
// ..do something
}
// remove this destroyed invoker
@Override
public void destroy() {
super.destroy();
target.destroy();
invokers.remove(this);
}
};
invokers.add(invoker);
return invoker;
}
```
XXXXX
XXXXX

[dubbo 4890]Undeleted invokers(destroyed) In AbstractProxyProtocol may cause memory leak

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/properties/DefaultDubboConfigBinder.java

When there are errors in properties file and data bind encounter error, dubbo now will not throw exception but ignore the errors.
The errors should be thrown to users.
DefaultDubboConfigBinder.java
XXXXX

throw exception when data bind from properties file encounter error

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

- Refactor getSharedClient
- fix #5987
- The current lock mode
```java
locks.putIfAbsent(key, new Object());
synchronized (locks.get(key)) {
//do some thing
//remove lock
locks.remove(key);
}
```
-  The situation which there is a problem: 
When thread A finishes executing locks.putIfAbsent(key, new Object()),
another thread B which holding the lock executes locks.remove(key),
and then thread A executes synchronized (locks.get(key)).
- Attempt get lock by computeIfAbsent like this:
```java
synchronized (locks.computeIfAbsent(key, (k) -> new Object())) {
try{
//do some thing
} finally {
//remove lock
locks.remove(key);
}
}
```
-  The situation which there is a problem: 
1.When thread A finishes executing `synchronized (locks.computeIfAbsent(key, (k) -> new Object()))` create the lock …

[Dubbo-5987] Fix lock in DubboProtocol#getSharedClient

---

dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/option/OptionUtil.java

``endKey[i] < 0xff``  is always true, so could simplify this method

simplify OptionUtil#prefixEndOf

---

dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java

The tests are not idempotent and fails if run twice in the same JVM, because each of the tests pollutes state shared among tests:
* `dubbo-common,org.apache.dubbo.common.extension.ExtensionLoaderTest.test_replaceExtension_Adaptive`
* `dubbo-common,org.apache.dubbo.common.extension.ExtensionLoaderTest.test_AddExtension`
* `dubbo-common,org.apache.dubbo.common.extension.ExtensionLoaderTest.test_replaceExtension`
It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by these tests.
Call `ExtensionLoader.resetExtensionLoader()` to reset the ExtensionLoader for the certain extension types used in each tests in `test_replaceExtension_Adaptive`, `test_AddExtension`, and `test_replaceExtension`.
With the proposed fix, the …

[Dubbo-6954] Reset ExtensionLoader in ExtensionLoaderTest

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExceptionFilter.java

Fix code typo
Change exceptionClassses to exceptionClasses
Verfied

fix code typo in ExceptionFilter

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java

Hidden the important password information to avoid be printed in plain text into the logger file
Update AbstractConfig.java
hidden password
`The registry[<dubbo:registry password="******" username="someone" timeout="10000" group="test" client="curator" address="127.0.0.1" protocol="zookeeper" port="2181" />] will be used as the config center, dubbo version: 2.7.8, current host: 127.0.0.1`

[Dubbo-AbstractConfig] Fix password be print in plain text

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocol.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocolTest.java

solve Broadcast cluster means that multiple machines will be called,  which is not converted to injvm protocol at this time.
see more detail from #6842 
XXXXX
XXXXX

solve Broadcast cluster means that multiple machines will be called,  which is not converted to injvm protocol at this time.

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java

Fix #5842
Move ContextFilter's order to the lowest, avoid RpcContext be cleared

Move ContextFilter to lowest order

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParser.java

ConfigParser#toParameterString and ConfigParser#toParameterString#appItemToUrls ，when after the toParameterString method call, the category parameter is added again
XXXXX
XXXXX

fix repeat adding parameters to the URL

---

.travis.yml
CONTRIBUTING.md
README.md
dubbo-configcenter/dubbo-configcenter-consul/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-metadata/dubbo-metadata-report-redis/pom.xml
dubbo-metadata/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
dubbo-registry/dubbo-registry-consul/pom.xml
dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulServiceDiscovery.java
dubbo-registry/dubbo-registry-multiple/pom.xml
dubbo-registry/dubbo-registry-multiple/src/test/java/org/apache/dubbo/registry/multiple/MultipleRegistry2S2RTest.java
dubbo-registry/dubbo-registry-redis/pom.xml
dubbo-registry/dubbo-registry-redis/src/test/java/org/apache/dubbo/registry/redis/RedisRegistryTest.java
dubbo-rpc/dubbo-rpc-redis/pom.xml
dubbo-rpc/dubbo-rpc-redis/src/test/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocolTest.java

Apache Dubbo is a Java application and thus should work fine on any architecture supported by the Java Virtual Machine.
But Dubbo depends on some libraries which use native binaries that do not have aarch64 version, for example embedded-redis and embedded-consul.
This PR updates those dependencies with newer versions which added support for ARM64 architecture!
The PR re-introduces TravisCI as a build tool to build and tests `master` branch every night.
This has been discussed at https://lists.apache.org/thread.html/r2742c51066b55787571417ed74843cd9607ba8202566ddd807f9bdab%40%3Cdev.dubbo.apache.org%3E
Someone from Dubbo team will have to setup the Cron job at TravisCI UI !

DUBBO-7349 Fix the build on Linux ARM64 CPU architecture

---

dubbo-common/src/main/java/com/alibaba/dubbo/config/annotation/Reference.java
dubbo-common/src/main/java/com/alibaba/dubbo/config/annotation/Service.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/ClusterRules.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoadbalanceRules.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboService.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Service.java
dubbo-common/src/test/java/org/apache/dubbo/common/constants/CommonConstantsTest.java

fixed: #7531
add ClusterRules 、LoadbalanceRules for cluster and  loadbalance properties。
We can user like 
`@DubboService(loadbalance = LoadbalanceRules.RANDOM,cluster = ClusterRules.FAIL_BACK)`
It was like this before
`@DubboService(loadbalance = "random",cluster = "failback")`

add ClusterRules LoadbalanceRules to dubbo common #7531

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java

fix #5971
fix tag router select wrong provider issue
Report
XXXXX 'Provider--A with no tag, Provider--B with tag (dubbo.tag=grey)'
1. Consumer with no tag, do select get A;
2. Consumer with tag(grey), do select get B;
3. Consumer with attachment(dubbo.tag=grey), do select get B;
4. Consumer with tag(grey_), do select get A;
ClusterUtils.class

consumer config tag override privode tag config

---

dubbo-common/src/main/java/org/apache/dubbo/event/DirectEventDispatcher.java
dubbo-common/src/main/java/org/apache/dubbo/event/EventDispatcher.java
dubbo-common/src/main/java/org/apache/dubbo/event/ParallelEventDispatcher.java

SPI default name adjustment

---

dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java
dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/JdkCompilerTest.java

I personally need this mechanism in one of my repos, (I have to copy/change this whole class now because not having such mechanism, I need a JdkCompiler to deal with java 1.8 codes)
and I think it helpful to other people too.
JdkCompiler

[DUBBO-78] Add options configuration mechanism for JdkCompiler.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java

[ISSUE-#7464] Fix unlisten key miatch problem.

---

dubbo-metadata/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
dubbo-registry/dubbo-registry-multiple/src/test/java/org/apache/dubbo/registry/multiple/MultipleRegistry2S2RTest.java
dubbo-registry/dubbo-registry-redis/src/test/java/org/apache/dubbo/registry/redis/RedisRegistryTest.java
dubbo-rpc/dubbo-rpc-redis/src/test/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocolTest.java

Clean up of embedded redis code.
Rewrote these classes:
- dubbo-metadata/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
- dubbo-registry/dubbo-registry-multiple/src/test/java/org/apache/dubbo/registry/multiple/MultipleRegistry2S2RTest.java
- dubbo-registry/dubbo-registry-redis/src/test/java/org/apache/dubbo/registry/redis/RedisRegistryTest.java
- dubbo-rpc/dubbo-rpc-redis/src/test/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocolTest.java
I couldn't run `mvn clean install`. Maven dies with this error:
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class …

Refactored use of embedded-redis

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcInvocation.java

Optimize code to remove useless objects
update before
public void addAttachments(Map<String, String> attachments) {
if (attachments == null) {
return;
}
if (this.attachments == null) {
this.attachments = new HashMap<String, String>();
}
this.attachments.putAll(attachments);
}
update after
public void addAttachments(Map<String, String> attachments) {
if (attachments == null) {
return;
}
if (this.attachments == null) {
this.attachments = attachments;
}else{
this.attachments.putAll(attachments);
}
}

Optimize code to remove useless objects

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportFactory.java

Use double-check to get elements from the cache

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouterTest.java

Add arguments router logic to ConditionRouter.
Add arguments router to ConditionRouter.
Compatible to current ConditionRouter logic.
Add arguments router to ConditionRouter
Add arguments router to ConditionRouter
In some cases, we need to choose the right provider while the arguments of the method is setted.
The condition rule is like
> arguments[1].str!=b  => host = 1.1.1.1
While the str property of the second argument is equal to b, the providers whose host is equal to 1.1.1.1 are to be choosed。
We could use this feature to route requests according to business params. 
The feature is compatible to current ConditionRouter logic.

Add arguments router to ConditionRouter

---

dubbo-dependencies-bom/pom.xml
dubbo-registry/dubbo-registry-kubernetes/pom.xml
dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscovery.java
dubbo-registry/dubbo-registry-kubernetes/src/test/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscoveryTest.java

- upgrade `io.fabric8` version
- use http protocol instead in ut

[3.0] Kubernetes Client dependency upgrade

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java

Optimize the creation of executor for ThreadPoolExecutor in ZookeeperDynamicConfiguration
see more detail from #7616

Optimize the creation of executor for ThreadPoolExecutor in ZookeeperDynamicConfiguration

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/FieldUtils.java

Fix field may be null, and NullPointerException will be thrown in FieldUtils
In this issue(#7619 ), this pr is to fix this issue, to avoid throwing NullPointerException in FieldUtils, thanks

Fix field may be null, avoid throwing NullPointerException(#7619)

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java

In this issue(https://github.com/apache/dubbo/issues/7626),in the getReturnType method of org.apache.dubbo.rpc.support.RpcUtils, the method may be null and a NullPointerException will be thrown,this pr is to fix this issue, to avoid throwing NullPointerException in RpcUtils, thanks

Fix method may be null in RpcUtils,avoid throwing NullPointerException(#7626)

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java

Fix localAddress may be null,and NullPointerException will be thrown in NetUtils
In this issue(#7621 ), this pr is to fix this issue, to avoid throwing NullPointerException in NetUtils, thanks

Fix localAddress may be null,avoid throwing NullPointerException(#7621)

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/RemoteMetadataServiceImpl.java

Remove duplicate calling metadataInfo#calAndGetRevision methods

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java

Fix method may be null, and NullPointerException will be thrown in MethodUtils
In this issue(https://github.com/apache/dubbo/issues/7605 ),Method may be null, and NullPointerException will be thrown in MethodUtils, this pr is to fix this issue, to avoid throwing NullPointerException in MethodUtils, thanks

Fix method may be null, and NullPointerException will be thrown in MethodUtils(#7605)

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

DubboBootstrap implements EventListener but there is no handle event method, maybe we should remove the implementation.

Remove EventListener implementation in DubboBootstrap

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ListenableRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshAppRuleListener.java
dubbo-common/src/main/java/org/apache/dubbo/common/BaseServiceMetadata.java
dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicParamSource.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicParamTable.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicValues.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/FixedParamValue.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java
dubbo-common/src/test/java/org/apache/dubbo/common/url/URLParamTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DynamicConfigurationServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/SelfHostMetaServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java

- Introduce init size for StringBuilder in BaseServiceMetadata
- Make timeout smaller in CacheableFailbackRegistry
- Simplify log
- Introduce DynamicParamSource to add constant param
- Reduce unnecessary boxing
- Reduce unnecessary iterator node creation of HashMap and HashSet
- Cache activateGroup and activateValue in ExtensionLoader
- Make URLParam support method parameters natively, reduce unnecessary map creation

[3.0] Optimization about memory performance

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java

Fix `setSkyWalkingDynamicField(java.lang.Object) not found`,the comment is a detailed description, in order to avoid misunderstanding, sorry to use Chinese  ,link issue, https://github.com/apache/dubbo/issues/2830

[Dubbo-2.7.10] Fix `setSkyWalkingDynamicField(java.lang.Object) not found`

---

dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdServiceDiscovery.java

Fix EtcdServiceDiscovery not overriding the getUrl method, causing subscribe to throw an exception
see more detail from #7636

Fix EtcdServiceDiscovery not overriding the getUrl method, causing subscribe to throw an exception

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

Dubbo zookeeper registry failed to re-subscribe
see more detail from #7665

Dubbo zookeeper registry failed to re-subscribe

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

dubbo2.7.x does not register serviceNameMapping information with the registry by default.
see more detail from #7670

dubbo2.7.x does not register serviceNameMapping information with the registry by default.

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/ServiceDefinitionBuilder.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/model/MethodDefinition.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/model/ServiceDefinition.java

1、Annotation是接口或方法的重要一部分；
2、元数据是泛化调用的重要辅助，元数据增加Annotation有助于前置业务的逻辑校验，可用于鉴权等场景。
为元数据中ServiceDefinition和MethodDefinition增加Annotation的声明字段

Add annotations field to matedata definition

---

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java

Solve the problem of Address already in use in ConfigTest#testDubboProtocolPortOverride
Fix the bug in ConfigTest#testDubboProtocolPortOverride, see #7695
Make the port available

fix: Address already in use in ConfigTest#testDubboProtocolPortOverride (#7695)

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

Fix ZookeeperServiceDiscovery#getInstances not deal with healthyOnly

---

dubbo-serialization/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/ExceptionWrapper.java
dubbo-serialization/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectInput.java
dubbo-serialization/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectOutput.java
dubbo-serialization/dubbo-serialization-gson/src/test/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectOutputTest.java

Using Gson serialization can cause Exception messages to be lost
当选用gson作为序列化协议后,如果provider返回异常,则异常信息会全部丢掉
原因:gson的反序列化协议哪里写的有点问题,默认传入Object.class后,会拿到Map.
这里有一个挺有意思的点,就是为啥fastjson没有此问题

Using Gson serialization can cause Exception messages to be lost

---

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/DemoService.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/DemoServiceImpl.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocolTest.java

当提供者和消费者部署在一起时，dubbo:service上的async参数无法生效，服务调用只执行同步调用。
从用户角度看，服务是同步调用/异步调用应该只与配置参数有关，而与部署方式无关。
issue-demo: https://github.com/70-cloud-lab/dubbo-issues/tree/main/210413-injvm-async
在InjvmInvoker.doInvoke时，如果async=true，则使用CompletableFuture+AsyncRpcResult返回result。async=false则保持原有逻辑。

Injvm protocol support async invoke

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcInvocation.java

This reverts commit d6252081
When RpcInvocation's attachemtns is null, it will share attachments.
It's indeed risk.
Thanks for your remind. @gonwan

Revert "Optimize code to remove useless objects (#7582)"

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java

```
@Override
public String getAddress() {
if (address == null) {
address = getAddress(host, port);
}
return address;
}
private static String getAddress(String host, int port) {
return port <= 0 ? host : host + ':' + port;
}
```
when the port is null, the Integer unbox will cause npe.

Fix getAddress will cause npe problem.

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java

Refer to constants instead of literals

Refer to constants instead of literals

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java

Fix consumer side call DefaultExecutorRepository#getExecutor method cannot hit the cache when use the service discovery pattern

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

[ISSUE-#7722] Fix serviceNameMapping didn't work problem.

---

dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java

[ISSUE-#7724] Nacos service discovery support service reversion and serviceName maping.

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfigurationFactory.java
dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReportFactory.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistryFactory.java

[Dubbo-7514]Ignore "dubbo" namespace when using nacos registry and metadata center

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java

RpcInvocation adds returnType assignment in initParameterDesc
see more detail from #7745

RpcInvocation adds returnType assignment in initParameterDesc

---

dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/MetadataReportConfigTest.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

At present, when `AbstractMetadataReport` is processing `String filename = reportServerURL.getParameter(FILE_KEY, defaultFilename);`, the user cannot actually specify the `file` parameter
issue #7744

Add configurable file parameter to MetadataReportConfig

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java

Only when enabled=true is satisfied, the rule is necessary for parsing

---

dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/MethodConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilder.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/api/MethodCallback.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/MethodConfigCallbackTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/impl/MethodCallbackImpl.java
dubbo-rpc/dubbo-rpc-api/custom-access.log.20210512

fix #6833 when use method annotation like below，callback method dose not work
@DubboReference(check = false,methods = {@Method(name = "sayHello",oninvoke = "methodCallback.oninvoke",onreturn = "methodCallback.onreturn",onthrow = "methodCallback.onthrow")})
private HelloService helloServiceMethodCallBack;

Fix method annotation callback do not work problem

---

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/AbstractInterfaceConfig.java

fix #7033 
add parameter side=consumer when loadMonitor
run `status -l` command get correct pool size

[Dubbo-7033] fix MonitorService missing side=consumer paramter issue #7033

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionFactory.java

Solve the repeated monitoring of applications managed by spring
see more detail from https://github.com/apache/dubbo/issues/7093
XXXXX
XXXXX

About the application of spring management repeated monitoring processing dubbo shutdown.

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java

There are some requirements to proxy DubboReference。
for example
https://github.com/apache/dubbo/issues/7615

feature:  The instance generated by DubboReference supports calling applyBeanPostProcessorsAfterInitialization

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandler.java

The Consumer will not work when id is null in <dubbo:reference>
see more detail from #7614

The Consumer will not work when id is null in <dubbo:reference>

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/support/ActivateComparatorTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/support/Order0Filter0.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/support/Order0Filter1.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/support/Order0Filter2.java

Filter Order was disrupted when user application extends the SPI of org.apache.dubbo.rpc.Filter
see more detail from #7757

Filter Order was disrupted when user application extends the SPI of org.apache.dubbo.rpc.Filter

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
dubbo-rpc/dubbo-rpc-api/pom.xml
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java

Invoking a dubbo service via calling from api gateway or running dynamic scripts like groovy by simply passing string values instead of using maps or updating jar files.
像网关和groovy动态脚本这样的调用,可以直接通过传递字符串完成一次rpc调用(不必自己再组装Map之类,或者更新jar包).变的更简单.(golang 夸语言的泛化调用也会大幅度降低难度,毕竟字符串更好产出出来,相较于struct)

Support sending generic requests in JSON format

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java

fix: #7736
LazyConnectExchangeClient remove addParameter: REQUEST_WITH_WARNING_KEY=true

fix: LazyConnectExchangeClient remove addParameter: REQUEST_WITH_WARNING_KEY=true #7736

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/RegistryConfigTest.java

Fixes #6034 
When I have follow setting, the final registry URL is: `nacos://127.0.0.1:8849/....?preferred=true`.
```xml
<dubbo:registry address="nacos://127.0.0.1:8849" preferred="true"/>
```
Because of `ZoneAwareClusterInvoker.PREFER_REGISTRY_KEY` is mismatching to `RegistryConfig.preferred` key, the following code can't works as expect.
```java
// method => org.apache.dubbo.rpc.cluster.support.registry.ZoneAwareClusterInvoker#doInvoke
if (clusterInvoker.isAvailable() && clusterInvoker.getRegistryUrl()
.getParameter(PREFER_REGISTRY_KEY, false)) {
return clusterInvoker.invoke(invocation);
}
```
* Aliasing `preferred` equal to `ZoneAwareClusterInvoker.PREFER_REGISTRY_KEY` when invoking `AbstractConfig#appendParameters` method.
* The final registry URL should be: …

[Dubbo-6034] Fix the RegistyUrl mismatching to ZoneAwareClusterInvoker.PREFER_REGISTRY_KEY

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/duplicated/DuplicatedOverriddenExt.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/duplicated/DuplicatedWithoutOverriddenExt.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/duplicated/impl/DuplicatedOverriddenExt1.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/duplicated/impl/DuplicatedOverriddenExt2.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/duplicated/impl/DuplicatedWithoutOverriddenExt1.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/duplicated/impl/DuplicatedWithoutOverriddenExt2.java
dubbo-common/src/test/resources/META-INF/dubbo/external/org.apache.dubbo.common.extension.duplicated.DuplicatedOverriddenExt
dubbo-common/src/test/resources/META-INF/dubbo/external/org.apache.dubbo.common.extension.duplicated.DuplicatedWithoutOverriddenExt
dubbo-common/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.common.extension.duplicated.DuplicatedOverriddenExt
dubbo-common/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.common.extension.duplicated.DuplicatedWithoutOverriddenExt

see #3575 
+ fix the bug on duplicated implementation by using SPI
+ add testcases

fix: ExtensionLoader only collect exceptions but do not throws when loadResource #3575

---

dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

Optimize the doUnsubscribe method to remove elements from related containers

Optimize the doUnsubscribe method to remove elements from related containers

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java

support set retry count through RpcContext,  cover the settings of default invoke times.
支持通过RpcContext设置重试次数，如果设置会覆盖默认重试设置。

support set retry count through RpcContext,  cover the settings of default invoke times

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java

Fix the bug that the doRemoveListener method does not remove the listener correctly

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Replace the toString() method with a public parameter to improve readability

Replace the toString() method with a public parameter

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/MultiMessageHandler.java

MultiMessageHandler should increase exception handling to prevent data loss
see more detail from #7815

MultiMessageHandler should increase exception handling to prevent data loss

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

Clear the container at the end of the DefaultExecutorRepository#destroyAll method
Reuse destroyRegistered variable

Clear the container at the end of the DefaultExecutorRepository#destroyAll method

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/interceptor/ConsumerContextClusterInterceptor.java

These operations of a already exist in `ConsumerContextFilter`, so remove the duplicate code of `ConsumerContextClusterInterceptor`

Remove repeat operations in ConsumerContextClusterInterceptor

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/LRUCache.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/LRUCacheTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/cache/CacheTest.java
dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/filter/CacheFilterTest.java

Update LRU to LRU-2
Reduce cache pollution by filtering one access data with a history list. This strategy will not occupy too much extra memory because the history list only saves the keys.
When the data accessed for the first time, add it to the history list. If the size of the history list reaches max capacity, eliminate the earliest data. When the data already exists in the history list, and be accessed for the second time, then it will be put into the real cache.
Also need to update LRUCacheTest, CacheTest, and CacheFilterTest due to the two-time verification mechanism of LRU-2, and two calls need to be performed to put the cache into LRUCache, which shows as commit. 
The performance between LRU and LRU2 refer to https://blog.csdn.net/Victorgcx/article/details/104378378.

enhance LRUCache

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java

[Dubbo-6837] fix dubbo @Service annotation bug

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

When the dubbo program is destroyed, for example, start from spring's` context.stop()`. `DubboBootstrap#destroy` will be called, and the `ExporterChangeableWrapper#unexport` method will be called twice in the logic.
- The first is in `destroyProtocols()->protocol.destroy()->Registry#destroy()->exporter.unexport()->ExporterChangeableWrapper#unexport`
- the second place is in `unexportServices()->sc.unexport()->exporter.unexport()->DestroyableExporter#unexport->ExporterChangeableWrapper#unexport`
So, I add this `unexported` variable to avoid repeated `unexport`

Add tag variables to avoid repeated calls to ExporterChangeableWrapper#unexport method

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/MockInvoker.java

The logic of the original code can be replaced with the `getMethodParameter `method. The logic of the `getMethodParameter `method is as follows:
For example, `URL url = "test://1.1.1.1/path?test.mock=xx&mock=yy"`, `url.getMethodParameter("test","mock") `will first get the parameter value of` test.mock`,if it does not exist,, then Get the `mock `parameter value directly

Optimize the logic of obtaining the mock parameter value in the MockInvoker#invoke method

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/all2/AllChannelHandler2.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/dispatcher/all2/AllDispatcher2.java
dubbo-remoting/dubbo-remoting-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.Dispatcher

Support timeout intercept on provider side
支持provider根据超时时间进行业务打断
场景就是:业务认为即使是provider ,如果一个 操作如果超时了,最好是打断(释放线程).而不是就打一个超时日志

Support timeout intercept on provider side

---

dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/CountTelnetHandlerTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/channel/MockChannel.java

see more from #7842
Add unit test for CountTelnetHandler

Add unit test for CountTelnetHandler

---

dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocolTest.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/ProtocolTest.java

Remove useless code in InjvmProtocolTest
see more detail from #7854

Remove useless code in InjvmProtocolTest

---

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/AbstractMonitorFactory.java

Fix the problem that if an exception is thrown when creating a monitor, it is not handled correctly.

[3.0] Improve monitor creating, handle errors

---

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/AbstractMonitorFactory.java

Fix the problem that if an exception is thrown when creating a monitor, it is not handled correctly.

Improve monitor creating, handle errors

---

dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/TraceTelnetHandlerTest.java

issue: #7843
Add unit test for TraceTelnetHandler

Add unit test for TraceTelnetHandler (#7843)

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java

see #2796 
1. support ignored Network Interfaces
2. add some testcases

feat: Support ignored Network Interfaces #2796

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceName.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosRegistryTest.java

fix Consumer aborted with ArrayIndexOutOfBoundsException when subscribing services from Nacos with '*' in group or version #6814

ignore non-dubbo nacos services

---

dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/CountTelnetHandlerTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/channel/MockChannel.java

#7842
Add unit test for CountTelnetHandler

[3.0] Add unit test for CountTelnetHandler

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ProtocolPortsMetadataCustomizer.java

The `metadataService.getExportedURLs()` method will be called in the `selectMetadataServiceExportedURL` method. This method has already made this judgment, so the repeated judgments here can be removed

Remove repetitive and unnecessary judgment

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataCustomizer.java

Remove the forced conversion in the ServiceInstanceMetadataCustomizer#customize method

Remove the forced conversion in the ServiceInstanceMetadataCustomizer#customize method

---

dubbo-all/pom.xml
dubbo-bom/pom.xml
dubbo-compatible/pom.xml
dubbo-config/dubbo-config-api/pom.xml
dubbo-registry/dubbo-registry-api/pom.xml

几处module未配置
dubbo-all/pom.xml 缺少依赖dubbo-remoting-redis、dubbo-remoting-zookeeper、dubbo-container-api
dubbo-all/pom.xml 遗漏打包org.apache.dubbo:dubbo-remoting-redis
dubbo-all/pom.xml 打包的org.apache.dubbo:dubbo-configcenter-api、org.apache.dubbo:dubbo-configcenter-definition不再存在
dubbo-bom/pom.xml 缺少dubbo-remoting-redis、dubbo-remoting-zookeeper、dubbo-registry-eureka、dubbo-container-api
2处依赖不合理
dubbo-config/dubbo-config-api/pom.xml 依赖的dubbo-filter-validation、dubbo-filter-cache的scope应该是test
dubbo-registry/dubbo-registry-api/pom.xml 不需要直接依赖dubbo-container-api
以上依赖调整后，改到dubbo-compatible/pom.xml

modules‘ dependency fix & optimize

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

improve the code that DubboProtocol.java#getClients

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

When using multiple registries, the registryAsConfigCenter method will be called multiple times. When the address of the registry is the same, the id of the generated ConfigCenterConfig is also the same, so there is no need to follow the logic behind, because in ConfigManager#addConfig Will judge the id to be repeated and return directly.
So add a judgment here, if the id of ConfigCenterConfig already exists in ConfigManager, just return it directly.
multiple registries like this (test case is `servicediscovery-transfer-provider#Application` in `dubbo-samples` project)
```
<dubbo:registry id="service-discovery" address="zookeeper://127.0.0.1:2181?registry-type=service"/>
<dubbo:registry id="normal" address="zookeeper://127.0.0.1:2181"/>
```
The registryAsMetadataCenter method is the same

Optimize the registryAsConfigCenter/MetadataCenter method to return directly when the id exists in configManger

---

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/filter/MockChannel.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/filter/TraceFilterTest.java

issue: #7876 
pick from master [38919254](https://github.com/apache/dubbo/commit/389192544fff99e7fae24f14e4e1dcbea492ad2d)

[3.0] Add unit test for TraceFilter

---

dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/TraceTelnetHandlerTest.java

issue: #7843
pick from master [d6d8d25d](https://github.com/apache/dubbo/commit/d6d8d25d2ee2eefbb82943296a90031ba559d87b)

[3.0] Add unit test for TraceTelnetHandler

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/DefaultCommandExecutor.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/PublishMetadata.java

1.Fix the bug that publishMetadata cmd does not work
2.Delay scheduling should be used instead of scheduled scheduling
3.The delay unit should be seconds, not milliseconds

Fix some bugs in publishMetadata command

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/ClearTelnetHandler.java

If it is not limited, if the user specifies a very large value (such as 999999999), it will cause a large number of data packets to be sent, and the java heap size is prompted under the mac, and the cmd window directly under my win is forced to close
dang
mac:

Limit the maximum number of lines for the clear command

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Application-granular service registration and discovery are compatible with api calling methods.
see more detail from #7364 
XXXXX
XXXXX

Application-granular service registration and discovery are compatible with api calling methods

---

dubbo-common/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java

RegistryConfig and MetadataReportConfig both has constructor with address param.
ConfigCenterConfig also support it.

ConfigCenterConfig add constructor with address param 

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

fix test case

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Help.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/HelpTelnetHandler.java

Cache the parsed result of the HelpCommand and HelpTelnetHandler to avoid repeated parsing and processing

Cache the parsed result of the HelpCommand and HelpTelnetHandler

---

dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/DubboMonitorFactoryTest.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/MetricsFilterTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvokerAvailableTest.java

Fix DubboProtocol is not directly used externally
see more detail from #7923

Fix DubboProtocol is not directly used externally

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

DubboProtocol#INSTANCE should not be initialized in the constructor
see more detail from #7949

DubboProtocol#INSTANCE should not be initialized in the constructor

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java

see more information from #7955
logs are stored using a Set replace with Queue

logs are stored using a Set replace with Queue

---

dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java

Adjust constant name

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

Fix the bug that calling the unregisterServiceInstance method in the DubboBootstrap#destroy method does not work

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepository.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepositoryTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ThreadNameTest.java

Cherry pick commits from #7109 to 3.0 branch, to fix #7054.

cherry pick pr7109 to 3.0

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/ProviderURLMergeProcessor.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/merger/DefaultProviderURLMergeProcessor.java
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.ProviderURLMergeProcessor
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.UrlMergeProcessor
dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/ConsumerBuilder.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

Keep the ProviderURLMergeProcessor API unchanged.
Change the name of the configuration item.
follow #7860

Keep the ProviderURLMergeProcessor API unchanged

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/interceptor/ConsumerContextClusterInterceptor.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/interceptor/ConsumerContextClusterInterceptorTest.java

issue: #7971 
Add unit test for ConsumerContextClusterInterceptor

Add unit test for ConsumerContextClusterInterceptor

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/interceptor/ZoneAwareClusterInterceptor.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/interceptor/ZoneAwareClusterInterceptorTest.java
dubbo-cluster/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.ZoneDetector

issue: #7973
Add unit test for ZoneAwareClusterInterceptor

Add unit test for ZoneAwareClusterInterceptor

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosConfigServiceWrapper.java
dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java

[ISSUE #7943]Handle illegal characters uniformly

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/LFUCacheTest.java

You can not get frequency of the key or delete the empty cache queue before.
1.Change the freqTable from Array to TreeMap
2.Add a timeout field to determine if an empty queue can be deleted
3.Add a method to get frequency of the key

[LFUCache]Add frequency of key and delete the empty cache queue

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/annotation/consumer/lazyinit/DefaultLazyInitConsumer.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/annotation/consumer/lazyinit/DefaultLazyInitService.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/annotation/consumer/lazyinit/DefaultNotLazyInitService.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/annotation/consumer/lazyinit/LazyInitConsumer.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/annotation/consumer/lazyinit/LazyInitService.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/annotation/consumer/lazyinit/NotLazyInitService.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/api/LazyInitHelloService.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/LazyInitDubboAnnotationTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/provider/DefaultLazyInitHelloService.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/impl/DemoServiceXMLLazyInitImpl1.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/impl/DemoServiceXMLLazyInitImpl2.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/impl/DemoServiceXMLNotLazyInitImpl.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandlerTest.java
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/demo-provider-lazy-init.xml
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/demo-provider-not-lazy-init.xml

see #829 
1. support @Lazy
2. add testcase to check default-lazy-init and lazy-init in XML
3. add testcase to check Lazy annotation

fix: Support Lazy annotation

---

dubbo-remoting/dubbo-remoting-api/src/main/java/com/alibaba/dubbo/remoting/transport/MultiMessageHandler.java

[dubbo2.6] cherry up #7815 to dubbo2.6
see more detail from #7991

[dubbo2.6] cherry up #7815 to dubbo2.6

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java

De-duplicate the filter returned by the getActivateExtension method
see more detail from fix #7587

De-duplicate the filter returned by the getActivateExtension method

---

dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/support/ClusterUtils.java

ref to #7985 
Just add some default keys to avoid such special cases

Dubbo 2.6.x may not support multi group consumer #7985

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

Optimize DubboProtocol code and extract constants
see more detail from #8003

Optimize DubboProtocol code and extract constants

---

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/provider/DefaultHelloService.java

see issue #3072
Add testcase to make sure `2.7.x` branch works well
Add testcase to check `DubboService#parameters`

feat: Add testcase for DubboService#parameters to verify issue#3072

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java

```java'
@Override
public String getParameter(String key) {
// call corresponding methods directly, then we can remove the following if branches.
if (GROUP_KEY.equals(key)) {
return getGroup();
} else if (VERSION_KEY.equals(key)) {
return getVersion();
} else if (APPLICATION_KEY.equals(key)) {
return getRemoteApplication();
} else if (SIDE_KEY.equals(key)) {
return getSide();
} else if (CATEGORY_KEY.equals(key)) {
return getCategory();
}
String value = null;
if (consumerURL != null) {
value = consumerURL.getParameter(key);
}
if (StringUtils.isEmpty(value)) {
value = super.getParameter(key);
}
return value;
}
```

[3.0] Address URL fault tolerance on getParameter usage

---

dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/com/alibaba/dubbo/config/spring/context/annotation/provider/DefaultHelloService.java

see issue #3072
1. Support @Service#parameters
2. Add some testcases

fix: @Service#parameters on issue#3072

---

dubbo-common/src/test/java/org/apache/dubbo/common/utils/JVMUtilTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PathUtilsTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ServiceAnnotationResolverTest.java

Add some unit test for common module

Add some unit test for common module

---

.editorconfig

- Unix-style newlines with a newline ending every file
- 4 space indentation for java, xml files

Add editorconfig for 3.0

---

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/status/ThreadPoolStatusCheckerTest.java

Optimize the ThreadPoolStatusCheckerTest test case
see more detail from #8022

Optimize the ThreadPoolStatusCheckerTest test case

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/ServiceDiscoveryMigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleListenerTest.java

Fixes #7999
- Fix Migration Notify key duplicated
- Service Discovery Migration Invoker force Service Discovery
- Remove MigrationInvoker reference after destroyed

Optimize Migration Rule

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/MetadataReportBuilder.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/builders/MetadataReportBuilderTest.java

Add the file parameter to MetadataReportBuilder

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

fix multi-registry bug

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

The deleted code snippet already covers this logic in the checkStubAndLocal(interfaceClass) method below

Remove redundant code in ServiceConfig#checkAndUpdateSubConfigs method

---

dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/util/KubernetesConfigUtils.java

The registry cannot work under the k8s API server using SSL. If there is no certificate related parameter, the empty string will be used by default. This is the result of not using kubernetes client ConfigFluentImpl correctly
see  ConfigFluentImpl#hasCaCertData(),hasClientCertData(),hasClientKeyData in kubernetes client

Registry cannot work under k8s API server using SSL

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/StatusTelnetHandler.java

Optimize StatusTelnetHandler code and extract constants
see more detail from  #8040

Optimize StatusTelnetHandler code and extract constants

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java

see #8045
change the access permission of [AddrCache](https://github.com/apache/dubbo/blob/3.0/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java)'s variables

Optimize AddrCache code

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

[3.0] fix multi-registry bug for 3.0

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java

optimize generic filter

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java

Remove needless toString convert

---

dubbo-common/src/main/java/com/alibaba/dubbo/common/utils/PojoUtils.java

Remove needless toString convert For 2.6

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/EventPublishingServiceDiscovery.java

to solve https://github.com/apache/dubbo/issues/8061
such as 
```
2021-06-16 16:58:02,210 [main] ERROR org.apache.dubbo.registry.client.EventPublishingServiceDiscovery (EventPublishingServiceDiscovery.java:287) -  [DUBBO] Execute action throws and dispatch a ServiceDiscoveryExceptionEvent, dubbo version: 2.7.12, current host: 172.23.233.52
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/curator/x/discovery/ServiceDiscovery
at org.apache.dubbo.registry.zookeeper.ZookeeperServiceDiscovery.doRegister(ZookeeperServiceDiscovery.java:92)
at org.apache.dubbo.registry.client.AbstractServiceDiscovery.register(AbstractServiceDiscovery.java:33)
at org.apache.dubbo.registry.client.EventPublishingServiceDiscovery.lambda$register$0(EventPublishingServiceDiscovery.java:159)
at …
```

EventPublishingServiceDiscovery add error log

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/MethodConfigTest.java

Improve config overrides of method and argument.
* Add method and argument config if found relative config props
* Override argument config of service: 
The match pattern is: `dubbo.service.{interfaceName}.{methodName}.{arg-index}.xxx=xxx`, e.g. `dubbo.service.org.apache.dubbo.config.api.DemoService.sayName.0.callback=true`

[3.0] Improve config overrides of method and argument

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java

1. URLStrParser#parseDecodedStr 和 URL#valueOf都是将String解析成URL，但是parseDecodedStr解析parameters时支持以；作为分割，valueOf不支持。此pr修改了valueOf方法，支持以；作为分隔符。
2. 优化URLStrParser#addParam方法。

improve the code of URLStrParser.java

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java

The destroy method should trigger the call of proxy.$destroy() like the destroyAll method

Fix the issue that the ReferenceConfigCache#destroy method does not call proxy.$destroy()

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/ServiceDefinitionBuilder.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/model/MethodDefinition.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/model/ServiceDefinition.java

https://github.com/apache/dubbo/issues/7907
修改MethodDefinition、ServiceDefinition中annotation序列化存储类型为String的字符串（FastJson在序列化List<Annotation>的时候存储的元数据就是[]，所以这里直接修改数据类型为List<String> ）

annotation cannt be serializable,so change to String

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceListener.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/mock/MockServiceListener.java
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.config.ServiceListener

Add ServiceListener SPI to watch export events of ServiceConfig

[3.0] Add ServiceListener SPI for ServiceConfig

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java

Get ServicePackagesHolder bean by name, avoid early init other FactoryBean

[3.0] Get ServicePackagesHolder bean by name, avoid early init other FactoryBean

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigMode.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigInitializationPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboInfraBeanRegisterPostProcessor.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/autoconfigure/DubboConfigurationProperties.java

Support config mode for unique config types.
*  Strict mode: accept only one config for unique config type, throw exceptions if found more than one configs for an unique config type.
* Override mode: accept last config, override previous config
* Ignore mode: accept first config, ignore later configs
Change config mode (`strict` by default): 
`dubbo.config.mode=strict`
OR override mode:
`dubbo.config.mode=override`
OR ignore mode:
`dubbo.config.mode=ignore`

[3.0] Support config mode for unique config types

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleAddressListenerInterceptor.java

see #8151 
Change `ConcurrentHashMap` to `org.apache.dubbo.common.utils.ConcurrentHashSet`

Optimize MeshRuleAddressListenerInterceptor code#8151

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java

when the return is template like class A<T>
the serialization decode like hession2 is use class A to create
so the result instance contain T is jsonobject, not the real type.
it must be error.

generic serialization decode need use readObject()

---

dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/Constants.java
dubbo-plugin/dubbo-auth/src/main/java/org/apache/dubbo/auth/DefaultAccessKeyStorage.java

#8135 
Reducing auth configuration
Adding a default value to accessKeyId

fix #8135 add a default value to accessKeyId

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

if user define interface service discovery, not publish service name mapping info

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/RegistryConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ReferenceConfigCacheTest.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanManager.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/context/annotation/consumer/test/TestConsumerConfiguration.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/ReferenceKeyTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/multiple-services-with-methods.xml
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/demo-provider.xml
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/init-reference-keys.xml
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/init-reference.xml

Check duplicated ReferenceConfig/ServiceConfig by unique service name, improve adding large numbers of references/services.

[3.0] Check duplicated ReferenceConfig/ServiceConfig by unique service name

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Now use REGISTRY_TYPE_KEY to judge is publish service name mapping or not, but this key is meaningful for RegistryProtol, maybe it will influence the origin logic. 
So add a particular key to judge is publish service name mapping info or not.

Use service name mapping key to avoid logic conflict.

---

compiler/src/main/resources/DubboGrpcStub.mustache

When a ImplBase class is generated, the default implements order is  io.grpc.BindableService, I{{serviceName}}
But when the processScannedBeanDefinition method of ServiceAnnotationPostProcessor is executed, in the resolveInterfaceName method of DubboAnnotationUtils, the order of finding the default interface is the first
[code address](https://github.com/apache/dubbo/blob/e7b41b2a3d54cb62133b9bb6bfe510a70de199c4/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java#L98)
Modify the default order to  I{{serviceName}}, io.grpc.BindableService

gRPC Compile class interface order 

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboInfraBeanRegisterPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanManager.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanSupport.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboBeanUtils.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/boot/configprops/SpringBootMultipleConfigPropsTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer/PropertyConfigurerTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer2/PropertySourcesConfigurerTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer3/PropertySourcesInJavaConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer3/app.properties
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer3/dubbo-consumer.xml
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/ReferenceKeyTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/localcallam/LocalCallMultipleReferenceAnnotationsTest.java
dubbo-spring-boot/dubbo-spring-boot-autoconfigure/src/test/java/org/apache/dubbo/spring/boot/autoconfigure/DubboRelaxedBinding2AutoConfigurationTest.java
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/metadata/AbstractDubboMetadata.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/test/java/org/apache/dubbo/spring/boot/autoconfigure/CompatibleDubboAutoConfigurationTest.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/test/java/org/apache/dubbo/spring/boot/autoconfigure/CompatibleDubboAutoConfigurationTestWithoutProperties.java

Improve property placeholder resolving of config bean
1. Improve  `PropertySourcesPlaceholderConfigurer` bean checking,  set `ignoreUnresolvablePlaceholders` to `true`
2. Resolve placeholder with both Spring Environment and BeanFactory
3. Add `PropertySourcesInJavaConfigTest`
4. Improve reference key and reference bean name mapping
5. Register ReferenceAnnotationBeanPostProcessor as BeanPostProcessor early

[3.0] Improve property placeholder resolving of reference bean

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConfigKeys.java
dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/MethodConfigTest.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/autoconfigure/DubboConfigurationProperties.java

Verify method config, extract `ConfigKeys`.
How to ignore invalid method config:  `dubbo.config.ignore-invalid-method-config=true`

[3.0] verify method config, extract ConfigKeys

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java

Don't trust the response format from nacos server.

Don't trust the response format from nacos server.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java

see #8259 
Remove redundant 'get' action after calling 'computeIFAbsent' on a ConcurrentHashMap.

Remove redundant 'get' action after calling 'computeIFAbsent' on a ConcurrentHashMap.

---

dubbo-common/src/test/java/org/apache/dubbo/common/URLBuilderTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ProtocolConfigTest.java

see #8250 
use tool to generate port instead of hard coding in URLBuilderTest and ProtocolConfigTest

Dubbo 3 Remove hard code about port in URLBuilderTest and ProtocolConfigTest

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java

消费者端ExecutorService在运行期间不应该shutdown
复现了 #8172 的的一种场景
1，启动3个提供者
2，启动1个消费者，开始服务调用
3，kill -9 提供者1，会发现消费者全局ExecutorService被CLOSE，后续服务调用使用SHARED_EXECUTOR
4，kill -9 提供者2，会发现SHARED_EXECUTOR被CLOSE
5，后续服务调用，报错及堆栈基本同issue描述
分析：提供者非正常下线（如netty先关闭，注册中心服务尚未下线），消费者端netty触发AbstractChannelHandlerDelegate.disconnected，从而触发futureExecutor.shutdownNow()。
而消费者端服务调用线程池是全局共享，在运行期间不应该被shutdown。
DefaultFuture. closeChannel时，不关闭ExecutorService。

[Dubbo-8172][3.0]Not shuwdown ExecutorService when DefaultFuture. closeChannel()

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java

Fix #8181 
At provider, it won't register service name mapping info.
At consumer, we will use application_first, it will use service discovery logic to find service name mapping info,
in NacosDynamicConfiguration, use httpAgent to get service name mapping info, but at nacos server lower version, if the config is not found, will return null response.
So we should do compatible work for lower nacos server version.

For compatible nacos server lower version, we should check the response from nacos server is null.

---

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/support/TelnetHandlerAdapterTest.java

add test for TelnetHandlerAdapter
see more detail from #8257

Ut telnet handler adapter test

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/UrlUtilsTest.java

Throw the IllegalArgumentException if the address is empty to avoid NPE.

Throw the IllegalArgumentException if the address is empty to avoid NPE.

---

dubbo-common/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml

1.metadata-report-config support protocol and port.
2.make ConfigCenterConfig setAddress be same with RegistryConfig.

Enhance metadata report config.

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/servicediscoveryregistry/AbstractServiceDiscoveryRegistryTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/servicediscoveryregistry/ServiceDiscoveryRegistry4DubboTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/servicediscoveryregistry/ServiceDiscoveryRegistryIntegrationService.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/servicediscoveryregistry/package-info.java

see #8276 
Checks if ServiceDiscoveryRegistry works well using reflection

test: Add integration testcase for testing RegistryProtocol and ServiceDiscoveryRegistry

---

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/telnet/support/TelnetHandlerAdapterTest.java

add TelnetHandlerAdapterTest to branch 3.0
see more detail from #8257

add TelnetHandlerAdapterTest to branch 3.0

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java

fix the Endpoint constructor error during Consumer start with FORCE_APPLICATION.
this place need default Endpoint constructor: https://github.com/apache/dubbo/blob/2e8dca636792f354f31661eca0d151e12a79cd4f/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java#L186
1. add Endpoint default constructor.

add Endpoint default constructor.

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/RegexProperties.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/RegexPropertiesTest.java

see #3168 
Solution: Extend Properties.class to support regex matching keys.

[3.0] p2p invoke support wildcard url match.

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLAddress.java

movitation:
fix org.apache.dubbo.common.url.component.URLAddress#parse method to judge the isPathAddress problem.
see #8285

fix org.apache.dubbo.common.url.component.URLAddress#parse method to judge the isPathAddress problem

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/governance/DefaultGovernanceRuleRepositoryImpl.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/DynamicConfiguration.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

* Initialize dynamic configuration in DubboBootstrap only
* Get dynamic configuration from Environment only

[3.0] Improve dynamic configuration initialization

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java

* Change `ConfigManager` to lock-free with `ConcurrentHashMap`
* Improve config `equals()` and `toString()` performance
* Improve checking large numbers of reference/service configs

[3.0] Lock-free ConfigManager and improve config checking

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java

Support the following format configuration properties. such as:
dubbo.registry.parameters.item3=value3
see #8303

support  dubbo.registry.parameters.item3=value3 configuration properties

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalance.java

ShortestResponseLoadBalance works as a RandomLoadBalance when the active value is zero ,but succeededAverageElapsed isn't zero.In my opinion, once succeededAverageElapsed is bigger than zero，ShortestResponseLoadBalance will chose the shortest invoker.
Active value should be bigger than zero so that  succeededAverageElapsed can play a vital role in this case.

Optimize ShortestResponseLoadBalance active param

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/com/alibaba/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java

related https://github.com/apache/dubbo/pull/6959

Backport 2.7, lazy connection warn log

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/BroadcastClusterInvoker.java

String.format lack of arg which is from BroadcastClusterInvoker
see #8341

fix String.format lack of arg which is from BroadcastClusterInvoker

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/mock/MockProtocol.java
dubbo-native/src/main/java/org/apache/dubbo/rpc/Protocol$Adaptive.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractProtocol.java

Add the lost annotation of the Subclass of Protocol.
- add override annotation in MockProtocol and AbstractProtocol.

Add the lost annotation of the Subclass of Protocol.

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java

Nacos `NamingEvent`'s name is group@@serviceName. 
It can't be pass by predicateEventListener.accept(event), the predicateEventListener's hold serviceNames format is serviceName, which is not formatted as group@@serviceName.
https://github.com/apache/dubbo/blob/41e989b853b151e01aae53e41b9504e31f5e8f4a/dubbo-common/src/main/java/org/apache/dubbo/event/AbstractEventDispatcher.java#L125

Fix instance change event name format problem.

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-dependencies-bom/pom.xml

1. change alibaba spring-context-support version of dubbo pom.xml to 1.0.11
2. set classValuesAsString and nestedAnnotationsAsMap attributes of ReferenceAnnotationBeanPostProcessor to false
fix #7797

change alibaba_spring_context_support_version to 1.0.11

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/migration/MigrationRule.java

fix migrationRule bug

---

dubbo-common/src/main/java/org/apache/dubbo/config/ConfigKeys.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ShutdownHookTest.java

support disable shutdown hook for special scenario. 
config key: `dubbo.lifecycle.disable-shutdown-hook`
Disable dubbo shutdown hook, Default value is false.
When disable the shutdown hook, you may need to do :
1. offline all services by qos manually before shutdown dubbo application
2. no DubboBootstrapStopedEvent will be sent
3. all ShutdownHookCallback will not be called
4. dubbo application will not be destroyed when spring context is closed

[3.0] support disable shutdown hook

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/SingleRegistryCenterDubboProtocolIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/listener/ExportedServiceListener.java
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.config.ServiceListener

see #8354 
1. Use SPI to load ServiceListener
2. Check if MetadataService exported successfully
3. Check if ServiceConfig exported successfully

test: Add testcase to check exported services

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleManager.java

Other routing group default to `dubbo`, mesh rule group default value should be `dubbo`.

[3.0]Change mesh rule group to config default value

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java

Compatible with nacos grouping via group
see #8317

Compatible with nacos grouping via group

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java

消费者端ExecutorService在运行期间不应该shutdown
复现了 #8172 的的一种场景
1，启动3个提供者
2，启动1个消费者，开始服务调用（异步调用）
3，kill -9 提供者1，会发现消费者全局ExecutorService被CLOSE，后续服务调用使用SHARED_EXECUTOR
4，kill -9 提供者2，会发现SHARED_EXECUTOR被CLOSE
5，后续服务调用，报错及堆栈基本同issue描述
分析：提供者非正常下线（如netty先关闭，注册中心服务尚未下线），消费者端netty触发AbstractChannelHandlerDelegate.disconnected，从而触发futureExecutor.shutdownNow()。
而消费者端服务调用线程池是全局共享，在运行期间不应该被shutdown。
DefaultFuture. closeChannel时，不关闭ExecutorService。

[Dubbo-8172]Not shuwdown ExecutorService when DefaultFuture. closeChannel()

---

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ExecuteLimitFilterTest.java

Link to issue: #8390
This PR is to fix a non-idempotent test `org.apache.dubbo.rpc.filter.ExecuteLimitFilterTest.testExecuteLimitInvokeWitException` 
- The test does not remove `RpcStatus` after running, which pollutes the state shared among tests.
- It may be better to clean state pollutions so that some other tests won't fail in the future due to the shared state pollution.
Removes the status of RPC when the test ends.

Clean shared state pollution to avoid flaky tests.

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/OverrideInstanceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

[2.7] Add Dynamic Configuration Override Support For ServiceDiscovery

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/state/BitListTest.java

Add unit test for BitList

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

move count down to final part to avoid meaningless waiting when exception throw

move count down to final part to avoid meaningless waiting when exception throw

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

support dubbo bootstrap start re-entry, export/refer new services.

[3.0] dubbo bootstrap start re-entry, export/refer new services

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

Ensure generated config id is unique, checking existed config.

[3.0] Ensure generated config id is unique, checking existed config

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java

Remove unused modifiable param

Remove unused modifiable param

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanSupport.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceCreator.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ParameterConvertTest.java

#8378
Sevice and reference convert parameter in the same method，which is compatible with symbol(:) colon and and equal(=).As As for other config, like mock ,it works as well.
#8379 for 2.7.

fix #8378 parameter convert error for 3.0

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/SelfHostMetaServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListenerTest.java

1. add a method to refresh instance, remove instance refresh logic in `isRetryAndExpired`.
2. remove second param `consumerUrl` at `ServiceInstancesChangedListener#getAddresses`.
3. remove second param `ServiceDiscovery` at `MetadataUtils#destroyMetadataServiceProxy`.
4. remove second param `ServiceDiscovery` at `MetadataUtils#getMetadataServiceProxy`

Refactor service change listener.

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConfigCenterConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/MethodConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java

see #8419 
1. Ignore of printing exception stack trace in ConfigCenterConfigTest#testOverrideConfig
2. Ignore of printing exception stack trace in MethodConfigTest#testVerifyMethodConfigOfService
3. Ignore of printing exception stack trace in ReferenceConfigTest#test1ReferenceRetry

perf: Ignore unnecessary exception stack trace in testcase

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java

https://github.com/apache/dubbo/blob/b64ea1d8c6c5b64828ef3d08f8cc432de59bb559/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java#L205-L212
Here use sleep to test delay, it's not suitable. It can't guarantee that delayService already exported.
So here use listener to check it.

Make ServiceConfigTest#testDelayExport more reasonable

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java

1. Do not wrap object in attachment
2. Fix triple server thread pool name's typo
3. Remove hanlded exception info from metadata

[3.0-Triple]Remove auto wrap when attachment is an object instance 

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleConstant.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHeaderEnum.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2ClientResponseHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleUtil.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryServerStream.java

Optimize tri header constant & avoid tri header in attachments
- change tri constant to enum
- Unified processing of attachment value & Determine whether it is larger than the default header size

[3.0 triple] Optimize tri header constant & avoid tri header in attachments

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/SingleProtocolConnectionManager.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/ConnectionTest.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStreamTest.java

1. Connect when invoking  instead of connecting after `Connection` created
2. Lower connection log from `INFO` to `DEBUG` to reduce log 
3. Fix async unary invocation's `callback.executor' NPE bug

[3.0-Triple]Optimize connection  & remove executor

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalance.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalanceTest.java

As we know , most micro services are built based on cloud.However, there are several factors that affect the service，for instance cpu steal ,network jitter and so on. LoadBalance should be more sensitive with running time of invoker when bad thing happens. ShortestResponseLoadBalance works not well for service has start for a long time so that average elapsed time  changed little  according to my past practice.Sliding window may be a good choice to solve this problem.
Average elapsed time depends on statistics in sliding window. Once sliding window is end,a async thread will clear past data of all invokers, which I have thought for a long time. Segmented execution seems a good practice, but it would bring some potential risks.How about giving me some advice?

optmization about shortestResponseLoadBalance

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java

当用户需要自己扩展dubbo-monitor实现后，配置有问题
如配置<dubbo:monitor procotol="myMonitor"/>，monitorUrl=null
如配置<dubbo:monitor procotol="myMonitor" address="ip:port"/>，monitorUrl=dubbo://ip:port，变成了dubbo协议？！
如配置<dubbo:monitor address="myMonitor://ip:port"/>，monitorUrl=myMonitor://ip:port，当如果扩展不需要ip:port呢
优化了org.apache.dubbo.config.utils.ConfigValidationUtils#loadMonitor，可支持如下配置方式
- dubbo.monitor.protocol=registry
- dubbo.monitor.protocol=service-discovery-registry
- dubbo.monitor.protocol=user
- dubbo.monitor.address=user://1.2.3.4:5678?k=v
- dubbo.monitor.protocol=user   +   dubbo.monitor.address=1.2.3.4:5678

[3.0] Optimize dubbo:monitor configuration

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/BroadcastClusterInvoker.java

fix broadcast log format bug
see #8480

fix broadcast log format bug

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilder.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ParameterConvertTest.java

#8378 
Sevice and reference convert parameter in the same method，which is compatible with symbol(:)  colon and  and equal(=).As As for other config, like mock ,it works as well.

fix #8378 parameter convert error

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/SingleRegistryCenterDubboProtocolIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderExporterListener.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderFilter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderRegistryProtocolListener.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderService.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderServiceImpl.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderServiceListener.java
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.config.ServiceListener
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.registry.integration.RegistryProtocolListener
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.rpc.Filter

see #8500 
1. Check if the exporter exported by RegistryProtocolListener, ServiceListener and ExporterListener
2. Check if the provider works well by Filter

test: verify the process of exported provider in single registry center

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboSpringInitializationContext.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboSpringInitializationCustomizer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboSpringInitializer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboComponentScanRegistrar.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboConfigConfigurationRegistrar.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboNamespaceHandler.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/SpringCompatUtils.java
dubbo-test/dubbo-test-spring/src/main/java/org/apache/dubbo/test/spring/SpringAnnotationBeanTest.java
dubbo-test/dubbo-test-spring/src/main/java/org/apache/dubbo/test/spring/SpringJavaConfigBeanTest.java
dubbo-test/dubbo-test-spring/src/main/java/org/apache/dubbo/test/spring/SpringXmlConfigTest.java
dubbo-test/dubbo-test-spring/src/main/java/org/apache/dubbo/test/spring/context/MockSpringInitializationCustomizer.java
dubbo-test/dubbo-test-spring/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.config.spring.context.DubboSpringInitializationCustomizer

Extract DubboSpringInitializer and support customize initialization.

[3.0] Extract DubboSpringInitializer and support customize initialization

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvokerTest.java

- Add unit test for class ZoneAwareClusterInvoker
- Fix class cast error when throw IllegalStateException in ZoneAwareClusterInvoker.java line 80
- Add unit test for class ZoneAwareClusterInvoker
- Fix class cast error when throw IllegalStateException in class ZoneAwareClusterInvoker

[3.0] Fix class cast error and add unit test for ZoneAwareClusterInvoker

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java

Fix #8527
Should not register real group for ServiceInstance, or this will cause consumer unable to fetch all of the providers from every group. Provider's group is invisible for consumer.

Fix nacos group inviable in consumer side

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java

PR #8477 带来一个bug，即未配置dubbo:monitor，ConfigValidationUtils#loadMonitor返回了dubbo协议的URL的错误。
感谢 @guohao 
当未配置dubbo:monitor，monitorUrl返回null，也就不会触发monitorFilter

[3.0] fix dubbo:monitor protocol bug after 8477

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalanceTest.java

ShortestResponseLoadBalanceTest#testSelectByResponse sometimes runs failed，for weightInvoker1's weight is standard unit and it maybe especially big or small. In my opinion, the asserts of weightInvoker2 and weightInvoker5  are enough，while maxDeviation should be bigger.
[Test failure](https://github.com/apache/dubbo/pull/8510/checks?check_run_id=3336766043)
[Relate pr](https://github.com/apache/dubbo/pull/8441#issuecomment-899264224)

fix ShortestResponseLoadBalanceTest failure

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ParameterConvertTest.java

improve annotation parameters test.
related issue: https://github.com/apache/dubbo/issues/8489

improve annotation parameters test

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java

Fix the issue of taking the zone parameter value in ZoneAwareClusterInvoker

---

dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ReferenceConfig.java

fix https://github.com/apache/dubbo/issues/8515

Dubbo ProviderConsumerRegTable class cause OutOfMemoryException

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeClassChecker.java

add the switch to open class check， default is true
my case have this problem
#7436

add the switch to open class check， default is true

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/MockInvoker.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceA.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceAMock.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceB.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceBMock.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvokerTest.java

fix Issue 8516 on branch 3.0: fix mock:true configuration.

---

dubbo-common/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/MetadataReportBuilder.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReportInstance.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/ListenerRegistryWrapper.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/RemoteMetadataServiceImpl.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/util/CuratorFrameworkUtils.java

1.fix check config anbout  registry and config cneter  
2.metatada report support check config
3.fix typo

【3.0】Enhance and fix check config

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

`checkAndUpdateSubConfigs` was called twice from `init` and `refresh`, this patch tries to remove the `init` call.

fix duplicate config init

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodecSupport.java

Fix on branch master, consumer invoke timeout cause NPE.

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryServerStream.java

Fix when exception occured in `invoker.invoke` , triple can not pass it to client.
Add `try-catch` in executor.
Run samples here
https://github.com/apache/dubbo-samples/pull/356

[3.0-Triple] Fix error in filters can not be returned to client

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ExceptionUtils.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHeaderEnum.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java

Default h2 header list size is 8192 byte, exception's `tw-bin` header and detail status header is too large .
1. Remove throwable tw-bin
2. Truncate exception to 10 stacks

[3.0-Triple] Remove throwable tw-bin header and truncate exception 

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

when use delay export service, the log info won't be print.
how to test it?
in dubbo-demo-xml-provider, modify the registry address to `redis://127.0.0.1:6379?registry-type=service` and run it.

When use delay to export service, catch the exception and log it.

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleServerConnectionHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleUtil.java

- add catch some harmless exception (like SocketException)
use https://github.com/grpc-ecosystem/grpc-health-probe and return status: SERVING,No exception log is generated on the server

[3.0-Triple] Catch some harmless exception

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/registrycenter/AbstractRegistryCenter.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer/PropertyConfigurerTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer2/PropertySourcesConfigurerTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer3/PropertySourcesInJavaConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/localcall/LocalCallTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/localcallam/LocalCallMultipleReferenceAnnotationsTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/registrycenter/AbstractRegistryCenter.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/GenericServiceWithoutInterfaceTest.java
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-generic-consumer-without-interface.xml
dubbo-dependencies-bom/pom.xml
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/PortTelnetTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ArgumentCallbackTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java
dubbo-test/dubbo-test-common/pom.xml
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/EmbeddedZooKeeper.java
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/ZooKeeperServer.java
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/registrycenter/AbstractRegistryCenter.java
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/registrycenter/RegistryCenter.java
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/registrycenter/ZookeeperMultipleRegistryCenter.java
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/registrycenter/ZookeeperRegistryCenter.java
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/registrycenter/ZookeeperSingleRegistryCenter.java
dubbo-test/dubbo-test-spring/src/main/java/org/apache/dubbo/test/spring/SpringAnnotationBeanTest.java
dubbo-test/dubbo-test-spring/src/main/java/org/apache/dubbo/test/spring/SpringJavaConfigBeanTest.java
dubbo-test/dubbo-test-spring/src/main/java/org/apache/dubbo/test/spring/SpringXmlConfigTest.java

fixes: Try to reduce the time consuming in UT

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java

HTTP2 Settings should be able to configured by user in different sences. Hard code in current code should be substituted.
supported to configure all HTTP2 settings: SETTINGS_HEADER_TABLE_SIZE, SETTINGS_ENABLE_PUSH, SETTINGS_MAX_CONCURRENT_STREAMS, SETTINGS_INITIAL_WINDOW_SIZE, SETTINGS_MAX_FRAME_SIZE, SETTINGS_MAX_HEADER_LIST_SIZE 
yes

#8685 supported to configure HTTP2 settings

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ServiceInstanceHostPortCustomizer.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/metadata/ServiceInstanceHostPortCustomizerTest.java

Fixes #8698 
Fixes #8599
Related to #8666

[3.0] Add preferredProtocol fallback strategy

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java

* Judge whether success or not by user's perspective in interface-appName mapping.
* By the way, format the function `MetadataServiceNameMapping#map`: change the indent spaces from 8 to 4.
Fixes #8722 
Every time the provider restarted after the first start,  it would raise an error "Failed register interface application mapping......".
But from the user's perspective, it means successful when the oldConfigContent has contained the current appName. So we should not throw an Exception to the user, it will confuse the user.
Just change one line code：
```java
// => org.apache.dubbo.registry.client.metadata.MetadataServiceNameMapping#map
public boolean map(URL url) {
// ......
if (StringUtils.isNotEmpty(oldConfigContent)) {
boolean contains = StringUtils.isContains(oldConfigContent, appName); …
```

[3.0] Judge whether success or not by user's perspective in interface-appName mapping.

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

[master] Simplify and unify local address getting method

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java

fix random assertion failure mentioned in #8689

[master] fix random assertion failure

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java

fix random assertion failure mentioned in #8689 on branch 3.0

[3.0] fix random assertion failure

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceDescriptor.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java

- fix tri stream method can not find methodDescriptor (Because of multiple instances)

[3.0-Triple] fix tri stream method can not find methodDescriptor

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsInterfaceDisplayNameHasMetaCharactersTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java

[3.0] fix ignored interface name matches method

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalMap.java

avoid foreseeable expanding in InternalThreadLocalMap
use the same code which in method ***expandIndexedVariableTableAndSet*** to caculate capacity when create a InternalThreadLocalMap instance

Caculate capacity in the default constructor of InternalThreadLocalMap

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Request.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java

fix #8695 on 3.0
DefaultFuture turn off logging optimization for Channel.

fix issue-8695:DefaultFuture turn off logging optimization for Channel

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

[master] fix destroy IllegalStateException and doOverrideIfNecessary NPE

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/directory/MockDirInvocation.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/MapUtils.java
dubbo-compatible/src/test/java/org/apache/dubbo/service/MockInvocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AttachmentsAdapter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvocation.java

In order to realize the conversion from Map<String, Object> to Map<String, String>, the implementation of AttachmentsAdapter is too complicated, and the inner class of the class is also used. For the sake of simplicity, the tool class MapUtils with less code is used to achieve the same function.
为了实现Map<String, Object>到Map<String, String>的转换，AttachmentsAdapter实现的太复杂，还使用类内部类。为了简单起见，使用更少代码的工具类MapUtils来实现一样的功能。

Use MapUtils instead of AttachmentsAdapter

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/Constants.java

Optimize some code of the dubbo metadata module

Optimize some code of the dubbo metadata module

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/Constants.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java

[master] do not show the warning at first replaceWithLazyClient()

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/SubMigrationRule.java

Extract constants of MigrationRule

Extract constants of MigrationRule

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java

provider doesn't expose to registry if add @Lazy annotation.
in issue #829 , @pinxiong said, `dubbo:service don't support lazy initialization`, I just remove lazy support in method `registerServiceBean`.

fix #8770: provider remove @Lazy support.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

[master] fix NPE in doOverrideIfNecessary

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture2.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java

[3.0-Triple] close stream when timeout

---

dubbo-common/src/main/java/org/apache/dubbo/common/deploy/ApplicationDeployer.java
dubbo-common/src/main/java/org/apache/dubbo/common/deploy/ModuleDeployer.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ModuleConfigManager.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepositoryTest.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigBeanInitializer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/boot/configprops/SpringBootConfigPropsTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/boot/configprops/SpringBootMultipleConfigPropsTest.java

* move ModuleConfig to ModuleConfigManager
* copy some config options to  ModuleConfig from ProviderConfig/ConsumerConfig, such as  `background` , `exportThreadNum`, `referThreadNum`
* support start module in background, do not await module start finish in Spring application

 [3.0] Support start module in background

---

dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/test/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClientTest.java

Optimize some UnitTest case cost time sharply

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/RemoteMetadataServiceImpl.java

Fix Class.forName when publish ServiceDefinition

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java

[3.0] TimeoutCheckTask should be cancelled when DefaultFuture has been cancelled

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture2.java

[3.0-Triple] TimeoutCheckTask should be cancelled when DefaultFuture2 has been cancel

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java

#8880
* set the client field of LazyConnectExchangeClient  to null at the end of close() and close(int timeout) methods
* move close status setting from HeaderExchangeChannel close(timeout) to close()

[3.0] set client to null at LazyConnectExchangeClient close methods

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java
dubbo-remoting/dubbo-remoting-http/src/test/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpBinderTest.java

fix #8919 on master
* add destroy() calling to close tomcat server port
* add NetUtils.isPortInUsed() from branch 3.0

[master] add destroy() calling to close tomcat server port

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClientTest.java

fix #8880 on master
* set the client field of LazyConnectExchangeClient  to null at the end of close() and close(int timeout) methods
* move close status setting from HeaderExchangeChannel close(timeout) to close()

[master] set client to null at LazyConnectExchangeClient close methods

---

dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java

[3.0] Fix-#8506 MultipleRegistry remove duplicate URL

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceURLBuilder.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/MetadataServiceURLBuilderTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/StandardMetadataServiceURLBuilderTest.java

Add unit test for StandardMetadataServiceURLBuilder

Add unit test for StandardMetadataServiceURLBuilder

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/MultiMessageHandler.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatHandlerTest.java

#8929
* catch handler.caught() throwable of MultiMessageHandler
* reset ChannelHandlers after each testing of HeartbeatHandlerTest

[master] catch handler.caught() throwable of MultiMessageHandler

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/MultiMessageHandler.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatHandlerTest.java

[3.0] catch handler.caught() throwable of MultiMessageHandler

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java

Revert LinkedHashMap in Invocation to HashMap

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-config/dubbo-config-spring/pom.xml
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/propertyconfigurer/consumer3/PropertySourcesInJavaConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java

* Destroy executor services
* `dubbo-config-spring`  surefire plugin  `reuseForks=true`
* Fix unregister `DubboShutdownHook` error
* Fix `DecodeableRpcResult`  read config NPE
* Improve registry center of tests: PropertySourcesInJavaConfigTest, JavaConfigReferenceBeanTest

[3.0] destroy executor and improve tests 0926

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

issue #8240
这个bug可能是因为这个PR引起的：#7965
当执行`DubboBootstrap#destroy()`的时候，`clear()`方法清除了`ConfigManager`的缓存
https://github1s.com/apache/dubbo/blob/master/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java#L1273-L1274
然后`DubboShutdownHook.destroyAll();`中去销毁`protocol`的时候去拿了`ApplicationConfig`，因为上面已经在缓存中清除了，所以报了NPE。
https://github1s.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java#L575-L576
另外`clear();`、`shutdown();`名字起的不是很好，我一并修改了。

[master] Fix #8240, on branch master, when provider and consumer stop cause NPE

---

dubbo-common/src/main/java/org/apache/dubbo/common/URLBuilder.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/tps/DefaultTPSLimiter.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/tps/DefaultTPSLimiterTest.java

Fix https://github.com/apache/dubbo/issues/4856

Support TPS config for method level

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java

Fix default ApplicationModel/FrameworkModel NPE
see https://github.com/apache/dubbo/runs/4042205535?check_suite_focus=true
```
[INFO] [29/10/21 03:20:24:347 UTC] ERROR listener.ServiceInstancesChangedListener:  [DUBBO] Failed to load service metadata, meta type is local, dubbo version: 3.0.5-SNAPSHOT, current host: 10.1.0.14
[INFO] java.lang.NullPointerException
[INFO] 	at org.apache.dubbo.registry.client.metadata.MetadataUtils.referProxy(MetadataUtils.java:82)
[INFO] 	at org.apache.dubbo.registry.client.metadata.MetadataUtils.lambda$getMetadataServiceProxy$0(MetadataUtils.java:67)
[INFO] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[INFO] 	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getMetadataServiceProxy(MetadataUtils.j …
```

[3.0] Fix default ApplicationModel NPE

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Some configuration working at the consumer cluster, we should not override by the configuration of provider cluster

[3.0] consumer cluster's configuration should not override by the configuration of provider cluster

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java

Avoid blocking `ApplicationModel.defaultModel()` calls during FrameworkModel destruction

[3.0] Avoid blocking `ApplicationModel.defaultModel()` during destroying

---

dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/FailbackRegistryTest.java

Fix `FailbackRegistryTest.testDoRetry()` test failure on windows.
```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.201 s <<< FAILURE! - in org.apache.dubbo.registry.support.FailbackRegistryTest
[ERROR] org.apache.dubbo.registry.support.FailbackRegistryTest.testDoRetry  Time elapsed: 1.187 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
at org.apache.dubbo.registry.support.FailbackRegistryTest.testDoRetry(FailbackRegistryTest.java:86)
```

[3.0] Fix testDoRetry failure on windows

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-config/dubbo-config-api/pom.xml
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/metadata/MetadataServiceExporterTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java

The protocol will always be Dubbo while the port is determined by following below steps:
1. Check explicitly specified port
2. Try to find currently working Dubbo protocol port by terating protocols 
3. use random port

change way to determine the port that metadata service will listen on

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java

#9168 
* shutdown export,refer executor at destroyExecutorRepository instead of onStarted

[3.0] Patch DefaultApplicationDeployer for delay exporting

---

dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboService.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ModuleConfigManager.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceCreator.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceCreatorTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/issues/issue9172/MultipleConsumerAndProviderTest.java
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/issues/issue9172/consumer.properties
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/issues/issue9172/provider.properties

* Lookup consumer config of `@DubboReference.consumer()` from `ModuleConfigManager`,  fix #9172
* Deprecate `@DubboReference.application()` and `@DubboService.application()`
* ModuleConfigManager delegates read methods of application ConfigManager 
* org.apache.dubbo.config.spring.issues.issue9172.MultipleConsumerAndProviderTest

[3.0] Fix @DubboReference.consumer() lookup error

---

dubbo-common/src/main/java/org/apache/dubbo/common/deploy/AbstractDeployer.java
dubbo-common/src/main/java/org/apache/dubbo/common/deploy/Deployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java

* Catch deploy error
* Improve module start waiting, if no async export/refer services, do not wait for started on new thread.

Catch deploy error, improve module start waiting

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/Compressor.java

IdentityCompressor and Compressor#NONE obtained through SPI are not the same object, causing OutboundTransportObserver#calcCompressFlag to perform IdentityCompressor.NONE.equals(compressor) to return false

Fix Compressor's getCompressor method

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/SslContexts.java
dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcOptionsUtils.java

fix #7161
`org.apache.dubbo.config.SslConfig#getServerKeyCertChainPathStream`  each call will create a new stream,should be closed after use.
```
public InputStream getServerKeyCertChainPathStream() throws IOException {
if (serverKeyCertChainPath != null) {
serverKeyCertChainPathStream = IOUtils.getURL(serverKeyCertChainPath).openStream();
}
return serverKeyCertChainPathStream;
}
```

[Master]Fix netty ssl file leak

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/SslContexts.java
dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcOptionsUtils.java

For #9197 change forget close `serverTrustCertCollectionPathStream`.

[Master]Fix netty server ssl context file leak

---

dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/config/ZookeeperConfig.java

Change zk server admin port to 18081/18082,  to avoid port confilcts.
Fix https://github.com/apache/dubbo/issues/9268

[3.0] change zk server admin port to 1808x

---

dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/Constants.java
dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/MonitorService.java
dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java
dubbo-monitor/dubbo-monitor-api/src/test/java/org/apache/dubbo/monitor/support/MonitorFilterTest.java
dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java
dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/Statistics.java
dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/StatisticsItem.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/DubboMonitorTest.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/MetricsFilterTest.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/StatisticsTest.java

For **dubbo-monitor** module
- Unify the constants into `Constants`(Move the constants of the original `MonitorService` to `Constants`) class
- Abstract the statistical array into StatisticsItem(Originally used `AtomicReference<long[]>`, now adjusted to `AtomicReference<StatisticsItem>`)

Unify the constants into Constants class and abstract the statistical array into StatisticsItem

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigBeanInitializer.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/issues/issue9207/ConfigCenterBeanTest.java
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/issues/issue9207/dubbo-properties-in-configcenter.properties

Fix `dubbo.config-center.include-spring-env` handling, fix #9207
1. Load `ConfigCenterBean` from props in ` DubboConfigBeanInitializer`
2. Inject spring context by beanFactory.initializeBean(configCenterBean,..)

Fix config-center includeSpringEnv #9207

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/InvokeTelnet.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/InvokeTelnetTest.java

If the user directly uses the invocation method without the service name prefix, that is, `invoke sayHello (xxxx)`, and has not executed the `cd xxx `command beforehand, the NPE problem will occur

Fix the problem of InvokeTelnet that user use [invoke sayHello(xxx)] without executing the cd command first

---

dubbo-common/src/main/java/org/apache/dubbo/common/timer/HashedWheelTimer.java

* The queue used by cancelledTimeouts is LinkedBlockingQueue
* Rename `MpscLinkedQueue` to `LinkedBlockingQueue` in annotation

optimize annotation

---

.gitignore
dubbo-test/dubbo-test-check/pom.xml
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/ZookeeperRegistryCenter.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/context/ZookeeperContext.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/initializer/ConfigZookeeperInitializer.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/initializer/DownloadZookeeperInitializer.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/initializer/UnpackZookeeperInitializer.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/StartZookeeperUnixProcessor.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/StartZookeeperWindowsProcessor.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/StopZookeeperUnixProcessor.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/ZookeeperUnixProcessor.java
pom.xml

see: https://github.com/apache/dubbo/issues/9227
1. Avoid the concurrence when donwloading zookeeper binary file
2. Destroy the process after stopped zookeeper instance in Unix OS
3. Support to provide zookeeper binary file by use self and avoid to download zookeeper binary file

fix: Fix the bug of downloading zk binary file

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetricsConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MonitorConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/SslConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ConfigCenterBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java

Add ScopeModel Constructor for Config

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

According to the official document [https://dubbo.apache.org/zh/docs/advanced/set-host/](https://dubbo.apache.org/zh/docs/advanced/set-host/)，`DUBBO_PORT_TO_REGISTRY`  env shoud not affect the binding port，but current code is incorrect.

fix: custom registry port

---

dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalTest.java

In InternalThreadLocalTest, testSize fails when run after testSetAndGet, testRemove, or testRemoveAll in the same test class. I found that running InternalThreadLocalMap.remove() before testSize ensures the starting state is correct such that testSize can pass even when run after those three tests. I introduced the setup method to ensure this resetting logic is run before each test. Please let me know if there is a more preferred way to address this issue.
Including a setup method that sets the state through InternalThreadLocalMap.remove().

Including setup method to clean state between tests

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

Fix the problem that Curator[5]ZookeeperClient does not handle RegistryConfig#session value

Fix the problem that Curator[5]ZookeeperClient does not handle RegistryConfig#session value

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/DefaultFilterChainBuilder.java

optimize of DefaultFilterChainBuilder

[3.0] optimize of DefaultFilterChainBuilder

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java

Reduce memory allocation in ServiceDiscovery

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/DefaultHessian2FactoryInitializer.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/WhitelistHessian2FactoryInitializer.java

configure -Ddubbo.hessian.allowNonSerializable=true to enable allowNonSerializable for hessian-lite
Fix #9339

Add system properties to support allow non-serializable class

---

dubbo-common/src/main/java/org/apache/dubbo/common/BaseServiceMetadata.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/invoker/DelegateProviderMetaDataInvoker.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/SimpleReferenceCache.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConfigScopeModelInitializerTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/metadata/ServiceInstanceHostPortCustomizerTest.java

Use existing methods to generate serviceKey for SimpleReferenceCache 
1.Use existing methods to generate serviceKey for SimpleReferenceCache
2.add test case for ServiceInstanceHostPortCustomizer
3.Remove the toString method of AbstractConfig subclass
4.Add unit test for ConfigScopeModelInitializer

Use existing methods to generate serviceKey for SimpleReferenceCache

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java

[3.0] Add router fail fast option

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java

When using extended parameters, Dubbo will keep the original keys if they are of snake/camel case format while at the same time creating new duplicate keys - dash-separated/kebab-case keys for compatibility purpose. For example, `testKey=value` will finally have a duplication of `test-key=value` in URL.
The following different ways of configurations are supported to add extra parameters:
1. spring boot `application.properties`
```yaml
dubbo:
application:
name: dubbo-springboot-demo-provider
parameters:
testKey: value
```
2. API/XML/Annotation/Spring-boot `dubbo.properties`
```properties
dubbo.registry.parameters=[{testKey:value},{testKey2:value2}]
```
3. XML
```xml
<dubbo:application name="demo-provider">
<dubbo:parameter key="testKey" value="value"/>
</dubbo:application>
```

keep both old and new keys

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/CacheableFailbackRegistryTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/MockCacheableRegistryImpl.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListenerTest.java
dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java
dubbo-registry/dubbo-registry-multiple/src/test/java/org/apache/dubbo/registry/multiple/MultipleRegistry2S2RTest.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

Stop empty address notification from taking effect on consumer side.
application.yml
```yaml
dubbo: 
registry:
enable-empty-protection: true/false
```
dubbo.properties
```properties
dubbo.registry.enable-empty-protection: true/false
```

support empty address protection

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java

[master] Fix #9086 NPE

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/config/DubboConfigEarlyRegistrationPostProcessor.java

add cache for DubboConfigEarlyInitializationPostProcessor#hasRegisteredCommonAnnotationBeanPostProcessor(#9397)

Optimize some code for DubboConfigEarlyRegistrationPostProcessor (#9397)

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/config/DubboConfigDefaultPropertyValueBeanPostProcessor.java

`Ordered.LOWEST_PRECEDENCE + 1` is equal to `Ordered.HIGHEST_PRECEDENCE`, using `Ordered.HIGHEST_PRECEDENCE` is more readable.
Improve the readability of the getOrder method.
Improve the readability of the getOrder method.
Same semantics, avoiding integer overflow.

Improve the readability of the getOrder method

---

.github/workflows/build-and-test-3.yml

see: #9430
Try to download zookeeper archive binary from different repositories

fix: Download zookeeper archive binary in github workflow

---

compiler/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/pom.xml
pom.xml

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046
> It was found that the fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was incomplete in certain non-default configurations. This could allows attackers with control over Thread Context Map (MDC) input data when the logging configuration uses a non-default Pattern Layout with either a Context Lookup (for example, $${ctx:loginId}) or a Thread Context Map pattern (%X, %mdc, or %MDC) to craft malicious input data using a JNDI Lookup pattern resulting in a denial of service (DOS) attack. Log4j 2.15.0 makes a best-effort attempt to restrict JNDI LDAP lookups to localhost by default. Log4j 2.16.0 fixes this issue by removing support for message lookup patterns and disabling JNDI functionality by default.

upgrade log4j2 to 2.16.0

---

dubbo-spring-boot/dubbo-spring-boot-actuator/README.md
dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointAnnotationAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/condition/CompatibleOnEnabledEndpointCondition.java

fix #9394 
CompatibleOnEnabledEndpointCondition only handle `org.springframework.boot.actuate.autoconfigure.endpoint.condition.OnEnabledEndpointCondition` (Spring Boot 2.0.0 ~ 2.2.x)
Endpint beans add @ConditionalOnAvailableEndpoint derectly (Spring Boot 2.2x +)
you can verify by this case: https://github.com/gitchenjh/dubbo-test

[3.0] dubbo-spring-boot-actuator compatible with Spring Boot Actuator 2.6.x

---

dubbo-spring-boot/dubbo-spring-boot-actuator/README.md
dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointAnnotationAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/condition/CompatibleOnEnabledEndpointCondition.java

dubbo-spring-boot-actuator compatible with Spring Boot Actuator 2.6.x

---

compiler/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/pom.xml
pom.xml

See https://github.com/apache/dubbo/pull/9438 comments
https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45105

Upgrade log4j2 version to 2.17.0

---

dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/util/CuratorFrameworkUtils.java

Fix the issue that ApplicationConfig#getmetadataserviceprotocol method maps the wrong key

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java

related issue https://github.com/apache/dubbo/issues/9440, https://github.com/apache/dubbo/pull/9442
The issue was found firstly when using instance-level service discovery, URL instance in LazyConnectionClient is InstanceAddressURL which relies on consumer URL in thread-local being set properly.

[3.0] Passing parameters down from Protocol to Remoting components directly

---

dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java

[2.7] Fix pond ignore in URLStrParser

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/DefaultFilterChainBuilder.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/FilterChainBuilder.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/filter/DefaultFilterChainBuilderTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/wrapper/AbstractClusterTest.java
dubbo-common/src/main/java/org/apache/dubbo/common/Experimental.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/AbstractRegistryCenterExporterListener.java
dubbo-plugin/dubbo-auth/src/test/java/org/apache/dubbo/auth/filter/ProviderAuthFilterTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncContextImpl.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/BaseFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/ListenableFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContextAttachment.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServiceContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ClassLoaderCallbackFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ContextFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java
dubbo-rpc/dubbo-rpc-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcContextTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/CompatibleFilterFilterTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/EchoFilterTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/TimeoutFilterTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvocation.java

related issues https://github.com/apache/dubbo/issues/9461 https://github.com/apache/dubbo/issues/8602
* RpcContext deep/shallow copy before async context switch, see AsyncRpcResult constructor.
* Update Future instance in RpcContext to guarantee user registered callbacks will be triggered after framework filter callbacks. See AyncRpcResult.whenCompleteWithContext()
* Refactor recursive filter callback stack to flat iteration to reduce context switch, see FilterChainBuilder.java

fix async call issues, rpc context and response future callback race conditions

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java

Support `responseObserver.onError` emit error to client

[3.0-Triple] Support stream err

---

.github/workflows/build-and-test-3.yml
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/ZookeeperRegistryCenter.java

see #9478 
1. Set priorities for the downloaed zookeeper path
2. Support environment variables

fix: Obtain the downloaded zookeeper path when run unit test

---

dubbo-dependencies/dubbo-dependencies-zookeeper-curator5/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
dubbo-dependencies/pom.xml
dubbo-distribution/dubbo-bom/pom.xml

Use lower version zookeeper and curator dependencies by default.

Distinguish zookeeper module from zookeeper-curator5

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/FutureContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java

- Add `future.sync.set` property to indicate whether set future when sync invoke
- Add `future.clear.once` property to indicate whether clear future once get

[3.0] Support Optional Clear Future

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ChannelWrappedInvoker.java

Fix callback timeout

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleTailHandler.java

Fix Http2SettingFrame and Http2SettingAckFrame unhandled exception

[3.0-Triple] Add tail handler

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/Metadata.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/QueuedCommand.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/ClientStreamTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/ServerStreamTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocolTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/WriteQueueTest.java

Fix  https://github.com/apache/dubbo/issues/9466
1. Add timeout check before send response at server side
2. Add channel active check before write to wire

[3.0-Triple] Add timeout check before send response

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java

Fixes #9086 again to solve race condition issue.

[master] Fixes #9086 again to solve race condition issue.

---

dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/resources/spring/dubbo-consumer.xml

The wrong metadata report address was used, causing the demo project to fail to start.
Change the metadata report address to the correct local IP address.

[master] fix: dubbo-demo-xml-consumer use correct metadata-report address

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Fix the problem that static tag does not work

Fix a problem where tag routing does not work when using static tags

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvokerTest.java

Fix the problem of wrong number of retries in failback mode. When the retries value is zero, the logic in failback mode resets it to the default value of 3, making it impossible to turn off the retry mechanism.
**before**
```java
if (retriesConfig <= 0) {
retriesConfig = DEFAULT_FAILBACK_TIMES;
}
```
**after**
```java
if (retriesConfig < 0) {
retriesConfig = DEFAULT_FAILBACK_TIMES;
}
```
**1. Reset retriesConfig to its default value only when it is zero.**
**2. Add some retry logs.**
Some test units.

fix: Fix the problem of wrong number of retries in failback mode

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/DeployerReadinessProbe.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/DeployerStartupProbe.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/ReadyTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/StartupTest.java

fix issue https://github.com/apache/dubbo/issues/9634
ReadinessProbe and StartupProbe cannot work well because of scope level mismatch.

fix probes

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/mock/MockServiceDiscovery.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/registry/MockServiceDiscovery.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/support/MockServiceDiscovery.java
dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastServiceDiscovery.java

- Fix when last ServiceInstancesChangedListener destroyed, service discovery registry notify new address will cause dead lock issue.
- Fix when reporting metadataInfo,  metadataInfo changed will cause metadataReport unexcepted content issue.

[3.0] Fix Service Discovery related concurrency issue

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java

The DubboDeployApplicationListener currently processes all applicationContext event from current ApplicationContext and all its child applicationContext. It will cause duplicate deployment and ApplicationDeployListener will receive multi duplicate vents. The most bad is that, when the application uses hot load of  child spring context, and destroys the child spring context at runtime,  the dubbo infrastructure will be destroyed once receives the child spring context's ContextClosedEvent. 
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java
see the case code in …

only process context event of original application context

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/AbstractReferenceBuilder.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilderTest.java

consumer support specify serialization type
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractReferenceConfig.java 
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboReference.java 
dubbo-common/src/main/java/org/apache/dubbo/config/annotation/Reference.java 
dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/AbstractReferenceBuilder.java

feat: consumer support specify serialization type

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalMap.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalTest.java

Fix InternalThreadLocalMap capacity expands overflow; Change access level of field InternalThreadLocalMap.UNSET to package private.
Related issues and PRs:
https://github.com/netty/netty/issues/11929
https://github.com/netty/netty/issues/11933
https://github.com/netty/netty/pull/11934
dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalMap.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalTest.java
Passes the unit tests of `InternalThreadLocalTest`.
- [] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other …

Fix InternalThreadLocalMap capacity expands overflow; Change access level of field InternalThreadLocalMap.UNSET to package private

---

dubbo-common/src/main/java/org/apache/dubbo/common/cache/FileCacheStore.java
dubbo-common/src/main/java/org/apache/dubbo/common/cache/FileCacheStoreFactory.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/cache/FileCacheStoreFactoryTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/cache/FileCacheStoreTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/StringUtilsTest.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/CountTelnet.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/PortTelnet.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/SelectTelnet.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/ShutdownTelnet.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/LogTelnetHandler.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/TraceTelnetHandler.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/MetaCacheManager.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/store/MetaCacheManagerTest.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/ClearTelnetHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/LogTelnetHandler.java

1. Prevent FileCacheStore cause crash when writing while reading
2. Add FileCacheStoreFactory to share FileCacheStore in the whole classloader. Prevent cache conflict in two application.
3. Strict legal name. Preven the recursion bypass.
4. Add `max file size limit` in `refreshCache`.
5. Add Empty Cache for cache conflict.
6. Remove auto generation of the file index.

[3.0] FileCacheStore refactor & Add FileCacheStoreFactory

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/directory/MockDirInvocation.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouterTest.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceDescriptor.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ScopeModelUtilTest.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invocation.java
dubbo-compatible/src/test/java/org/apache/dubbo/service/MockInvocation.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/ServiceDiscoveryMigrationInvoker.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvocation.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java

- Prevent `ServiceConfig#exportUrl` fetch service definition from global data.
- Make `serviceDefinitions` map work
- `ServiceDescriptor#serviceName`: distinguish serviceName and interfaceName
- Refactor `isInternal` property in scope model

[3.0] ServiceDefinition usage refactor & distinguish serviceName and interfaceName

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java

netty4支持继承扩展
比如直接绑定lz4的压缩encode和decode
目的：
机房内代理rpc的服务，机房间的通信使用dubbo但是需要扩展通讯的方式，希望可以支持扩展

netty4_extend

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Fix the issue that providerUrl could not be registered in the application-level registry when simplified is set to true

---

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

Fix the issue that the default protocol configured by the consumer does not take effect in the application-level mode
issue #9682

Fix the issue that the default protocol configured by the consumer does not take effect in the application-level mode

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java

fix bug lazy client ThreadlessExecutor.sharedExecutor is null error
发现的现象：
lazy模式的dubboreference第一次调用不会返回直到超时（实际数据已经很快返回收到）
问题点：
ThreadlessExecutor.execute函数，waiting = false，所以sharedExecutor is null 报空指针
原因分析：
lazy模式ThreadlessExecutor先创建，后Exchangers.connect导致（因为线程创建在AbstractClient的构造函数initExecutor）

fix bug lazy client share_executor is null

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java

issue #9647
When processing all properties of `@Method`, the `parameters` property is an empty array, resulting in null return at `obj = DubboAnnotationUtils.convertParameters((String[]) obj);`, the following `else if (obj.getClass().isArray ())` NPE appears

Fix the problem that NPE may appear in ReferenceBeanSupport#convertToString method

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/src/main/resources/spring/dubbo-provider.xml
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReport.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/NopMetadataReport.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportFactoryTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java

When metadata type is set to 
* Local,  will not publish metadata to remote center, use `dubbo.metadata-report.report-metadata=true` to enable remote publish.
* Remote, will always publish metadata to remote center.

add more configuration items for control of remote metadata registration

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java

Fix #9666
A -> B -> C
When B invoke C, url from TL should be changed to cluster invoker's url.

[3.0] Fix isConsumerSide not work in sub invoke

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ProviderModel.java

also see https://github.com/apache/dubbo/pull/9777

Fix concurrent modification exception of stated urls

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalanceTest.java

see https://github.com/apache/dubbo/pull/9786

Fix 2.7 multi registry

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemoryLimitedLinkedBlockingQueue.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemoryLimiter.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/MemoryLimitedLinkedBlockingQueueTest.java

see https://github.com/apache/dubbo/issues/9721 and https://github.com/apache/dubbo/pull/9722

[ISSUE #9721] support MemoryLimitedLinkedBlockingQueue

---

compiler/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/pom.xml
pom.xml

upgrade logging jars due to security issues

---

dubbo-dependencies-bom/pom.xml

https://github.com/apache/dubbo/issues/9812

[issue-9812] upgrade libthrift due to security issue

---

dubbo-dependencies-bom/pom.xml

https://github.com/apache/dubbo/issues/9810
security concern over resteasy-client

[issue-9810] update resteasy version due to cve

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java

`org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker#select` may return `null` when `invokers` list is empty.
add null check in `org.apache.dubbo.rpc.cluster.support.registry.ZoneAwareClusterInvoker#doInvoke`

[3.0] Fix npe in zone aware invoker

---

dubbo-common/src/main/java/org/apache/dubbo/metadata/definition/builder/MapTypeBuilder.java

fix #9847
翻了以前的一些issue 比如 https://github.com/apache/dubbo/issues/8212 和 https://github.com/apache/dubbo/issues/5122 都提到过这个问题，我认为这段强校验的代码没必要存在。
if (actualTypeArgsLength != 2) {
throw new IllegalArgumentException(MessageFormat.format(
"[ServiceDefinitionBuilder] Map type [{0}] with unexpected amount of arguments [{1}]."
+ Arrays.toString(actualTypeArgs), type, actualTypeArgs));
}
虽然可以通过SPI来扩展，但是还是给用户带来了一定的困扰。

[3.0] fix #9847

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

When constructing the request data, the RpcContext data can not be cleaned up in advance, because the `path` and other information depend on the RpcContext

Fix triple protocol async call

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/builder/MapTypeBuilder.java

fix #9847
翻了以前的一些issue 比如 https://github.com/apache/dubbo/issues/8212 和 https://github.com/apache/dubbo/issues/5122 都提到过这个问题，我认为这段强校验的代码没必要存在。
if (actualTypeArgsLength != 2) {
throw new IllegalArgumentException(MessageFormat.format(
"[ServiceDefinitionBuilder] Map type [{0}] with unexpected amount of arguments [{1}]."
+ Arrays.toString(actualTypeArgs), type, actualTypeArgs));
}
虽然可以通过SPI来扩展，但是还是给用户带来了一定的困扰。

[master] fix #9847

---

dubbo-dependencies-bom/pom.xml

See details: https://tanzu.vmware.com/security/cve-2022-22965

Bump spring to 5.2.20 to mitigate CVE-2022-22965

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java

Add detail log for `generic` and `interface` type conflicts. 
```
Found conflicting attributes for interface type: [interfaceClass=org.apache.dubbo.config.api.DemoService] and [generic=true], because the 'generic' attribute has higher priority than 'interfaceClass', so change 'interfaceClass' to 'org.apache.dubbo.rpc.service.GenericService'. Note: it will make this reference bean as a candidate bean of type 'org.apache.dubbo.rpc.service.GenericService' instead of 'org.apache.dubbo.config.api.DemoService' when resolving dependency in Spring., dubbo version: , current host: 30.250.193.243
```

[3.x] add detail log for generic and interface type conflicts

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStream.java

Add too many close listeners to parent channel  will cause mem leak

[3.0 Triple] Fix mem leak

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServerHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/GracefulShutdown.java

[3.0 Triple] Fix graceful shutdown not work

---

dubbo-dependencies-bom/pom.xml
dubbo-rpc/dubbo-rpc-triple/pom.xml
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/compressor/Snappy.java
dubbo-rpc/dubbo-rpc-triple/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.protocol.tri.compressor.Compressor
dubbo-rpc/dubbo-rpc-triple/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.protocol.tri.compressor.DeCompressor
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/compressor/SnappyTest.java

tri 压缩算法支持snappy，它的目标并非最大压缩率或与其他压缩程序库的兼容性，而是非常高的速度和合理的压缩率。

[3.0] tri support Snappy

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocal.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServiceContext.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

- Recover RpcServiceContext after consumer invocation. (For AsyncContext.start after consumer invocation)
- Fix InvokeMode loss after RpcInvocation cloned
- Clone RpcResult in InjvmInvoker. (For attribute clean up)

[3.0] Fix some context related issues

---

dubbo-dependencies-bom/pom.xml
dubbo-rpc/dubbo-rpc-triple/pom.xml
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/compressor/Bzip2.java
dubbo-rpc/dubbo-rpc-triple/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.protocol.tri.compressor.Compressor
dubbo-rpc/dubbo-rpc-triple/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.protocol.tri.compressor.DeCompressor
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/compressor/Bzip2Test.java

tri 压缩算法支持bzip2，bzip2比传统的gzip的压缩效率更高，但是它的压缩速度较慢

[3.0] tri support Bzip2

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java

This PR inspired by issue #9910, when nacos enabled authenticate,
RegistryConfig and ConfigCenterConfig setUsername and setPassword is not working
also fixed in master PR #9941 
org.apache.dubbo.registry.nacos.util.NacosNamingServiceUtils
org.apache.dubbo.configcenter.support.nacos.NacosDynamicConfiguration

[3.0] Fix can't authenticate by username and password when use Nacos

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

[3.0-Triple] Fix response type use hessian2 not hessian4

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java

fix the issue #9953 
Modified the way the logQueue is traversed to ensure that items are removed from the queue before throwing an exception.
修改了logQueue的遍历方式，确保在抛出异常前将item从队列中移除。

Fix issue#9953

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/SimpleReferenceCache.java

related issue https://github.com/apache/dubbo/issues/9829
This patch is more like a code optimization, it cannot fully solve the issue mentioned in #9829. We cannot  simply change the mapping key for now. So the best way to solve it is to try to reuse ReferenceConfig all the time.

Fix #9829, SimpleReferenceCache bug to cause genericInvoke high latency

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

fix issue #9922 , merge the provider side parameters exclude tag

 fix issue#9922, merge the provider side parameters exclude tag

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

init(org.apache.dubbo.config.ReferenceConfig#init) is a synchronized method, and field initialized only access in init, so volatile on initialized is redundant.
remove redundant volatile flag on initialized

remove redundant volatile on initialized

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DefaultMetadataParamsFilter.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataParamsFilter.java
dubbo-metadata/dubbo-metadata-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.MetadataParamsFilter
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/MetadataInfoTest.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/filter/CustomizedParamsFilter.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/filter/ExcludedParamsFilter.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/filter/ExcludedParamsFilter2.java
dubbo-metadata/dubbo-metadata-api/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.MetadataParamsFilter
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataCustomizerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/store/ExcludedParamsFilter.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/store/ExcludedParamsFilter2.java
dubbo-registry/dubbo-registry-api/src/test/resources/META-INF/dubbo/org.apache.dubbo.metadata.MetadataParamsFilter

related issue #9990
New definition of ParamsFilter is as below
```java
/**
* This filter applies an either 'include' or 'exclude' policy with 'include' having higher priority.
* That means if 'include' is specified then params specified in 'exclude' will be ignored
*
* If multiple Filter extensions are provided, then,
* 1. All params specified as should be included within different Filter extension instances will determine the params that will finally be used.
* 2. If none of the Filter extensions specified any params as should be included, then the final effective params would be those left after removed all the params specified as should be excluded.
*
* It is recommended for most users to use 'exclude' policy for service params and 'include' policy for instance params.
* Please use …
```

Add 'exclude' filtering policy for instance-level params

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/SimpleReferenceCache.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ReferenceCacheTest.java

related to https://github.com/apache/dubbo/issues/10012

Followup of #10010, share proxy instance among References that have the same key.

---

dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboService.java

fix #10035 
change "DubboService#loadbalance() default ClusterRules.EMPTY"  to " loadbalance() default LoadbalanceRules.EMPTY"

[3.0] fix #10035 ,In DubboService.java loadbalance does not have a correct default value

---

dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsInterfaceDisplayNameHasMetaCharactersTest.java

[3.0] fix UT regex spell mistake

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListenerTest.java

issue #10079
related solution https://github.com/apache/dubbo/pull/10076

fix #10079, address notification issue with service discovery multi subscription

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java

fix #10059, fix ZookeeperDynamicConfiguration remove cache listener mistake

[2.7] fix ZookeeperDynamicConfiguration remove cache listener mistake

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/AccessLogFilterTest.java

[3.0] Cherry pick #9978 to 3.0

---

dubbo-common/src/test/java/org/apache/dubbo/common/utils/SerializeClassCheckerTest.java

In `dubbo-common`, several test cases in `PojoUtilsTest.java` can trigger `java.lang.IllegalArgumentException`  when being run after running tests in `SerializeClassCheckerTest.java`. 
For example, if we run the following command:
```
o=reversealphabetical; mvn test -Dsurefire.runOrder=$o -Dtest=org.apache.dubbo.common.utils.PojoUtilsTest#testArrayToCollection,SerializeClassCheckerTest#testBlockAll
```
We get the following error:
```
[ERROR] org.apache.dubbo.common.utils.PojoUtilsTest.testArrayToCollection  Time elapsed: 0.61 s  <<< ERROR!
java.lang.IllegalArgumentException: Trigger the safety barrier! Catch not allowed serialize class. Class name: org.apache.dubbo.common.model.person . This means currently maybe being attacking by others.If you are sure this is a mistake, please add this …
```

Fixed test order dependencies in class `PojoUtilsTest`

---

dubbo-common/src/main/java/org/apache/dubbo/common/status/support/LoadStatusChecker.java
dubbo-common/src/main/java/org/apache/dubbo/common/system/OperatingSystemBeanManager.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java

Now system metrics are obtained from com.sun.management.OperatingSystemMXBean for HotSpot JVM, but these are in com.ibm.lang.management.OperatingSystemMXBean for Ibm J9, so need to deduce the target source.

Support for ibm J9 

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLPlainParam.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicParamTable.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicValues.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/FixedParamValue.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/ParamValue.java

assume key is in constant pool, improve performance

[3.0] Improve compressed URL param performance

---

dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java

fix #9910, metadata-report support a separate configuration username and password
have been fixed in 3.x #9912

fix #9910, metadata-report support a separate configuration username and password

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java

This PR inspired by issue #9910, when nacos enabled authenticate,
RegistryConfig and ConfigCenterConfig setUsername and setPassword is not working
org.apache.dubbo.registry.nacos.util.NacosNamingServiceUtils
org.apache.dubbo.configcenter.support.nacos.NacosDynamicConfiguration

Fix can't authenticate by username and password when use Nacos

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemoryLimitCalculator.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemoryLimiter.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemorySafeLinkedBlockingQueue.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/cached/CachedThreadPool.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/fixed/FixedThreadPool.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/limited/LimitedThreadPool.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/MemorySafeLinkedBlockingQueueTest.java

Can completely solve the OOM problem caused by {@link java.util.concurrent.LinkedBlockingQueue}, does not depend on {@link java.lang.instrument.Instrumentation} and is easier to use than {@link MemoryLimitedLinkedBlockingQueue}.

[ISSUE #10020] add MemorySafeLinkedBlockingQueue

---

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

fix bug #10181 
make ``EventThread`` non-blocking to fix bug #10181

Fixed the problem that the service was offline for a long time without re-registration

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/InvokeTelnetHandler.java

telnet command add context argument.
1. command add a new option.
2. parse this option.
3. put it into attachment.

#9940 feat: telnet invoke command with context argument. 

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/MetaCacheManager.java

Remove `LRUCache` initialization, Because it's initialized in the parent class

Perf(MataCacheManager):Remove cache initialization

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/LFUCacheTest.java

Fix #10085, LFUCache Memory leak problem
revert #7967

Fix #10085, LFUCache Memory leak problem

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectOutput.java

fix #10219
remove ``ThreadLocal`` from ``Hessian2ObjectInput`` and ``Hessian2ObjectOutput ``

[2.7] fix memory leak

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java

Fix repeatedly creating registry when multiple threads running at the same time (#10249)

[ISSUES #10249]Fix repeatedly creating registry in AbstractRegistryFactory#getRegistry #10249

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcContext.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/DefaultCommandExecutor.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryProtocolTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/ExchangeCodecTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/TelnetCodecTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcContext.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java

Standard code comment format.

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java

fix UnsupportedOperationException in invokeSetParameters

---

dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

fix bug #10181 
make ``EventThread`` non-blocking to fix bug #10181 
ref PR: #10182

[3.0] Fixed the problem that the service was offline for a long time without re-registration

---

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidatorNew.java

I think the parameter check is not an error, it is an expected behavior, so the log level should not be error, the info level is more reasonable.
**Another option is to give a configuration that allows developers to specify the level of logging they need.**
We can discuss which option is more reasonable?
Modify the parameter validation log level to info

refactor: Modify the parameter validation log level to info

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AsyncToSyncInvoker.java

Interrupt current thread when InterruptException occur
org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.java
``` java
@Override
public Result invoke(Invocation invocation) throws RpcException {
Result asyncResult = invoker.invoke(invocation);
try {
if (InvokeMode.SYNC == ((RpcInvocation) invocation).getInvokeMode()) {
asyncResult.get(Integer.MAX_VALUE, TimeUnit.MILLISECONDS);
}
} catch (InterruptedException e) {
// interrupt thread
Thread.currentThread().interrupt();
throw new RpcException("Interrupted unexpectedly while waiting for remote result to return!  method: " +
invocation.getMethodName() + ", provider: " + getUrl() + ", cause: " + e.getMessage(), e);
} 
return asyncResult;
}
```
Interrupt current thread when InterruptException occur

Interrupt current thread when InterruptException occur

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java

fix for java.lang.NullPointerException
底层调用方法：
org.apache.dubbo.metadata.MetadataInfo#getValidServiceInfo 
调用方：
org.apache.dubbo.registry.client.InstanceAddressURL#getServiceInfo
org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory#urlChanged
问题原因：底层调用方法会返回null，调用方没有判空，导致有可能造成空指针
解决方式：调用方增加判空逻辑

fix for issue 10303

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/metadata/MetadataServiceURLParamsMetadataCustomizerTest.java

fix  #10054 
use dubbo protocol port as metadata service default export port

fix metadata service export port incorrect issue

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java

更换 AbstractRegistry、AbstractRegistryFactory 和 CacheableFailbackRegistry 的日志实现。
Replace logging implementation with Error-Type-Aware Logger in AbstractRegistry, AbstractRegistryFactory, and CacheableFailbackRegistry.
在 CacheFailbackRegistry 加入错误码。
Adds error code in invocation of logger in CacheFailbackRegistry.
另附使用的错误码：

Replacing logger implementation of AbstractRegistry, AbstractRegistryFactory, and CacheableFailbackRegistry.

---

pom.xml

Fix `java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;`
https://github.com/eclipse/jetty.project/issues/3244
https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/

Patch maven compiler byte code not support

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/ListenerRegistryWrapper.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryNotifier.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceHostPortCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandler.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/ServiceDiscoveryMigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/util/CuratorFrameworkUtils.java

对 Registry 模块的日志实现进行全数替换。并在 RegistryDirectory 类中加入错误码。
Replace logging implementation with Error-Type-Aware Logger in all classes in registry module. Adding error code in RegistryDirectory.
另附迄今为止使用的错误码：
1-12 Failed to fetch (server) instance since …

Adding error code and replacing logger implementation of multiple classes in registry module.

---

dubbo-common/src/main/java/org/apache/dubbo/common/logger/support/FailsafeErrorTypeAwareLogger.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/FileSystemServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ReflectionBasedServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceDelegation.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceHostPortCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/StandardMetadataServiceURLBuilder.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

对 Registry 模块中多个类中加入错误码。
另附迄今为止使用的错误码：
1-14 - Failed to parse raw …

Adding error code to multiple classes in registry module.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java

当配置了`DUBBO_PORT_TO_REGISTRY `环境变量来改变注册端口时，会导致提供者无法提供服务(100%复现)，异常信息如下：
```
Not found exported service: hello-rpc/org.apache.dubbo.metadata.MetadataService:1.0.0:20880 in 
[hello-rpc/org.apache.dubbo.metadata.MetadataService:1.0.0:20885, com.example.dubbo3test.service.HelloService:20880], 
may be version or group mismatch , channel: consumer: /172.10.40.224:63160 --> provider: /172.10.40.224:20880, message:RpcInvocation [methodName=getMetadataInfo, parameterTypes=[class java.lang.String], arguments=[], attachments={input=231, path=org.apache.dubbo.metadata.MetadataService, dubbo=2.0.2, version=1.0.0, timeout=5000, group=hello-rpc}], dubbo version: 3.0.10, current host: 172.10.40.224
```
MetadataService的端口数据不正确(应该使用bindPort而不是registryPort)导致找不到对应的`exported service`。

fix: metadata service port error when config DUBBO_PORT_TO_REGISTRY env

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/ModuleEnvironment.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ModuleConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-common/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.context.ModuleExt
dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionDirectorTest.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/extension/SpringExtensionInjector.java

When spiXXX implements ScopeModelAware, ExtensionAccessorAware, the setXXX of ScopeModelAware and ExtensionAccessorAware does not need to be injected(ExtensionDirectorTest#testInjection can be reproduced)

Fix the problem of partial setXXX method injection of spi class

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/AbstractDynamicConfiguration.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/config/DubboConfigDefaultPropertyValueBeanPostProcessor.java
dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-metadata/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/javassist/JavassistProxyFactory.java

另附迄今为止使用的错误码：
1-14 - Failed to parse raw dynamic config. - 动态配置识别失败 …

Adding error code to multiple classes in multiple modules.

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java

all param no export to meta，param export will be error
like：
{"app":"utopia-channel-server","revision":"2f81280817228650c619cd9751a5e54d","services":{"main-a/com.utopia.channel.kernel.config.api.UChannelInstance:1.0.3:channel_dubbo":{"allParams":{"release":"3.0.10_fix","methods":"request","logger":"slf4j","deprecated":"false","dubbo":"2.0.2","interface":"com.utopia.channel.kernel.config.api.UChannelInstance","service-name-mapping":"true","threadpool":"ownerFixed","channel-codec":"channel_dubbo_v2","dynamic":"true","REGISTRY_CLUSTER":"global","anyhost":"true","group":"main-a","side":"provider","threads":"100","version":"1.0.3","register-mode":"instance","generic":"false","revision":"2.0.0","serialization":"kryo","metadata-type":"remote","application":"utopia-channel-server","channel_codec": …

all param no export to meta

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboExporter.java

dubbo2.7.x fix 
#6720 
https://github.com/apache/dubbo/pull/6720

fix_delete_error_exporter

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/eager/EagerThreadPool.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/fixed/FixedThreadPool.java
dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/Fastjson2CreatorManager.java
dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/java/JavaObjectInput.java
dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/java/JavaSerialization.java
dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/nativejava/NativeJavaSerialization.java

另附迄今为止使用的错误码：
0-1: Thread pool is EXHAUSTED! - 线程池资源耗尽。
1-14 - Failed …

Add error code 2-2, 6-1, 6-2, 0-1.

---

dubbo-compiler/src/main/resources/Dubbo3TripleStub.mustache
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/stub/StubInvocationUtil.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/stub/StubInvocationUtilTest.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

Remove processing streamObserver in TripleInvoker#invokeUnary
/cc @EarthChen

Remove processing streamObserver in TripleInvoker#invokeUnary

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStreamObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStreamObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/observer/CallStreamObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/observer/ClientCallToObserverAdapter.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/observer/ServerCallToObserverAdapter.java

Abstract the disableAutoFlowControl method of CallStreamObserver, because ClientStreamObserver#disableAutoRequest and ServerStreamObserver#disableAutoInboundFlowControl are both similar.
/cc @EarthChen

Abstract the disableAutoFlowControl method of CallStreamObserver

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/Configuration.java
dubbo-common/src/test/java/org/apache/dubbo/common/config/InmemoryConfigurationTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/ZookeeperClient.java

另附迄今为止使用的错误码：
0-1: Thread pool is EXHAUSTED! - 线程池资源耗尽。
0-2 - Property type mismatch. - 属性类型不匹配
1-2 - （空缺）
1-14 - …

Change error code 1-2 to 0-2, add code of logging error code 2-2, optimize javadoc, and add unit tests in Configuration.

---

dubbo-common/src/main/java/org/apache/dubbo/common/status/support/MemoryStatusChecker.java

Fix memory alarm bug:Alarm when spare memory < 2M,not <2K

Fix memory alarm bug:Alarm when spare memory < 2M,not <2K

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/TreePathDynamicConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/file/FileSystemDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDataListener.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationFactory.java

**现状**
目前ZK监听的逻辑是，所有的ConfigurationListener都在CacheListener中维护。
给ZK添加监听器的时候，每个path对应一个CuratorZookeeperClient.NodeCacheListenerImpl，且所有的NodeCacheListenerImpl都是映射的同一个CacheListener。每当有任意一个path的监听事件发生的时候，都需要在CacheListener根据path取出对应的Set<ConfigurationListener>，并每次都需要解析出group和key，然后调用ConfigurationListener#process。
**调整**
现在增加ZookeeperDataListener，使得一个NodeCacheListenerImpl只对应一个ZookeeperDataListener，这样path事件触发直接获取ZookeeperDataListener的Set<ConfigurationListener>，然后调用ConfigurationListener#process。使得path、NodeCacheListenerImpl、ZookeeperDataListener三者一一对应，关系更明确、独立。
TreePathDynamicConfiguration#doAddListener方法冗余传递key和group，用以赋值到ZookeeperDataListener的属性中，这样每次事件发生的时候不需要再像原有逻辑那样根据rootPath以及path来解析key和group。
CacheListener内部只维护path和ZookeeperDataListener的映射关系，事件监听逻辑即dataChanged方法挪到了 ZookeeperDataListener 。

Optimize the logic of zkDataListener

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/FrameworkExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/ProviderReadinessProbe.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceHostPortCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/CacheableFailbackRegistryTest.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Protocol.java

另附迄今为止使用的错误码：
0-1: Thread pool is EXHAUSTED! - 线程池资源耗尽。
0-2 - Property type mismatch. - 属性类型不匹配
1-2 - （空缺）
1-14 - …

Add code that shows error code 2-2, 1-9, 5-1 with code optimization.

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java

针对 #10445 做的修复，自己debug test case遇见的NPE问题（case `MultiInstanceTest#testDefaultConsumerApplication`）
消费者在双订阅场景下，应用程序正常关闭的时候，内部会调用 `MigrationInvoker#destroy`，该方法内部会调用`invoker.destroy() `和 `serviceDiscoveryInvoker.destroy()` ，同时两个invoker都有自己的routerChain对象，也会执行各自`routerChain#destroy`方法，该方法内部会遍历 stateRouters 并调用 `router.stop()` ，部分router会调用`ZookeeperDynamicConfiguration#doRemoveListener` 。
但因为两个routerChain里面的`TagStateRouter、ServiceStateRouter、AppStateRouter`都是一个对象引用（因为他们的SPI工厂都用了缓存），所以两个routerChain各自添加这三个router的时候，只注册了一次监听器(主要是ServiceStateRouter和AppStateRouter)，即调用了一次`doAddListener`方法；而两个routerChain各自销毁的时候对这三个router重复调用了各自的`router.stop()`方法，即调用两次`doRemoveListener`方法，第二次没有判空引发NPE。

Fix potential NPE of ZookeeperDynamicConfiguration#doRemoveListener method

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java

https://github.com/apache/dubbo/issues/10419 
https://github.com/apache/dubbo/issues/10407
目前比较的时候没有看`parameters`里面的数据
本次修改影响`equals`、`hashCode`、`toString` 三个方法

Fix config equals for issus#10419

---

README.md
dubbo-common/src/main/java/org/apache/dubbo/common/concurrent/AbortPolicy.java
dubbo-common/src/main/java/org/apache/dubbo/common/concurrent/DiscardOldestPolicy.java
dubbo-common/src/main/java/org/apache/dubbo/common/concurrent/DiscardPolicy.java
dubbo-common/src/main/java/org/apache/dubbo/common/concurrent/RejectException.java
dubbo-common/src/main/java/org/apache/dubbo/common/concurrent/Rejector.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemorySafeLinkedBlockingQueue.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/MemorySafeLinkedBlockingQueueTest.java

Up dev issue#10388

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

为了解决issue列表中 https://github.com/apache/dubbo/issues/10402 的问题，该问题主要描述如下： 
AbstractRegistry.doSaveProperties()虽然采用文件锁、版本号以及重试等方式对竟争场景做了处理，但是在竟争文件锁失败创建重试任务时，没有sleep，仍会有概率出现上一个版本保存操作还没有释放锁，新版本重试次数达到上限导致新版本数据没有保存到cache文件的情况。
改动点主要是将默认共享线程池 SharedExecutor 换成了 SharedScheduleExecutor 以支持增加默认的延迟，避免快速重试导致上述问题出现。
也考虑过通过实现类似Spring-Retry方式实现，但对于现有结构改动较大且收益不高，所以采用 ScheduleExecutor 方式改动

add default interval for retries of saving properties

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanManager.java

在注解方式配置模式中，在`ReferenceAnnotationBeanPostProcessor#registerReferenceBean` 方法中会执行 `ReferenceBeanSupport.generateReferenceKey(attributes, applicationContext)` 会生成`referenceKey`并写入`ReferenceManager#referenceKeyMap`缓存中。
后续发生`ReferenceAnnotationBeanPostProcessor#doGetInjectedBean` -> ` ReferenceBean#afterPropertiesSet` -> `ReferenceManager#addReference`，该方法中又再次调用`generateReferenceKey`方法来构建`referenceKey`（`generateReferenceKey`方法相对耗时），其实可以从缓存直接获取。
并且` ReferenceBeanManager#initReferenceBean` 方法发生在 `ReferenceBeanManager#addReference`方法后，也可以先尝试从`ReferenceManager#referenceKeyMap`缓存中获取

Try to get it from the cache before generating the referenceKey

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java

[2.7] Remove to rpcInvocation string

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosAggregateListener.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

[2.7] Fix Nacos aggregate listen

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

另附迄今为止使用的错误码：
0-1: Thread pool is EXHAUSTED! - 线程池资源耗尽。
0-2 - Property type mismatch. - 属性类型不匹配
1-1: Address invalid. - 地址非法（服务版本或分组不匹配）
1-2 - （空缺）
1-13 - reach the most times of retry. …

Add some code about error code 1-1, 4-1 with code optimization.

---

.github/workflows/build-and-test-3.1.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/merger/MergerFactory.java

cluster faq建设
调整MergerFactory日志warn详细输出。

cluster模块faq建设

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/status/SpringStatusChecker.java

stack:
```
Caused by: java.lang.UnsupportedOperationException: GenericWebApplicationContext does not support getConfigLocations()
at org.springframework.web.context.support.GenericWebApplicationContext.getConfigLocations(GenericWebApplicationContext.java:270)
... 41 more
```

Fix spring status check failed

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/AppResponseTest.java

FIX #10487
This PR proposes a minor improvement that could apply to two test cases in `AppResponseTest`(`testSetExceptionWithEmptyStackTraceException` and `testAppResponseWithEmptyStackTraceException`). I will use [testSetExceptionWithEmptyStackTraceException](https://github.com/apache/dubbo/blob/a4052563b779ba0ee8a67eb717b4060698b6960a/dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/AppResponseTest.java#L67-L78) as an example.
```java
Throwable throwable = buildEmptyStackTraceException();
if (throwable == null) {
return;
}
```
On line [68-71](https://github.com/apache/dubbo/blob/a4052563b779ba0ee8a67eb717b4060698b6960a/dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/AppResponseTest.java#L68-L71), it uses an if condition to check if a precondition is violated, i.e. …

Refactoring app response test with JUnit Assume

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocol.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/Hello1ServiceImpl.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/Hello2ServiceImpl.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/HelloService.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocolTest.java

Solve https://github.com/apache/dubbo/issues/8777

Local references support mergeable

---

dubbo-rpc/dubbo-rpc-rmi/src/main/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocol.java
dubbo-rpc/dubbo-rpc-rmi/src/test/java/org/apache/dubbo/rpc/protocol/rmi/RemoteService2Impl.java
dubbo-rpc/dubbo-rpc-rmi/src/test/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocolTest.java

see 9913 bug.
I added support for grouping and versioning in the RmiProtocol doRefer(), createExporter() method. A test method is written in RmiProtocolTest to verify its correctness.

Fixes #9913, rmi protocol supoort group and version

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java

Fix `ConcurrentModificationException` when initializing dubbo concurrently.
Scenario:
Assume there are two beans `A` and `B`
1. `A` is iterating `PropertiesConfiguration` for `prefix` configs.
2. `B` is writing its `Registry/Application/Protocol Config` to `PropertiesConfiguration`
Cuz it is not thread-safe when iterating `HashTable` with `put` concurrently, a `ConcurrentModificationException` will be thrown by `HashTable`.
Return a copied `Map` under `sync` block.

Fix ConcurrentModification when initializing concurrently

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MappingCacheManager.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryChangeWatcher.java

改动说明：
1. AbstractServiceNameMapping 所需要的ApplicationModule通过构造方法注入，可以去除 `implements ScopeModelAware`
2. MappingCacheManager#update 方法和父类一致，无需重写，因此可以去掉。
3. AbstractRegistry#getCacheUrls 方法优先从notified中获取缓存的urls列表，因为直接从properties获取需要解析（split）。
4. ZookeeperRegistry#destroy 方法移除childListener监听器。
5. ZookeeperServiceDiscovery#recover 用于在ZK重连后重新注册监听，使用的serviceName应该是先前注册的watcher.getServiceName()，而不是当前消费者应用的serviceName。

Fix recover method of ZookeeperServiceDiscovery

---

dubbo-dependencies-bom/pom.xml
dubbo-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesMeshEnvListener.java
dubbo-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscovery.java
dubbo-kubernetes/src/test/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscoveryTest.java

Fix: #10535 
Replace the watch mechanism with a high-performance informer mechanism.
Informer maintains a memory cache, which can return the results of List/Get requests more quickly and reduce direct calls to kubenetes API.
- Update fabric8_kubernetes_version from v5.3.2 to v6.1.1 because of adding informer api.
- Replace all watch APIs.
org.apache.dubbo.registry.kubernetes.KubernetesServiceDiscoveryTest can verify.

feat: replace kube-apiserver watch with informer

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java

1. fix application based service discovery failed in port reuse

fix discovery paramater "protocol" works abnormally in port reuse

---

dubbo-dependencies-bom/pom.xml

Update Fastjson2 version

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/PojoUtilsTest.java

Fix #10631 Fix PojoUtils support localdatetime,lcaldate,localtime serializable and deserialize

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/decoder/TelnetCommandDecoder.java

Fixes #10405.
When use telnet command `invoke` that has args containing Space in method, no invalid parameters error will be reported.
Use telnet to connect to dubbo provider: `telnet {ip} {port}`.
Invoke the service exported with telnet command: `invoke {service name}.{method name}({args that contain Space})`

fix issue 10405: if the parameter contains Spaces, the invoke telnet command will fail.

---

.github/workflows/build-and-test-3.1.yml

#10663 中 “另外的修改” 部分。 / "Another changes" part in #10663 .
1. 由于 GitHub Actions 的 Ubuntu 18 运行器已经弃用 <sup>[1]</sup>。本 PR 修改了 Ubuntu 运行器的版本为 Ubuntu 20。
1. Since Ubuntu 18 runner in GitHub Actions is deprecated <sup>[1]</sup>, this pull request also changes the version of Ubuntu runner to Ubuntu 20.
[1] https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

[CI] Bump GitHub Actions Runner to Ubuntu 20.

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/AbstractAnnotationBeanPostProcessor.java

`InstantiationAwareBeanPostProcessorAdapter`  was deleted by Spring 6.x

Replace InstantiationAwareBeanPostProcessorAdapter with InstantiationAwareBeanPostProcessor

---

dubbo-dependencies-bom/pom.xml

There are 12 security vulnerabilities found in org.apache.tomcat.embed:tomcat-embed-core 8.5.43
- [CVE-2019-17563](https://www.oscs1024.com/hd/CVE-2019-17563)
- [CVE-2020-13934](https://www.oscs1024.com/hd/CVE-2020-13934)
- [CVE-2020-13943](https://www.oscs1024.com/hd/CVE-2020-13943)
- [CVE-2020-17527(critical)](https://www.oscs1024.com/hd/CVE-2020-17527)
- [CVE-2020-9484](https://www.oscs1024.com/hd/CVE-2020-9484)
- [CVE-2020-11996](https://www.oscs1024.com/hd/CVE-2020-11996)
- [CVE-2021-30640](https://www.oscs1024.com/hd/CVE-2021-30640)
- [CVE-2021-24122](https://www.oscs1024.com/hd/CVE-2021-24122)
- [CVE-2021-25122](https://www.oscs1024.com/hd/CVE-2021-25122)
- [CVE-2021-25329](https://www.oscs1024.com/hd/CVE-2021-25329)
- [CVE-2021-41079](https://www.oscs1024.com/hd/CVE-2021-41079)
- …

fix(sec): upgrade org.apache.tomcat.embed:tomcat-embed-core to 8.5.78

---

dubbo-dependencies-bom/pom.xml

There are 1 security vulnerabilities found in org.bouncycastle:bcprov-jdk15on 1.68
- [MPS-2022-54305](https://www.oscs1024.com/hd/MPS-2022-54305)
Upgrade org.bouncycastle:bcprov-jdk15on from 1.68 to 1.69 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade org.bouncycastle:bcprov-jdk15on to 1.69

---

dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/AbstractProtocol.java

Fix xds long time wait

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ModuleModelTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/DubboShutdownHookTest.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboSpringInitializer.java

Fixes #10709
Mark Dubbo Module if is spring managed. Wait the module bound to Spring to be handled by Spring before Dubbo shutdown hook executing.

fix issue: resolve the conficts between Dubbo shutdown hook and Spring.

---

dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/AbstractProtocol.java

这一块代码的future是在StreamObserver onNext的方法里面进行complete，不联系上下文很难理解，以为是future的新特性。
身边几个人阅读时都无法理解这段代码，可读性偏差。增加注释增加可读性。

add xds futrue note

---

.github/workflows/build-and-test-3.1.yml

原先的 PR / Legacy PR: #10663 
检查机制的实现的 PR / The inspector code implementation: https://github.com/apache/dubbo-test-tools/pull/1
这个 PR 实现了在 GitHub Actions 中 warn, error 链接指向的检查机制。
This pull request implements the mechanism that checks (document links of) error code in logger invocations.
1. 代码中全部错误码的提取 （见下述截图中的 All Error Codes 部分）
2. 错误码文档链接失效的判定 （见下述截图中的 Error codes which document links are not reachable 部分）
3. 未用错误码的 Logger 方法的提示 （见下述截图中的 Illegal logger method invocations 部分）
4. GitHub Actions 的自动检查。（目前不会抛出异常。其会将结果上传到 GitHub 的 Artifacts。）
1. Error code extraction. ('All Error Codes' in screenshot)
2. Link testing of document of error codes. ('Error codes which document links are not reachable' in screenshot)
3. Hint of logger method invocations which don't use error code. ('Illegal logger …

[FAQ, CI] Apply Dubbo Error Code Inspector in GitHub Actions

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/Hessian2FactoryInitializer.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/WhitelistHessian2FactoryInitializer.java

System.getProperty is executed for each execution, causing the thread to be blocked.

Avoid getting the whitelist every time and causing performance degradation

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java

Partial backport of #10691, which adds error code which represents internal errors.
Add some error codes in `dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java`.

Adds error code which represents internal errors. (Partial backport of #10691)

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.0.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/release-test-3.1.yml

With Node.js 12.x has been out of support <sup>[1]</sup>, it's recommended for us to upgrade all GitHub Actions to the version that uses Node.js 16.x.
[1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Due to the statement in #10788 : 
_The codecov actions will not be updated in this PR since I don't have the token to test. It will be updated by a separate PR._
This PR does the remaining thing.
Update some actions versions in workflow files.

[CI] Bump the codecov action from v1 to v3.

---

dubbo-dependencies-bom/pom.xml

将nacos-client升级到2.1.2版本，因nacos-client 2.0.4-2.1.1版本存在不能正确处理指定serverlist endpoint的情况，问题详细可见https://github.com/alibaba/nacos/issues/8882

to #10860 将nacos-client升级到2.1.2版本

---

dubbo-native-plugin/src/main/java/org/apache/dubbo/maven/plugin/ClassFinder.java
dubbo-native/src/main/java/org/apache/dubbo/utils/ClassFinder.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/initializer/ConfigZookeeperInitializer.java

[use Files.newInputStream instead of new FileInputStream](https://github.com/apache/dubbo/commit/8f1cfe1a0973970e69b65c32faf7576275693aa6)
[null check](https://github.com/apache/dubbo/commit/24415c20f45dc860668f39e535c70449c9b183c9)

use Files.newInputStream instead of new FileInputStream and null check

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/CacheableSupplier.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyChannel.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyCodecAdapter.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/NettyChannelTest.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandlerTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java

支持用户线程处理encode，eventloop线程只负责发送消息，以此提高dubbo性能
参数: `encode.in.io=false`
1.`NettyChannel`encode message，降低`eventloop`上串行encode的压力
2.`DecodeableRpcInvocation`支持懒加载，以减少该对象在`eventloop`上初始化的耗时

support encode in user thread, optimize decode in user thread

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/LoadBalanceBaseTest.java

Support consistent hash load balance when gerenic invoke
For generalization calls, the toKey function in org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalance has been changed

Support consistent hash load balance when gerenic invoke

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/ObjectInput.java

Fix https://github.com/apache/dubbo/issues/10868

Fix dubbo get wrong return type when generic impl invoke

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Fixes #10892
When `subscribeUrl` is null, use default server shutdown timeout.

fix issue: unexport() throws NPE when register fail.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/pu/PortUnificationTransporter.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationTransporter.java
dubbo-remoting/dubbo-remoting-netty4/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.api.pu.PortUnificationTransporter

Port Unification is disabled by default, and the spi key implemented by Netty4 port unification is changed

---

dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioConstant.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/XdsChannel.java

Support plain text for xds channel

Support plain text for xds channel

---

.licenserc.yaml
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/EmbeddedZooKeeper.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/issues/issue6000/adubbo/HelloDubbo.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/ReferenceKeyTest.java
dubbo-config/pom.xml
dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
dubbo-spring-boot/dubbo-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/resources/META-INF/spring/org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration.imports
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
dubbo-test/dubbo-test-common/src/main/java/org/apache/dubbo/test/common/utils/TestSocketUtils.java
pom.xml

This commit is closing [gh-10565](https://github.com/apache/dubbo/issues/10565) 
- Support new Auto-configuration mechanism in Spring Boot 3
Since Spring Boot 3, loading Auto-configuration classes is supported with `.imports` files only.
In order to be compatible with the lower version of Spring Boot, we have retained the `spring.factories` file

Support for Spring Framework 6 and Spring Boot 3

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/pu/QosWireProtocol.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/AbstractWireProtocol.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/WireProtocol.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/EmptyProtocol.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/api/EmptyWireProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleInvokerTest.java

WireProtocol still relies on netty at present. I decouple channel pipeline.

feat: decoupling WireProtocol by netty

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Fix the warning problem when invokerUrls is checked
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Fix the warning problem when invokerUrls is checked

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/utils/UrlUtils.java

fix comments

---

dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ApplicationConfigTest.java
dubbo-config/dubbo-config-api/src/test/resources/dubbo.properties

fix #10880
Set  `true`  as  default value  of ApplicationConfig.enableFileCache

Fix ApplicationConfig.enableFileCache default value is not true (#10880)

---

dubbo-common/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/FastJson2Impl.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerAdapter.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/jcl/JclLoggerAdapter.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/jdk/JdkLoggerAdapter.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j/Log4jLoggerAdapter.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/log4j2/Log4j2LoggerAdapter.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/slf4j/Slf4jLoggerAdapter.java
dubbo-container/dubbo-container-spring/pom.xml

Enhance logger adapter to use a configured logger

---

.licenserc.yaml
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriHttp2RemoteFlowController.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java
pom.xml

Triple client flowcontrol
TriHttp2RemoteFlowController   isOverFlowControl
when windowsize=0,will throw flowexception.

client flowcontrol

---

dubbo-metadata/dubbo-metadata-report-zookeeper/src/main/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReport.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/AbstractZookeeperClient.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/zookeeper/ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/test/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClientTest.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/test/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClientTest.java

```java
zkClient.createOrUpdate(pathKey, content, false, ticket == null ? 0 : ((Stat) ticket).getVersion());
```
When the ticket is null because the original data was empty, setting the ticket to `0` will overwrite new data created by other processes.

Fix data being updated by default ticket

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvokerTest.java

This PR is mainly about https://github.com/apache/dubbo/issues/10874
1. Add NPE and empty list check in AwareClusterInvoker#doInvoke.
2. Add unit test accordingly.

Add NPE and empty list check in AwareClusterInvoker#doInvoke.

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/QosConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/pu/QosWireProtocol.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/handler/ForeignHostPermitHandler.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/handler/LocalHostPermitHandler.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/handler/QosProcessHandler.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/ForeignHostPermitHandlerTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/LocalHostPermitHandlerTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/server/handler/QosProcessHandlerTest.java

> Currently, Dubbo qos only support qosAcceptForeignIp and this will deny all of the foreign ips, we may need support foreign ip whitelist.
close #11014 
Support config `qos.accept.foreign.ip.whitelist` with `specific ip and an ip range from CIDR specification`, delimiter is `,`.  i.e.
`qos.accept.foreign.ip.whitelist=172.12.32.1, 123.23.1.1/24`

update(qos): support foreign ip whitelist.

---

dubbo-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesMeshEnvListener.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/listener/ListenerInvokerWrapper.java

There's a missing of the error code in a logger invocation in ListenerInvokerWrapper.
Add the error code in the logger invocation.

Add error code in ListenerInvokerWrapper.

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/compat/dubbo.xsd
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

closed https://github.com/apache/dubbo/issues/10563

Support dump thread switch and directory config

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/IsolationExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/executor/AbstractIsolationExecutorSupport.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java
dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java

- Add default thread name for protocol
- Defaultly do not create isolated executor

Enhance isolate executor

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServerHandler.java

Fix ssl npe

---

dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/EdsEndpointListener.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/EdsEndpointManager.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/RdsRouteRuleManager.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/RdsVirtualHostListener.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/XdsRouteRuleListener.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/XdsRouter.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/XdsRouterFactory.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/XdsScopeModelInitializer.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/ClusterWeight.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/DestinationSubset.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/HTTPRouteDestination.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/HeaderMatcher.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/HttpRequestMatch.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/LongRangeMatch.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/PathMatcher.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/rule/XdsRouteRule.java
dubbo-xds/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.router.state.StateRouterFactory
dubbo-xds/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.model.ScopeModelInitializer
dubbo-xds/src/test/java/org/apache/dubbo/rpc/cluster/router/xds/EdsEndpointManagerTest.java
dubbo-xds/src/test/java/org/apache/dubbo/rpc/cluster/router/xds/RdsRouteRuleManagerTest.java
dubbo-xds/src/test/java/org/apache/dubbo/rpc/cluster/router/xds/RdsVirtualHostListenerTest.java
dubbo-xds/src/test/java/org/apache/dubbo/rpc/cluster/router/xds/XdsRouteTest.java
dubbo-xds/src/test/java/org/apache/dubbo/rpc/cluster/router/xds/rule/HeaderMatcherTest.java
dubbo-xds/src/test/java/org/apache/dubbo/rpc/cluster/router/xds/rule/PathMatcherTest.java

相关 issue #10581, 解析路由规则参考了 https://github.com/grpc/grpc-java 部分代码.

Feat xdsroute parse

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java

Support `dubbo.reference` and `dubbo.service` override default properties in `ReferenceConfig` and `ServiceConfig`.
Fix https://github.com/apache/dubbo/issues/11095

Fix dubbo.reference not work in 3.x

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java
dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java

宿主机16c 容器硬限制4c，连接数3w场景下，启动存在cpu冲高，交易超时问题，分析cpu和dump信息，nettywork线程都在处理getChannels操作, 社区2.7.8 把getChannels操作中的hashSet改为ArrayList，并取消isconnected的判断，一定程度上提升了性能，但仍然存在冲高和交易失败现象。通过分析，在启动和停机过程中 有两处只是为了获取channes的大小，没有必要将handler里获取的channel转存，直接通过handler里的map获取大小，可大大提高性能损耗，解决连接建立导致交易超时问题。

optimization-netty-server

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ProtocolPortsMetadataCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceHostPortCustomizer.java

fix #10958 and polish duplicates code

fix #10958 and polish duplicates code

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHeaderEnum.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/StreamUtils.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/stream/StreamUtilsTest.java

Fix tri convert upper header

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/MultiInstanceTest.java

Lazy init scope model in config

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/Configuration.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ProtocolPortsMetadataCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java

Add missing error code.
1. Add error code of 'port is overridden' hint.
2. Since 4-19 is same as 0-2, this PR merged original code 4-19 to code 0-2.

Change constant name of error code 0-2, merge 4-19 to 0-2. Add error code of 'port is overridden' hint.

---

.github/workflows/build-and-test-pr.yml
.github/workflows/build-and-test-scheduled-3.1.yml
.github/workflows/build-and-test-scheduled-3.2.yml
.github/workflows/release-test-3.1.yml

Close #11127 .
Change the `report-as-error` property.

Turn on error reporting of Error Code Inspector.

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/LoggerCodeConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultMetricsServiceExporter.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/connection/AbstractConnectionClient.java
dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionHandler.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodec.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboIsolationExecutorSupport.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/TripleIsolationExecutorSupport.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioEnv.java
dubbo-xds/src/main/java/org/apache/dubbo/rpc/cluster/router/xds/RdsVirtualHostListener.java

Fix error code in 3.2 branch

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java

Fix deadlocks in lazy-init situations.

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

Fix zookeeper instance update

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/DefaultCommandExecutor.java

Add some qos command logs

---

dubbo-common/src/main/java/org/apache/dubbo/common/metrics/collector/DefaultMetricsCollector.java
dubbo-common/src/main/java/org/apache/dubbo/common/metrics/collector/stat/MetricsStatComposite.java
dubbo-common/src/main/java/org/apache/dubbo/common/metrics/event/RequestEvent.java
dubbo-common/src/main/java/org/apache/dubbo/common/metrics/model/MetricsKey.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/filter/MetricsCollectExecutor.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java

Add timeout limit metric ( #11221)

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleServerStream.java

Remove grpc-status-details when no pb exists

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/SingleRouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/StaticDirectory.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/RouterChainTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Fix invokers has changed when router chain switch

---

dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/PilotExchanger.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/AbstractProtocol.java
dubbo-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/impl/LdsProtocol.java

fix lds resource empty and get cache null

feat: fix lds observe

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-nacos/src/test/java/org/apache/dubbo/configcenter/support/nacos/RetryTest.java
dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java
dubbo-metadata/dubbo-metadata-report-nacos/src/test/java/org/apache/dubbo/metadata/store/nacos/RetryTest.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtilsTest.java

Add Nacos sub try test

---

dubbo-common/src/main/java/org/apache/dubbo/common/metrics/collector/DefaultMetricsCollector.java
dubbo-common/src/main/java/org/apache/dubbo/common/metrics/model/MetricsKey.java
dubbo-common/src/test/java/org/apache/dubbo/common/metrics/collector/DefaultMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java

Add dubbo prefix(dubbo.provider) to dubbo's provider.
Link issue: https://github.com/apache/dubbo/issues/11252

Add dubbo prefix(dubbo.provider) to dubbo's provider.

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

Serialization and deserialization use classes in the wrapper

---

dubbo-common/src/main/java/org/apache/dubbo/common/cache/FileCacheStoreFactory.java

when two servers started on the same machine. the first one can acquire the lock, and the second one failed.
but when the second server shutdown, the lock file held by the first server will be deleted.
change to only delete lock when successfully acquiring file lock

don't delete lock file when lock is held by other

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/directory/MockDirInvocation.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invocation.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/RpcInvocation.java
dubbo-compatible/src/test/java/org/apache/dubbo/cache/CacheTest.java
dubbo-compatible/src/test/java/org/apache/dubbo/filter/LegacyInvocation.java
dubbo-compatible/src/test/java/org/apache/dubbo/service/MockInvocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/RpcInvocationTest.java

```java
/**
* To add invoked invokers into invocation. Can be used in ClusterFilter or Filter for tracing or debugging purpose.
* Currently, only support in consumer side.
*
* @param invoker invoked invokers
*/
void addInvokedInvoker(Invoker<?> invoker);
/**
* Get all invoked invokers in current invocation.
* NOTICE: A curtain invoker could be invoked for twice or more if retries.
*
* @return invokers
*/
List<Invoker<?>> getInvokedInvokers();
```

Introduce Invocation#getInvokedInvokers to get invokers for ClusterFilter

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/ChannelHandlerDispatcher.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/transport/ChannelHandlerDispatcherTest.java

fix channelHandlers has null object bug

fix channelHandlers has null object (#11357)

---

dubbo-common/src/main/java/org/apache/dubbo/common/cache/FileCacheStore.java
dubbo-common/src/main/java/org/apache/dubbo/common/io/StreamUtils.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/buffer/ChannelBufferInputStream.java

Some methods are declared to not be synchronized, but they override a synchronized method declared in their parent.
This practically breaks the contract stated by the parent class. I'm not aware of any actual problem that this causes but nontheless, it should be fixed.
Adding a `synchronized` statement to overriding methods that were missing it. 
Not really testable, so there is no way to verify it.

Make methods synchronized to match parent declaration

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleInvokerTest.java

修改了`NettyConnectionClient`中的`isAvailable`逻辑以便消除锁竞争。
该方法会被`TripleInvoker.isAvailable`调用，而调用`TripleInvoker.isAvailable`时处于用户线程而非EventLoop线程，则此时会与EventLoop线程上的`channel.write`出现锁竞争问题。
可以看到，图中已经没有了`ensureWriteOpen`方法的损耗
ref: #11439

optimized sync on channel write

---

README.md

Replace the 404 link in the readme file with an available link, but because the English document of admin manual on dubbo website is not synchronized, the Chinese document link is used for the time being.
fix #11426

repair 404 page links

---

dubbo-compiler/src/main/resources/Dubbo3TripleStub.mustache
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/stub/StubInvocationUtil.java

issue #11458:Triple stub support async mode

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/DescriptorService.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethodTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/call/ReflectionServerCallTest.java

fix https://github.com/apache/dubbo/issues/11447 not stub

Fix tri future

---

dubbo-distribution/dubbo-all/pom.xml

When the metrics function is enabled, the t-digest package needs to be referenced separately, otherwise an exception will be thrown

fix t-digest miss

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/directory/MockDirInvocation.java

#11526 11526
optimize MockDirInvocation setObjectAttachmentIfAbsent method code

optimize MockDirInvocation setObjectAttachmentIfAbsent method code（#11526）

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java

Fix hasPreparedInternalModule is always false. (#11535)

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/filter/observation/ObservationReceiverFilter.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/filter/observation/ObservationSenderFilter.java

dubbo-metrics-api 在dobbo-all pom 文件在配置依赖时，maven 配置的依赖为可选配置，当ExtensionLoader 在读取Filter里面的配置进行实例化出现异常

observationreceiver instance error

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java

link to https://github.com/apache/dubbo/issues/11424

feat: fix oom

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TimeoutFilter.java

Revert clear response operation of timeoutfilter

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java
dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/MultipleSerialization.java

Fix triple protocol's  wrapper mode  can not recognize primitive method.
```java
interface A{
// call0
void call(int a);
// call1
void call(Integer b);
}
```
When client wants to invoke `call0` with argument `1`,
Server will call `call1` with `(Integer)1`
1. Pass interface's argument types instead of actual types.
2. Delete unused methods in `MultipleSerialization` interface.

[Triple] Fix boxed type methods

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameCodecBuilder.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java

remove duplicate flowcontroller listener
add `TripleHttp2FrameCodecBuilder` to customize connection before building
before: 
after:

remove duplicate flowcontroller listener

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/SslConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/nested/AggregationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/nested/PrometheusConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/GetConfig.java
dubbo-plugin/dubbo-qos/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.qos.command.BaseCommand
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/GetConfigTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java

Add `getConfig` command to get config in runtime
Examples:
1. `getConfig`
2. `getConfig ApplicationConfig`
3. `getConfig ReferenceConfig com.example.DemoService`
```bash
➜  dubbo-samples git:(apache-master) ✗ telnet 127.0.0.1 22222
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
___   __  __ ___   ___   ____     
/ _ \ / / / // _ ) / _ ) / __ \  
/ // // /_/ // _  |/ _  |/ /_/ /    
/____/ \____//____//____/ \____/   
dubbo>getConfig
ApplicationModel: Dubbo Application[1.1](first-dubbo-provider)
ApplicationConfig: first-dubbo-provider
<dubbo:application enableFileCache="true" executorManagementMode="default" environment="product" parameters="{}" name="first-dubbo-provider" protocol="dubbo" />
ProtocolConfig: dubbo
<dubbo:protocol …
```

Introduce getConfig QoS Command

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/ConfiguratorTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/filter/DefaultFilterChainBuilderTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConsumerConfigTest.java
dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/filter/ValidationFilterTest.java
dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/support/jvalidation/JValidatorTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/CommandContextTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/service/generic/GenericServiceTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/ZKTools.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/MockNamingService.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosConnectionsManagerTest.java
dubbo-registry/dubbo-registry-nacos/src/test/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapperTest.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/test/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClientTest.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/test/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperTransporterTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/TimeoutFilterTest.java

Remove redundant exceptions that are not actually thrown.
Types such as:
Exception 'java.io.IOException' is never thrown in the method
This is the first PR, expect 3 more.

fix: remove redundancy exceptions

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-common/src/test/java/org/apache/dubbo/common/bytecode/ClassGeneratorTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/AdaptiveCompilerTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/JavassistCompilerTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/JdkCompilerTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/logger/LoggerAdapterTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/logger/LoggerTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ReflectUtilsTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidatorNew.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/jackson/ObjectMapperCodec.java
dubbo-remoting/dubbo-remoting-http/src/test/java/org/apache/dubbo/remoting/http/jetty/JettyLoggerAdapterTest.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/RpcMessageHandler.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericImplFilter.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmClassLoaderTest.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/util/MultiValueCreator.java

```
@Deprecated(since="9")
public T newInstance()
```
The newInstance() method is marked as obsolete, and this pr uses a new method to obtain an instance.
Java 9 introduces a new way to create an instance using the `privateLookupIn(Class<?> declaringClass `,  `MethodHandles.Lookup lookup` method of the `MethodHandles.Lookup class`. This method can return a MethodHandles.Lookup object with private access, and then use the findConstructor method of this object to create an instance.

Reactor some newInstance method

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java

Fix https://github.com/apache/dubbo/issues/11716

Fix metadata proxy load filter

---

dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLStrParserTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java

When value has no value, make sure value is an empty string, rather than assigning the value of name to value
For key-value pair `key_name=`, the generated URL parameter should be 'key_name=' rather than `key_name=key_ name`

Fix #11767,  restore the original parameter pair instead of giving default value when doing URL.parse.

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invoker.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Result.java

fix bug see https://github.com/apache/dubbo/issues/11644
Add compatible method of com.alibaba.dubbo.rpc.Result and com.alibaba.dubbo.rpc.Invoker
I test calling 2.6.x's method both sync and async

Fix 2.6.x LoadBalance SPI not work

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

Remove redundant synchronized

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java

1. Fix HeaderExchangeChannel close potential bug
2. 'channel != null' must be satisfied, simplify hashCode and equals

Fix HeaderExchangeChannel close potential bug

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java

Fix bug that client gets `null` if deserialize error.
Add 'onClose' call when deserialize error.

[Triple] Fix client can not get error when deserialize response failed .

---

dubbo-spring-boot/dubbo-spring-boot-autoconfigure/pom.xml
dubbo-spring-boot/dubbo-spring-boot-observability-starter/pom.xml

The introduction of starter can use the metrics capability。
When you don't need observability, import the dubbp-starter package. If necessary, import the dubbo-spring-boot-observability-starter package

dubbo-starter  import metrics dep

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java

[3.1] Fix #11524 (#11524)

---

dubbo-dependencies/dubbo-dependencies-zookeeper-curator5/pom.xml

如果我们使用了高版本JDK,例如JDK17,我们的dubbo应用启动会报错，
java.lang.IllegalArgumentException: 
Unable to canonicalize address 127.0.0.1/<unresolved>:2181 because it's not resolvable
因为引入的dubbo-dependencies-zookeeper-curator5中zookeeper是低版本的，
我们需要重新引入高版本zookeeper或者使用JDK8。
#11966

dubbo-dependencies-zookeeper-curator5在dubbo新版本兼容 

---

dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-consumer/pom.xml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/pom.xml

Start dubbo-demo-spring-boot error, qos&metrics is not available.
```java
java.lang.ClassNotFoundException: org.apache.dubbo.qos.protocol.QosProtocolWrapper
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at org.apache.dubbo.common.utils.ClassUtils.forName(ClassUtils.java:259)
at org.apache.dubbo.common.utils.ClassUtils.forName(ClassUtils.java:210)
at org.apache.dubbo.config.utils.ConfigValidationUtils.checkQosDependency(ConfigValidationUtils.java:501)
at org.apache.dubbo.config.utils.ConfigValidationUtils.validateApplicationConfig(ConfigValidationUtils.java:495)
```
1、add qos dep
2、remove unuse …

fix demo dep

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

when there is a referenceConfig get for a dependent jar package, the loading order will change, causing exceptions in abstractServiceDiscovery update
1、it will fix abstractServiceDiscovery update exception caused by loading order
2、Fix issue Closes #12032

Fix abstractServiceDiscovery update exception caused by loading order

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

1、After the QoS offline, executing the QoS online will report an error

1、fix after offline and online error

---

dubbo-spring-boot/dubbo-spring-boot-observability-starter/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/DubboObservationAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-observability-starter/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/otel/OpenTelemetryAutoConfiguration.java

- Fix missing registerBean ObservationRegistry.class
- Fix OpenTelemetryAutoConfiguration ConditionalOnClass error

fix: fix observ-starter some bugs

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
dubbo-dependencies-bom/pom.xml
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/ExchangeCodecTest.java
dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/ObjectInput.java
dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/ObjectOutput.java
dubbo-serialization/dubbo-serialization-fastjson2/pom.xml
dubbo-serialization/dubbo-serialization-fastjson2/src/main/java/org/apache/dubbo/common/serialize/fastjson2/FastJson2ObjectInput.java
dubbo-serialization/dubbo-serialization-fastjson2/src/test/java/com/example/test/TestPojo.java
dubbo-serialization/dubbo-serialization-fastjson2/src/test/java/org/apache/dubbo/common/serialize/fastjson2/FastJson2SerializationTest.java
dubbo-serialization/dubbo-serialization-fastjson2/src/test/java/org/apache/dubbo/common/serialize/fastjson2/TrustedNotSerializable.java
dubbo-serialization/dubbo-serialization-fastjson2/src/test/java/org/apache/dubbo/common/serialize/fastjson2/TrustedPojo.java
dubbo-serialization/dubbo-serialization-fastjson2/src/test/java/org/apache/dubbo/common/serialize/fastjson2/TrustedPojo2.java
dubbo-serialization/dubbo-serialization-fastjson2/src/test/java/org/apache/dubbo/common/serialize/fastjson2/TypeMatchTest.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2FactoryManager.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/Hessian2SerializerFactory.java
dubbo-serialization/dubbo-serialization-hessian2/src/test/java/com/example/test/TestPojo.java
dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/hessian2/Hessian2SerializationTest.java
dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/hessian2/TrustedNotSerializable.java
dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/hessian2/TrustedPojo.java
dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/hessian2/TrustedPojo2.java
dubbo-serialization/dubbo-serialization-hessian2/src/test/java/org/apache/dubbo/common/serialize/hessian2/TypeMatchTest.java

Fix serializable check & Add test cases

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/HeaderFilter.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java

Fix tri headerfilter 3.1

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MethodMetricsInterceptor.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilter.java

Fix business exception

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/BroadcastClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailsafeClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AvailableClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailSafeClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvokerTest.java

[issue](https://github.com/apache/dubbo/issues/12138)

fix: Adjusting cluster invoker checks 

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MetricsFilter.java

fix #12130 
Lower MetricsFilter's order

Lower MetricsFilter's order

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/event/MetricsEvent.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/key/MetricsKey.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/filter/MethodMetricsInterceptor.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollectorTest.java

…ble.count Metrics
fix #12129 
Collect No Provider Request count as dubbo.consumer.invoker.no.available.count Metrics

Collect No Provider Request count 

---

dubbo-spring-boot/dubbo-spring-boot-observability-starters/dubbo-spring-boot-observability-autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/exporter/zipkin/ZipkinAutoConfiguration.java

`ZipkinAutoConfiguration` create Zipkin sender and exporter when you are using Boot < 3.0 or you are not using spring-boot-starter-actuator.
When you use SpringBoot 3.*, priority should be given to loading S3 related configurations. Dubbo related zipkin configurations are invalid.
springboot3 zipkin config:
```yaml
management:
zipkin:
tracing:
endpoint: http://localhost:9411/api/v2/spans
```

fix: load zipkin after springboot3

---

dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollector.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/collector/AggregateMetricsCollectorTest.java

Disable Aggregation by default

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/GracefulShutdown.java
dubbo-plugin/dubbo-qos/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.qos.api.BaseCommand
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/GracefulShutdown.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboGracefulShutdown.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

- Send readonly in Shutdown Hook
- Support `gracefulShutdown` QoS command

Support offline notify

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanSupport.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/registryNA/consumer/DubboXmlConsumerTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/registryNA/consumer/dubbo-consumer.xml
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/registryNA/consumer/dubbo-registryNA-consumer.xml
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/registryNA/provider/DubboXmlProviderTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/registryNA/provider/dubbo-provider.xml

Fix consumer startup failure when using registry="N/A" #12099 
1. Use registries instead of registry to avoid some errors in ReferenceBeanSupport
2. registry="N/A" requires lazy loading

Fix consumer startup failure

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ControllerServiceConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/api/SpringControllerService.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/ServiceConfigTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/mvc/SpringControllerService.java

rest provider  impl class support by changing  service config  interface judge
@AlbumenJ

rest provider interface judge modify

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/FailedUnsubscribedTask.java

fix inappropriate invoke in unsubscribe retry task

fix: fix inappropriate invoke in unsubscribe retry task

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/retry/FailedUnsubscribedTask.java

(backport of https://github.com/apache/dubbo/pull/12231 for 3.2 branch.)
fix inappropriate invoke in unsubscribe retry task

backport of 'fix inappropriate invoke in unsubscribe retry task'

---

dubbo-metadata/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java

fix the bug of not support redis cluster password
init the value of password before use it, when redis model is cluster.

fix #12233 redis cluster not support password bug.

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/InvokeTelnet.java

to fix #12290 
1. clean the RpcContext in ThreadLocal after QoS invoke in the ```InvokeTelnet```
2. synchronously get the result while async started, so the invoke command could get the correct result instead of null

clean the RpcContext in ThreadLocal after QoS invoke, synchronously get the result while async started

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java

Enhance shutdown hook logs

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/SerializationException.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Response.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/codec/ExchangeCodecTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/transport/codec/DeprecatedExchangeCodec.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AsyncToSyncInvoker.java

fix https://github.com/apache/dubbo/issues/12279

Fix When serialization fails, the code value in org.apache.dubbo.rpc.RpcException is set incorrectly. (#12279)

---

dubbo-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/util/KubernetesConfigUtils.java

fix #12326
fix k8s client http2Disable default value.

fix: k8s client http2Disable default value is wrong(#12326)

---

dubbo-metrics/dubbo-metrics-registry/src/main/java/org/apache/dubbo/metrics/registry/event/RegistrySubDispatcher.java

registry directory metrics only show num_valid_total ，The key should be dynamically obtained when collecting

bugfix of registry directory metrics only show num_valid_total

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/ScopeClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/wrapper/ScopeClusterInvokerTest.java

Provide broadcast rules to adapt the call mode and provide logs to assist debug.
close #12334

Fix issue #12334.provide broadcast rules to adapt the calling mode.

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java

1. `org.apache.dubbo.config.spring.util.DubboAnnotationUtils.convertParameters`
When the `put` target is an empty String array, the empty `HashMap` instead of `java.util.Collections.EmptyMap` supports subsequent scalable `put` operations  #12350 
So that `@DubbboService#parameter`, even if empty, does not affect the extra put operation causing the program to throw an exception
```java
if (ArrayUtils.isEmpty(parameters)) {
return Collections.emptyMap();
}
```
---->
```java
if (ArrayUtils.isEmpty(parameters)) {
return new HashMap<>();
}
```
`Collections.emptyMap()`is a special implementation of EmptyMap inside Collections that doesn't support change, so I don't think it makes any sense to set a Map of that type here
```java
public V put(K key, V value) {
throw new …
```

When PropertyValue "parameters" is [null] or [EMPTY], return to HashMap that can be modified

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/MethodStatComposite.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/ServiceStatComposite.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MetricsSupport.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/key/CategoryOverall.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/key/MetricsCat.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/key/MetricsKey.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/key/MetricsKeyWrapper.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/MetricsSupportTest.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/DefaultConstants.java
dubbo-metrics/dubbo-metrics-default/src/main/java/org/apache/dubbo/metrics/event/DefaultSubDispatcher.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/collector/DefaultCollectorTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java
dubbo-metrics/dubbo-metrics-metadata/src/main/java/org/apache/dubbo/metrics/metadata/event/MetadataSubDispatcher.java
dubbo-metrics/dubbo-metrics-metadata/src/test/java/org/apache/dubbo/metrics/metadata/MetadataMetricsCollectorTest.java
dubbo-metrics/dubbo-metrics-registry/src/main/java/org/apache/dubbo/metrics/registry/event/RegistrySubDispatcher.java
dubbo-metrics/dubbo-metrics-registry/src/test/java/org/apache/dubbo/metrics/registry/metrics/collector/RegistryMetricsCollectorTest.java

1、For metrics data sets at the servce and method levels, if a key exists in a certain category of data, it should set the default 0 for other categories to make the data aligned
2、some code opt/ add metrics code comment。delete MetricsKey.formatName,It will change the attribute value of the enum causing ci to fail. 
3、MetricSample.Type changed from invocation to built-in property of MetricsKeyWrapper to avoid fillZero injecting a fixed key
add testcase.
dubbo_registry_subscribe_service_num_total{application_module_id="1.1",application_name="dubbo-springboot-demo-provider",application_version="3.2.2-SNAPSHOT",git_commit_id="9df27cb8b256fed00928a4958e1977d6b51d1bcc",hostname="linyaoMac.local",interface="dubbo-springboot-demo-provider/org.apache.dubbo.metrics.service.MetricsService:1.0.0",ip=" …

Metrics default val set 0

---

dubbo-dependencies-bom/pom.xml

There are 1 security vulnerabilities found in org.yaml:snakeyaml 1.33
- [CVE-2022-1471](https://www.oscs1024.com/hd/CVE-2022-1471)
Upgrade org.yaml:snakeyaml from 1.33 to 2.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS

fix(sec): upgrade org.yaml:snakeyaml to 2.0

---

dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/annotation/ConditionalOnDubboTracingEnable.java
dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/exporter/zipkin/ZipkinAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-observability-starters/autoconfigure/src/test/java/org/apache/dubbo/spring/boot/observability/autoconfigure/observability/DubboMicrometerTracingAutoConfigurationTests.java

Previously, there was an error in using the `matchIfMissing` attribute. 
When the user did not configure 'dubbo.tracing. enable', the default setting was that 'ConditionalOnDubboTracingEnable' does not need to be activated.

fix: remove ConditionalOnDubboTracingEnable matchIfMissing

---

dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/beans/factory/annotation/ReferenceAnnotationWithAotBeanPostProcessor.java
dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/beans/factory/annotation/ServiceAnnotationWithAotPostProcessor.java
dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/utils/AotUtils.java

Support for automatic identification of serialization classes and generation of native image configuration

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/TripleWriteQueue.java

support catch actual exception
When the provider is offline, the consumer continues to send requests, and it is expected that the `ClosedChannelException` will be caught

support catch actual exception

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/BiStreamServerCallListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/TripleServerConnectionHandler.java

fix #12434 
BiStream Server side: reset all active stream on connection close

reset all active stream on connection close

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/pu/QosDetector.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/pu/QosHTTP1Detector.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/pu/TelnetDetector.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ProtocolDetector.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/pu/ChannelOperator.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConfigOperator.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServerHandler.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/pu/DubboDetector.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/Http2ProtocolDetector.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/Http2ProtocolDetectorTest.java

Support passing detect context to help build netty handlers.
Supports multiple versions of the same protocol, for example: HTTP -> HTTP1, HTTP2, HTTP3

support passing detect context to help build netty handlers

---

dubbo-common/src/main/java/org/apache/dubbo/common/convert/StringToDurationConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-common/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.convert.Converter
dubbo-common/src/test/java/org/apache/dubbo/common/convert/StringToDurationConverterTest.java

I found Dubbo can not convert String to Duration.class in config from #12453 
So I resloved it.

feat: add Duration as SIMPLE_TYPE and Convert

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invoker.java

When using 2.6.x DIY ConsistentHashLoadBalance, Invoker will wrap to CompatibleInvoker. Then invokers.hashCode() will return different hashCode event original Invokers not change. This will cause many duplicate Object like ConsistentHashSelector in jvm Eden space, and young gc will be very frequently.
Compatible of invokers' hashCode method using in 2.6.x's DIY ConsistentHashLoadBalance
In CompatibleInvoker.java, call invoker.hashCode()
Verified on my local env

Fix hashCode change in 2.6 DIY ConsistentHashLoadBalance

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ToStringUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java

```java
@Test
void testToString() {
ServiceConfig<DemoService> serviceConfig = new ServiceConfig<>();
service.setRef(new DemoServiceImpl() {
@Override
public String toString() {
throw new IllegalStateException();
}
});
try {
serviceConfig.toString();
} catch (Throwable t) {
Assertions.fail(t);
}
}
```

Fix ServiceConfig Ref unable to toString

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/InternalServiceConfigBuilder.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/AbstractRegistryCenterExporterListener.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/multiple/exportprovider/MultipleRegistryCenterExportProviderIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/multiple/injvm/MultipleRegistryCenterInjvmIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/single/exportprovider/SingleRegistryCenterExportProviderIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/integration/single/injvm/SingleRegistryCenterInjvmIntegrationTest.java

Disable all filters for internal service

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/aot/Netty4ReflectionTypeDescriberRegistrar.java
dubbo-rpc/dubbo-rpc-triple/pom.xml
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/aot/TripleReflectionTypeDescriberRegistrar.java
dubbo-rpc/dubbo-rpc-triple/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.aot.api.ReflectionTypeDescriberRegistrar

fix #12535 
add tri native image support 
every netty channelHandler should have a reflect-config conf in native image build
as netty does https://github.com/netty/netty/pull/12794, https://github.com/netty/netty/pull/12738
otherwise will cause io.netty.channel.ChannelHandlerMask#isSkippable check failed
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelHandlerMask.java#L177

add tri native image support

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java

- `register=false` never register
- `delay=-1` not register by default and can be register by `online` command

Service not register to registry if specify register=false

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/identifier/MetadataIdentifier.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java

Issue Number: close https://github.com/apache/dubbo/issues/12532
Use serviceKey to replace interfaceName.
If a user service does not define version, it will still look like interfaceName
```
dubbo_registry_subscribe_num_total{application_module_id="1.1",application_name="dubbo-springboot-demo-provider",application_version="",git_commit_id="",hostname="192.168.10.100",ip="192.168.10.100",} 0.0
dubbo_metadata_push_num_succeed_total{application_module_id="1.1",application_name="dubbo-springboot-demo-provider",application_version="",git_commit_id="",hostname="192.168.10.100",ip="192.168.10.100",} 0.0
jvm_buffer_total_capacity_bytes{application_name="dubbo-springboot-demo-provider",id="direct",} 10963.0
jvm_buffer_total_capacity_bytes{application_name="dubbo-springboot-demo-provider",id="mapped …
```

Use serviceKey when to metadata ServiceSubscribeEvent

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboBeanUtils.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ServiceBeanTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/status/DataSourceStatusCheckerTest.java

- Prevent set `ApplicationConfig` to `ConfigManager` when initialize `ServiceBean`

Enable spring bean autowired to get scope model in advance

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcServiceContext.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java

https://github.com/apache/dubbo/issues/12631
- [x ] Each commit in the pull request should have a meaningful subject line and body.
fix the consumer remoteApplicationName is null

fix the consumer remoteApplication is null

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeChannel.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeHandler.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/ReferenceCountInvokerWrapper.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/SharedClientsProvider.java

- Use shutdown timeout to `ReferenceCountInvokerWrapper`
- Cal shutdown time in shutdown hook and reset all shutdown timeout

Fix server shutdown await timeout

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/MethodStatComposite.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/RtStatComposite.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/ApplicationMetric.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/MethodMetric.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/ServiceKeyMetric.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/model/container/LongContainer.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/filter/MetricsFilterTest.java
dubbo-metrics/dubbo-metrics-default/src/test/java/org/apache/dubbo/metrics/metrics/model/MethodMetricTest.java
dubbo-metrics/dubbo-metrics-metadata/src/test/java/org/apache/dubbo/metrics/metadata/MetadataStatCompositeTest.java
dubbo-metrics/dubbo-metrics-registry/src/test/java/org/apache/dubbo/metrics/registry/metrics/collector/RegistryStatCompositeTest.java

When the version  has the _ symbol, there is an error in getting the rt indicator.
Use metric obj for key
MetricsFilterTest modify VERSION = "1.0.0_BETA"
invoke testSucceedRequests method failed before pr and success after pr

Bugfix: Use metric obj for key of LongContainer to fix split bug

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/DeadlineFuture.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

ref #12632
fix throw RejectedExecutionException when ThreadlessExecutor has been shutdown

fix throw RejectedExecutionException

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceBeanManager.java

Test cases: https://github.com/apache/dubbo-samples/pull/876
If reference has been trigger when starting, application deployer will start early. When `ApplicationContextRefeshed` event published, application deployer will not being start again. This will cause some later built reference config not being `get` when start.

Fix reference bean has not been init if deployer is early started

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/DubboMergingDigest.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/aggregate/TimeWindowQuantileTest.java

Due to the testcase problem of #12223, the concurrency bug of digest was not completely solved.
Because the exception thrown by the thread pool will not be transmitted to the main thread.
Cause Analysis：
In the following code snippet, about every thousand times, the condition tempUsed.get() >= tempWeight.length - lastUsedCell.get() - 1 will be satisfied, and the merge operation will be performed.
The mergeNewValues method and the following codes simultaneously modify shared variables, such as tempUsed. Then every thousand or so times, a thread-safe event occurs, causing the error.
```java
private void add(double x, int w, List<Double> history) {
if (Double.isNaN(x)) {
throw new IllegalArgumentException("Cannot add NaN to t-digest");
}
if (tempUsed.get() >= tempWeight.length - …
```

fix digest thread_safe bug

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java

fix #12620 线程死锁问题
1. 在spring容器中启动时,如果开启了` @EnableScheduled` 且在 `@Scheduled `注解修饰的方法中调用了 `dubbo` 接口,
如图中`spring`容器正常启动以后 发布了 `ContextRefreshedEvent ` 即会 先调用 `scheduleProcessor `再调用 `dubboDeployApplicationListener `   (事件`listener`如果没有配置单独的线程池异步执行(大部分情况应该都没配置)，则是同步顺序执行的) ，就可能会出现 异步任务调用 `reference.get` 获取了`spring `单例锁(3.1.5 修改引入)，`dubboDeployApplicationListener ` 调用 deploy.start 获取了 dubbo 发布器锁, 此时如果 dubbo 存在 引用 懒加载的 spring bean 则会导致 死锁
解决方式 
1.1 提升 `dubboDeployApplicationListener ` 优先级先于 `scheduleProcessor ` 处理。 (如果是listener 是配置了异步执行则无效) 
1.2 在 `dubboDeployApplicationListener ` 调用 deploy 之前 先加 spring 单例锁 保证锁的获取顺序
2. 容器启动过程中 在init 中调用了 dubbo 接口。 
2.1 同步调用 此时可能存在 部分服务发布、订阅非预期 ， 
2.2 异步调用 dubbo 启动过程中 可能存在部分服务发布、订阅非预期 或者同 `@Scheduled ` 调度执行一样 造成死锁  可以通过`deploy `加锁    进行排序加锁 
3. 其他情况的异步线程调用 …

Fix deadlock when starting

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/connection/AbstractConnectionClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java

When netty client connect failed at init, `org.apache.dubbo.remoting.transport.netty4.NettyConnectionClient.ConnectionListener#operationComplete` will check connection is used. But `NettyConnectionClient` has not been initialized and count has not been set.
Fix https://github.com/apache/dubbo/issues/12658

Fix netty close when init count is 0

---

dubbo-dependencies-bom/pom.xml
dubbo-metadata/dubbo-metadata-rest/pom.xml
dubbo-metadata/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/rest/RestMetadataConstants.java
dubbo-metadata/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/rest/springmvc/SpringMvcServiceRestMetadataResolver.java
dubbo-metadata/dubbo-metadata-rest/src/test/java/org/apache/dubbo/metadata/rest/feign/FeignClientController.java
dubbo-metadata/dubbo-metadata-rest/src/test/java/org/apache/dubbo/metadata/rest/feign/FeignClientControllerImpl.java
dubbo-metadata/dubbo-metadata-rest/src/test/java/org/apache/dubbo/metadata/rest/springmvc/FeignClientAnnotationTest.java
dubbo-rpc/dubbo-rpc-rest/pom.xml
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/FeignClientRestProtocolTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/mvc/feign/FeignClientController.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/mvc/feign/FeignClientControllerImpl.java

feign client annotation  support
[#87](https://github.com/apache/dubbo-samples/pull/879)
@chickenlj

add feign client annotation  support

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/AbstractNoAnnotatedParameterProcessor.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest/ArgInfo.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RestInvoker.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/annotation/param/parse/provider/BodyProviderParamParser.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/HttpMessageCodecManager.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/HttpMessageDecode.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/ByteArrayCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/JsonCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/MultiValueCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/ResteasyResponseCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/StringCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/TextCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/message/codec/XMLCodec.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/util/DataParseUtils.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DemoService.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DemoServiceImpl.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/HttpMessageCodecManagerTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/JaxrsRestProtocolTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/User.java

add generic reflect type for collection,map,array json & ut
@AlbumenJ  @chickenlj

add generic reflect type for collection,map,array json

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

fix(#12646 ) 在zookeeper 恢复后，由于之前的session创建的Ephermal节点未及时删除导致provider 不能再次注册上的问题

fix dubbo provider lose when zookeeper restored to normal after network fluctuations.(#12646)

---

dubbo-native/src/main/java/org/apache/dubbo/aot/generate/JarScanner.java

fix win11 graalvm17 dubbo aot compile throws java.nio.file.NoSuchFileException
Because in Windows OS ,   file separator is  "\\" .
However in jvm/graalvm ,  .class file  URL is always  splited by  "/"
So the   following code does not work in Windows 
org.apache.dubbo.aot.generate.JarScanner#toClassName(String path)
```java
path.substring(0, path.length() - 6).replace(File.separator, ".")
```
I change to 
```java
path.contains(File.separator) ? path.substring(0, path.length() - 6).replace(File.separator, ".") : path.substring(0, path.length() - 6).replace("/", ".");
```
[y] [dubbo_issue: win11 graalvm17 dubbo aot compile throws java.nio.file.NoSuchFileException](https://github.com/apache/dubbo/issues/12768)

fix_win11_aot_compile_NoSuchFileException,because of File.separator

---

dubbo-dependencies-bom/pom.xml

There is a dependency conflict between dubbo and dubbo-spi-extensions. The jsonrpc4j not used in dubbo-dependencies-bom will overwrite the version in the dubbo-http-rpc module

remove jsonrpc4j

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscoveryFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryFactory.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscoveryFactory.java

解决 nacos 应用级别注册时无法实现多注册的问题，详情见：https://github.com/apache/dubbo/issues/12629
1. 通过重写 createRegistryCacheKey 保证不同的 Nacos 配置产生不同的 ServiceDiscoveryRegistryFactory 对象
2. 通过重写 getServiceDiscovery 保证不同的 Nacos 配置产生不同的 NacosServiceDiscoveryFactory 对象
验证同一个域名下的多个nacos 配置可以注册到多个命名空间

multiple registration cannot be achieved when nacos application level registration

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/RpcExceptionFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TpsLimitFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/tps/TpsLimitFilterTest.java

When Filter throws an `RpcException` on the provider side, the consumer does not get the real `RpcException`, only errorMsg.

Support real RpcException be thrown.

---

dubbo-metadata/dubbo-metadata-definition-protobuf/src/main/java/org/apache/dubbo/metadata/definition/protobuf/ProtobufTypeBuilder.java

Make sure project has protobuf dependency before loading ProtobufTypeBuilder extension

Adding onClass attribute on ProtobufTypeBuilder

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/event/MetricsEventBus.java

add try catch to avoid metric bug

:ambulance: avoid metric bug

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/frame/TriDecoder.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStreamTest.java

fix memory leak

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboSpringInitializer.java

Optimize code in DubboSpringInitializer

Optimize code in DubboSpringInitializer

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/aggregate/DubboMergingDigest.java
dubbo-metrics/dubbo-metrics-api/src/test/java/org/apache/dubbo/metrics/aggregate/TimeWindowQuantileTest.java

Fix DubboMergingDigest concurrent issue

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

fix triple npe

---

dubbo-spring-boot/dubbo-spring-boot-autoconfigure/README.md

Update README.md of  spell errors

Update README.md of  spell errors

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/netty/ChunkOutputStream.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/netty/NettyHttpResponse.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/netty/RestHttpRequestDecoder.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/JaxrsRestProtocolTest.java

#12891 
fix chunkoutputstream chunksize exception
@CrazyHZM

fix chunkoutputstream chunksize exception

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/StringUtilsTest.java
dubbo-plugin/dubbo-plugin-router-tag/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStateRouter.java
dubbo-plugin/dubbo-plugin-router-tag/src/test/java/org/apache/dubbo/rpc/cluster/router/tag/TagStateRouterTest.java

fix issue #12672
tag with multi level will search tag as following: 
requestTag=beta|team1|partner1
step0: if force=true , just search tag(beta|team1|partner1)
step1:  search invokers with tag(beta|team1|partner1) , if result is empty , run step2
step2: search invokers with tag(beta|team1), if result is empty , run step3
step3: search invokers with tag(beta)
----
there are 10 deploy with tag=null and 10 deploy with dubbo.tag=beta, but my team just work with 8 deploy for a big feature-A , and my partners just work with 3 deploy for a small feature-A-1 :
my team want deploy 8 deploy with tag=beta|team1 , and share the deploy(tag=beta)
my partners want deploy 3 deploy with tag=beta|team1|partner1 , and share the deploy(tag=beta|team1)
add some test case to search addresses with muti level …

tag support multi level

---

dubbo-common/src/main/resources/security/serialize.allowlist

#12959 
serialize.allowlist is not include SingletonMap

serialize.allowlist is not include SingletonMap

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/QosBindException.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Constants.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyPortUnificationServer.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/ConnectionTest.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/PortUnificationServerTest.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/api/MultiplexProtocolConnectionManagerTest.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/api/SingleProtocolConnectionManagerTest.java

Cleanup and throw exception if bind failed

---

dubbo-remoting/dubbo-remoting-http12/pom.xml
dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/JsonCodec.java
dubbo-remoting/dubbo-remoting-http12/src/main/java/org/apache/dubbo/remoting/http12/message/NoOpStreamingDecoder.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/h12/AbstractServerTransportListener.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/h12/http2/GenericHttp2ServerTransportListener.java

fix h2 curl error

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java

Fixes #12765

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/exchange/support/DefaultFutureTest.java

As the title says, fix incorrect timeout message. The time it takes for the client to send messages may exceed the set timeout. In this case, the timeout information should prompt "client-side timeout" instead of "server-side timeout".
* Modified org.apache.dubbo.remoting.exchange.support.DefaultFuture#getTimeoutMessage
* Add org.apache.dubbo.remoting.exchange.support.DefaultFutureTest#clientTimeoutSend

Fix incorrect timeout message

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java

to avoid AbortPolicyWithReport dump again
fixed: #13042  https://github.com/apache/dubbo/issues/13042
- only update AbortPolicyWithReport.java

fix: AbortPolicyWithReport concurrency #13042

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/aot/QosReflectionTypeDescriberRegistrar.java

update qos native-image reflect config

update qos module native-image reflect config

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java

Add the volatile keyword to AbstractInvoker's destroyed field to ensure multithreading visibility.
#13060

Add volatile on destroyed filed ensure visibility

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCall.java

Fix nullpoint problem when channel inactive

---

dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/NoAnnotationRestProtocolTest.java

Gson not support object as map key

Fix uts on 3.3

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/NoAnnotationRestProtocolTest.java

For example, environment variable DUBBO_REGISTRY_ADDRESS=zookeeper://127.0.0.1:2182 should override same configuration in dubbo.properties dubbo.registry.address=zookeeper://127.0.0.1:2181.

fix loading process cannot load environment variables.

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/beans/factory/annotation/ReferenceAnnotationWithAotBeanPostProcessor.java
dubbo-config/dubbo-config-spring6/src/main/java/org/apache/dubbo/config/spring6/beans/factory/annotation/ServiceAnnotationWithAotPostProcessor.java

ReferenceAnnotationWithAotBeanPostProcessor should extends ReferenceAnnotationBeanPostProcessor

---

.artifacts
dubbo-plugin/dubbo-plugin-loom/pom.xml
dubbo-plugin/dubbo-plugin-loom/src/main/java/org/apache/dubbo/common/threadpool/support/loom/VirtualThreadPool.java
dubbo-plugin/dubbo-plugin-loom/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.threadpool.ThreadPool
dubbo-plugin/dubbo-plugin-loom/src/test/java/org/apache/dubbo/common/threadpool/support/loom/VirtualThreadPoolTest.java
dubbo-plugin/pom.xml
dubbo-test/dubbo-test-modules/src/test/java/org/apache/dubbo/dependency/FileTest.java

Support `setThreadpool("virtual")` to enable virtual thread as server thread
Related https://github.com/apache/dubbo/issues/10768

Support project loom as thread pool factory

---

dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/filter/AuthenticationExceptionTranslatorFilter.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/filter/ContextHolderAuthenticationPrepareFilter.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/filter/ContextHolderAuthenticationResolverFilter.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/model/SecurityScopeModelInitializer.java
dubbo-plugin/dubbo-spring-security/src/main/java/org/apache/dubbo/spring/security/utils/SecurityNames.java

Enhance spring security class check

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/RegistryConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java

modify variable naming and extract constants

refactor: modify variable naming and extract constants

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriplePingPongHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleWritePingHandler.java

fix #12945
add ping pong for tri protocol
add fixed delay write ping frame handler

add ping pong for tri protocol

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigBeanInitializer.java

modify modulemodel obtain from beanfactory

refactor: modify modulemodel obtain from beanfactory

---

dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/filter/ServiceInvokeRestFilter.java

If there is no accept in the request header, set the default value.
refer to https://datatracker.ietf.org/doc/html/rfc2616#page-100

fix: set default value for accept

---

dubbo-dependencies-bom/pom.xml
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java

Similarly, to #13153, I noticed that in `RpcUtilsTest`, there is also a duplicate creation of the mock.
The `Invoker` was duplicated to create the mock object 10 times, in 10 test cases.
I used a similar approach refactoring to increase code readability.
I refactored the code to introduce two methods: `CreateMockInvoker(URL url)` and `CreateMockInvoker()`. I've used these methods in 10 test cases to reduce the repetitive creation of the `Invoker` mock.
I also noticed that this pattern appears in different test files for different packages, do you prefer to use shared utility classes or define these methods in each file?

Refactor rpc utils test

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/ReflectionAbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/call/ReflectionServerCallTest.java

Fix triple method override

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/LazyTargetInvocationHandler.java

```
Found one Java-level deadlock:
=============================
"xxx-Scheduler-1":
waiting to lock monitor 0x00007f7212cf1508 (object 0x000000072c394be0, a java.util.concurrent.ConcurrentHashMap),
which is held by "main"
"main":
waiting to lock monitor 0x00007f72131fd1c8 (object 0x000000072d2ed5f0, a org.apache.dubbo.config.spring.util.LazyTargetInvocationHandler),
which is held by "xxx-Scheduler-1"
Java stack information for the threads listed above:
===================================================
"xxx-Scheduler-1":
at org.apache.dubbo.config.spring.ReferenceBean.getCallProxy(ReferenceBean.java:407)
- waiting to lock <0x000000072c394be0> (a java.util.concurrent.ConcurrentHashMap)
at org.apache.dubbo.config.spring.ReferenceBean.access$100(ReferenceBean.java:109)
at …
```

Remove sync lock for lazy target

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java

Only throws exception when exporting service

---

dubbo-config/pom.xml

See: #13226
Use maven profile activation to include module  dubbo-config-spring6 only when the jdk version is >= 17.
Compile successfully with jdk 1.8

Dubbo 3.3 support compilation with jdk 1.8

---

dubbo-compatible/src/test/java/org/apache/dubbo/config/MethodConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/MethodConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/common/Person.java

Optimize code in MethodConfigTest, and add a new test.
- Remove unnecessary exception throw code
- Add the `convertMethodConfig2AsyncInfo` test in the `MethodConfigTest` class in `dubbo-config-api` module, which was added in `dubbo-compatible` module.
- The `MethodConfigTest` class in the `dubbo-compatible` module should test `MethodConfig` class in `com.alibaba.dubbo.config` package instead of the class with the same name in `org.apache.dubbo.config` package, which is tested in another test class.
- Remove the unnecessary manual cast from String type to Object type when calling `assertEquals` and `assertThat`, the type erasure mechanism will do it (the matcher will eventually be treated as `Matcher<Map>` instead of `Matcher<Map<Object, Object>>`).
run both MethodConfigTest.

feat: optimize MethodConfigTest

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java

optimize AbstractConfigTest
org.apache.dubbo.config.AbstractConfigTest
- Rewrite `testAppendProperties` related tests because `AbstractConfig.appendProperties` no longer exists.
- Remove unused inner test class `PropertiesConfig`.

optimize AbstractConfigTest

---

dubbo-common/src/main/java/org/apache/dubbo/common/json/impl/JacksonImpl.java

Consistent with RestEasy, deserialization no longer fail on unknown properties.

fix: jackson deserialization,not fail on unknown properties.

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractCacheManager.java

While the cache of meta-data/mapping info changing or refresh, it's print log by `AbstractCacheManager`, this is suitable for debugging not for production environment.
Modify suitable log level for the cache operate.

Modify suitable log level for the cache operate

---

dubbo-config/pom.xml

Fix compilation failure on jdk21
- Include module dubbo-config-spring6 in jdk17 higher versions.

Include module dubbo-config-spring6 in jdk17 higher versions

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/protocol/QosProtocolWrapper.java

If qos server isn't in started state, wouldn't stop it and log stop info.

Judging qos is in started state when stopping qos

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/factory/ScopeBeanFactory.java

remove unused method in ScopeBeanFactory.java
org.apache.dubbo.common.beans.factory.ScopeBeanFactory

opt: remove unused method in ScopeBeanFactory.java

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboInfraBeanRegisterPostProcessor.java

refactor: remove unuse applicationContext

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryNotifier.java

https://github.com/alibaba/nacos/issues/11294

Added scheduler closure check during RegistryNotifier notify.

---

dubbo-plugin/dubbo-compiler/src/main/java/org/apache/dubbo/gen/AbstractGenerator.java
dubbo-plugin/dubbo-compiler/src/main/java/org/apache/dubbo/gen/utils/ProtoTypeMap.java

when `option java_outer_classname` is empty and use Dubbo3TripleGenerator generate code , the DubboxxxServiceTriple has error.
My proto file :
```proto
syntax="proto3";
option java_package="com.example.dubbo.proto";
option java_multiple_files=true;
service TestService {
rpc echo(EchoReq)returns(EchoRes);
}
message EchoReq{
string name = 1;
}
message EchoRes{
string msg = 1;
}
```
and protoc-plugin
```xml
<plugin>
<groupId>org.xolstice.maven.plugins</groupId>
<artifactId>protobuf-maven-plugin</artifactId>
<version>0.6.1</version>
<configuration>
<protocArtifact>com.google.protobuf:protoc:${protoc.version}:exe:${os.detected.classifier}</protocArtifact>
<pluginId>grpc-java</pluginId>
<protocPlugins>
<protocPlugin>
<id>dubbo</id>
<groupId>org.apache.dubbo</groupId> …
```

fix:Dubbo3TripleGenerator use OuterClassName error

---

dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointAnnotationAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboMetricsAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboEndpointMetadataAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/autoconfigure/DubboHealthIndicatorAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-starters/observability/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/DubboMicrometerTracingAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-starters/observability/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/DubboObservationAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-starters/observability/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/brave/BraveAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-starters/observability/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/exporter/otlp/OtlpAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-starters/observability/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/exporter/zipkin/ZipkinAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-starters/observability/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/otel/OpenTelemetryAutoConfiguration.java

Fix dubbo.enabled=false not work in actuator configurators

---

dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalTest.java

- In `dubbo-common`, several test cases in the test class `dubbo-common,org.apache.dubbo.common.threadlocal.InternalThreadLocalTest.java` can trigger `java.lang.ClassCastException`, when being run after the unit test in `testConstructionWithIndex()` in the same class because it pollutes state shared among tests.
- It may be good to clean this state pollution so that some other tests do not fail in the future due to the shared state polluted by this test.
Issue Link: [DUBBO-13359](https://github.com/apache/dubbo/issues/13359)
- Changed `nextIndex.get()` to `nextIndex.incrementAndGet()` in `InternalThreadLocalTest.java` to properly restore the polluted state `InternalThreadLocalMap.NEXT_INDEX`
- With the proposed fix, the test does not pollute the shared state.
- All the tests pass when run …

Fix order dependent tests in `InternalThreadLocalTest`

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/TripleGoAwayHandler.java

Fix go away handler

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/ReflectUtils.java

Remove useless code
The findMethodByMethodSignature method in ReflectUtils.java，The `signature` field is not used

remove useless code in ReflectUtils.java

---

dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/h12/AbstractServerTransportListener.java

Fix ci execution failed due to missing error code

fix(rpc-triple): Fix missing error code

---

dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/dubbo-spring-boot-starters/observability/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/observability/autoconfigure/otel/OpenTelemetryAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-starters/observability/pom.xml

Bump io.micrometer:micrometer-tracing-bom from 1.1.6 to 1.2.0

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosAggregateListener.java

in NacosAggregateListener serviceInstances will be change when notify
so hashcode is not same with export put in nacosRegistry.nacosListeners 
so it can not delete when unexport

fix listener hash code error

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

- Fix #13436 
- Integration test cases: https://github.com/apache/dubbo-samples/pull/1027

Fix generic invoke failed for triple

---

dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/MethodStatComposite.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/data/RtStatComposite.java
dubbo-metrics/dubbo-metrics-api/src/main/java/org/apache/dubbo/metrics/report/AbstractMetricsExport.java

servce level  config is init after application config be load
test result is such as:

:bug: fix metrics servce level config bug

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/DataWrapper.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/DescriptorService.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethodTest.java

fix [#13363](https://github.com/apache/dubbo/issues/13363)
obtain actual type that is parameterized type in streamobserver.
see `org.apache.dubbo.rpc.protocol.tri.ReflectionPackableMethodTest#testObtainActualType`

Fix streamobserver actual type

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/aot/AotWithSpringDetector.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java

Fix https://github.com/apache/dubbo/issues/13465

Fix method annotation compile failed in native

---

dubbo-spring-boot/dubbo-spring-boot-autoconfigure/src/main/java/org/apache/dubbo/spring/boot/autoconfigure/DubboRelaxedBinding2AutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/autoconfigure/DubboAutoConfiguration.java

fix #13434
fix DubboAutoConfiguration and DubboRelaxedBinding2AutoConfiguration init too early,
can not be processed AOT in spring native image scenario

fix DubboAutoConfiguration can not be processed AOT in spring native image scenario

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/ssl/SslServerTlsHandler.java

…ode should remove and return instead of printing the error log.
When I read part of the Dubbo netty4 source code, I found SslServerTlsHandler#decode method in dealing with "providerConnectionConfig.getAuthPolicy() == AuthPolicy.NONE" not timely return，
this will cause it to print the error log

SslServerTlsHandler#decode early return

---

dubbo-compatible/src/test/java/org/apache/dubbo/generic/GenericServiceTest.java

The propose of this change is to make tests run faster. `DubboBootstrap` is only used once in the test `org.apache.dubbo.generic.GenericServiceTest`. There are five tests in the test class `org.apache.dubbo.generic.GenericServiceTest`. However, only `testGenericCompatible` tries to modify with `DubboBootstrap` and other four tests are not dealing with `DubboBootstrap`. Repeatly calling `DubboBootstrap.reset();` may cause a big cost in time. On our local machine, the time can jump from 4.281 s to 1.429 s after applying the change.
Change the `@BeforeEach` annotation to `@AfterEach` annotation to only call `DubboBootstrap.reset();` once.
We confirm that if make this change, the test run time can jump from `4.281 s` to `1.429 s`.

only call DubboBootstrap.reset(); once to make the test faster

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/ProtocolBuilder.java

ProtocolBuilder add sslEnabled and extProtocol fields, aligned with ProtocolConfig.

ProtocolBuilder add sslEnabled and extProtocol fields

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Fix issue https://github.com/apache/dubbo/issues/13496
* Add provider config `useJavaPackageAsPath`
* `useJavaPackageAsPath=ture` : Provider will export with java_package as path, which will cause exception when `package` and `java_package` are different.
* `useJavaPackageAsPath=false` (default) : Provider will export with package as path.

Fix proto `package` and ` java_package` issue

---

dubbo-common/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ProtobufUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ProtobufUtilsTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/HelloReply.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/HelloRequest.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ReflectionPackableMethod.java

The isProtobufClass method is extracted as a tool class, and the implementation is optimized.
optimize isProtobufClass method impl

optimize isProtobufClass method impl

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/StubMethodDescriptor.java
dubbo-compiler/src/main/resources/Dubbo3TripleStub.mustache
dubbo-compiler/src/main/resources/ReactorDubbo3TripleStub.mustache

One possible solution to fix issues mentioned in https://github.com/apache/dubbo/pull/13221

Fix StubMethodDescriptor generate issue

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

Fix https://github.com/apache/dubbo/issues/13184  
(`dubbo.tag` override by `consumer.tag` in `NacosRegistry`, which causes `TagStateRouter` not worked properly when provider using interface-level registry.)

Fix dubbo.tag override by consumer.tag in NacosRegistry

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java

* fix https://github.com/apache/dubbo/issues/12614

Fix MergeableClusterInvoker log issue

---

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/DefaultParamDeepCopyUtil.java

* fix https://github.com/apache/dubbo/issues/13497 
* fix https://github.com/apache/dubbo/issues/13498
* fix https://github.com/apache/dubbo/issues/13158

Fix protobuf class deep copy issue

---

.editorconfig

Maintain the source code format and spotless plugin format the same as much as possible through editorconfig

style(editorconfig): Maintain the source code format and spotless plugin

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/AbortPolicyWithReport.java

https://github.com/apache/dubbo/issues/13605
fix AbortPolicyWithReport Semaphore lock not released

fix AbortPolicyWithReport Semaphore lock not released

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ExceptionFilter.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/ExceptionFilterTest.java

there is a test method but execute by org.apache.dubbo.common.extension.ExtensionLoader#injectExtension
org.apache.dubbo.rpc.filter.ExceptionFilter#setLogger
ignore test method when  extensionLoader inject instance.
- [x ] Each commit in the pull request should have a meaningful subject line and body.

do not invoke test method(#13589)

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ConfigValidationUtilsTest.java

for #13341
* stop startup if the configuration of dubbo application name is invalid
* fix unit tests affected by this PR

check application name

---

dubbo-remoting/dubbo-remoting-http/src/test/java/org/apache/dubbo/remoting/http/rest/RestClientTest.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/constans/RestConstant.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/request/RequestFacade.java
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/util/DataParseUtils.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/DataParseUtilsTest.java
dubbo-rpc/dubbo-rpc-rest/src/test/java/org/apache/dubbo/rpc/protocol/rest/NettyRequestFacadeTest.java

When utilizing Dubbo REST with the @QueryParam annotation on parameters, issues with Chinese character decoding may arise. Refer to the [13349 issue](https://github.com/apache/dubbo/issues/13349#issuecomment-1879523852) for a comprehensive and detailed description of the problem, including its cause, solution, and an explanation of why it works.
RequestFacade.initParameters will decode the request uri with UTF-8 before parsing uri to parameters.
- I add more unit tests , then can pass, and I recommend you refer the [13349 issue](https://github.com/apache/dubbo/issues/13349#issuecomment-1879523852)

Hotfix rest Chinese encoding

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyConnectionClient.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriplePingPongHandler.java

Close the connection but not the client
optimize #13546

Close the connection but not the client
