apache/dubbo

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md
SECURITY.md

Various grammar fixes and improvements for documentation.
- Commented out a section of the PR template so that even if contributors don't delete the guidance section, it won't show up in the final submitted PR.
- Various grammar fixes in the contributing guidelines, README and security policy.
N/A

Grammar fixes

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodUtils.java

remove redundant modifiers

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/ConnectionListener.java

[Dubbo3.0-Triple]Simplify connection reconnect

---

dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java

Revert "Adjust the default log priority order,  use slf4j first"

---

dubbo-config/dubbo-config-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.event.EventListener

加载扩展的时候找不:org.apache.dubbo.config.event.listener.ServiceNameMappingList问题修复
XXXXX
XXXXX

3.0  ServiceNameMappingList class not found exeception

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/ConsulConstants.java
dubbo-configcenter/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfiguration.java
dubbo-metadata/dubbo-metadata-report-consul/src/main/java/org/apache/dubbo/metadata/store/consul/ConsulMetadataReport.java
dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/AbstractConsulRegistry.java
dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java
dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulServiceDiscovery.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Constants.java

Optimize some code related to consul
see more detail from #7518

Optimize some code related to consul

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java

Optimize Proxy WeakReference to SoftReference

Optimize Proxy WeakReference to SoftReference

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Proxy.java

fix  cache Class avoid PermGen space OOM in dubbo3.0
see more detail from #6742 
XXXXX
XXXXX

fix  cache Class avoid PermGen space OOM in dubbo3.0

---

dubbo-dependencies-bom/pom.xml
dubbo-rpc/dubbo-rpc-xml/pom.xml

Adjust the introduction of the xml rpc module

---

dubbo-rpc/dubbo-rpc-rmi/src/test/java/org/apache/dubbo/rpc/protocol/rmi/RmiProtocolTest.java

Disable RMI protocol test on github actions

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java

fix incorrect definition of instance variable name

fix incorrect definition of instance variable name

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java

For-#7528
log error to log system when getRegistry error.

When getRegistry error, log error.

---

dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/support/expiring/ExpiringCacheFactoryTest.java

add some test cases for this pr
add some test cases for expire cache
All the test cases has been passed

[requests-6480] add some test cases for this pr

---

dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java

Make [NetUtilsTest#testGetIpByHost()](https://github.com/apache/dubbo/blob/master/dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java) run successfully.
see #7552
update [NetUtilsTest#testGetIpByHost()](https://github.com/apache/dubbo/blob/master/dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java) test case
In some companies, there are short domains to simplify the full domain. So, the OPS team will set some rules to convert the short domain to IP address. Sometimes, the short domains is a string without separating with dots.
There are some examples in my company below:
+ run `ping dubbo`
+ run `ping assdfasdfasdfasd`
+ run `ping dubbo.local`
Update the domain and make sure the domain contains dot.
Also, we can see the domain `dubbo` has been …

fix: test case of NetUtilsTest#testGetIpByHost

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceRepository.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/support/GroupServiceKeyCache.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/support/ProtocolUtils.java
dubbo-metadata/dubbo-metadata-report-failover/src/test/java/org/apache/dubbo/metadata/store/failover/MockMetadataReport.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/tps/DefaultTPSLimiter.java
dubbo-rpc/dubbo-rpc-thrift/src/main/java/org/apache/dubbo/rpc/protocol/thrift/ThriftCodec.java

Revert "optimize putIfAbsent method to computeIfAbsent which may reduce some …"

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java

Fix tag override by consumer

---

dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryProtocolTest.java

fix RegistryProtocolTest.testExport run fail
see #7575

fix RegistryProtocolTest.testExport run fail

---

dubbo-metadata/dubbo-metadata-report-failover/src/main/java/org/apache/dubbo/metadata/store/failover/FailoverMetadataReport.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdRegistry.java
dubbo-registry/dubbo-registry-multicast/src/main/java/org/apache/dubbo/registry/multicast/MulticastRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

use CollectionUtils methods to perform Collection null validation
for issue #7560

Use CollectionUtils methods to perform Collection null validation

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

`RegistryProtocol` logger use own class.

[ Code Quality]Fix `RegistryProtocol` Logger

---

dubbo-registry/dubbo-registry-default/src/test/java/org/apache/dubbo/registry/dubbo/RegistryProtocolTest.java

Clean up useless code in RegisitryProtocolTest
see more detail from #7564

Clean up useless code in RegisitryProtocolTest

---

dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java

Make [MulticastRegistryTest#testUrlError()](https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java) run successfully.
see #7566
update [MulticastRegistryTest#testUrlError()](https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java) test case
see #7553
run `ping multicast`
run `ping dubbo.multicast`
Update the domain and make sure the domain contains dot.

fix: MulticastRegistryTest#testUrlError will throw wrong exception

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReportInstance.java

Fix issue that could lead to multiple init in MetadataReportInstance#init

---

dubbo-registry/dubbo-registry-nacos/src/main/java/com/alibaba/dubbo/registry/nacos/NacosRegistryFactory.java

Nacos StringUtils has version compatibility issues.

replace nacos StringUtils with dubbo-common StringUtils.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java

fix remove redundant references

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MonitorConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProtocolConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java

Fix Expected single matching of application, but found 2 instances, will randomly pick the first one. #6461

Fix default config is invalid

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshAppRuleListener.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleAddressListenerInterceptor.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleManager.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java

【3.0】Fix typo

---

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java

Restore part of the code that was mistakenly deleted (#6179 )， fix #7529 .

fix #7529, RegistryProtocol registerStatedUrl NPE.

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/issues/Issue6252Test.java

Remove unused import
Fix DubboBootstrapTest
Disable Issue6252Test

[3.0] Fix unit test

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/ConfigItem.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/DynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DynamicConfigurationServiceNameMapping.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/support/AbstractZookeeperClient.java

Add a new storage structure for zookeeper serviceNameMapping
see more detail from #7628

Add a new storage structure for zookeeper serviceNameMapping

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java

Convert the IllegalArgumentException generated by PojoUtils.realize in GenericFilter to RpcException
see more detail from #7642

Convert the IllegalArgumentException generated by PojoUtils.realize in GenericFilter to RpcException

---

dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml

Make each sub-demo in the dubbo-demo project consistent in the telnet function, remove the dubbo-qos dependency in dubbo-demo-xml-provider
see more detail from #7646

Make each sub-demo in the dubbo-demo project consistent in the telnet function, remove the dubbo-qos dependency in dubbo-demo-xml-provider

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/builders/AbstractInterfaceBuilderTest.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java
dubbo-metadata/dubbo-metadata-processor/src/test/java/org/apache/dubbo/metadata/annotation/processing/util/TypeUtilsTest.java

fix testPublishConfigCas exec fail

fix testPublishConfigCas exec fail

---

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/TimeoutCountDownTest.java

add test case for TimeoutCountDown
see more detail from #7661

add test case for TimeoutCountDown

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-dependencies-bom/pom.xml

nacos-client version upgrade to 1.4.1

Upgrade nacos-client version to 1.4.1

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/event/listener/PublishingServiceDefinitionListenerTest.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/ServiceDefinitionBuilder.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/store/AbstractAbstractWritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java

Fix injvm and metadata testcases

---

dubbo-common/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/reporter/FrameworkStatusReporter.java
dubbo-common/src/main/java/org/apache/dubbo/common/status/reporter/FrameworkStatusReporter.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DynamicConfigurationServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/ServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/WritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscoveryFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Introduces new SPI -- FrameworkStatusReporter and weaved it into the core process.

Collecting registration and consumption status inside process

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/EventPublishingServiceDiscovery.java

Fix method naming errors

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryChangeWatcher.java

Use volatile to modify variables to ensure visibility

---

dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/AbstractCacheFactory.java

Fix the concurrency problem when AbstractCacheFactory creates Cache
see more detail from #7674

Fix the concurrency problem when AbstractCacheFactory creates Cache

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Remove useless interface implementations declarations

---

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/RpcUtilsTest.java

add test case for RpcUtils.
see more detail from #7706

add test case for RpcUtils.

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java

[Dubbo-7715]Fix url was truncated unexpectedly

---

dubbo-rpc/dubbo-rpc-http/src/main/java/org/apache/dubbo/rpc/protocol/http/HttpProtocol.java

采用jsonrpc协议，当Provider侧比Consumer侧字段多时，会导致反序列化失败，报UnrecognizedPropertyException。
```java
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException;
import lombok.Data;
import org.junit.Before;
import org.junit.Test;
public class TestUnrecognizedFeld {
private String json;
@Before
public void setUp() {
this.json = "{\"id\": 1, \"name\": \"klz\", \"job\": \"it\"}";
}
@Test(expected = UnrecognizedPropertyException.class)
public void beforeFix() throws JsonProcessingException {
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.readValue(json, User.class);
}
@Test
public void afterFix() throws …
```

[Dubbo-7704]fix UnrecognizedPropertyException for jsonrpc

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractEndpoint.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractServer.java

These two properties have no actual call point, so think they can be removed

Remove unused property which retrieved from the URL

---

dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/util/NacosNamingServiceUtils.java

[ISSUE-#7729] Unify nacos param between metadataReport and dynamicConfig.

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java

Fix the logic error of CacheListener#getGroup method

---

dubbo-all/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/Constants.java
dubbo-serialization/dubbo-serialization-msgpack/pom.xml
dubbo-serialization/dubbo-serialization-msgpack/src/main/java/org/apache/dubbo/common/serialize/msgpack/MsgpackObjectInput.java
dubbo-serialization/dubbo-serialization-msgpack/src/main/java/org/apache/dubbo/common/serialize/msgpack/MsgpackObjectOutput.java
dubbo-serialization/dubbo-serialization-msgpack/src/main/java/org/apache/dubbo/common/serialize/msgpack/MsgpackSerialization.java
dubbo-serialization/dubbo-serialization-msgpack/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.serialize.Serialization
dubbo-serialization/dubbo-serialization-msgpack/src/test/java/org/apache/dubbo/common/serialize/msgpack/MsgpackObjectOutputTest.java
dubbo-serialization/pom.xml

Add msgpack serialization support
支持msgpack方式的序列化协议

Add msgpack serialization support

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/RpcUtils.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java

- Reduce case convert
- Reduce iterator creation
- Add attribute to MethodDescriptor

[3.0] Performance Optimization

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboLifecycleComponentApplicationListener.java

Remove unused variable

---

dubbo-common/src/main/java/org/apache/dubbo/common/URLBuilder.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLBuilderTest.java

Fix URLBuilder#addParametersIfAbsent 
see more information from #7761

Fix URLBuilder#addParametersIfAbsent (#7761)

---

dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java

Add test cases with # in the parameters for URLTest
see more detail from #7766

Add test cases with # in the parameters for URLTest

---

dubbo-metadata/dubbo-metadata-report-zookeeper/src/test/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReportTest.java

Revert and fix ZookeeperMetadataReportTest
see more info from #7768

Revert and fix ZookeeperMetadataReportTest (#7768)

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java

Optimize the initialization logic of AbstractMetadataReport
see more detail from  #7590

Optimize the initialization logic of AbstractMetadataReport

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilder.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/builder/DefaultTypeBuilder.java

process TypeDefinition#properties when necessary
for issue #7580

Process TypeDefinition#properties when it is not a primitive type object

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java

Fix Filter Disappear when theirs simple name is equals

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java

Optimize the AbstractConfig#appendAnnotation method

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/AnnotatedInterfaceConfigBeanBuilder.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceBeanBuilder.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboReferencePostProcessAfterInitializationTest.java

https://github.com/apache/dubbo/issues/7789

feature: As a FactoryBean type, ReferenceBean supports calling applyBeanPostProcessorsAfterInitialization. Add Unit Test

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java

```
private boolean needWrap() {
if (CommonConstants.$INVOKE.equals(methodName) || CommonConstants.$INVOKE_ASYNC.equals(methodName)) {
return true;
} else if ($ECHO.equals(methodName)) {
return true;
} 
...
...
}
```
method need methodName to judge, but methodName initial place after this judgement.

Make method and methodName first set.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Optimize ServiceConfig code and extract constants
see more detail from #7792

Optimize ServiceConfig code and extract constants

---

dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/ReferenceCountManagedChannel.java

Fix ReferenceCountManagedChannel#incrementAndGetCount return type
see more detail in #7794

Fix ReferenceCountManagedChannel#incrementAndGetCount return type

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

Make sure change local serviceInstance after remote operation.

Make sure change local serviceInstance after remote operation.

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/RemotingServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/ExchangeServerDelegate.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/header/HeaderExchangeServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractEndpoint.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/ServerDelegate.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyCodecAdapter.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java

Optimize the code in some places for HeaderExchangeServer and NettyServer

Optimize the code in some places

---

dubbo-serialization/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/optimized/KryoObjectInput2.java
dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/kryo/KryoSerialization2Test.java

Fix the problem that occurs when using kryo to deserialize Attachments.
修复kryo反序列化Attachments异常错误

Fix the problem that occurs when using kryo to deserialize Attachments

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/InvokeTelnetHandler.java

Optimize InvokeTelnetHandler code format
issue: #7813

Optimize InvokeTelnetHandler code format

---

dubbo-metadata/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
dubbo-registry/dubbo-registry-multiple/src/test/java/org/apache/dubbo/registry/multiple/MultipleRegistry2S2RTest.java
dubbo-registry/dubbo-registry-redis/src/test/java/org/apache/dubbo/registry/redis/RedisRegistryTest.java
dubbo-rpc/dubbo-rpc-redis/src/test/java/org/apache/dubbo/rpc/protocol/redis/RedisProtocolTest.java

Improve test cases about redis

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java

Add tests for ZookeeperDynamicConfiguration (#7823)
Related issue: #7823

Add tests for ZookeeperDynamicConfiguration

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java

Fix stateRouter‘s addrCache error

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/DubboComponentScanRegistrar.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/autoconfigure/DubboAutoConfiguration.java

see more information from #7667

[3.0] ServiceAnnotationBeanPostProcessor should be changed to ServiceClassPostProcessor

---

dubbo-common/src/main/java/org/apache/dubbo/common/URLBuilder.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLBuilderTest.java

see more information from #7761

[3.0] Fix URLBuilder#addParametersIfAbsent 

---

dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/ReferenceCountManagedChannel.java

see more information from #7794

[3.0] Fix ReferenceCountManagedChannel#incrementAndGetCount return type

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/InvokeTelnetHandler.java

see more information from #7813

[3.0] Optimize InvokeTelnetHandler code format

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AddrCache.java

Fix semaphore usage error when calculating address.

---

.github/workflows/build-and-test-3.yml
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/event/listener/PublishingServiceDefinitionListenerTest.java
dubbo-config/dubbo-config-spring/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-metadata/dubbo-metadata-report-redis/pom.xml
dubbo-metadata/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/MetricsFilterTest.java
dubbo-registry/dubbo-registry-multicast/src/test/java/org/apache/dubbo/registry/multicast/MulticastRegistryTest.java
dubbo-registry/dubbo-registry-multiple/pom.xml
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ThreadNameTest.java

Improve Test cases for Dubbo 3.0, from #7592 #7829

[Github-Actions] Improve Test cases

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceAddressURL.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/LRUCache.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/LRUCacheTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/cache/CacheTest.java
dubbo-distribution/dubbo-all/pom.xml
dubbo-filter/dubbo-filter-cache/src/test/java/org/apache/dubbo/cache/filter/CacheFilterTest.java

- fix get wrong `group` key from `AbstractInvoker`
- LRU2 is cherry picked from #7461
- Add dubbo-filter-cache and dubbo-filter-validation into dubbo-all

Fix Integration Test

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/DynamicConfigurationServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/ServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java

Remove unused variables

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java
dubbo-registry/dubbo-registry-consul/src/test/java/org/apache/dubbo/registry/consul/ConsulRegistryTest.java

- Opt ConsulRegistryTest Retry
- Change zk remove listener check key

Improve UT cases

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/Constants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java

Optimize ConfigValidationUtils, extract constants
see more detail from #7834

Optimize ConfigValidationUtils, extract constants

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackCluster.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailfastCluster.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverCluster.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailsafeCluster.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingCluster.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareCluster.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/CharSequenceComparator.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/MethodComparator.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/JavaCodeTest.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/DubboConfigAliasPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
dubbo-metadata/dubbo-metadata-processor/src/main/java/org/apache/dubbo/metadata/annotation/processing/rest/AbstractServiceRestMetadataResolver.java
dubbo-metadata/dubbo-metadata-processor/src/main/java/org/apache/dubbo/metadata/annotation/processing/util/ExecutableElementComparator.java
dubbo-metadata/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/InterfaceCompatibleRegistryProtocol.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdRegistry.java
dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdServiceDiscovery.java
dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java
dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/RpcMessageHandler.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/MockInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java
dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcProtocol.java
dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/java/JavaObjectInput.java

Reorder the modifiers to comply with the Java Language Specification.

Reorder the modifiers to comply with the Java Language Specification.

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/UrlMergeProcessor.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/DefaultUrlMergeProcessor.java
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.UrlMergeProcessor
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ClusterUtilsTest.java
dubbo-common/src/main/java/org/apache/dubbo/config/ConsumerConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/builders/ConsumerBuilder.java
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/dubbo.xsd

Support url merge processor extension

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java

issue: #7862 
Optimize ZookeeperDynamicConfiguration#doClose

Optimize ZookeeperDynamicConfiguration#doClose (#7862)

---

dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/listener/InvokerListenerTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/listener/MapInvokerListener.java
dubbo-rpc/dubbo-rpc-api/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.InvokerListener

add test case for InvokerListener
see more detail from #7872

add test case for InvokerListener

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java

Fix the problem that the info method is called at the debug log level

Fix the problem that the info method is called at the debug log level

---

dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/filter/MockChannel.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/filter/TraceFilterTest.java

issue: #7876 
Add unit test for TraceFilter

Add unit test for TraceFilter

---

dubbo-common/src/main/java/org/apache/dubbo/common/BaseServiceMetadata.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ReferenceConfigCache.java

Reuse the existing method of generating ServiceKey

Reuse the existing method of generating ServiceKey

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/TimeoutCountDown.java

Fix the calculation error of TimeoutCountDown#elapsedMillis method

---

dubbo-configcenter/dubbo-configcenter-apollo/src/test/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfigurationTest.java

Add unit test for ApolloDynamicConfiguration #7892 
Update org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java file

feat: add aubbo_configcenter_apollo_removeListener_test

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/SslConfigTest.java

add unit test for SslConfig #7878 
add src/test/java/org/apache/dubbo/config/SslConfigTest.java file

add unit test for SslConfig

---

dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ThreadNameTest.java

Opt ThreadNameTest check

---

dubbo-common/src/main/java/org/apache/dubbo/common/BaseServiceMetadata.java
dubbo-common/src/test/java/org/apache/dubbo/common/BaseServiceMetadataTest.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/Ready.java

Fix the problem that it does not work when using telnet for online/offline

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/Server.java

Optimize  qos server to be compatible with linux epoll

Optimize  qos server to be compatible with linux epoll

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/NetUtilsTest.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/status/ServerStatusCheckerTest.java

add test case for ServerStatusChecker
see more detail from #7888

add test case for ServerStatusChecker

---

dubbo-distribution/dubbo-bom/pom.xml

[3.0] Fix dubbo-bom

---

dubbo-bom/pom.xml

Fix dubbo-bom

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/server/handler/HttpProcessHandler.java

Extract common logic for HttpProcessHandler to optimize it

Extract common logic for HttpProcessHandler to optimize it

---

dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryFactoryTest.java
dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryTest.java

issue: #7921
Add test cases for dubbo-registry-zookeeper

Add test cases for dubbo-registry-zookeeper

---

dubbo-common/src/main/java/org/apache/dubbo/config/SslConfig.java
dubbo-dependencies-bom/pom.xml
dubbo-remoting/dubbo-remoting-netty4/pom.xml
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/SslContexts.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/SslContextsTest.java
pom.xml

ssl support ciphers&protocols

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java

Disable ZkDynamicConfigTest

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

[ISSUE-#6758] The forbidden change to false must depend on invokerUrls isNotEmpty.

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java

issue: #7925 
Replace list with set in ExtensionLoader

Replace list with set in ExtensionLoader

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java
dubbo-common/src/main/java/org/apache/dubbo/common/compiler/Compiler.java
dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JavassistCompiler.java
dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/ThreadPool.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/cached/CachedThreadPool.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/eager/EagerThreadPool.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/fixed/FixedThreadPool.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/limited/LimitedThreadPool.java
dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/CacheFactory.java
dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/expiring/ExpiringCacheFactory.java
dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/jcache/JCacheFactory.java
dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/lfu/LfuCacheFactory.java
dubbo-filter/dubbo-filter-cache/src/main/java/org/apache/dubbo/cache/support/lru/LruCacheFactory.java

Use constants instead of literals

Use constants instead of literals

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/AbstractConfigurator.java

The action to fill the collection comes after the URL matching process to avoid invalid fill collections
XXXXX
XXXXX

Fill conditionKeys collections when necessary

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java

refactor(3.0): refactor to optimize the {@code AbstractInvoker#invoke()} code
+ comments added
+ code optimization
+ make process clearer
Relative issues: #7947
In {@code AbstractInvoker}:
1. Add more comments.
2. Divide {@code invoke()} into three sub-step functions.
3. Fix `Different expressions` in #7947
4. Fix `Useless try-catch` in #7947

[3.0] refactor to optimize the {@code AbstractInvoker#invoke()} code

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/test/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClientTest.java

Use nodeCache to take place of treeCache

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocolTest.java

add test case for DubboProtocol
see more detail from #7916

add test case for DubboProtocol

---

NOTICE
dubbo-cluster/src/test/resources/org/apache/dubbo/rpc/cluster/router/file/availablerule.javascript
dubbo-cluster/src/test/resources/org/apache/dubbo/rpc/cluster/router/file/methodrule.javascript
dubbo-cluster/src/test/resources/org/apache/dubbo/rpc/cluster/router/file/notAvailablerule.javascript
dubbo-rpc/dubbo-rpc-native-thrift/src/test/idls/DemoService.thrift
dubbo-rpc/dubbo-rpc-native-thrift/src/test/idls/UserService.thrift
dubbo-rpc/dubbo-rpc-thrift/src/test/thrift/ClassNameTestDubbo.thrift
dubbo-rpc/dubbo-rpc-thrift/src/test/thrift/ClassNameTestThrift.thrift
dubbo-rpc/dubbo-rpc-thrift/src/test/thrift/Demo.thrift
pom.xml

- rat check .thrift and .javascript files
- remove protobuf notice

Fix license

---

NOTICE
dubbo-cluster/src/test/resources/org/apache/dubbo/rpc/cluster/router/file/availablerule.javascript
dubbo-cluster/src/test/resources/org/apache/dubbo/rpc/cluster/router/file/methodrule.javascript
dubbo-cluster/src/test/resources/org/apache/dubbo/rpc/cluster/router/file/notAvailablerule.javascript
pom.xml

fix license for 3.0

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceAddressURL.java

Fix get wrong path for ServiceAddressURL

---

dubbo-dependencies-bom/pom.xml
dubbo-registry/dubbo-registry-xds/pom.xml
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/XdsCertificateSigner.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/XdsEnv.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/XdsServiceDiscovery.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/XdsServiceDiscoveryFactory.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioCitadelCertificateSigner.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioConstant.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/istio/IstioEnv.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/util/PilotExchanger.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/util/XdsChannel.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/AbstractProtocol.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/impl/EdsProtocol.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/impl/LdsProtocol.java
dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds/util/protocol/impl/RdsProtocol.java
dubbo-registry/dubbo-registry-xds/src/main/proto/ca.proto
dubbo-registry/dubbo-registry-xds/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.xds.XdsCertificateSigner
pom.xml

- Introduce `IstioCitadelCertificateSigner`
- Convert delta-xds to polling mode
- xDS basically work

Introduce cert signer for xDS, opt xDS Impl

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/CustomizedLoaderClassPath.java

Add generics to avoid forced conversion

Add generics to avoid forced conversion

---

dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/concurrent/ScheduledCompletableFutureTest.java

Add unit test for ScheduledCompletableFuture

Add unit test for ScheduledCompletableFuture

---

dubbo-common/src/test/java/org/apache/dubbo/common/config/EnvironmentConfigurationTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/infra/InfraAdapterTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConfigUtilsTest.java

Add InfraAdapterTest

---

dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryFactoryTest.java
dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryTest.java

pick from https://github.com/apache/dubbo/pull/7922/commits/6562935fae20bc558a36df3e51a03aa1eef04328

[3.0] Add test cases for dubbo-registry-zookeeper

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java

[Dubbo-7989][3.0] Add shutdown logic for Executor in ExecutorRepository

---

dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepositoryTest.java

add test case for ExecutorRepository
see more detail from #7993

add test case for ExecutorRepository

---

dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java

Add test case for URL

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java

[3.0] Remove redundant get method

---

.gitignore
dubbo-demo/dubbo-demo-triple/pom.xml
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/GreeterService.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/GreeterServiceImpl.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/GreeterWrapperService.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/GreeterWrapperServiceImpl.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/consumer/ApiConsumer.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/consumer/ApiWrapperConsumer.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/provider/ApiProvider.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/provider/ApiWrapperProvider.java
dubbo-demo/dubbo-demo-triple/src/main/proto/helloworld.proto
dubbo-demo/dubbo-demo-triple/src/main/resources/log4j.properties
dubbo-demo/pom.xml

The reason for adding the `triple` protocol as a `dubbo-demo` is as follows:
+ `triple` protocol released in `3.0-preview` version. There are not many people who know it, we can promote it through `dubbo-demo`
+ There are 4 examples in `dubbo-demo`, they are good for `dubbo` protocol but not good for `triple` protocol
+ We can make a good comparison between the `dubbo` protocol and `triple` protocol
+ I know all of dubbo's samples are in the [dubbo-samples](https://github.com/apache/dubbo-samples) project. However, the purpose of this project is to let users know how to use it, not be good for developers to study. It is very inconvenient for people who like to read the source codes
Therefore, I strongly recommend to add `triple` protocol into `dubbo-demo` module.
1. add …

feat: add triple demo

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java

Fix urls may be null, and NullPointerException will be thrown in ConfigValidationUtils
In this issue(https://github.com/apache/dubbo/issues/8020 ), this pr is to fix this issue, to avoid throwing NullPointerException in ConfigValidationUtils, thanks
Fixes https://github.com/apache/dubbo/issues/8020

Fix urls may be null, and NullPointerException will be thrown in ConfigValidationUtils (#8020)

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLPlainParam.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DefaultDynamicParamSource.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicParamSource.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicParamTable.java
dubbo-common/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.url.component.param.DynamicParamSource
dubbo-distribution/dubbo-all/pom.xml
dubbo-monitor/dubbo-monitor-api/src/main/java/org/apache/dubbo/monitor/support/MonitorFilter.java
dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/DubboMonitorTest.java

Add default Dynamic Param Key

---

dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/pom.xml
dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/pom.xml
dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/pom.xml
dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/pom.xml
dubbo-demo/dubbo-demo-generic-call/pom.xml
dubbo-demo/dubbo-demo-triple/pom.xml
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/pom.xml
dubbo-demo/dubbo-demo-xml/pom.xml

[ISSUE #8033] Add zk, nacos dependent dependency at demo module

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscovery.java

[3.0] Format code

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Fix concurrent modified problem

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java

see #8046 
1. remove the wrong logger
2. extract constant
3. update access permission
4. remove unnecessary import

Optimize RouterChain code

---

dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/util/KubernetesConfigUtils.java

formatting code

---

dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JavassistCompiler.java
dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/pom.xml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/src/main/java/com/apache/dubbo/demo/graalvm/consumer/Application.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-interface/pom.xml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/pom.xml
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/src/main/java/org/apache/dubbo/demo/graalvm/provider/Application.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/src/main/java/org/apache/dubbo/demo/graalvm/provider/DemoServiceImpl.java
dubbo-demo/dubbo-demo-native/pom.xml
dubbo-graalvm/pom.xml
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java

support native image

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

Ignore invalid MetadataReportConfig.

[3.0] Ignore invalid MetadataReportConfig

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

Ignore invalid MetadataReportConfig.

[2.7] Ignore invalid MetadataReportConfig

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java

修复Consumer启动时报空指针异常的问题，相关issue：https://github.com/apache/dubbo/issues/8078
修复Consumer启动时报空指针异常的问题，相关issue：apache#8078
* 方法 ReferenceAnnotationBeanPostProcessor#isAnnotatedReferenceBean 增加判空逻辑。
按照现有单元测试即可。

[3.0] Fix NullPointerException on consumer startup#8078

---

.github/workflows/build-and-test-3.yml

Disable File System Test for all envs

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java

Remove needless toString convert & Enable checking by default

---

.asf.yaml
.travis.yml
PULL_REQUEST_TEMPLATE.md
README.md
SECURITY.md

Migrate Github Rule Profile

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/PathURLAddress.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/ServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReport.java
dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java
dubbo-metadata/dubbo-metadata-report-zookeeper/src/main/java/org/apache/dubbo/metadata/store/zookeeper/ZookeeperMetadataReport.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandler.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/SubMigrationRule.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparatorTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandlerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleListenerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/model/MigrationRuleTest.java

Refactor NameMapping to Metadata, Support application field in MigrationRule

---

dubbo-registry/dubbo-registry-xds/pom.xml

Upgrade grpc gen version

---

.travis.yml

limit maven log length in travis

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java

[3.0] Optimize MigrationRuleListener

---

dubbo-common/src/main/java/org/apache/dubbo/common/logger/LoggerFactory.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Fix some compatiable issues

---

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/init-reference.xml

Add tests for reference tag attribute.
Issue: https://github.com/apache/dubbo/issues/8094

[2.7] Add tests for reference tag attribute

---

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessorTest.java
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/init-reference.xml
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/legacy/ShutdownTelnetHandlerTest.java

Add tests for reference tag attribute.  
Issue: https://github.com/apache/dubbo/issues/8094

[3.0] Add tests for reference tag attribute

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/BootstrapTakeoverMode.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/BootstrapTakeoverState.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapApplicationListener.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleHandler.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java

- Extract default migration value from consumerURL
- fix NPE in getServices
- change ConfigValidation check of filter support cluster filter
- introduce BootstrapTakeoverState

Optimize Service related issues

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapServletContextListener.java

Support servlet takeover mode.
* Add `DubboBootstrapServletContextListener`
* Check before change bootstrap takeover mode

[3.0] Support servlet takeover mode

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/model/MigrationRule.java

Opt Migration & Fix reSubscribe for ServiceDiscovery

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReport.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Fix NPE in MetadataInfo

---

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/PortUnificationServerTest.java

Fix NettyServerTest test case problem for 3.0
see more detail from #8105

Fix NettyServerTest test case problem for 3.0

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java

Optimize NetUtils#getAvailablePort to avoid port occupation for 3.0
see more detail from #8118

Optimize NetUtils#getAvailablePort to avoid port occupation for 3.0

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataCustomizer.java

Fix customizer not changed

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/mock/MockServiceListener.java

Add service config to bootstrap when init, fix raw api scenario.

[3.0] Add service config to bootstrap when init

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java

Ignore duplicated equivalent config, for resolving hsf3 add duplicated config-centers.

[3.0] Ignore duplicated equivalent config

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

Clone ServiceInstance for multi registry

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvoker.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvoker.java
dubbo-common/src/main/java/org/apache/dubbo/common/Version.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java

Optimize performance & Fix some potential bugs

---

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ConsumerModel.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/GenericServiceTest.java
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-generic-consumer.xml
dubbo-config/dubbo-config-spring/src/test/resources/log4j.xml

Support generic call by reference without interface class locally.

[3.0] Support generic call by reference without interface class locally

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ServiceBean.java

Improve service exported logic.

[3.0] Improve service exported logic

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java

see #8153 
1. update the access permission of variables
2. make variables visible under multi-thread conditions

perf:The access permission and variable visibility are unreasonable

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java

add exception catch for RemovalTask, ensure semaphore release

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/WritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

Now the code already is't be used.
https://github.com/apache/dubbo/blob/c8cefee04f82199646fe79b8b401d489d27d0e3b/dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java#L117-L120
Do some work for remove.

Code clean: ready to remove ApplicationModel.application

---

dubbo-rpc/dubbo-rpc-triple/pom.xml
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocolTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/support/IGreeter.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/support/IGreeterImpl.java

add test case for TripleProtocol
see more detail from #8146

add test case for TripleProtocol

---

dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/MultiplexProtocolConnectionManagerTest.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/SingleProtocolConnectionManagerTest.java

add test case for MultiplexProtocolConnectionManager
see more detail from #8162

add test case for MultiplexProtocolConnectionManager

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java

see #8166 
Update `Random` to `ThreadLocalRandom`

perf: Improve the performance for generating random numbers

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceBeanNameBuilder.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/util/DubboAnnotationUtils.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/consumer.properties
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/schema/GenericServiceTest.java
dubbo-config/dubbo-config-spring/src/test/resources/META-INF/spring/dubbo-generic-consumer.xml

Support export generic service with @DubboService annotation, without service interface locally

[3.0] Improve generic service with @DubboService annotation

---

dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java
dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java
dubbo-demo/dubbo-demo-triple/pom.xml
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/consumer/ApiConsumer.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/consumer/ApiWrapperConsumer.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/provider/ApiProvider.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/provider/ApiWrapperProvider.java

Use new code model in dubbo-demo-triple.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

fix re-start override dynamic config

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java

ignore instance when metadataInfo is null

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/configcenter/ConfigItem.java
dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/WritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/RemoteMetadataServiceImpl.java

Code clean at metadata service.

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java

see #8182 
1. make invokers visible
2. update log variable style and access permission

perf: Make invokers visible to all threads

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

fix issue-8042
use originUrl  instead of currentUrl  when creating new url

fix issue-8042

---

dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TriplePathResolverTest.java

add test case for TriplePathResolver
see #8204

add test case for TriplePathResolver

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/PropertiesConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java

issues 8194 fix  better 

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/AbstractRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/ConditionRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/AppRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ListenableRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ServiceRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mock/MockInvokersSelector.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/script/ScriptRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java

perf: Optimize access permissions of variables

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java

fix CompletableFuture call methods  #8202

FIX issue 8202

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/ConnectionTest.java

Fix the problem that in the Triple protocol, an error will be reported immediately when the service is exposed
see more detail from #8124

Fix the problem that in the Triple protocol, an error will be reported immediately when the service is exposed

---

dubbo-common/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConfigCenterConfigTest.java

Fix ConfigCenterConfig.setAddress #8237

[3.0] Fix ConfigCenterConfig.setAddress #8237

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/metadata/ConfigurableMetadataServiceExporter.java

[Dubbo-8241] Service delay export config ignore metadata service

---

dubbo-common/src/main/java/org/apache/dubbo/config/ConfigKeys.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/boot/conditional4/JavaConfigReferenceBeanConditionalTest4.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/ReferenceKeyTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java

improve duplicated config checking and add tests for reference annotation.

[3.0] improve duplicated config checking and add tests for reference annotation.

---

dubbo-common/pom.xml
dubbo-common/src/test/java/org/apache/dubbo/descriptor/DescriptorService.java
dubbo-common/src/test/java/org/apache/dubbo/descriptor/MethodDescriptorTest.java
dubbo-common/src/test/java/org/apache/dubbo/proto/HelloReply.java

1.add test case for MethodDescriptor#rpcType
2.Fix the spelling problem of MethodDescritorTest
see #8235

add test case for MethodDescriptor

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ServiceConfigTest.java

see #8261
Optimize code in ServiceConfig.doExportUrlsFor1Protocol.

Optimize code in ServiceConfig.doExportUrlsFor1Protocol.

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/ZooKeeperServerTesting.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/AbstractIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/IntegrationService.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/IntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/registryprotocol/AbstractRegistryProtocolTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/registryprotocol/RegistryProtocol4DubboTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/registryprotocol/RegistryProtocolIntegrationService.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/registryprotocol/package-info.java

see #8245 
1. define an integration framework
2. test RegistoryProtocol with dubbo protocol

Add integration testcase for testing ServiceConfig and RegistryProtocol

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java

Fix org.apache.dubbo.rpc.protocol.tri.TripleClientHandler#writeRequest in getServiceKey throwing NPE problem
see more detail from #8244

Fix org.apache.dubbo.rpc.protocol.tri.TripleClientHandler#writeRequest in getServiceKey throwing NPE problem

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java

Fix NPE when parse migration rule error happen

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionLoaderTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/activate/impl/ActivateExt1Impl1.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/activate/impl/OrderActivateExtImpl1.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/activate/impl/OrderActivateExtImpl2.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/support/ActivateComparatorTest.java

Fix Activated Extensions order

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java

Replace with ring for registry notification & suppress property checker

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/ProviderURLMergeProcessor.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java

Remove some local only parameters

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/Constants.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/OverrideInstanceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/InMemoryWritableMetadataService.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

[3.0] Add Dynamic Configuration Override Support For ServiceDiscovery

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/SingleRegistryCenterDubboProtocolIntegrationTest.java

see #8301 
Add integration testcase for testing `ReferenceConfig` and `RegistryProtocol`
- [] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

test: Add integration testcase for testing ReferenceConfig and RegistryProtocol

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/ServiceDefinitionBuilder.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/model/MethodDefinition.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/model/ServiceDefinition.java

merge 2.7 metadata annotations definition to 3.0

merge 2.7 metadata annotations definition to 3.0

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

add provider configuration override disable option

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java

Optimize calculation of capacity in URLParam

Optimize calculation of capacity in URLParam

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java

Fix Config id Override when both using API and Spring

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Use TreeSet to ensure ServiceNames order

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/OverrideInstanceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java

fix service discovery not work on bootstrap & fix address pollution

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/SingleRegistryCenterDubboProtocolIntegrationTest.java

Add integration testcase to check the process from RegistryProtocol to ServiceDiscoveryRegistryDirectory
Add testcases

Add integration testcases for consumer side

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryNotifier.java

Make first 10 calls notify not delay

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/definition/builder/EnumTypeBuilder.java

Remove logger output when init & Fix Enum inaccessible cause NPE

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLParam.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/param/DynamicParamTable.java

Adjust the modifier of DynamicParamTable#init method

Adjust the modifier of DynamicParamTable#init method

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

并发访问时，这行代码可能未执行
server.reset(url);

concurrent call,lost reset

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java

[3.0]Nacos notify `ServiceInstancesChangedEvent`

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

Make initialize synchronized

---

dubbo-common/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java
dubbo-config/dubbo-config-api/pom.xml
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/config/YamlPropertySourceFactory.java
dubbo-dependencies-bom/pom.xml
dubbo-distribution/dubbo-all/pom.xml
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java

Dependencies Upgrade

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java

[3.0] Remove parse placeholder in beanName logic

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java

Fix ServiceInfo contains runtime params

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java

Fix service parameter fetch order

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Add the lost @Override annotation of Config.

Add the lost @Override annotation of Config.

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

see #8381 #8225 
1. Make the exception more explicit
2. Threw RepException instead of logging

bugfix: Throw RpcException when NacosException occurred

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java

Fix Metadata Service Info param filter not work

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/ReferenceBean.java

[3.0] Fix idea warning no beans of type "xxx" found

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java

Configcenter ban accessLogKey and FileRouterFactory key.

Configcenter ban accessLogKey and FileRouterFactory key

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/injvm/InjvmFilter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/injvm/SingleRegistryCenterInjvmIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/injvm/SingleRegistryCenterInjvmService.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/injvm/SingleRegistryCenterInjvmServiceImpl.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/listener/InjvmExporterListener.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/listener/InjvmServiceListener.java
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.config.ServiceListener
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.rpc.ExporterListener
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.rpc.Filter

see #8394 
1. Verify the exported services through the custom ServiceListener
2. Verify the exported exporters through the custom ExporterListener
3. Verify the filter chain through the custom Filter

test: Add testcases for checking the process of exporting Injvm protocol

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapApplicationListener.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigBeanInitializer.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboInfraBeanRegisterPostProcessor.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/autoconfigure/DubboAutoConfiguration.java

improve config bean initialization compatible with spring 3.x/4.1.x.

[3.0] improve config bean initialization compatible with spring 3.x/4.1.x

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboBootstrapApplicationListener.java

fix error of  register dubbo bootstrap application listener if not found  `DubboConfigBeanInitializer` bean

fix error of  register dubbo bootstrap application listener manually

---

dubbo-dependencies-bom/pom.xml
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/DefaultHessian2FactoryInitializer.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/WhitelistHessian2FactoryInitializer.java

[3.0] Upgrade hessian lite version

---

dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/DefaultHessian2FactoryInitializer.java
dubbo-serialization/dubbo-serialization-hessian2/src/main/java/org/apache/dubbo/common/serialize/hessian2/dubbo/WhitelistHessian2FactoryInitializer.java

[3.0] `org.apache.dubbo.*` add serialization whitelist

---

dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
pom.xml

Update pom to 2.7.14-SNAPSHOT

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java

Compact with filed change declaration override for Javaassist

---

dubbo-dependencies-bom/pom.xml

upgrade netty、httpclient、zookeeper、tomcat、jetty、apollo、commons-io.

Upgrade dependencies

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshAppRuleListener.java

Fix delete mesh rule `NullPointerException `

[3.0]Fix delete mesh rule npx

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshAppRuleListener.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java

Add volatile modifier to some variables

Add volatile modifier to some variables

---

dubbo-dependencies-bom/pom.xml

upgrade hessian-lite version

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java

Compact with adaptive extensions when ApplicationModel is null

---

dubbo-remoting/dubbo-remoting-zookeeper-curator5/pom.xml

dubbo-remoting-zookeeper-curatot5 test may throw npe, it's curator problem.
stack error:
```
java.lang.NullPointerException
at org.apache.zookeeper.server.persistence.FileTxnSnapLog.fastForwardFromEdits(FileTxnSnapLog.java:321)
at org.apache.zookeeper.server.ZKDatabase.fastForwardDataBase(ZKDatabase.java:300)
at org.apache.zookeeper.server.ZooKeeperServer.shutdown(ZooKeeperServer.java:821)
at org.apache.zookeeper.server.ZooKeeperServer.shutdown(ZooKeeperServer.java:772)
at org.apache.zookeeper.server.NIOServerCnxnFactory.shutdown(NIOServerCnxnFactory.java:922)
at org.apache.curator.test.TestingZooKeeperMain.close(TestingZooKeeperMain.java:186)
at org.apache.curator.test.TestingZooKeeperServer.stop(TestingZooKeeperServer.java:118)
at …
```

upgrade curator version to 5.1.0.

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/DubboConfigBeanInitializerTest.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/localcall/LocalCallTest2.java
dubbo-config/dubbo-config-spring/src/test/resources/log4j.xml
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReportFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java

1. See #8438
2. Any exceptions occurred will cause the resource can not be released, when calling `DubboBootstrap#destroy` method.
```java
public void destroy() {
if (destroyLock.tryLock()
&& shutdown.compareAndSet(false, true)) {
try {
if (destroyed.compareAndSet(false, true)) {
if (started.compareAndSet(true, false)) {
unregisterServiceInstance();
unexportMetadataService();
unexportServices();
unreferServices();
}
destroyRegistries();
destroyProtocols();
destroyServiceDiscoveries();
destroyExecutorRepository();
destroyMetadataReports();
// check config
checkConfigState();
clear();
shutdown();
release();
onStop();
}
destroyDynamicConfigurations();
ShutdownHookCallbacks.INSTANCE.clear();
}finally {
initialized.set(false);
startup.set(false);
destroyLock.unlock();
}
}
```
1. Catch and …

perf: Avoid that resources are not released during calling destroy

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/rule/VirtualServiceRuleTest.java

Add unit test for VirtualServiceRule

Add unit test for VirtualServiceRule

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshAppRuleListener.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleAddressListenerInterceptor.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/rule/DestinationRuleTest.java

Extract constants and use tool methods to judge empty

Extract constants and use tool methods to judge empty

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryServerStream.java

https://github.com/apache/dubbo/issues/8363

[3.0-Triple] Support attachment when triple\'s resopnse is an exception

---

dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java

compact with some registry without address

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java

avoid get interface from classloader

Change Service Info revision cal structure

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/injvm/MultipleRegistryCenterInjvmIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/SingleRegistryCenterDubboProtocolIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/injvm/SingleRegistryCenterInjvmIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/registrycenter/DefaultMultipleRegistryCenter.java

fix address in used error of port 2181

[3.0] fix address in used error of port 2181

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractMethodConfigTest.java

I noticed that there is a test subclass [MethodConfig](https://github.com/wx930910/dubbo/blob/master/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractMethodConfigTest.java#L123) extends production class [AbstractMethodConfig](https://github.com/wx930910/dubbo/blob/321789d8131f5a3769b240c9304ea468eae48d61/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java#L28) to test the parent production class. This might not be the best priactice in unit testing and can be improved by leveraging mocking frameworks.
- Replace MethodConfig with spying objects created by Mockito.

refactor MethodConfig by using mocking object created by Mockito

---

dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/AbstractStorage.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/Storage.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/servicediscoveryregistry/MultipleRegistryCenterServiceDiscoveryRegistryIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/servicediscoveryregistry/MultipleRegistryCenterServiceDiscoveryRegistryRegistryServiceListener.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/servicediscoveryregistry/MultipleRegistryCenterServiceDiscoveryRegistryService.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/servicediscoveryregistry/MultipleRegistryCenterServiceDiscoveryRegistryServiceImpl.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/servicediscoveryregistry/ServiceDiscoveryRegistryInfoWrapper.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/servicediscoveryregistry/ServiceDiscoveryRegistryStorage.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/SingleRegistryCenterDubboProtocolIntegrationTest.java
dubbo-config/dubbo-config-api/src/test/resources/META-INF/services/org.apache.dubbo.registry.RegistryServiceListener

see #8490 
1. Check ServiceDiscoveryRegistry
2. Check InMemoryWritableMetadataService

test: verify service-discovery-registry protocol in multiple registry center

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagDynamicStateRouter.java

Fix typo and some optimizations

Fix typo and some optimizations

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleConstant.java

- Fixed TLS using scheme HTTP when using TRI protocol

Fixed TLS using scheme HTTP when using TRI protocol

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java

Just fixed a couple things in spell or grammar

fix some comments

---

dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
pom.xml

update version to 3.0.3-SNAPSHOT.

update version to 3.0.3-SNAPSHOT.

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java

https://github.com/apache/dubbo/issues/8544

fix NPE on serialization checking when request timed out

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshEnvListenerFactory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleManager.java
dubbo-distribution/dubbo-all/pom.xml
dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesMeshEnvListenerFactory.java
dubbo-registry/dubbo-registry-kubernetes/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.router.mesh.route.MeshEnvListener
dubbo-registry/dubbo-registry-kubernetes/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.router.mesh.route.MeshEnvListenerFactory

Compact with dubbo-all without farbic-io

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java
dubbo-common/src/test/java/org/apache/dubbo/descriptor/DescriptorService.java
dubbo-common/src/test/java/org/apache/dubbo/descriptor/MethodDescriptorTest.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java

run samples https://github.com/guohao/dubbo-samples/tree/add-tri-samples/dubbo-samples-triple

[3.0-Triple] Support triple server stream

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/BroadcastClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/BroadCastClusterInvokerTest.java

Fix bug of BroadcastClusterInvoker and add test cases

Fix bug of BroadcastClusterInvoker and add test cases

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConfigUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ModuleConfig.java
dubbo-common/src/test/java/org/apache/dubbo/config/AbstractInterfaceConfigTest.java
dubbo-common/src/test/java/org/apache/dubbo/config/Greeting.java
dubbo-common/src/test/java/org/apache/dubbo/config/GreetingLocal1.java
dubbo-common/src/test/java/org/apache/dubbo/config/GreetingLocal2.java
dubbo-common/src/test/java/org/apache/dubbo/config/GreetingLocal3.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ConfigValidationUtilsTest.java

【3.0】Verify additional configuration during service reference

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java

Fix MetadataService connections leak

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/MockInvoker.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceA.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceAMock.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceB.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/DemoServiceBMock.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvokerTest.java

same as #8520, submitted to wrong branch.

fix Issue 8516 on branch master: fix mock:true configuration.

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/absent/AbsentConfiguratorTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/override/OverrideConfiguratorTest.java

Add test cases to the Configurator after version 2.7

Add test cases to the Configurator after version 2.7

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

Ignore Exception when creating Reference (for generic call)

---

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ConfigTest.java

ignore the testcase before fixed
merged PR: https://github.com/apache/dubbo/pull/8534
related test pipeline
+ [8579](https://github.com/apache/dubbo/pull/8579/checks?check_run_id=3399549539#step:5:27908)
+ [8578](https://github.com/apache/dubbo/pull/8578/checks?check_run_id=3398128823#step:5:27943)
+ [8573](https://github.com/apache/dubbo/pull/8573/checks?check_run_id=3397391785#step:5:33004)
disable testcase of ConfigTest#testReferGenericExport

fix: disable testcase of ConfigTest#testReferGenericExport

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java

Fix some grammar error in the code

Fix some grammar error

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboCodecSupport.java

Fix issue #8589, should be use Camel-Case rule

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/HeaderFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/TokenHeaderFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.HeaderFilter
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryServerStream.java

Add Header Filter for Triple Protocol

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java

Support unary void response
run samples here 
https://github.com/apache/dubbo-samples/blob/bc03fc59d27e7e3d03133ff231c5525e2d73ff36/dubbo-samples-triple/src/main/java/com/apache/dubbo/sample/basic/ApiWrapperConsumer.java

[3.0-Triple]Support triple void response

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/Stream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientInboundHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2ClientResponseHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleServerInboundHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStreamTest.java

[3.0-Triple] Remove operation handler

---

dubbo-rpc/dubbo-rpc-triple/pom.xml
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/GrpcStatus.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/HealthStatusManager.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriBuiltinService.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriHealthImpl.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriService.java
dubbo-rpc/dubbo-rpc-triple/src/main/proto/health.proto
pom.xml

- Add tri inner health service
use https://github.com/grpc-ecosystem/grpc-health-probe and return `status: SERVING`

[3.0-triple] Add tri inner health service

---

README.md

on branch 2.7.x, fix issue #8611, use HTTPS

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceDiscovery.java

Statement lambda can be replaced with expression lambda.

[3.0] Statement lambda can be replaced with expression lambda

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/WrapperComparator.java

fix #8387  remove unused code.
this commit has been merged into 3.0 branch.

fix issue-8387 on master: remove unused code.

---

dubbo-rpc/dubbo-rpc-api/src/main/java/com/alibaba/dubbo/rpc/support/MockInvoker.java
dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/support/DemoServiceA.java
dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/support/DemoServiceAMock.java
dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/support/DemoServiceB.java
dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/support/DemoServiceBMock.java
dubbo-rpc/dubbo-rpc-api/src/test/java/com/alibaba/dubbo/rpc/support/MockInvokerTest.java

fix #8516 on branch 2.6.x.
ps: this commit has been merge into 3.0 and master branch.

fix issue-8516 on 2.6.x: fix mock:true configuration

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/url/UrlTestBase.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/reference/javaconfig/JavaConfigReferenceBeanTest.java

Add ApplicationModel destroy support and ut support

---

compiler/pom.xml
dubbo-rpc/dubbo-rpc-triple/pom.xml

Bump compiler version to 0.0.3  release

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java

[3.0-Triple] Fix client can not recognize trailers only

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java

[3.0-Triple]OnError in executor

---

dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/java/JavaSerialization.java
dubbo-serialization/dubbo-serialization-jdk/src/main/java/org/apache/dubbo/common/serialize/nativejava/NativeJavaSerialization.java

Add Serialization warning message to java serialization

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/SerializeClassChecker.java

2.7.13 fix add serialize check switch，use config to read SerializeClassChecker config

2.7.13 fix add serialize check switch

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java

AbstractLoadBalance#getWeight should be decorated with protected (#8692)

---

.github/workflows/build-and-test-3.yml
dubbo-common/src/main/java/org/apache/dubbo/common/utils/NetUtils.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-monitor/dubbo-monitor-default/src/test/java/org/apache/dubbo/monitor/dubbo/MetricsFilterTest.java

[3.0] Simplify and unify local address getting method

---

.github/workflows/build-and-test-3.yml
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

[3.0] only unsubscribe not null listener in RegistryProtocol.unexport

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModelDestroyListener.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java

- Add ScopeModel Destroy Listener Support
- Add ApplicationModel to DubboBootstrap binding refer

[3.0] Opt Scope Model

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryNotifier.java

Add log output when notify error

---

dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java

Inject ScopeModel when adding into ConfigManger

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

FIX: the consumerModel's NPE in TripleClientHandler

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceAddressURL.java

Add ConsumerUrl adapt to ServiceAddressURL

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServerHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/WireProtocol.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/EmptyProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java

[3.0-Triple] Add multiple instance support for wire protocol

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagDynamicStateRouter.java

[3.0] remove duplicate catch block

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java

Failed retries of failback should be judged first

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailbackClusterInvoker.java

fix issue-8715 on master: failback retries=0 should only invoke once

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/PropertiesConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionDirector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConfigUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/PojoUtils.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/ExtensionDirectorTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConfigUtilsTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/AbstractConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConfigCenterConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ConsumerConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapTest.java
dubbo-container/dubbo-container-api/src/main/java/org/apache/dubbo/container/Main.java
dubbo-container/dubbo-container-spring/src/main/java/org/apache/dubbo/container/spring/SpringContainer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/OverrideInstanceAddressURL.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

Add ClassLoader Binding for ScopeModel

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

fix issue-8726 on master: improve code readability

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/ExchangeClient.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java

[3.0] close client immediately when destroy unused invoker

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/ExchangeClient.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java

fix #8752 #8748 #6404 on master

[master] close client immediately when destroy unused invoker

---

dubbo-config/dubbo-config-spring/pom.xml
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/registrycenter/AbstractRegistryCenter.java

Slightly reduce the UT time in `dubbo-config-spring` module
1. Upgrade zookeeper to 3.6.0
2. Upgrade curator to 5.1.0

test: Upgrade the version for UT in dubbo-config-spring

---

dubbo-dependencies-bom/pom.xml

[2.7] Update Hessian Lite Version

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/CacheableFallbackRegistryTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMappingTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/MetadataUtilsTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/store/InMemoryMetadataServiceTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/model/MigrationRuleTest.java

Refactor Destroy Listener for ScopeModel

---

dependencies-bom/pom.xml

[2.6] update hessian lite version

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/Request.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/support/DefaultFuture.java

[master] DefaultFuture turn off logging optimization for Channel(issue #8695)

---

dubbo-common/src/main/java/org/apache/dubbo/common/BaseServiceMetadata.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceModel.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java

Fix Triple Classloader & Add backward of ServiceMetadata

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/identifier/BaseApplicationMetadataIdentifier.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/identifier/BaseServiceMetadataIdentifier.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/identifier/BaseApplicationMetadataIdentifierTest.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/identifier/BaseServiceMetadataIdentifierTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Add unit test for Base[Service/Application]MetadataIdentifier

Add unit test for Base[Service/Application]MetadataIdentifier

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkServiceRepository.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/SingleRegistryCenterDubboProtocolIntegrationTest.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryScopeModelInitializer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/status/RegistryStatusChecker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/RegistryManager.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryFactoryTest.java
dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistryTest.java
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/src/main/java/org/apache/dubbo/spring/boot/actuate/endpoint/metadata/DubboShutdownMetadata.java

Refactor AbstractRegistryFactory (exact static field)

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/DubboBootstrapMultiInstanceTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/exportprovider/MultipleRegistryCenterExportProviderFilter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/multiple/injvm/MultipleRegistryCenterInjvmFilter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/exportprovider/SingleRegistryCenterExportProviderFilter.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/integration/single/injvm/SingleRegistryCenterInjvmFilter.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/StandardMetadataServiceURLBuilder.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-api/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.client.ServiceInstanceCustomizer
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java

Fix DubboProtocol state & Fix NPE when destroy

---

dubbo-cluster/src/main/java/org/apache/dubbo/registry/AddressListener.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/ClusterFilter.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Filter.java
dubbo-rpc/dubbo-rpc-dubbo/src/test/java/org/apache/dubbo/rpc/protocol/dubbo/ArgumentCallbackTest.java

Change Filter & AddressListener scope to Module

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/StandardMetadataServiceURLBuilder.java

Fix MetadataInfo Module

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java

Add ModelName for ScopeModel

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/OrderedPropertiesProvider.java

Change OrderedPropertiesProvider SPI scope to Module

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java
dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/CtClassBuilder.java

Fix Javaassist ClassPool ClassPath

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleConstant.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleUtil.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriBuiltinService.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriHealthImpl.java

Adapt Triple Protocol to Multi-Instances

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java

Fix ModuleModel update environment when update Classloaders

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboDeployApplicationListener.java

Catch exception of stop module when spring closing

Catch exception of stop module when spring closing

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/migration/MigrationRule.java

[2.7] Change default step to FORCE_INTERFACE

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/ModuleEnvironment.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/OrderedPropertiesConfiguration.java

Fix ModuleModel update Properties

---

dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

[3.0]Fix nacos admin protocol cant't get interface name

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java

string judge optimization
`StringUtils.isEmpty(xxx)`substitute for `xxx == null`

[3.0] String judge optimization

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Add ScopeModel to Local Invoke

---

dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java

[3.0] fix StringIndexOutOfBoundsException at addParam()

---

dubbo-common/src/main/java/org/apache/dubbo/common/URLStrParser.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java

[master] fix StringIndexOutOfBoundsException at addParam()

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java

[3.0] add invocation null check at decode(Channel, InputStream)

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

[master] add zookeeper node data created event check

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/CacheListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

[3.0] add zookeeper node data created event check

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/MetadataReportInstance.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/AbstractServiceNameMappingTest.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/report/MetadataReportInstanceTest.java

Add unit test for MetadataReportInstance and AbstractServiceNameMapping

Add unit test for MetadataReportInstance and AbstractServiceNameMapping

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java

add some FailoverClusterInvoker unit tests

[3.0] Enhance FailoverClusterInvoker unit test

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationRuleListenerTest.java

1.Improve the logic of MigrationRuleListener#destroy method
2.Fix typo

Improve the logic of MigrationRuleListener#destroy method

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java

[master] Remove useless code.

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvokerTest.java

1.add some FailfastClusterInvokerTest unit test
2.pretty code

[3.0] Enhance FailfastClusterInvokerTest unit test

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvokerTest.java

1.add some ForkingClusterInvoker unit test
2.pretty code

[3.0] Enhance ForkingClusterInvoker unit test

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

[2.7.x] Fix CountDownLatch not being released(#8845)

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleModel.java

Fix destroy notify order

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java

Revert FrameworkModel notify destroy order

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java
dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistryTest.java

1. ZookeeperRegistry CountDownLatch should be release
2. add some unit test

[3.0] ZookeeperRegistry CountDownLatch should be release and add some UT

---

dubbo-common/src/main/java/org/apache/dubbo/common/logger/jcl/JclLogger.java
dubbo-common/src/main/java/org/apache/dubbo/common/logger/slf4j/Slf4jLogger.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractMethodConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractServiceConfig.java

fix some wrong serialVersionUID

[3.0] fix serialVersionUID

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/factory/ScopeBeanFactory.java

Fix concurrent bean creation error

Fix concurrent bean creation error

---

dubbo-common/src/main/java/org/apache/dubbo/common/logger/support/FailsafeLogger.java

Add Logger Disabled Option

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassLoaderResourceLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConfigUtils.java

Add ClassLoaderResourceLoader to cache ClassLoader's resources

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/Menu.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/MenuComparator.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/Page.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/PageHandler.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/PageServlet.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/ResourceFilter.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/pages/HomePageHandler.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/pages/LogPageHandler.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/pages/StatusPageHandler.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/container/page/pages/SystemPageHandler.java

Fix #8843, recover Servlet Page API

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

[3.0] Fix CountDownLatch not being released(#8845)

---

dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java

[3.0] Fix when subscribing, the check configuration section is unavailable(#8841)

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagDynamicStateRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStaticStateRouter.java

[3.0] fix-#8518, remove meaningless code

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java

Try Load Class from interface parameter

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboConfigBeanInitializer.java

Add ModuleModel Qualifier for SpringBean Initializer

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java

Convert TimeoutException when invoke timeout

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java

socks proxy filtering local address

[3.0] socks proxy filtering local address

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/event/listener/MockServiceInstancesChangedListener.java

Support Multi Subscribe for Service Discovery

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java

Fix delay export not work for ServiceConfig

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java

[3.0] fix MergeableClusterInvoker NPE

---

dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtilsTest.java

Add test case for ServiceInstanceMetadataUtilsTest

Add test case for ServiceInstanceMetadataUtilsTest

---

dubbo-remoting/dubbo-remoting-http/src/main/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpServer.java
dubbo-remoting/dubbo-remoting-http/src/test/java/org/apache/dubbo/remoting/http/tomcat/TomcatHttpBinderTest.java

[3.0] add destroy() calling to close tomcat server port

---

dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/AbstractServiceDiscoveryFactoryTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/support/MockServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/support/MockServiceDiscoveryFactory.java
dubbo-registry/dubbo-registry-api/src/test/resources/META-INF/dubbo/org.apache.dubbo.registry.client.ServiceDiscoveryFactory
dubbo-registry/dubbo-registry-api/src/test/resources/META-INF/services/org.apache.dubbo.registry.client.ServiceDiscovery
dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/util/CuratorFrameworkUtilsTest.java

Add unit test for CuratorFrameworkUtils and AbstractServiceDiscoveryFactory

Add unit test for CuratorFrameworkUtils and AbstractServiceDiscoveryFactory

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java

[3.0] fix testInvoke_retryTimes_withBizException

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java

[3.0-Triple] optimize triple server send frame error handler

---

dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java

[master] Fix-#8506 MultipleRegistry remove duplicate URL

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/EventPublishingServiceDiscovery.java

issue  #8339, remove duplicate validation

[master] Fix #8339, remove duplicate validation

---

dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleRegistry.java
dubbo-registry/dubbo-registry-multiple/src/main/java/org/apache/dubbo/registry/multiple/MultipleServiceDiscovery.java

[3.0] Optimize Multiple some code

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java

1.add volatile
2.log level
3.fix comments

Fix the AbstractServiceDiscovery#serviceInstance attribute without adding volatile modifier

---

dubbo-demo/dubbo-demo-generic-call/src/main/java/org/apache/dubbo/demo/consumer/GenericApplication.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/GenericFilter.java

+ An optimization of generic invocation in gson format

An optimization of generic invocation in gson format

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AvailableClusterInvokerTest.java

add some AvailableClusterInvoker unit test

[3.0] add some AvailableClusterInvoker unit test

---

dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
pom.xml

3.0.3 release

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java

remove duplicate method on DubboBootstrap#destroy()

[master] Fix remove duplicate method

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java
dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java

1. nacos support doUnsubscribe
2. MockClusterInvoker destroy need destroy directory
#8895 second question， notify and recreate the destroy ReferenceConfig connect

Nacos unsub support and RegistryDirectory destroy

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java

Fix State Router Throw Exception when Address is Empty

---

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java
dubbo-rpc/dubbo-rpc-injvm/src/test/java/org/apache/dubbo/rpc/protocol/injvm/InjvmDeepCopyTest.java

Reset ServiceModel in Injvm Invoke

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalanceTest.java

The same pr has been merged in master branch. And this is a patch for 3.0
Improve consistent hashing load balancing with a new algorithm which can resolve problems mentioned in #4103
A new algorithm "Consistent Hashing with Bounded Loads"introduced by Vahab Mirrokni (work at Google Research) in 2018 can resolve this problem.
Brief introduction quoted from a blog which use this new algorithm and works well (https://medium.com/vimeo-engineering-blog/improving-load-balancing-with-a-new-consistent-hashing-algorithm-9f1bd75709ed):
Here is a simplified sketch of the algorithm. Some details are left out, and if you intend to implement it yourself, you should definitely go to the original paper for information.
First, define a balancing factor, c, which is greater than 1. c controls how much …

Improve consistent hashing load balancing with a new algorithm(patch for 3.0)

---

dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java
dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/JavaCodeTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/compiler/support/JdkCompilerTest.java

optimise jdk compile error message

optimise compile error message in jdk compiler.(#8942)

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouterTest.java

[ISSUES #8940]Fix instance mode mesh route can't get url parameters

---

dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/DubboStateListener.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/ShutdownHookTest.java
dubbo-config/dubbo-config-spring/src/test/resources/org/apache/dubbo/config/spring/demo-provider.xml

[3.0] Patch shutdown hook test

---

dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryTest.java

[master] add latch waiting for registration finished

---

dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryTest.java

[3.0] add latch waiting for registration finished

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvoker.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/MergeableClusterInvokerTest.java

add some MergeableClusterInvoker unit test

[3.0] Enhance mergeable cluster invoker test

---

dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java

Fix exception info
Fix the current thread's ClassLoader did not switch back

Fix exception info

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/factory/ScopeBeanFactory.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionDirector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java

* Check destroyed state of bean factory and extension loader
Maybe get bean after bean factory is destroyed.
see https://github.com/apache/dubbo/runs/4042205535?check_suite_focus=true
```
Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.069 s <<< FAILURE! - in org.apache.dubbo.registry.support.AbstractRegistryFactoryTest
Error:  org.apache.dubbo.registry.support.AbstractRegistryFactoryTest.testDestroyAllRegistries  Time elapsed: 0.026 s  <<< ERROR!
java.lang.IllegalStateException: Unable to fetch RegistryManager from ApplicationModel BeanFactory. Please check if `setApplicationModel` has been override.
at org.apache.dubbo.registry.support.AbstractRegistryFactoryTest.testDestroyAllRegistries(AbstractRegistryFactoryTest.java:119)
```

[3.0] Check destroyed state of bean factory and extension loader

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/tps/StatItem.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/tps/DefaultTPSLimiterTest.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/filter/tps/StatItemTest.java

Fix https://github.com/apache/dubbo/issues/4280

Fix statItem attribute memory visibility problem

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java

Destroy ServiceInstancesChangedListener

[3.0] Destroy ServiceInstancesChangedListener

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ClientOutboundTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/OutboundTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/ServerOutboundTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleClientRequestHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleCommandOutBoundHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/WriteQueue.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/CancelQueueCommand.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/DataQueueCommand.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/FlushQueueCommand.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/HeaderQueueCommand.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/QueuedCommand.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/TextDataQueueCommand.java

[3.0-Triple] Add WriteQueue for Triple

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/MD5Utils.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/MD5UtilsTest.java
dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/RevisionResolver.java
dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java

* Fix MD5Utils concurrent error
* Add MD5UtilsTest

[3.0] Fix MD5Utils concurrent error

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2FrameServerHandler.java

Support upper-case method for native grpc client

[3.0-Triple] Support upper case method

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/test/java/org/apache/dubbo/common/URLTest.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/common/URL.java
dubbo-remoting/dubbo-remoting-zookeeper-curator5/src/main/java/org/apache/dubbo/remoting/zookeeper/curator5/Curator5ZookeeperClient.java
dubbo-remoting/dubbo-remoting-zookeeper/src/main/java/org/apache/dubbo/remoting/zookeeper/curator/CuratorZookeeperClient.java

According to rfc3986, Revise the logic of changing the authority in the URL
Fix https://github.com/apache/dubbo/issues/5202

Revise the logic of changing the authority in the URL

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/StandardMetadataServiceURLBuilder.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/MetadataUtilsTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/StandardMetadataServiceURLBuilderTest.java

Fix MetadataService referProxy error #9190

[3.0] Fix MetadataService referProxy error #9190

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/OutboundTransportObserver.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TransportState.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TransportStateTest.java

Fix exception when method not found 
> Exception in processing triple message, dubbo version: 3.0.5.1-SNAPSHOT, current host: 11.166.11.136
java.lang.IllegalStateException: Metadata endStream already sent to peer, send DefaultHttp2Headers[:status: 200, content-type: application/grpc+proto, grpc-status: 12, grpc-message: Method%20%3AsayHello%20not%20found%20of%20s
ervice%3Acom.helloworld.Greeter] failed!
at org.apache.dubbo.rpc.protocol.tri.OutboundTransportObserver.checkSendMeta(OutboundTransportObserver.java:36)
at org.apache.dubbo.rpc.protocol.tri.ServerOutboundTransportObserver.onMetadata(ServerOutboundTransportObserver.java:44)
at org.apache.dubbo.rpc.protocol.tri.TripleHttp2FrameServerHandler.responseErr(TripleHttp2FrameServerHandler.java:279)
at …

[3.0-Triple] Fix bad state error when method not found

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

Add get raw invokers in Directory Support

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceConfigURL.java

[3.0] lazy init attributes in URL

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java
dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/src/main/resources/spring/dubbo-consumer.properties
dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-provider/src/main/resources/spring/dubbo-provider.properties
dubbo-demo/dubbo-demo-api/dubbo-demo-api-consumer/src/main/java/org/apache/dubbo/demo/consumer/Application.java
dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java
dubbo-demo/dubbo-demo-generic-call/src/main/java/org/apache/dubbo/demo/consumer/GenericApplication.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-consumer/src/main/java/com/apache/dubbo/demo/graalvm/consumer/Application.java
dubbo-demo/dubbo-demo-native/dubbo-demo-native-provider/src/main/java/org/apache/dubbo/demo/graalvm/provider/Application.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/consumer/ApiConsumer.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/consumer/ApiWrapperConsumer.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/provider/ApiProvider.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/provider/ApiWrapperProvider.java
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/resources/spring/dubbo-consumer.xml

Fix https://github.com/apache/dubbo/issues/9148 https://github.com/apache/dubbo/issues/9182

Fix MetadataService port conflict

---

dubbo-dependencies-bom/pom.xml

upgrade to jedis 3.7.0

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListenerTest.java

[3.0] cancel last retryFuture, destory listener after each test

---

dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/autoconfigure/DubboListenerAutoConfiguration.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/resources/META-INF/spring.factories

[3.0] Fix WelcomeLogoApplicationListener not triggered

---

dubbo-common/src/test/java/org/apache/dubbo/common/utils/AnnotationUtilsTest.java

The test `org.apache.dubbo.common.utils.AnnotationUtilsTest#testGetAllDeclaredAnnotations` is flaky. If run with different random seeds it will fail occasionally.
The root cause of it is due to an ordering bug in `java.lang.reflect` package. The function `getDeclaredAnnotation` does not have persistent order when calling each time.
This fix is mainly to mute the acknowledge the existence of the ordering issue and mute the bug in test case.
Rewrite the testcase in a different manner.
The new testcase is not assuming a fixed order of `annotations`. Instead it dynamically tries to match the types.
The previous test fails here because the wrong order of `annotations` may lead to an impossible conversion.
`mvn -pl dubbo-common edu.illinois:nondex-maven-plugin:1.1.2:nondex …

[3.0] Fix flaky due to annotation order Issue #9121

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/serial/SerializingExecutor.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/PortUnificationExchanger.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/CancellationContextTest.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/GrpcStatus.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/SingleProtobufUtils.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryServerStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriBuiltinService.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/service/TriHealthImpl.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/GrpcDataDecoderTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/SingleProtobufUtilsTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2ClientResponseHandlerTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/service/TriBuiltinServiceTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/service/TriHealthImplTest.java

Add unit test for rpc-triple module

Add unit test for rpc-triple module

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistryDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

[3.0] Pre-allocate map size in Directory

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceAddressURL.java

[3.0] Print consumerURL parameters in ServiceAddressURL

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLAddress.java

[3.0] Cache hashCode of URL to improve hash performance

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionDirector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java

[3.0] Reduce object creation when getting extensions

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/BitList.java

[3.0] Reduce array creation when routing

---

dubbo-rpc/dubbo-rpc-grpc/src/test/java/org/apache/dubbo/rpc/protocol/grpc/GrpcProtocolTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocolTest.java

[3.0] release CPU to run StreamObserver methods

---

dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/rest/SpringRestService.java
dubbo-metadata/dubbo-metadata-processor/src/test/java/org/apache/dubbo/metadata/rest/SpringRestService.java

Remove param directly return in RestService

---

dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/rest/SpringRestService.java
dubbo-metadata/dubbo-metadata-processor/src/test/java/org/apache/dubbo/metadata/rest/SpringRestService.java

Remove all method with param directly return in RestService

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/test/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfigurationTest.java

Optimize of ZookeeperDynamicConfigurationTest

[3.0] Optimize of ZookeeperDynamicConfigurationTest

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java

[3.0] Ignore configFile get from dynamicConfiguration if disabled

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

[3.0] InJvmInvoker copied RpcInvoker add targetServiceUniqueName

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/SslContexts.java
dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/GrpcOptionsUtils.java

[3.0]Fix netty ssl file leak

---

dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-consumer/pom.xml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-consumer/src/main/java/org/apache/dubbo/springboot/demo/consumer/ConsumerApplication.java
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-consumer/src/main/resources/application.yml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-consumer/src/main/resources/log4j.properties
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-interface/pom.xml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-interface/src/main/java/org/apache/dubbo/springboot/demo/DemoService.java
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/pom.xml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/src/main/java/org/apache/dubbo/springboot/demo/provider/DemoServiceImpl.java
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/src/main/java/org/apache/dubbo/springboot/demo/provider/ProviderApplication.java
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/src/main/resources/application.yml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/src/main/resources/log4j.properties
dubbo-demo/dubbo-demo-spring-boot/pom.xml
dubbo-demo/pom.xml
pom.xml

Add dubbo spring boot demo

---

dubbo-demo/dubbo-demo-annotation/dubbo-demo-annotation-consumer/src/main/resources/spring/dubbo-consumer.properties
dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/resources/spring/dubbo-consumer.xml

Revert zk config for demo

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java

Fix NPE when calculateState

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java

[3.0] revert AbstractConfiguratorListener#genConfiguratorsFromRawRule

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/AbstractConfiguratorListener.java

[master] revert AbstractConfiguratorListener#genConfiguratorsFromRawRule

---

dubbo-common/src/test/java/org/apache/dubbo/common/utils/AnnotationUtilsTest.java

The purpose of this change is to **fix 2 flaky tests** in the 3.0 version. 
The following tests are flaky:
```
org.apache.dubbo.common.utils.AnnotationUtilsTest.testGetAllMetaAnnotations
org.apache.dubbo.common.utils.AnnotationUtilsTest.testGetMetaAnnotations
```
The tests passes when run regular test command line:
```
mvn -pl dubbo-common test -Dtest=org.apache.dubbo.common.utils.AnnotationUtilsTest#testGetAllMetaAnnotations
mvn -pl dubbo-common test -Dtest=org.apache.dubbo.common.utils.AnnotationUtilsTest#testGetMetaAnnotations
```
But it fails when running the NonDex Tools:
```
mvn -pl dubbo-common edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.dubbo.common.utils.AnnotationUtilsTest#testGetAllMetaAnnotations
mvn -pl dubbo-common …
```

[3.0] Fix flaky tests caused by java getDeclaredAnnotations()

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java

dubbo MigrationInvoker promotion problem

optimization MigrationInvoker promotion (#9270)

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java

[3.0] Fix issue where dead connections would not be reconnected.

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/support/InstantiationStrategy.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/LoadingStrategy.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassLoaderResourceLoader.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkServiceRepository.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModelAwareExtensionProcessor.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceMetadata.java
dubbo-common/src/test/java/org/apache/dubbo/common/CommonScopeModelInitializerTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/FrameworkServiceRepositoryTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ModuleServiceRepositoryTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ScopeModelAwareExtensionProcessorTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ScopeModelUtilTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ServiceRepositoryTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/support/DemoService.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/support/DemoServiceImpl.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/support/MockScopeModelAware.java

Add unit test for common-module and fix unregisterProvider method

Add unit test for common-module and fix unregisterProvider method

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/ChangeTelnetHandler.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/legacy/TraceTelnetHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/ClearTelnetHandler.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/telnet/support/command/ExitTelnetHandler.java

[3.0] Limit the maximum number of lines for the clear command #7911

[3.0] Limit the maximum number of lines for the clear command

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/DataQueueCommand.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/AbstractStreamTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/ClientStreamTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/ServerStreamTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocolTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/WriteQueueTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/support/IGreeterImpl.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/support/MockAbstractStreamImpl.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/support/MockStreamObserver.java

- Add test case for TripleProtocolTest and add unit test for [Unary]ClintStream, AbstractStream
- Add unit test for WriteQueue and [Unary]ServerStream

Add test case for TripleProtocolTest and add unit test for [Unary]ClintStream, AbstractStream

---

dubbo-common/src/main/java/org/apache/dubbo/common/beans/factory/ScopeBeanFactory.java
dubbo-common/src/main/java/org/apache/dubbo/common/resource/GlobalResourcesRepository.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ServiceModel.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataParamsFilter.java

[3.0] Ensure Concurrent Safe of Model & Change MetadataParamsFilter scope

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataParamsFilter.java

Revert MetadataParamsFilter Scope

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java

Change to ConcurrentHashMap for CacheableFailbackRegistry

---

dubbo-common/src/main/java/org/apache/dubbo/common/lang/ShutdownHookCallbacks.java
dubbo-common/src/main/java/org/apache/dubbo/common/resource/GlobalResourcesRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassLoaderResourceLoader.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ModuleConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-common/src/test/java/org/apache/dubbo/common/config/ConfigurationCacheTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/resource/GlobalResourcesRepositoryTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ClassLoaderResourceLoaderTest.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigManagerTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ApplicationModelTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/FrameworkModelTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ModuleModelTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/model/ScopeModelTest.java
dubbo-common/src/test/java/org/apache/dubbo/rpc/support/MockScopeModelDestroyListener.java

Add unit test for FrameworkModel/ApplicationModel/ModuleModel and add test case for ConfigManager

Add unit test for FrameworkModel/ApplicationModel/ModuleModel and add test case for ConfigManager

---

dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/initializer/ConfigZookeeperInitializer.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/StartZookeeperUnixProcessor.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/StopZookeeperUnixProcessor.java
dubbo-test/dubbo-test-check/src/main/java/org/apache/dubbo/test/check/registrycenter/processor/ZookeeperUnixProcessor.java

Optimize the code on global zookeeper
1. Avoid compiling pattern every time
2. Avoid port already in use
3. Output all configuration information of global zookeeper instances

perf: Optimize the code on global zookeeper

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/CompositeConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/Environment.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/OrderedPropertiesConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/inject/SpiExtensionInjector.java
dubbo-common/src/main/java/org/apache/dubbo/common/status/reporter/FrameworkStatusReportService.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConfigUtils.java
dubbo-common/src/test/java/org/apache/dubbo/common/config/EnvironmentTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/config/OrderedPropertiesConfigurationTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/config/PropertiesConfigurationTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/extension/inject/AdaptiveExtensionInjectorTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/status/reporter/FrameworkStatusReportServiceTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/status/reporter/MockFrameworkStatusReporter.java
dubbo-common/src/test/java/org/apache/dubbo/common/utils/ConfigUtilsTest.java
dubbo-common/src/test/java/org/apache/dubbo/config/context/ConfigConfigurationAdapterTest.java
dubbo-common/src/test/resources/META-INF/dubbo/internal/org.apache.dubbo.common.status.reporter.FrameworkStatusReporter
dubbo-common/src/test/resources/dubbo-migration.yaml

Add unit test for common-module
- CompositeConfigurationTest  
- PropertiesConfigurationTest 
- AdaptiveExtensionInjectorTest 
- FrameworkStatusReportServiceTest 
- ConfigConfigurationAdapterTest
- Add some cases to the existing Test

Add unit test for common-module

---

dubbo-dependencies-bom/pom.xml

Update Hessian Lite Version

---

dubbo-configcenter/dubbo-configcenter-apollo/src/main/java/org/apache/dubbo/configcenter/support/apollo/ApolloDynamicConfiguration.java

[3.0]fix #9318, close apollo connect

---

dubbo-common/src/main/java/org/apache/dubbo/config/ProviderConfig.java

Remove duplicate code of ProviderConfig

Remove duplicate code of ProviderConfig

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractClient.java

[2.7] Fix issue where dead connections would not be reconnected.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceInstance.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/DefaultServiceInstanceTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtilsTest.java
dubbo-registry/dubbo-registry-zookeeper/src/test/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryTest.java

[3.0] Opt ServiceInstance Memory Usage

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

revert invoker check failed log

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHeaderEnum.java

Remove unused Tri Header Enum

---

dubbo-common/src/main/java/org/apache/dubbo/common/io/StreamUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeByteArrayOutputStream.java
dubbo-common/src/main/java/org/apache/dubbo/common/io/UnsafeStringWriter.java
dubbo-common/src/test/java/org/apache/dubbo/common/io/UnsafeStringWriterTest.java

Fix UnsafeStringWriter constructor

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java

delete duplicate code
here is [reason](https://github.com/apache/dubbo/issues/9354)

delete duplicate code

---

dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/MetricsFilter.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java

optimize some code metrics filter

[master]optimize some code metrics filter

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvoker.java

[3.0] Reduce memory allocation

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleServiceRepository.java

[3.0] Fix reRegisterProvider not update FrameworkServiceRepository

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-common/src/test/java/org/apache/dubbo/common/bytecode/WrapperTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/javassist/JavassistProxyFactory.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java

[3.0] Fail back use JDK Proxy factory when javassist occurred exception

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/javassist/JavassistProxyFactory.java

Fix log when JDK Proxy factory occurred exception

Fix log when JDK Proxy factory occurred exception

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java

[3.0] Fix RouterSnapshot not build when disable route fail fast

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/BitList.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mock/MockInvokersSelectorTest.java

[3.0] Reduce Memory Allocation when routing

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/BitList.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouterResult.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ModuleServiceRepository.java
dubbo-config/dubbo-config-spring/pom.xml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-consumer/pom.xml
dubbo-demo/dubbo-demo-spring-boot/dubbo-demo-spring-boot-provider/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/dubbo-spring-boot-actuator/pom.xml
dubbo-spring-boot/dubbo-spring-boot-autoconfigure/pom.xml
dubbo-spring-boot/dubbo-spring-boot-compatible/actuator/pom.xml
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/pom.xml
dubbo-spring-boot/dubbo-spring-boot-starter/pom.xml
dubbo-spring-boot/pom.xml

Fix the bug of log4j
efer: https://github.com/apache/logging-log4j2/pull/608
1. Update the version of log4j-api and log4j-core to 2.15.0
2. Exclude the log4j-api in spring-boot

fix: Update the version of log4j for bug fixes

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java

fix #9374(Directory already destroyed), stop process when check=false is not set

---

dubbo-common/src/main/java/org/apache/dubbo/common/config/CompositeConfiguration.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationCache.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/InmemoryConfiguration.java

issue #9346 
1. use CopyOnWriteArrayList
2. opt some code

[3.0] fix #9346 use CopyOnWriteArrayList

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractClientStream.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/Compressor.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/IdentityCompressor.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/command/DataQueueCommand.java
dubbo-rpc/dubbo-rpc-triple/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.protocol.tri.Compressor
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/ClientStreamTest.java
dubbo-rpc/dubbo-rpc-triple/src/test/java/org/apache/dubbo/rpc/protocol/tri/CompressorTest.java

https://github.com/apache/dubbo/issues/9387

[3.0-Triple] remove `identity` message-encoding

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/InstanceAddressURL.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/LazyConnectExchangeClient.java

fix https://github.com/apache/dubbo/issues/9404

Fix when consumer shutdown occurs npe

---

dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyBackedChannelBuffer.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyBackedChannelBufferTest.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyBackedChannelBuffer.java
dubbo-remoting/dubbo-remoting-netty4/src/test/java/org/apache/dubbo/remoting/transport/netty4/NettyBackedChannelBufferTest.java

Fix https://github.com/apache/dubbo/issues/6207

Fix The logic of setBytes does not meet expectations

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/AbstractServerStream.java

[3.0-Triple] Fix method sigs that may not pass original check

---

compiler/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/pom.xml
pom.xml

Follow https://github.com/apache/dubbo/pull/9433

Upgrade log4j to 2.16.0

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractEndpoint.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatHandlerTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientReconnectTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyClientTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyClientToServerTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyStringTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ThreadNameTest.java

Fix https://github.com/apache/dubbo/issues/9440
Fix https://github.com/apache/dubbo/issues/9435

 Adjust the way to obtain codec extension

---

.github/workflows/build-and-test-3.yml

Optimize the shell script in github workflow
1. Avoid to download zookeeper if cached
2. Optimize the shell script

perf: Optimize the shell script in github workflow

---

dubbo-common/src/main/java/org/apache/dubbo/common/status/reporter/FrameworkStatusReportService.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationInvokerTest.java

Add FrameworkStatusReportService for MigrationInvoker

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/Constants.java
dubbo-metadata/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java

Fix the problem that some key values of MetadataReportConfig cannot be obtained

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouterTest.java

Fix ut in MeshRuleRouterTest

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/ReferenceCountExchangeClient.java

[3.0] Save url attributes on initialization

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ClassLoaderFilter.java

[3.0] Fallback use class's cl to adapt ut

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ProfilerServerFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java

[3.0] Fix timeout cal in Profiler exceed int range

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/ClusterScopeModelInitializer.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/RouterChain.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/RouterSnapshotFilter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/RouterSnapshotSwitcher.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mock/MockInvokersSelector.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/AbstractStateRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/BitList.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/RouterGroupingState.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/StateRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/state/TailStateRouter.java
dubbo-cluster/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.rpc.cluster.filter.ClusterFilter
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/RouterSnapshotFilterTest.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/DisableRouterSnapshot.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/EnableDetailProfiler.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/EnableRouterSnapshot.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/GetEnabledRouterSnapshot.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/GetRecentRouterSnapshot.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/GetRouterSnapshot.java
dubbo-plugin/dubbo-qos/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.qos.command.BaseCommand
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/CommandHelperTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java

- Add QoS Router Snapshot Print
- Add Router Snapshot Print Filter for service level
- Add QoS Enable service level Router Snapshot Print

[3.0] Add Router Snapshot Print Support

---

dubbo-config/dubbo-config-spring/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper-curator5/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
dubbo-distribution/dubbo-bom/pom.xml
dubbo-remoting/dubbo-remoting-zookeeper-curator5/pom.xml
pom.xml

follow up of https://github.com/apache/dubbo/pull/9528

add jdk17 profile

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

[3.0] Add Optional Injvm deep copy when module are the same

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/DubboServiceAddressURL.java
dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceAddressURL.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

introduce getAllparameters in URL

fix client parameters, consumer parameters was not included

---

dubbo-dependencies-bom/pom.xml

https://github.com/advisories/GHSA-wrvw-hg22-4m67

Bump protobuf version to 3.19.2

---

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java

[3.0] Save interface class in ReferenceConfig

---

dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/DubboLoaderClassPath.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationCache.java
dubbo-common/src/main/java/org/apache/dubbo/common/config/InmemoryConfiguration.java

[3.0] Fix cached configuration not work

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java

Improve code readability
Use Method#isAnnotationPresent() to determine whether DisableInject annotation exists.
The truth value returned by this method is equivalent to: getAnnotation(annotationClass) != null

refactor: Optimize DisableInject annotation judgment method

---

dubbo-dependencies-bom/pom.xml

maybe have a bug. Subscribe service failed when local filesystem has cache file.
[nacos issue 7550](https://github.com/alibaba/nacos/issues/7550)
update nacos version

Update nacos client version

---

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmProtocol.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java

Refactor the code, delete the TripleProtocol class and the InjvmProtocol class to repeatedly implement the Protocol interface

Refactor the inheritance relationship of Protocol subclasses

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java

Improve code readability
Optimize Extension annotation import

refactor: Optimize Extension annotation import

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/schema/DubboBeanDefinitionParser.java

Improve code readability
Use the StringUtils to judge that the string is not blank.

refactor: Improve and perfect StringUtils

---

dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/GreeterService.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/GreeterServiceImpl.java
dubbo-demo/dubbo-demo-triple/src/main/java/org/apache/dubbo/demo/consumer/ApiConsumer.java
dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/DefaultMultipleSerialization.java

Fix the problem of hessian2 deserialization object exception
close #9533

fix hessian2 deserialize fail (#9533)

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java

refactor: Add missing @Override to MockClusterInvoker

---

dubbo-common/src/main/java/org/apache/dubbo/config/annotation/DubboService.java

fix JavaDoc in DubboService
fix JavaDoc in DubboService

fix JavaDoc in DubboService

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleProtocol.java

[3.0] Fix import check

---

dubbo-dependencies-bom/pom.xml
dubbo-filter/dubbo-filter-validation/pom.xml
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/filter/ValidationFilter.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidationNew.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidatorNew.java
dubbo-filter/dubbo-filter-validation/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.validation.Validation
dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/support/jvalidation/JValidatorTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcException.java

Java EE has been renamed from javax to jakarta, Related jar packages no longer use the package name starting with javax, including the jsr-303 api. To support Hibernate Validator 7.x, a new JValidatorNew file has been added for compatibility with version 7.x
close #9544
- Add JValidatorNew, use new api.
- ValidationFilter masks implementation class exceptions
I can't write new unit tests because Hibernate Validator 7.x and 6.x can't exist under the classpath at the same time and there would be a class conflict. But I have tested 7.x separately in my development environment and it works fine, so I hope someone else can test it again to make sure it works!

feature: support jsr-303 jakarta namespace

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AbstractClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/AvailableClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailSafeClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailfastClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/FailoverClusterInvokerTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvokerTest.java

[3.0] fix @test annotation

---

dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/filter/ValidationFilter.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java
dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidatorNew.java
dubbo-filter/dubbo-filter-validation/src/test/java/org/apache/dubbo/validation/support/jvalidation/JValidatorTest.java

[3.0] Fix validation exception

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/AbstractConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigManager.java
dubbo-common/src/main/java/org/apache/dubbo/config/context/ConfigMode.java

[3.0] Add ignore properties support

---

dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/DubboInfraBeanRegisterPostProcessor.java

also see https://github.com/apache/dubbo/pull/9045

set spring context for module model

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/DeployerReadinessProbe.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/DeployerStartupProbe.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/ProviderReadinessProbe.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/ReadyTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/StartupTest.java

fix probe extensions

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-common/src/main/java/org/apache/dubbo/common/cache/FileCacheStore.java
dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-common/src/test/java/org/apache/dubbo/common/cache/FileCacheStoreTest.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-metadata/dubbo-metadata-api/src/test/java/org/apache/dubbo/metadata/MetadataInfoTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/DefaultServiceInstance.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/ServiceDiscoveryRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ProtocolPortsMetadataCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceHostPortCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataCustomizer.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/store/MetaCacheManager.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/DefaultMigrationAddressComparator.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/DynamicDirectory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistryFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListenerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/metadata/store/MetaCacheManagerTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/support/MockServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/integration/RegistryProtocolTest.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/support/AbstractRegistryTest.java

Fix ServiceInstancesChangedListenerTest and some code optimizations

Fix ServiceInstancesChangedListenerTest and some code optimizations

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/MockClusterInvoker.java

Simplify the code
Use ConfigUtils to check 
Use ConfigUtils in MockClusterInvoker to determine if the parameter is empty

refactor: Use ConfigUtil in MockClusterInvoker

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java

If there is already an element in the queue, it is no longer requested

refactor: Optimize performance

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/MethodDescriptor.java

[3.0] Add some log when failed to get return types

---

dubbo-common/src/main/java/org/apache/dubbo/common/profiler/Profiler.java
dubbo-common/src/test/java/org/apache/dubbo/common/profiler/ProfilerTest.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ProfilerServerFilter.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/InvokerInvocationHandler.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

[3.0] Make Profiler work in Injvm invoke

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java

Fix https://github.com/apache/dubbo/issues/9640

Fix the callback fails when the service is grouped

---

dubbo-common/src/main/java/org/apache/dubbo/config/AbstractInterfaceConfig.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyFactory.java

[3.0] Fix Dubbo Refer failed if a generic class's dependency is incomplete

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/directory/MockDirInvocation.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouterTest.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/Invocation.java
dubbo-compatible/src/test/java/org/apache/dubbo/service/MockInvocation.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/ServiceDiscoveryMigrationInvoker.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/Invocation.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java
dubbo-rpc/dubbo-rpc-api/src/test/java/org/apache/dubbo/rpc/support/MockInvocation.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

revert invocation changes in #9659 for compatibility purpose.

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java

[3.0] Support registry delay export

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleInvoker.java

[3.0-Triple] Set default timeout to 3s and read from invocation

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/LoadingStrategy.java

[3.0] Add Included package filter in ExtensionLoader

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/UnaryClientStream.java

[3.0-Triple] Do not deserialize if data is null

---

dubbo-common/src/main/java/org/apache/dubbo/common/profiler/Profiler.java
dubbo-common/src/main/java/org/apache/dubbo/common/profiler/ProfilerEntry.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/AbstractProxyInvoker.java

[3.0] Add max entry limit for Profiler

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocal.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalTest.java

[3.0] InternalThreadLocal extend ThreadLocal for compatible

---

dubbo-common/src/main/java/org/apache/dubbo/config/ApplicationConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/context/event/DubboConfigBeanDefinitionConflictApplicationListener.java

merge redundant if branches

---

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ReferenceConfig.java

Revert "Fix the issue that the default protocol configured by the consumer does not take effect in the application-level mode"

---

dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClient.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyServer.java

netty4_extend

---

dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/DefaultParamDeepCopyUtil.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

[3.0] Remove attribute pass when Injvm invoke

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/RouterSnapshotSwitcher.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ListenableStateRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ServiceStateRouter.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/condition/config/ServiceStateRouterFactory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh/route/MeshRuleRouter.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/RouterChainTest.java

Design test cases so that each type of `StateRouter` can effectively filter out non-compliant `invokers`

Add test case for RouterChain

---

dubbo-common/src/test/java/org/apache/dubbo/metadata/definition/TypeDefinitionBuilderTest.java

Fix TypeDefinitionBuilderTest NPE

Init builders before test to fix ut

---

dubbo-dependencies-bom/pom.xml

Degrade protobuf-java to avoid compatibility problems

[3.0 Triple] Degrade protobuf-java version to 3.11.0

---

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/ServiceCheckUtilsTest.java

Fixed for [telnet for ls commond](https://github.com/apache/dubbo/issues/9765)
1. modify dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java
2. add unit test at dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/util/ServiceCheckUtilsTest.java

Add instanceOf before class cast 

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/StringUtils.java

…turn
method not have comment
update StringUtil class

add some comment to StringUtil

---

dubbo-configcenter/dubbo-configcenter-zookeeper/src/main/java/org/apache/dubbo/configcenter/support/zookeeper/ZookeeperDynamicConfiguration.java

Fix the logic of ZookeeperDynamicConfiguration#doRemoveListener method

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ApplicationModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModel.java
dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ScopeModelDestroyListener.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/FrameworkModelCleaner.java

https://github.com/apache/dubbo/issues/9422

[3.0]Fix shutdown process, destroy registry and protocol server first before destroying of other resources

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/ProviderModel.java

[3.0]Fix concurrent modification exception of stated urls

---

dubbo-common/src/main/java/org/apache/dubbo/common/utils/CompatibleTypeUtils.java

fix bigDecimal scientific notation

---

dubbo-common/src/main/java/org/apache/dubbo/rpc/model/FrameworkModel.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/DeployerReadinessProbe.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/probe/impl/DeployerStartupProbe.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/ReadyTest.java
dubbo-plugin/dubbo-qos/src/test/java/org/apache/dubbo/qos/command/impl/StartupTest.java

also see https://github.com/apache/dubbo/pull/9762

fix #9752, ignore internal application model

---

dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/AbstractCompiler.java
dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java

[3.0] Fix api for AbstractCompiler

---

dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java

also see https://github.com/apache/dubbo/pull/9782

Fix 3.0 registry as metadata

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/limited/MemoryLimitedLinkedBlockingQueue.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/limited/MemoryLimiter.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/support/limited/MemoryLimitedLinkedBlockingQueueTest.java

Can completely solve the OOM problem caused by {@link java.util.concurrent.LinkedBlockingQueue}.

[ISSUE #9721] add memory limited linked blocking queue

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/Constants.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalance.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/RandomLoadBalance.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/loadbalance/AbstractLoadBalanceTest.java

related issue https://github.com/apache/dubbo/issues/9546

fix weight cannot work properly on multi-registry scenario

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

see https://www.runoob.com/manual/jdk11api/java.base/java/nio/channels/OverlappingFileLockException.html

[3.0]fix #9341, ignore OverlappingFileLockException

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

add info log for OverlappingLockException

followup of #9358

---

.github/workflows/build-and-test-3.yml

ignore cache.
recover if https://github.com/actions/toolkit/pull/1015 merged

Fix integration test cache

---

compiler/pom.xml
dubbo-dependencies-bom/pom.xml
dubbo-spring-boot/pom.xml
pom.xml

CVEs in logger jars
https://github.com/apache/dubbo/issues/9792

upgrade logger jars due to security concerns

---

dubbo-dependencies-bom/pom.xml
dubbo-dependencies/dubbo-dependencies-zookeeper/pom.xml
dubbo-test/dubbo-test-check/pom.xml

Upgrade due to CVE
https://github.com/apache/dubbo/issues/9798

upgrade zookeeper due to security issue

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java

In the current implementation, org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation#decode(org.apache.dubbo.remoting.Channel, java.io.InputStream) will catch exceptions in readObject, and then only print WARN-level log, If the log level of the provider is ERROR, the error cannot be seen. A common problem is that a NullPointerException be throw when the provider executes business logic. Finally, the consumer gets a NullPointerException, which makes the problem difficult to troubleshoot.
For example, when the argument class has only one constructor with parameters, and the constructor parameter is a non-primitive type, Hession will initialize the parameter to be null. If the parameter is used in the constructor to execute business logic, it will trigger related exceptions, such as …

Optimize argument decode exception handling.

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java

[3.0] Fix concurrent modification in Invocation attribute

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/directory/AbstractDirectory.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/loadbalance/ShortestResponseLoadBalance.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/ForkingClusterInvoker.java
dubbo-common/src/main/java/org/apache/dubbo/common/CommonScopeModelInitializer.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/DefaultExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/ExecutorRepository.java
dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/manager/FrameworkExecutorRepository.java
dubbo-common/src/test/java/org/apache/dubbo/common/threadpool/manager/FrameworkExecutorRepositoryTest.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultModuleDeployer.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/bootstrap/MultiInstanceTest.java
dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java
dubbo-monitor/dubbo-monitor-default/src/main/java/org/apache/dubbo/monitor/dubbo/DubboMonitor.java
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/PublishMetadata.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/RegistryNotifier.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationRuleListener.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/CacheableFailbackRegistry.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListenerTest.java
dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperServiceDiscoveryChangeWatcher.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/AccessLogFilter.java

[3.0] reuse some executor services in framework level

---

dubbo-common/src/main/java/org/apache/dubbo/common/URL.java

[3.0]fix mistake code

---

dubbo-dependencies-bom/pom.xml
dubbo-native-plugin/pom.xml

security concerns
https://github.com/apache/dubbo/issues/9801

update spring and hibernate

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/ServiceAddressURL.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

see https://github.com/apache/dubbo/issues/9557 for more details

[3.0] Should not read group and version from default consumer url if it's empty in provider url.

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataServiceNameMapping.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

See https://github.com/apache/dubbo/issues/9742

[3.0] mapping report log optimization.

---

dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java

fix #9824
org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol

fix stubevent can't work

---

dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/model/ConfigItem.java
dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/configurator/parser/model/ConfiguratorConfig.java

Optimize code for base practice
modify org.apache.dubbo.rpc.cluster.configurator.parser.model.ConfigItem make some "words" to publis static final String. For base practice

Optimize code for base practice for 3.x

---

dubbo-common/src/main/java/org/apache/dubbo/common/url/component/URLItemCache.java

optimize some code of URLItemCache

[3.0]optimize some code of URLItemCache

---

dubbo-common/src/main/java/org/apache/dubbo/config/SslConfig.java

optimize some code of SslConfig

[3.0]optimize some code of SslConfig

---

dubbo-common/src/main/java/org/apache/dubbo/config/MetadataReportConfig.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/deploy/DefaultApplicationDeployer.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/MetadataReportConfigTest.java
dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/utils/ConfigValidationUtilsTest.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

also see https://github.com/apache/dubbo/pull/9807

Fix 9806, check metadata protocol

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/filter/ProfilerServerFilter.java

[3.0]fix #9832

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/absent/AbsentConfiguratorTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParserTest.java

In `org.apache.dubbo.rpc.cluster.configurator.absent.AbsentConfiguratorTest` the expected value and actual value is inverse, so i fix it

optimize unit test

---

dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/absent/AbsentConfiguratorTest.java
dubbo-cluster/src/test/java/org/apache/dubbo/rpc/cluster/configurator/parser/ConfigParserTest.java
dubbo-dependencies-bom/pom.xml

For RedHat repository-specific dependencies.

Revert 9811 patch 2

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServer.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TripleHttp2Protocol.java

Fix hang when use port unification server 
```txt
"NettyServerWorker-5-3" #65 daemon prio=5 os_prio=0 cpu=7860.08ms elapsed=2189.86s tid=0x00007fcae04bfc00 nid=2176 waiting for monitor entry  [0x00007fcac59fb000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.apache.dubbo.rpc.model.FrameworkModel.resetDefaultAppModel(FrameworkModel.java:283)
- waiting to lock <0x0000100009ef8050> (a java.lang.Object)
at org.apache.dubbo.rpc.model.FrameworkModel.defaultApplication(FrameworkModel.java:211)
at org.apache.dubbo.rpc.model.ApplicationModel.defaultModel(ApplicationModel.java:92)
at org.apache.dubbo.common.config.ConfigurationUtils.getScopeModelOrDefaultApplicationModel(ConfigurationUtils.java:139)
at org.apache.dubbo.common.config.ConfigurationUtils.getGlobalConfiguration(Configuratio …
```

[3.0] Fix shutdown hang when use port unification handler

---

dubbo-common/src/main/java/org/apache/dubbo/common/CommonScopeModelInitializer.java
dubbo-common/src/main/java/org/apache/dubbo/common/URL.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/Converter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/ConverterUtil.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToArrayConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToBlockingDequeConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToBlockingQueueConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToCollectionConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToDequeConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToIterableConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToListConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToNavigableSetConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToQueueConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToSetConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToSortedSetConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/convert/multiple/StringToTransferQueueConverter.java
dubbo-common/src/main/java/org/apache/dubbo/common/utils/ClassUtils.java
dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java
dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-common/src/test/java/org/apache/dubbo/common/convert/ConverterTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/convert/multiple/StringToArrayConverterTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/convert/multiple/StringToQueueConverterTest.java
dubbo-common/src/test/java/org/apache/dubbo/common/convert/multiple/StringToSetConverterTest.java
dubbo-metadata/dubbo-metadata-processor/src/main/java/org/apache/dubbo/metadata/annotation/processing/rest/DefaultServiceRestMetadataResolver.java

[3.0] Optimize Converter to cache

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServerHandler.java

```txt
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100
)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.j
ava:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.j
ava:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.jav
a:357)
at …
```

[3.0] Do not release ByteBuf manually in port unification handler

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServerHandler.java

Add remote address log when no protocol found

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServer.java
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServerHandler.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleServerStream.java

[3.0] Fix tls not work when use pu handler

---

.github/workflows/build-and-test-3.yml

Enable mvn cache in actions

---

.github/workflows/build-and-test-3.yml
compiler/src/main/resources/Dubbo3TripleInterfaceStub.mustache
compiler/src/main/resources/Dubbo3TripleStub.mustache

Dismiss compiling warns
Dismiss compiling warns

Fix warn in compiler

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java

Printing message when delete file failed

Optimize deleting file

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleServerStream.java

[3.0-Triple] Delete repeat code

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleServerStream.java

[3.0-Triple] Avoid listener npe  on rst

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/AbstractServerCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/stream/TripleClientStream.java

Try 'Throwable' and add logs when serialize failed

[3.0 Triple] Add log when serialize failed

---

dubbo-spring-boot/dubbo-spring-boot-compatible/autoconfigure/src/main/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessor.java

[Optimize] improve performance

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/support/AccessLogData.java

Change to thread-safe date processing class

Change to thread-safe date processing class

---

dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/TripleHttp2ClientResponseHandler.java

[3.0 Triple] Fix client on error

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AppResponse.java
dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/protocol/AbstractInvoker.java
dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/interceptors/RpcContextInterceptor.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/call/TripleClientCall.java
dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/transport/AbstractH2TransportListener.java

[Optimization] Init map size

---

dubbo-common/src/main/java/org/apache/dubbo/common/threadlocal/InternalThreadLocalMap.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

[3.0] Clear ThreadLocal before injvm invoke

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/SslContexts.java

There are too many logs of tls with each connection
Degrade log level

Degrade log level to reduce tls logs

---

dubbo-common/src/main/java/org/apache/dubbo/config/ReferenceConfigBase.java

optimize some code of ReferenceConfigBase

---

dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionDirector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/inject/AdaptiveExtensionInjector.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/ActivateComparator.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/MultiInstanceActivateComparator.java
dubbo-common/src/main/java/org/apache/dubbo/common/extension/support/WrapperComparator.java

I've been studying extension recently and found that some codes can be optimized.
- remove unless code
- add some method  annotion like `SuppressWarnings`
- replace some `for` useage with stream
- reduce `if` nesting usage

typo & format extension

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServer.java

Idle event and heartbeat   shoulde be triggered by specifed protocol

Remove idle handler

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/PortUnificationServer.java

Fix duplicate ssl init

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/migration/MigrationInvoker.java
dubbo-registry/dubbo-registry-api/src/test/java/org/apache/dubbo/registry/client/migration/MigrationInvokerTest.java

[3.0] Add dynamic decide invoker in APPLICATION_FIRST mode

---

dubbo-common/src/main/java/org/apache/dubbo/config/MethodConfig.java
dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/reference/ReferenceCreator.java
dubbo-config/dubbo-config-spring/src/test/java/org/apache/dubbo/config/spring/beans/factory/annotation/ReferenceCreatorTest.java

fix #9863, @Method annotation parma isReturn invalid

[3.0]fix #9863, @Method annotation parma isReturn invalid

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java

related issue https://github.com/apache/dubbo/issues/9972

fix getAttachment, return default value

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/AbstractServiceNameMapping.java

Related issue https://github.com/apache/dubbo/issues/9992

Fix interface-app mapping, recored mapping init status for each unique interface key.

---

dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/AbstractServiceDiscovery.java

related issue https://github.com/apache/dubbo/issues/9986

Fix offlineApp does not work as expected,  check of EMPTY_REVISION stopped instance address from being offline from regsitry.

---

dubbo-compatible/src/main/java/com/alibaba/dubbo/cache/CacheFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/monitor/MonitorFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/RegistryFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/registry/support/AbstractRegistryFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/Configurator.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/ConfiguratorFactory.java
dubbo-compatible/src/main/java/com/alibaba/dubbo/rpc/cluster/RouterFactory.java
dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/MetadataUtils.java
dubbo-rpc/dubbo-rpc-grpc/src/main/java/org/apache/dubbo/rpc/protocol/grpc/ReferenceCountManagedChannel.java

fixes https://github.com/apache/dubbo/issues/9977

[3.0] 'com.alibaba.dubbo' package compatibility

---

dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/AsyncRpcResult.java
dubbo-rpc/dubbo-rpc-injvm/src/main/java/org/apache/dubbo/rpc/protocol/injvm/InjvmInvoker.java

[3.0] Support Injvm invoke server async

---

dubbo-common/src/main/java/org/apache/dubbo/common/constants/CommonConstants.java
dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/DubboShutdownHook.java

Add shutdown hook ignore support

---

dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java
dubbo-remoting/dubbo-remoting-api/src/test/java/org/apache/dubbo/remoting/api/ConnectionTest.java

[3.0 Triple] Optimize Connection

---

dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java

[3.0] fix #10045, fix unsupported operation list
